### PR TITLE
Fix some portability issues with the new C bindings

### LINKED ISSUE #10403: C API assumes Boehm-Demers-Weiser GC is in use
In the Windows build where I happen to have disabled GC (temporarily), I noticed errors like
```
src/libexpr-c/nix_api_value.cc:4:10: fatal error: gc/gc.h: No such file or directory
    4 | #include "gc/gc.h"
      |          ^~~~~~~~~
```

### PR DESCRIPTION
**Pull request by Ericson2314**
# Motivation

Build without GC is unbroken

Fix #10403

Also building tests with Windows (assuming rest of Windows fixes) is unbroken.

# Context

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

File: tests/unit/libstore-support/tests/nix_api_store.hh [hunk 1]
```diff
@@ -24,21 +26,35 @@ public:
...
+    }
+
     void init_local_store()
     {
-        auto tmpl = nix::getEnv("TMPDIR").value_or("/tmp") + "/tests_nix-store.XXXXXX";
+#ifdef _WIN32
+        // no `mktempd` with MinGW
+        nixDir = nix::defaultTempDir() + "/tests_nix-store";
+        remove_test_files();
+        fs::create_directory(nixDir);
```
Comment (thufschmitt) [inline tests/unit/libstore-support/tests/nix_api_store.hh:52]: That looks scarily racy :astonished: 
If there's no `mktemp` equivalent at all, maybe at least add the current pid or something as a suffix?

**Review by thufschmitt — APPROVED** [review]

File: tests/unit/libstore-support/tests/nix_api_store.hh (hunk 1 above)
Comment (Ericson2314) [reply tests/unit/libstore-support/tests/nix_api_store.hh]: Oh good point, thanks!

I made it try numbers sequentially, which is not the most efficient algorithm, but will avoid such races.

Comment (thufschmitt) [reply tests/unit/libstore-support/tests/nix_api_store.hh]: Simple and brutal, love that :D
