### PR TITLE
Emit basic dry run message for garbage collection

### LINKED ISSUE #5704: "nix store gc --dry-run" doesn't print anything: fix or remove?
**Describe the bug**

The `nix store gc` command supports `--dry-run` as described in it's `--help`:

```
      · --dry-run
        Show what this command would do without doing it.
```

However nothing is printed.

**Steps To Reproduce**

1. Have items available for gc
2. `nix store gc --dry-run`
3. Wait for command to do a bunch of work but then report nothing

**Expected behavior**

List of what would be deleted, as described by `--help`/docs.

**`nix-env --version` output**

```
nix-env (Nix) 2.5pre20211126_55275fc
```

**Additional context**

Investigating a little, the relevant code is here:

https://github.com/NixOS/nix/blob/f3f32f0c30f197af2fd5a90702f7002ae74b2dfb/src/nix/store-gc.cc#L39

Which converts "dry run" into telling gc bits to return paths in `results` but they are ignored instead of printed.

See also:  #1751.

Unlike with that issue, it seems `nix store gc --dry-run` doesn't list generations that would be removed either.

Hopefully this can be fixed with some sort of `if (dryRun) for (auto &r: results) printSomehow(r)` addition, I'll put together a PR if can populate that last  part with something reasonable :).

### PR DESCRIPTION
**Pull request by lisanna-dettwyler**
nix store gc: prints number of paths that would be freed, but not bytes
nix-collect-garbage: ditto
nix-store --gc: retains current behavior

It would be very non-trivial to also compute the bytes that would be freed, due to hardlinking in the store.

Also adds checking for incompatible mixing of dry-run and max-freed options.

Resolves #5704

## Motivation

A very basic output (path count) is better than the current behavior (no output / no-op). The current behavior is kind of dangerous because a user may take the empty output of `--dry-run` at face value, and assume running without it will not delete anything (or will delete less than it actually will, if combined with `--delete-old`).

## Context

#5704

https://github.com/NixOS/nix/pull/5705

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by Ericson2314** [comment]
@lisanna-dettwyler Could you make `PrintFreed` into a plain function which is called from inside the lambda of a `Finally`?

File: src/nix/nix-store/nix-store.cc [hunk 1]
```diff
@@ -693,12 +699,13 @@ static void opGC(Strings opFlags, Strings opArgs)
...
 
     else {
-        PrintFreed freed(options.action == GCOptions::gcDeleteDead, results);
         gcStore.collectGarbage(options, results);
 
         if (options.action != GCOptions::gcDeleteDead)
             for (auto & i : results.paths)
                 cout << i << std::endl;
+        else
+            PrintFreed freed(false, results);
```
Comment (Ericson2314) [inline src/nix/nix-store/nix-store.cc]: Here is an example of why I want to use `Finally` -- we don't always just put the new `printFreed` on the inside.
```suggestion
        Finally{[&]{
            if (options.action != GCOptions::gcDeleteDead)
                for (auto & i : results.paths)
                    cout << i << std::endl;
                else
                    printFreed(false, results);
        });
        gcStore.collectGarbage(options, results);
```

Comment (lisanna-dettwyler) [reply src/nix/nix-store/nix-store.cc]: Done - curious though, why is it better here to be using an end-of-scope mechanism than to just put the print code immediately after the call to `collectGarbage`? Won't this cause the print to still run even if an exception occurred?

Comment (lisanna-dettwyler) [reply src/nix/nix-store/nix-store.cc]: I suppose in the non-dry-run case, that's desirable behavior, because you would still want to know what all was freed before the exception occurred.
