### PR TITLE
libutil: treat EIO as EOF in `readLine`

### LINKED ISSUE #15181: Getting EIO errors from nix build
## Describe the bug

While running nix build inside a gvisor container, I intermittently see the following error:

```
error:
       … while waiting for the build environment for '/nix/store/58w946lldvwmy4isl79lz1vnl5qh23ls-sandbox-env.drv' to initialize (succeeded, previous messages: )

       error: reading a line: Input/output error  
```

From gvisor's strace I see that the cause of this error is a read from /dev/pts/ptmx that returns EIO.  EIO is an expected error that occurs when the slave closes the file descriptor.

However, the code here:
https://github.com/NixOS/nix/blob/e4ce788f9d8de1bc5e58002d01088cd71c6703d0/src/libstore/unix/build/derivation-builder.cc#L994

just uses the `readLine` function that does not correctly treat EIO as EOF.

https://github.com/NixOS/nix/blob/e4ce788f9d8de1bc5e58002d01088cd71c6703d0/src/libutil/unix/file-descriptor.cc#L101

When the code to use a pty was first added (https://github.com/NixOS/nix/pull/2878), special handling of EIO was also added.  But it appears that the code for reading the output was later refactored to use `readLine` without taking into account the possibility of EIO.

## Steps To Reproduce

I don't have a straightforward reproduction.  I suspect that gvisor may be slower or otherwise have slightly different behavior that significantly increases the chance of this error occurring.

However, the cause seems clear and shouldn't require a reproduction.

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open bug issues and pull requests] for possible duplicates

[latest Nix manual]: https://nix.dev/manual/nix/development/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by amaanq**
## Motivation

Reading from a pty master returns `EIO` once the slave side closes, however, `readLine` lets it propagate as an uncaught `SysError`, which causes spurious build failures in gvisor and similar sandboxed environments where pty teardown races differently. This commit catches `EIO` inside the read lambda and maps it to a zero-length read, reusing the existing EOF path.	

## Context

When pty support was first added in #2878, EIO was handled at the call site, but a later refactor moved reading to the generic `readLine` which didn't carry the handling over, though muxable-pipe.cc still has it.

Note that the test is skipped on macOS, because macOS returns EOF with 0 immediately and discards all buffered data ([ref](https://developer.apple.com/forums/thread/663632)). 

- Fixes #15181

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

File: src/libutil/file-descriptor.cc [hunk 1]
```diff
@@ -76,8 +76,18 @@ std::string readLine(Descriptor fd, bool eofOk, char terminator)
...
+            try {
+                return read(fd, {reinterpret_cast<std::byte *>(&ch), 1});
+            } catch (SystemError & e) {
+                // On pty masters, EIO signals that the slave side closed,
+                // which is semantically EOF. Map it to a zero-length read
+                // so the existing EOF path handles it.
+                if (e.is(std::errc::io_error))
+                    return 0;
+                throw;
+            }
```
Comment (xokdvium) [inline src/libutil/file-descriptor.cc:89]: Shouldn't we apply the same treatment to FdSource::readLine/readUnbuffered under a certain flag maybe? I don't think we want to keep the one-byte-at-a-time reading function for too long anyway.
