### PR TITLE
Make debugger significantly faster

### LINKED ISSUE #10796: Poor performance of `nix build --debugger`
**Describe the bug**

Adding `--debugger` to an invocation of `nix build` adds many minutes to a build. From the order of 30 seconds without the option to over 20 minutes on one of my flakes.

**Steps To Reproduce**

`nix build .#blah --debugger`

**Expected behavior**

I would expect that performance would be similar to a build without `--debugger`.

**nix-env (Nix) 2.22.1**

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### LINKED ISSUE #11286: coredump while printing env from the debugger
**Describe the bug**

Using this flake:

```nix
{
  description = "A very basic flake";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs?ref=0874168639713f547c05947c76124f78441ea46c";
    treefmt-nix = {
      url = "github:numtide/treefmt-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, systems, nixpkgs, treefmt-nix }:
  let
    eachSystem = f: nixpkgs.lib.genAttrs (import systems) (system: f nixpkgs.legacyPackages.${system});

    # Eval the treefmt modules from ./treefmt.nix
    treefmtEval = eachSystem (pkgs: treefmt-nix.lib.evalModule pkgs ./treefmt.nix);
  in {
    formatter = eachSystem (pkgs: treefmtEval.${pkgs.system}.config.build.wrapper);
  };
}
```

treefmt.nix:

```nix
{ pkgs, ... }:
{
  # Used to find the project root
  projectRootFile = "flake.nix";

  #programs.nixpkgs-fmt.enable = true;
  programs.ruff.check = false;
  programs.ruff.format = false;
}
```

run `nix eval .#formatter.x86_64-linux --show-trace --debugger`

In the debugger run `:c` to continue past the warning about `<nixpkgs-overlays>`.
When the debugger is stopped type in `:env` and watch nix dump core.

```console
[jkolb@nixos:~/blah]$ nix eval .#formatter.x86_64-linux --show-trace --debugger
warning: Git tree '/home/jkolb/blah' is dirty
error: cannot look up '<nixpkgs-overlays>' in pure evaluation mode (use '--impure' to override)

This exception occurred in a 'tryEval' call. Use --ignore-try to skip these.

Nix 2.23.3 debugger
Type :? for help.
nix-repl> :c
error: The option `warnings' does not exist. Definition values:
       - In `/nix/store/23qfzpsx2dsgi4rzdvfarr1h0376vv42-source/programs/ruff.nix': [ ]

nix-repl> :env
Env level 0
static: firstDef baseMsg 

Env level 1
static: type config result options checked merged extendModules withWarnings legacyModules regularModules internalModule checkUnmatched 

Env level 2
static: args prefix modules check specialArgs extensionOffset evalModulesArgs 

Env level 3
static: mkIf importJSON importTOML evalModules setDefaultModuleLocation unifyModuleSyntax applyModuleArgsIfFunction mergeModules mergeModules' mergeOptionDecls evalOptionValue mergeDefinitions pushDownProperties dischargeProperties filterOverrides sortProperties fixupOptionType mkAssert mkMerge mkOverride mkOptionDefault mkDefault mkImageMediaOverride mkForce mkVMOverride mkFixStrictness mkOrder mkBefore mkAfter mkAliasDefinitions mkAliasAndWrapDefinitions fixMergeModules mkRemovedOptionModule mkRenamedOptionModule mkRenamedOptionModuleWith mkMergedOptionModule mkChangedOptionModule mkAliasOptionModule mkDerivedConfig doRename collectModules filterOverrides' defaultPriority mkAliasIfDef mkAliasAndWrapDefsWithPriority 

Env level 4
static: isFunction isString isBool attrNames isAttrs catAttrs mapAttrs zipAttrsWith isList head filter elem concatLists length foldl' any all sort concatMap concatStringsSep id types min warnIf attrByPath setAttrByPath getAttrFromPath mapAttrsToList mapAttrsRecursiveCond optionalAttrs recursiveUpdate imap1 findFirst optional toList reverseList optionalString isOption literalExpression showOption showFiles unknownModule mkOption showDefs showDeclPrefix showRawDecls 

Env level 5
Aborted (core dumped)
```

**Steps To Reproduce**

See above

**Expected behavior**

It should not crash.

**nix-env (Nix) 2.23.3**

**Additional context**

```console
[jkolb@nixos:~/blah]$ coredumpctl info --no-pager
           PID: 267396 (nix)
           UID: 1000 (jkolb)
           GID: 100 (users)
        Signal: 6 (ABRT)
     Timestamp: Mon 2024-08-12 11:04:22 EDT (4min 37s ago)
  Command Line: nix eval .#formatter.x86_64-linux --show-trace --debugger
    Executable: /nix/store/qa76400bs3qsqxriwd4his04hi5mfhz8-nix-2.23.3/bin/nix
 Control Group: /user.slice/user-1000.slice/user@1000.service/session.slice/vte-spawn-8e6e69f1-f2a7-48bf-a47b-8bf712147f6d.scope
          Unit: user@1000.service
     User Unit: vte-spawn-8e6e69f1-f2a7-48bf-a47b-8bf712147f6d.scope
         Slice: user-1000.slice
     Owner UID: 1000 (jkolb)
       Boot ID: 26b8ce2a56184e92897d6341816233e0
    Machine ID: bee984703f0c4de58d57703565a26d2e
      Hostname: nixos
       Storage: /var/lib/systemd/coredump/core.nix.1000.26b8ce2a56184e92897d6341816233e0.267396.1723475062000000.zst (present)
  Size on Disk: 5.7M
       Message: Process 267396 (nix) of user 1000 dumped core.
                
                Module libkeyutils.so.1 without build-id.
                Module libkrb5support.so.0 without build-id.
                Module libcom_err.so.3 without build-id.
                Module libk5crypto.so.3 without build-id.
                Module libkrb5.so.3 without build-id.
                Module libunistring.so.5 without build-id.
                Module libattr.so.1 without build-id.
                Module libbrotlicommon.so.1 without build-id.
                Module libaws-c-common.so.1 without build-id.
                Module libaws-checksums.so.1.0.0 without build-id.
                Module libaws-c-sdkutils.so.1.0.0 without build-id.
                Module libaws-c-cal.so.1.0.0 without build-id.
                Module libaws-c-compression.so.1.0.0 without build-id.
                Module libs2n.so.1 without build-id.
                Module libaws-c-io.so.1.0.0 without build-id.
                Module libaws-c-http.so.1.0.0 without build-id.
                Module libaws-c-auth.so.1.0.0 without build-id.
                Module libaws-c-s3.so.0unstable without build-id.
                Module libaws-c-event-stream.so.1.0.0 without build-id.
                Module libaws-c-mqtt.so.1.0.0 without build-id.
                Module libgssapi_krb5.so.2 without build-id.
                Module libpsl.so.5 without build-id.
                Module libidn2.so.0 without build-id.
                Module libnghttp2.so.14 without build-id.
                Module libxml2.so.2 without build-id.
                Module libbz2.so.1 without build-id.
                Module libzstd.so.1 without build-id.
                Module liblzma.so.5 without build-id.
                Module libacl.so.1 without build-id.
                Module libz.so.1 without build-id.
                Module libssh2.so.1 without build-id.
                Module libpcre.so.1 without build-id.
                Module libhttp_parser.so.2.9 without build-id.
                Module libcpuid.so.16 without build-id.
                Module libbrotlidec.so.1 without build-id.
                Module libbrotlienc.so.1 without build-id.
                Module libseccomp.so.2 without build-id.
                Module libaws-crt-cpp.so without build-id.
                Module libaws-cpp-sdk-core.so without build-id.
                Module libaws-cpp-sdk-s3.so without build-id.
                Module libaws-cpp-sdk-transfer.so without build-id.
                Module libarchive.so.13 without build-id.
                Module libgit2.so.1.7 without build-id.
                Module libboost_context.so.1.81.0 without build-id.
                Module libgcc_s.so.1 without build-id.
                Module libstdc++.so.6 without build-id.
                Module liblowdown.so.1 without build-id.
                Module libeditline.so.1 without build-id.
                Stack trace of thread 267396:
                #0  0x00007fe24bdb57dc __pthread_kill_implementation (libc.so.6 + 0x927dc)
                #1  0x00007fe24bd63516 raise (libc.so.6 + 0x40516)
                #2  0x00007fe24bd4b935 abort (libc.so.6 + 0x28935)
                #3  0x00007fe24ca38fc0 _ZN3nix16printEnvBindingsERKNS_11SymbolTableERKNS_9StaticEnvERKNS_3EnvEi.cold (libnixexpr.so + 0x38fc0)
                #4  0x00007fe24ca97e23 _ZN3nix16printEnvBindingsERKNS_9EvalStateERKNS_4ExprERKNS_3EnvE (libnixexpr.so + 0x97e23)
                #5  0x00007fe24c7b5abd _ZN3nix7NixRepl11processLineENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE (libnixcmd.so + 0x6dabd)
                #6  0x00007fe24c7b7bf8 _ZN3nix7NixRepl8mainLoopEv (libnixcmd.so + 0x6fbf8)
                #7  0x00007fe24c7be118 _ZN3nix15AbstractNixRepl9runSimpleENS_3refINS_9EvalStateEEERKSt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPNS_5ValueESt4lessISA_E19traceable_allocatorISt4pairIKSA_SC_EEE (libnixcmd.so + 0x76118)
                #8  0x00007fe24ca9b858 _ZN3nix9EvalState12runDebugReplEPKNS_5ErrorERKNS_3EnvERKNS_4ExprE (libnixexpr.so + 0x9b858)
                #9  0x00007fe24ca93f53 _ZN3nix16EvalErrorBuilderINS_11ThrownErrorEE10debugThrowEv (libnixexpr.so + 0x93f53)
                #10 0x00007fe24cb3008c _ZNSt17_Function_handlerIFvRN3nix9EvalStateENS0_6PosIdxEPPNS0_5ValueERS4_ENS0_L12primop_throwMUlS2_S3_S6_S7_E_EE9_M_invokeERKSt9_Any_dataS2_OS3_OS6_S7_.lto_priv.0 (libnixexpr.so + 0x13008c)
                #11 0x00007fe24caa066f _ZN3nix9EvalState12callFunctionERNS_5ValueEmPPS1_S2_NS_6PosIdxE (libnixexpr.so + 0xa066f)
                #12 0x00007fe24caa415c _ZN3nix8ExprCall4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0xa415c)
                #13 0x00007fe24ca9fbbc _ZN3nix7ExprLet4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x9fbbc)
                #14 0x00007fe24cb0dfe5 _ZN3nixL8prim_seqERNS_9EvalStateENS_6PosIdxEPPNS_5ValueERS3_.lto_priv.0 (libnixexpr.so + 0x10dfe5)
                #15 0x00007fe24caa09d2 _ZN3nix9EvalState12callFunctionERNS_5ValueEmPPS1_S2_NS_6PosIdxE (libnixexpr.so + 0xa09d2)
                #16 0x00007fe24caa415c _ZN3nix8ExprCall4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0xa415c)
                #17 0x00007fe24ca8ab35 _ZN3nix9EvalState10forceAttrsIZNS0_10forceAttrsERNS_5ValueENS_6PosIdxESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_EEvS3_T_S8_ (libnixexpr.so + 0x8ab35)
                #18 0x00007fe24caa267b _ZN3nix10ExprSelect4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0xa267b)
                #19 0x00007fe24caa0341 _ZN3nix9EvalState12callFunctionERNS_5ValueEmPPS1_S2_NS_6PosIdxE (libnixexpr.so + 0xa0341)
                #20 0x00007fe24caa415c _ZN3nix8ExprCall4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0xa415c)
                #21 0x00007fe24caa0341 _ZN3nix9EvalState12callFunctionERNS_5ValueEmPPS1_S2_NS_6PosIdxE (libnixexpr.so + 0xa0341)
                #22 0x00007fe24caa415c _ZN3nix8ExprCall4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0xa415c)
                #23 0x00007fe24ca860ad _ZN3nix10eval_cache10AttrCursor10forceValueEv (libnixexpr.so + 0x860ad)
                #24 0x00007fe24c796481 _ZN3nix16InstallableFlake7toValueERNS_9EvalStateE (libnixcmd.so + 0x4e481)
                #25 0x000055f5838891d6 _ZN7CmdEval3runEN3nix3refINS0_5StoreEEENS1_INS0_16InstallableValueEEE (nix + 0x1311d6)
                #26 0x00007fe24c783cac _ZN3nix23InstallableValueCommand3runENS_3refINS_5StoreEEENS1_INS_11InstallableEEE (libnixcmd.so + 0x3bcac)
                #27 0x00007fe24c7a977c _ZN3nix18InstallableCommand3runENS_3refINS_5StoreEEE (libnixcmd.so + 0x6177c)
                #28 0x00007fe24c7853f7 _ZN3nix12StoreCommand3runEv (libnixcmd.so + 0x3d3f7)
                #29 0x000055f5838af903 _ZN3nix11mainWrappedEiPPc (nix + 0x157903)
                #30 0x00007fe24cca1865 _ZN3nix16handleExceptionsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt8functionIFvvEE (libnixmain.so + 0x23865)
                #31 0x000055f5837f8b7c main (nix + 0xa0b7c)
                #32 0x00007fe24bd4d14e __libc_start_call_main (libc.so.6 + 0x2a14e)
                #33 0x00007fe24bd4d209 __libc_start_main@@GLIBC_2.34 (libc.so.6 + 0x2a209)
                #34 0x000055f5837fd7f5 _start (nix + 0xa57f5)
                
                Stack trace of thread 267398:
                #0  0x00007fe24bdb00ce __futex_abstimed_wait_common (libc.so.6 + 0x8d0ce)
                #1  0x00007fe24bdb321d pthread_cond_clockwait@GLIBC_2.30 (libc.so.6 + 0x9021d)
                #2  0x00007fe24cc9f793 _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN3nix11ProgressBarC4EbEUlvE_EEEEE6_M_runEv (libnixmain.so + 0x21793)
                #3  0x00007fe24c0e86d3 execute_native_thread_routine (libstdc++.so.6 + 0xe86d3)
                #4  0x00007fe24bdb3a42 start_thread (libc.so.6 + 0x90a42)
                #5  0x00007fe24be3305c __clone3 (libc.so.6 + 0x11005c)
                
                Stack trace of thread 267397:
                #0  0x00007fe24bd6438a __sigtimedwait (libc.so.6 + 0x4138a)
                #1  0x00007fe24bd6398c sigwait (libc.so.6 + 0x4098c)
                #2  0x00007fe24c39e9c5 _ZN3nixL19signalHandlerThreadE10__sigset_t (libnixutil.so + 0xd49c5)
                #3  0x00007fe24c3a401c _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJPFv10__sigset_tES3_EEEEE6_M_runEv (libnixutil.so + 0xda01c)
                #4  0x00007fe24c0e86d3 execute_native_thread_routine (libstdc++.so.6 + 0xe86d3)
                #5  0x00007fe24bdb3a42 start_thread (libc.so.6 + 0x90a42)
                #6  0x00007fe24be3305c __clone3 (libc.so.6 + 0x11005c)
                ELF object binary architecture: AMD x86-64


```

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### LINKED ISSUE #12527: builtins.break/--debugger no longer works properly
## Describe the bug
Using `--debugger` often does one or both of the following on Nix 2.24.12
- slows evaluation to a crawl
- throws the following error
```
terminating due to unexpected unrecoverable internal error: Unexpected condition in operator[] at src/libexpr/symbol-table.hh:119
Aborted (core dumped)
```
Switching back to 2.18 fixes the issue.

## Steps To Reproduce
Add a break point with `builtins.break` somewhere in your code an run `nix build --debugger`

## Expected behavior
It works like it does on nix 2.18 - fast and no errors.

## Checklist

- [ ] checked [latest Nix manual] \([source])
- [ ] checked [open bug issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by xokdvium**
## Motivation

The underlying issue is that debugger code path was
calling `PosTable::operator[]` in each `eval` method.
This has become incredibly expensive since https://github.com/NixOS/nix/commit/5d9fdab3de0ee17c71369ad05806b9ea06dfceda.

While we are it it, I've reworked the code to
not use std::shared_ptr where it really isn't necessary.

As I've documented in previous commits, this is actually
more a workaround for recursive header dependencies now
and is only necessary in `error.hh` code.

Some ad-hoc benchmarking:

After this commit:

```
Benchmark 1: nix eval nixpkgs#hello --impure --ignore-try --no-eval-cache --debugger
  Time (mean ± σ):     784.2 ms ±   7.1 ms    [User: 561.4 ms, System: 147.7 ms]
  Range (min … max):   773.5 ms … 792.6 ms    10 runs
```

On master https://github.com/NixOS/nix/commit/3604c7c51a0e5370fac7381b2469d4fa0bb02d3c:

```
Benchmark 1: nix eval nixpkgs#hello --impure --ignore-try --no-eval-cache --debugger
  Time (mean ± σ):     22.914 s ±  0.178 s    [User: 18.524 s, System: 4.151 s]
  Range (min … max):   22.738 s … 23.290 s    10 runs
```

## Context

- Fixes #12527
- Fixes #10796
- Closes #11286

cc @roberth for https://github.com/NixOS/nix/pull/12645/commits/50123f2a566bd9157ef6ed64d95799473e5d8670
cc @tomberek, https://github.com/NixOS/nix/pull/12544#issuecomment-2674631258

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

File: src/libexpr/eval.hh [hunk 1]
```diff
@@ -170,12 +170,60 @@ struct RegexCache;
...
-    bool isError;
+class DebugTrace
+{
+    /* WARNING: Converting PosIdx -> Pos should be done with extra care. This is
+       due to the fact that operator[] of PosTable is incredibly expensive. */
+    std::variant<Pos, PosIdx> pos_;
+    const Expr & expr_;
+    const Env & env_;
+    HintFmt hint_;
+    bool isError_;
```
[the remark this answers is not in the document]
Comment (roberth) [reply src/libexpr/eval.hh:181]: Somewhat soon to say now, but I [get](https://matrix.to/#/#nix-dev:nixos.org) the impression that we don't want this, or if we do, it'd be a bit of a project to use it consistently, handle some merge conflicts etc. Best to remove the `_` suffixes for now. I feel like maybe opinions can be swayed, but let's keep that as something separate.

**Comment by kjeremy** [comment]
Should also fix #10796

File: src/libutil/error.hh [hunk 2]
```diff
@@ -50,6 +50,14 @@ struct LinesOfCode {
...
 };
 
+/* NOTE: position.hh recursively depends on source-path.hh -> source-accessor.hh
+   -> hash.hh -> config.hh -> experimental-features.hh -> error.hh -> Pos.
+   There are other such cycles.
+   Thus, Pos has to be an incomplete type in this header. But since ErrorInfo/Trace
+   have to refer to Pos, they have to use pointer indirection via std::shared_ptr
+   to break the recursive header dependency.
+   FIXME: Untangle this mess. Should there be AbstractPos as there used to be before
+   4feb7d9f71? */
```
Comment (Ericson2314) [inline src/libutil/error.hh:60]: I am guessing `experimental-features.hh` is the easy thing to make more abstract

I was planning on doing that anyways for a new settings system.

Comment (roberth) [reply src/libutil/error.hh:60]: Forgot to write down more thoughts.

While it would be good to slim down `nix-util` and have more things in libraries with well-defined scopes, I think it's ok to consider `Pos` to be part of a text handling component; not the evaluator. This frees it up to be used in `nix.conf` logic and other file types.

**Comment by roberth** [comment]
Thank you so much @xokdvium!

**Comment by roberth** [comment]
Released in
- 2.24.13
- 2.27.0
- 2.28.0

Backported but end-of-life
- 2.26
