### PR TITLE
deduplicate inherit-from source expr work

### LINKED ISSUE #9149: `inherit` duplicates evaluation work
**Describe the bug**

`e` in `{ inherit (e) a1 a2; }` is evaluated [by name](https://en.wikipedia.org/wiki/Evaluation_strategy#Call_by_name) rather than [by need](https://en.wikipedia.org/wiki/Evaluation_strategy#Call_by_need).

This is unexpected in a language where basically everything is call by need.

It is a (potentially) asymptotic performance bug.

**Steps To Reproduce**

1.

```nix
nix-repl> { inherit (builtins.trace "doing it" { a1 = null; a2 = null; }) a1 a2; }
{ a1 = trace: doing it
null; a2 = trace: doing it
null; }
```

2. Observe that the `trace` call is evaluated twice.

**Expected behavior**

1.

```nix
nix-repl> { inherit (builtins.trace "doing it" { a1 = null; a2 = null; }) a1 a2; }
{ a1 = trace: doing it
null; a2 = null; }
```

2. Observe that the trace call is performed once, and is then remembered for all subsequent use.

**Suggested solution**

- For each `inherit` statement that has multiple attrs, allocate a thunk when evaluating the attrset literal.
- Construct thunks that reference this thunk and perform an attribute selection. This might warrant a new type of thunk (this would be the fourth type of thunk).

**`nix-env --version` output**

2.13.5

**Additional context**

Thanks @piegames for raising this on matrix.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by pennae**
# Motivation

fix #9149. also fix exponential increase in error message size with nested inherit-from expressions. (cc @roberth)

# Context

we now allocate an extra env for attrsets containing inherit-from directives for all the from expressions, as a sibling the in-set scope env. this lets us avoid keeping the entire scope around when inherited attributes are picked out, and it makes access to memoized values easier. considering how rare inherit-from are in practice it didn't seem worth the more complicated code needed to allocate one env for each directive.

fun fact: `rec { inherit (x) y` evaluates `x` in the *inner* scope wile `rec { inherit y` evaluates `y` in the outer scope. this is inconsistent and feels like an implementation bug that is now become spec by virtue of having been there for way too long.

depends on #9776. seemed more reasonable to not rebase this onto master and have to resolve conflicts after either gets merged.

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

File: src/libexpr/nixexpr.hh [hunk 1]
```diff
@@ -274,6 +314,11 @@ struct ExprAttrs : Expr
     ExprAttrs() : recursive(false) { };
     PosIdx getPos() const override { return pos; }
     COMMON_METHODS
+
+    std::shared_ptr<const StaticEnv> bindInheritSources(
+        EvalState & es, const std::shared_ptr<const StaticEnv> & env);
+    Env * buildInheritFromEnv(EvalState & state, Env & up);
+    void showBody(const SymbolTable & symbols, std::ostream & str) const;
```
Comment (roberth) [inline src/libexpr/nixexpr.hh:321]:
```suggestion
    void showBindings(const SymbolTable & symbols, std::ostream & str) const;
```

In a lambda, the body is the part after `:`.
In a `let`, I would the expect the body to be the part after `in`, but this is the part between `let` and `in`.

File: src/libexpr/nixexpr.hh [hunk 2]
```diff
@@ -252,16 +269,39 @@ struct ExprAttrs : Expr
     bool recursive;
     PosIdx pos;
     struct AttrDef {
-        bool inherited;
+        enum class Kind {
+            plain,
+            inherited,
+            inheritedFrom,
```
Comment (roberth) [inline src/libexpr/nixexpr.hh:275]:
```suggestion
            /** `attr = expr;` */
            Plain,
            /** `inherit attr1 attrn;` */
            Inherited,
            /** `inherit (expr) attr1 attrn;` */
            InheritedFrom,
```

Upper camel case, to follow the other `enum class`/`enum struct`s, except, unfortunately `LogFormat`.

**Review by roberth — COMMENTED** [review]
Will review again as this
- depends on #9776

**Comment by roberth** [comment]
@pennae would you mind to rebase this?

**Comment by Ericson2314** [comment]
I think @roberth already knows the answer, but I am surprised this fix seems more involved than I'd imagine

```nix
{ inherit (expr) a b c; }
```
to
```nix
let e = expr; in { inherit (e) a b c; }
```

would be

**Comment by Ericson2314** [comment]
Thanks @pennae. That makes sense. Basically, I am not used to thinking about these env objects. They feel like something that ought to not exist in a lexically scoped language with just a little bit of work, but maybe I am just being too compiler-brained rather than interpreter-brained about it.

**Comment by thufschmitt** [comment]
Discussed during the Nix maintainers meeting on 2024-02-12.
Assigned to @roberth.

<details>

Fixing a very weird behaviour on the evaluator (not memoizing the subexpression of `inherit`).

Agreement that we want it, @roberth to review it
</details>

**Comment by roberth** [comment]
It still is.

-------- Original Message --------

File: src/libexpr/nixexpr.cc [hunk 3]
```diff
@@ -328,31 +358,56 @@ void ExprOpHasAttr::bindVars(EvalState & es, const std::shared_ptr<const StaticE
             i.expr->bindVars(es, env);
 }
 
+std::shared_ptr<const StaticEnv> ExprAttrs::bindInheritSources(
+    EvalState & es, const std::shared_ptr<const StaticEnv> & env)
+{
+    if (!inheritFromExprs)
+        return nullptr;
+
```
Comment (roberth) [inline src/libexpr/nixexpr.cc:366]: This seems like helpful context:

```suggestion

    // The inherit (from) values are inserted into an Env of its own, which
    // does not introduce any variable names.
```

File: src/libexpr/parser.y [hunk 4]
```diff
@@ -313,17 +313,28 @@ binds
...
       }
       delete $3;
     }
   | binds INHERIT '(' expr ')' attrs ';'
     { $$ = $1;
+      if (!$$->inheritFromExprs)
+          $$->inheritFromExprs = std::make_unique<std::vector<Expr *>>();
+      $$->inheritFromExprs->push_back($4);
+      auto from = new nix::ExprInheritFrom(state->at(@4), $$->inheritFromExprs->size() - 1);
       /* !!! Should ensure sharing of the expression in $4. */
```
Comment (roberth) [inline src/libexpr/parser.y:328]:
```suggestion
```

You've solved this!

File: src/libexpr/nixexpr.hh [hunk 5]
```diff
@@ -135,6 +135,18 @@ struct ExprVar : Expr
     COMMON_METHODS
 };
 
+struct ExprInheritFrom : ExprVar
```
Comment (roberth) [inline src/libexpr/nixexpr.hh:138]:
```suggestion
/**
 * A pseudo-expression for the purpose of evaluating the `from` expression in `inherit (from)` syntax.
 * Unlike normal variable references, the displacement is set during parsing, and always refers to
 * `ExprAttrs::inheritFromExprs` (by itself or in `ExprLet`), whose values are put into their own `Env`.
 */
struct ExprInheritFrom : ExprVar
```

**Review by roberth — COMMENTED** [review]
Overall LGTM.
- `inherited()` could be renamed or removed
- Some suggestions for code comments

Apologies for the delay

File: doc/manual/rl-next/inherit-from-by-need.md [hunk 6]
```diff
@@ -0,0 +1,7 @@
+---
+synopsis: "`inherit (x) ...` evalutates `x` only once"
+prs: 9847
+---
+
+`inherit (x) a b ...` now evalutates the expression `x` only once for all inherited attributes rather than once for each inherited attribute.
```
Comment (roberth) [inline doc/manual/rl-next/inherit-from-by-need.md:6]:
```suggestion
synopsis: "`inherit (x) ...` evaluates `x` only once"
prs: 9847
---

`inherit (x) a b ...` now evaluates the expression `x` only once for all inherited attributes rather than once for each inherited attribute.
```

**Review by roberth — APPROVED** [review]
A typo made it through, but LGTM!

**Comment by roberth** [comment]
Thank you @pennae
