### PR TITLE
Restore Nix 2.3 behaviour for {__impure,__contentAddressed} = false

### LINKED ISSUE #8405: `__contentAddressed` and `__impure` improperly elided from derivation
**Describe the bug**

When `__contentAddressed` or `__impure` are configured in a Nix derivation, but set to `false`, their key is elided from the Nix derivation's environment. This means that, while they evaluate fine on a pre-introduction Nix version (e.g. 2.3), the generated derivation's environment doesn't match.

**Steps To Reproduce**

1. Evaluate `derivation { name = "name"; builder = "builder"; system = "x86_64-linux"; __contentAddressed = false; __impure = false; }` on Nix 2.3 and a newer version of Nix

**Expected behavior**

The derivation hashes being the same.

**`nix-env --version` output**

```
nix-env (Nix) 2.13.3
nix-env (Nix) 2.3.16
```

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by edolstra**
# Motivation

Fixes #8405.

# Context

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [ ] agreed on idea
 - [ ] agreed on implementation strategy
 - [ ] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests - `tests/nixos/*`
 - [ ] documentation in the manual
 - [ ] documentation in the internal API docs
 - [ ] code and comments are self-explanatory
 - [ ] commit message explains why the change was made
 - [ ] new feature or incompatible change: updated release notes

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

### CODE REVIEW

File: src/libexpr/primops.cc [hunk 1]
```diff
@@ -1152,16 +1152,14 @@ drvName, Bindings * attrs, Value & v)
...
+                experimentalFeatureSettings.require(Xp::CaDerivations);
             }
 
-            else if (i->name == state.sImpure) {
-                isImpure = state.forceBool(*i->value, noPos, context_below);
-                if (isImpure)
-                    experimentalFeatureSettings.require(Xp::ImpureDerivations);
+            else if (i->name == state.sImpure && state.forceBool(*i->value, noPos, context_below)) {
+                isImpure = true;
+                experimentalFeatureSettings.require(Xp::ImpureDerivations);
```
Comment (roberth) [inline src/libexpr/primops.cc:1162]: These changes don't look like a change in behavior to me.
For example when `__impure = false;` is passed, then `isImpure` would end up `false` both before and after this PR, iiuc.

Comment (puckipedia) [reply src/libexpr/primops.cc:1162]: If I read correctly (I haven't tested this yet), if `__impure = false;`, it will be added to the environment instead of being elided entirely, matching Nix 2.3 behavior. I do agree that the code is very unclear on this :p

Comment (Ericson2314) [reply src/libexpr/primops.cc:1162]: Ah that is an interesting point. I think the real solution is to find a way to do forwards compat for toggles that don't yet exist. I.e. something that if *not* recognized would cause an error rather than an environment variable entry.

Comment (edolstra) [reply src/libexpr/primops.cc:1162]: In the future we should use `requiredSystemFeatures` for this, e.g. `requiredSystemFeatures = [ "impure" ]`. That triggers an error if you don't have the required feature.

Comment (puckipedia) [reply src/libexpr/primops.cc:1162]: Except `requiredSystemFeatures` are only checked on build time, not when instantiating the derivation - so features that modify the way a derivation is made (e.g. `__impure` and `__contentAddressed`) can't work like that.

Have you maybe considered just requiring all derivation attributes starting with `__` to be known to the interpreter?
