### PR TITLE
libstore: guard against empty archive in unpack paths

### LINKED ISSUE #15116: nix-prefetch-url --unpack segfaults with zero sized file as input
## Describe the bug

`nix-prefetch-url --unpack` crashes if given a zero size file as input using the file protocol.

## Steps To Reproduce

```
$ touch foo
$ nix-prefetch-url --unpack file://$PWD/foo
Segmentation fault         (core dumped) nix-prefetch-url --unpack file://$PWD/foo
```

## Expected behavior

Segmentation fault should never occur regardless of input values.

## Metadata

nix-env (Nix) 2.31.2

Platform: `aarch64`

nixpkgs commit: `d351d0653aeb7877273920cd3e823994e7579b0b`

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open bug issues and pull requests] for possible duplicates

[latest Nix manual]: https://nix.dev/manual/nix/development/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by amaanq**
## Motivation

`DirectoryIterator` is dereferenced without an end check, which segfaults when unpacking an empty or zero-sized archive. This commit adds an emptiness check before the dereference in both `prefetchFile` and `builtinUnpackChannel`, throwing a descriptive error instead.

## Context

- Fixes #15116

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by Ericson2314** [comment]
@xokdvium should we have some sort of `empty` or `end` method on `DirectoryIterator` to be compliant?

**Comment by xokdvium** [comment]
> should we have some sort of empty or end method on DirectoryIterator to be compliant?

The current situation is fine. It's not a range, but an iterator, so it's all good. Think `std::istream_iterator`.

File: src/nix/prefetch.cc [hunk 1]
```diff
@@ -131,6 +131,8 @@ std::tuple<StorePath, Hash> prefetchFile(
             unpackTarfile(tmpFile, unpacked);
 
             auto entries = DirectoryIterator{unpacked};
+            if (entries == DirectoryIterator{})
+                throw Error("archive '%s' is empty", url.to_string());
```
Comment (xokdvium) [inline src/nix/prefetch.cc:135]: Note that old versions (like 2.18) created an empty file. Not sure what's the best way to address this is.

Comment (amaanq) [reply src/nix/prefetch.cc:135]: Not sure at all, though I guess it was a bug/unintended side effect that there were empty archives created before.

Comment (xokdvium) [reply src/nix/prefetch.cc:135]: Probably, can we discuss the intended behaviour in the linked issue?

**Review by xokdvium — APPROVED** [review]
The builtin builder change is good regardless. I think it's fine to stick with error out in all code paths too.
