### PR TITLE
Explain when `man` is missing

### LINKED ISSUE #10677: `--help` fails in a confusing way if `man` isn't installed
**Describe the bug**

This is related to https://github.com/NixOS/nix/issues/6186

I installed nix in a docker container, in order to play with it. The `--help` argument of nix-* commands fails, and it was quite difficult to understand how to fix it:

```
$ nix-env --help
error: command 'man nix-env' failed: No such file or directory
```

A suggestion: perhaps add a note saying something like "Showing help requires `man` installed. You can install it using your OS package manager".

**Steps To Reproduce**

1. Install nix in an ubuntu:22.04 docker container.
2. Run `nix-env --help`

**Expected behavior**

See the help

**`nix-env --version` output**

```
nix-env (Nix) 2.22.1
```

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by roberth**
# Motivation

Low hanging UX fruit.
Fixes #10677

# Context

- Fixes #10677

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

File: tests/functional/misc.sh [hunk 1]
```diff
@@ -13,6 +13,9 @@ source common.sh
 # Can we ask for the version number?
 nix-env --version | grep "$version"
 
+nix_env=$(type -P nix-env)
+(PATH=""; ! $nix_env --help 2>&1 ) | grepQuiet -F "The 'man' command was not found, but it is needed for 'nix-env' and some other 'nix-*' commands' help text. Perhaps you could install the 'man' command?"
+
 # Usage errors.
 expect 1 nix-env --foo 2>&1 | grep "no operation"
 expect 1 nix-env -q --foo 2>&1 | grep "unknown flag"
```
Comment (Ericson2314) [inline tests/functional/misc.sh:21]: Should we be using `expectStderr`?

**Review by Ericson2314 — APPROVED** [review]

File: tests/functional/misc.sh (hunk 1 above)
Comment (roberth) [reply tests/functional/misc.sh:21]: Normally I would, but I've also cleared `PATH` here, so wasn't sure.
It's fine.
