### PR TITLE
builtins.fetchurl: Fix segfault on s3:// URLs

### LINKED ISSUE #11674: nix 2.24.8 segfault fetchurl from s3
**Describe the bug**

fetching files from s3 via fetchurl

eg

```
nix repl 
Nix 2.24.8
Type :? for help.
nix-repl> builtins.fetchurl "s3://highlighter-public/405b3ba02ccb2f07ec6aba9f233d4194.mp4?region=ap-southeast-2"
Segmentation fault (core dumped)
```

causes segfault in nix 2.24.8 but works in 2.18.8

```
           PID: 128406 (nix-build)
           UID: 1001 (kirillvr)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: Fri 2024-10-11 12:40:24 AEDT (4min 50s ago)
  Command Line: nix-build
    Executable: /nix/store/rl4q0j5fxa816w50543xvd84nybmz9m3-nix-2.24.8/bin/nix
 Control Group: /user.slice/user-1001.slice/user@1001.service/session.slice/vte-spawn-544c60dc-1b9a-4fc5-85b4-bf58757334cf.scope
          Unit: user@1001.service
     User Unit: vte-spawn-544c60dc-1b9a-4fc5-85b4-bf58757334cf.scope
         Slice: user-1001.slice
     Owner UID: 1001 (kirillvr)
       Boot ID: 906c7a57e1fe4b77973077881624a0ce
    Machine ID: 0af174045ea841cbbd7d814dadf6b481
      Hostname: tsutenkaku
       Storage: /var/lib/systemd/coredump/core.nix-build.1001.906c7a57e1fe4b77973077881624a0ce.128406.1728610824000000.zst (present)
  Size on Disk: 98.2M
       Message: Process 128406 (nix-build) of user 1001 dumped core.
                
                Module libkeyutils.so.1 without build-id.
                Module libkrb5support.so.0 without build-id.
                Module libcom_err.so.3 without build-id.
                Module libk5crypto.so.3 without build-id.
                Module libkrb5.so.3 without build-id.
                Module libunistring.so.5 without build-id.
                Module libattr.so.1 without build-id.
                Module libbrotlicommon.so.1 without build-id.
                Module libaws-c-common.so.1 without build-id.
                Module libaws-checksums.so.1.0.0 without build-id.
                Module libaws-c-sdkutils.so.1.0.0 without build-id.
                Module libaws-c-cal.so.1.0.0 without build-id.
                Module libaws-c-compression.so.1.0.0 without build-id.
                Module libs2n.so.1 without build-id.
                Module libaws-c-io.so.1.0.0 without build-id.
                Module libaws-c-http.so.1.0.0 without build-id.
                Module libaws-c-auth.so.1.0.0 without build-id.
                Module libaws-c-s3.so.0unstable without build-id.
                Module libaws-c-event-stream.so.1.0.0 without build-id.
                Module libaws-c-mqtt.so.1.0.0 without build-id.
                Module libgssapi_krb5.so.2 without build-id.
                Module libpsl.so.5 without build-id.
                Module libidn2.so.0 without build-id.
                Module libnghttp2.so.14 without build-id.
                Module libxml2.so.2 without build-id.
                Module libbz2.so.1 without build-id.
                Module libzstd.so.1 without build-id.
                Module liblzma.so.5 without build-id.
                Module libacl.so.1 without build-id.
                Module libz.so.1 without build-id.
                Module libssh2.so.1 without build-id.
                Module libpcre.so.1 without build-id.
                Module libcpuid.so.17 without build-id.
                Module libbrotlidec.so.1 without build-id.
                Module libbrotlienc.so.1 without build-id.
                Module libseccomp.so.2 without build-id.
                Module libaws-crt-cpp.so without build-id.
                Module libaws-cpp-sdk-core.so without build-id.
                Module libaws-cpp-sdk-s3.so without build-id.
                Module libaws-cpp-sdk-transfer.so without build-id.
                Module libarchive.so.13 without build-id.
                Module libgit2.so.1.8 without build-id.
                Module libboost_context.so.1.81.0 without build-id.
                Module libgcc_s.so.1 without build-id.
                Module libstdc++.so.6 without build-id.
                Module liblowdown.so.1 without build-id.
                Module libeditline.so.1 without build-id.
                Stack trace of thread 128406:
                #0  0x00007ff7b6953df6 _ZN3nix8fetchers12downloadFileENS_3refINS_5StoreEEERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_RKSt6vectorISt4pairIS9_S9_ESaISE_EE (libnixfetchers.so + 0x9ddf6)
                #1  0x00007ff7b6c279cc _ZN3nixL5fetchERNS_9EvalStateENS_6PosIdxEPPNS_5ValueERS3_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEbSC_ (libnixexpr.so + 0x10a9cc)
                #2  0x00007ff7b6c27f9c _ZN3nixL13prim_fetchurlERNS_9EvalStateENS_6PosIdxEPPNS_5ValueERS3_ (libnixexpr.so + 0x10af9c)
                #3  0x00007ff7b6bb09ca _ZN3nix9EvalState12callFunctionERNS_5ValueEmPPS1_S2_NS_6PosIdxE (libnixexpr.so + 0x939ca)
                #4  0x00007ff7b6bb474c _ZN3nix8ExprCall4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x9774c)
                #5  0x00007ff7b6bb07b2 _ZN3nix9EvalState12callFunctionERNS_5ValueEmPPS1_S2_NS_6PosIdxE (libnixexpr.so + 0x937b2)
                #6  0x00007ff7b6bb474c _ZN3nix8ExprCall4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x9774c)
                #7  0x00007ff7b6baef7d _ZN3nix17ExprConcatStrings4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x91f7d)
                #8  0x00007ff7b6bb07b2 _ZN3nix9EvalState12callFunctionERNS_5ValueEmPPS1_S2_NS_6PosIdxE (libnixexpr.so + 0x937b2)
                #9  0x00007ff7b6bb8326 _ZN3nix9EvalState14coerceToStringENS_6PosIdxERNS_5ValueERSt3setINS_20NixStringContextElemESt4lessIS5_ESaIS5_EESt17basic_string_viewIcSt11char_traitsIcEEbbb (libnixexpr.so + 0x9b326)
                #10 0x00007ff7b6c18ab5 _ZN3nixL21prim_concatStringsSepERNS_9EvalStateENS_6PosIdxEPPNS_5ValueERS3_.lto_priv.0 (libnixexpr.so + 0xfbab5)
                #11 0x00007ff7b6bb09ca _ZN3nix9EvalState12callFunctionERNS_5ValueEmPPS1_S2_NS_6PosIdxE (libnixexpr.so + 0x939ca)
                #12 0x00007ff7b6bb474c _ZN3nix8ExprCall4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x9774c)
                #13 0x00007ff7b6baef7d _ZN3nix17ExprConcatStrings4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x91f7d)
                #14 0x00007ff7b6c02095 _ZN3nixL24derivationStrictInternalERNS_9EvalStateERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKNS_8BindingsERNS_5ValueE.lto_priv.0 (libnixexpr.so + 0xe5095)
                #15 0x00007ff7b6bfd17b _ZN3nixL21prim_derivationStrictERNS_9EvalStateENS_6PosIdxEPPNS_5ValueERS3_.lto_priv.0 (libnixexpr.so + 0xe017b)
                #16 0x00007ff7b6bb09ca _ZN3nix9EvalState12callFunctionERNS_5ValueEmPPS1_S2_NS_6PosIdxE (libnixexpr.so + 0x939ca)
                #17 0x00007ff7b6bb474c _ZN3nix8ExprCall4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x9774c)
                #18 0x00007ff7b6b9a7dd _ZN3nix9EvalState10forceAttrsIZNS0_10forceAttrsERNS_5ValueENS_6PosIdxESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_EEvS3_T_S8_ (libnixexpr.so + 0x7d7dd)
                #19 0x00007ff7b6bff8bd _ZN3nix12prim_getAttrERNS_9EvalStateENS_6PosIdxEPPNS_5ValueERS3_ (libnixexpr.so + 0xe28bd)
                #20 0x00007ff7b6bb09ca _ZN3nix9EvalState12callFunctionERNS_5ValueEmPPS1_S2_NS_6PosIdxE (libnixexpr.so + 0x939ca)
                #21 0x00007ff7b6bb474c _ZN3nix8ExprCall4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x9774c)
                #22 0x00007ff7b6bb2dee _ZN3nix10ExprSelect4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x95dee)
                #23 0x00007ff7b6bb83d2 _ZN3nix9EvalState14coerceToStringENS_6PosIdxERNS_5ValueERSt3setINS_20NixStringContextElemESt4lessIS5_ESaIS5_EESt17basic_string_viewIcSt11char_traitsIcEEbbb (libnixexpr.so + 0x9b3d2)
                #24 0x00007ff7b6bb8619 _ZN3nix9EvalState14coerceToStringENS_6PosIdxERNS_5ValueERSt3setINS_20NixStringContextElemESt4lessIS5_ESaIS5_EESt17basic_string_viewIcSt11char_traitsIcEEbbb (libnixexpr.so + 0x9b619)
                #25 0x00007ff7b6baee93 _ZN3nix17ExprConcatStrings4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x91e93)
                #26 0x00007ff7b6bb25d9 _ZN3nix7ExprVar4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x955d9)
                #27 0x00007ff7b6baef7d _ZN3nix17ExprConcatStrings4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x91f7d)
                #28 0x00007ff7b6baef7d _ZN3nix17ExprConcatStrings4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x91f7d)
                #29 0x00007ff7b6c02095 _ZN3nixL24derivationStrictInternalERNS_9EvalStateERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKNS_8BindingsERNS_5ValueE.lto_priv.0 (libnixexpr.so + 0xe5095)
                #30 0x00007ff7b6bfd17b _ZN3nixL21prim_derivationStrictERNS_9EvalStateENS_6PosIdxEPPNS_5ValueERS3_.lto_priv.0 (libnixexpr.so + 0xe017b)
                #31 0x00007ff7b6bb09ca _ZN3nix9EvalState12callFunctionERNS_5ValueEmPPS1_S2_NS_6PosIdxE (libnixexpr.so + 0x939ca)
                #32 0x00007ff7b6bb474c _ZN3nix8ExprCall4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x9774c)
                #33 0x00007ff7b6b9a7dd _ZN3nix9EvalState10forceAttrsIZNS0_10forceAttrsERNS_5ValueENS_6PosIdxESt17basic_string_viewIcSt11char_traitsIcEEEUlvE_EEvS3_T_S8_ (libnixexpr.so + 0x7d7dd)
                #34 0x00007ff7b6bff8bd _ZN3nix12prim_getAttrERNS_9EvalStateENS_6PosIdxEPPNS_5ValueERS3_ (libnixexpr.so + 0xe28bd)
                #35 0x00007ff7b6bb09ca _ZN3nix9EvalState12callFunctionERNS_5ValueEmPPS1_S2_NS_6PosIdxE (libnixexpr.so + 0x939ca)
                #36 0x00007ff7b6bb474c _ZN3nix8ExprCall4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x9774c)
                #37 0x00007ff7b6bb2dee _ZN3nix10ExprSelect4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x95dee)
                #38 0x00007ff7b6bb83d2 _ZN3nix9EvalState14coerceToStringENS_6PosIdxERNS_5ValueERSt3setINS_20NixStringContextElemESt4lessIS5_ESaIS5_EESt17basic_string_viewIcSt11char_traitsIcEEbbb (libnixexpr.so + 0x9b3d2)
                #39 0x00007ff7b6bb8619 _ZN3nix9EvalState14coerceToStringENS_6PosIdxERNS_5ValueERSt3setINS_20NixStringContextElemESt4lessIS5_ESaIS5_EESt17basic_string_viewIcSt11char_traitsIcEEbbb (libnixexpr.so + 0x9b619)
                #40 0x00007ff7b6baee93 _ZN3nix17ExprConcatStrings4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x91e93)
                #41 0x00007ff7b6baef7d _ZN3nix17ExprConcatStrings4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x91f7d)
                #42 0x00007ff7b6bb07b2 _ZN3nix9EvalState12callFunctionERNS_5ValueEmPPS1_S2_NS_6PosIdxE (libnixexpr.so + 0x937b2)
                #43 0x00007ff7b6bb8326 _ZN3nix9EvalState14coerceToStringENS_6PosIdxERNS_5ValueERSt3setINS_20NixStringContextElemESt4lessIS5_ESaIS5_EESt17basic_string_viewIcSt11char_traitsIcEEbbb (libnixexpr.so + 0x9b326)
                #44 0x00007ff7b6c18ab5 _ZN3nixL21prim_concatStringsSepERNS_9EvalStateENS_6PosIdxEPPNS_5ValueERS3_.lto_priv.0 (libnixexpr.so + 0xfbab5)
                #45 0x00007ff7b6bb09ca _ZN3nix9EvalState12callFunctionERNS_5ValueEmPPS1_S2_NS_6PosIdxE (libnixexpr.so + 0x939ca)
                #46 0x00007ff7b6bb474c _ZN3nix8ExprCall4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x9774c)
                #47 0x00007ff7b6bb07b2 _ZN3nix9EvalState12callFunctionERNS_5ValueEmPPS1_S2_NS_6PosIdxE (libnixexpr.so + 0x937b2)
                #48 0x00007ff7b6bb474c _ZN3nix8ExprCall4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x9774c)
                #49 0x00007ff7b6bb07b2 _ZN3nix9EvalState12callFunctionERNS_5ValueEmPPS1_S2_NS_6PosIdxE (libnixexpr.so + 0x937b2)
                #50 0x00007ff7b6bb474c _ZN3nix8ExprCall4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x9774c)
                #51 0x00007ff7b6baef7d _ZN3nix17ExprConcatStrings4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x91f7d)
                #52 0x00007ff7b6bb25d9 _ZN3nix7ExprVar4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x955d9)
                #53 0x00007ff7b6bb07b2 _ZN3nix9EvalState12callFunctionERNS_5ValueEmPPS1_S2_NS_6PosIdxE (libnixexpr.so + 0x937b2)
                #54 0x00007ff7b6bb474c _ZN3nix8ExprCall4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x9774c)
                #55 0x00007ff7b6baef7d _ZN3nix17ExprConcatStrings4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x91f7d)
                #56 0x00007ff7b6baef7d _ZN3nix17ExprConcatStrings4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x91f7d)
                #57 0x00007ff7b6c02095 _ZN3nixL24derivationStrictInternalERNS_9EvalStateERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPKNS_8BindingsERNS_5ValueE.lto_priv.0 (libnixexpr.so + 0xe5095)
                #58 0x00007ff7b6bfd17b _ZN3nixL21prim_derivationStrictERNS_9EvalStateENS_6PosIdxEPPNS_5ValueERS3_.lto_priv.0 (libnixexpr.so + 0xe017b)
                #59 0x00007ff7b6bb09ca _ZN3nix9EvalState12callFunctionERNS_5ValueEmPPS1_S2_NS_6PosIdxE (libnixexpr.so + 0x939ca)
                #60 0x00007ff7b6bb474c _ZN3nix8ExprCall4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x9774c)
                #61 0x00007ff7b6bb25d9 _ZN3nix7ExprVar4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x955d9)
                #62 0x00007ff7b6bb2752 _ZN3nix10ExprSelect4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x95752)
                #63 0x00007ff7b6bb2dee _ZN3nix10ExprSelect4evalERNS_9EvalStateERNS_3EnvERNS_5ValueE (libnixexpr.so + 0x95dee)
                
                Stack trace of thread 135910:
                #0  0x00007ff7b5e220af __poll (libc.so.6 + 0x1020af)
                #1  0x00007ff7b5367988 Curl_poll (libcurl.so.4 + 0x6c988)
                #2  0x00007ff7b535cc9c multi_wait.part.0 (libcurl.so.4 + 0x61c9c)
                #3  0x00007ff7b535ce57 curl_multi_wait (libcurl.so.4 + 0x61e57)
                #4  0x00007ff7b656ebb5 _ZN3nix16curlFileTransfer16workerThreadMainEv (libnixstore.so + 0x16ebb5)
                #5  0x00007ff7b65736a0 _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN3nix16curlFileTransferC4EvEUlvE_EEEEE6_M_runEv (libnixstore.so + 0x1736a0)
                #6  0x00007ff7b60e86d3 execute_native_thread_routine (libstdc++.so.6 + 0xe86d3)
                #7  0x00007ff7b5db0d02 start_thread (libc.so.6 + 0x90d02)
                #8  0x00007ff7b5e303ac __clone3 (libc.so.6 + 0x1103ac)
                
                Stack trace of thread 135914:
                #0  0x00007ff7b5e3086e epoll_wait (libc.so.6 + 0x11086e)
                #1  0x00007ff7b46fa0f0 aws_event_loop_thread (libaws-c-io.so.1.0.0 + 0x1f0f0)
                #2  0x00007ff7b45534b1 thread_fn (libaws-c-common.so.1 + 0x364b1)
                #3  0x00007ff7b5db0d02 start_thread (libc.so.6 + 0x90d02)
                #4  0x00007ff7b5e303ac __clone3 (libc.so.6 + 0x1103ac)
                
                Stack trace of thread 135917:
                #0  0x00007ff7b5e3086e epoll_wait (libc.so.6 + 0x11086e)
                #1  0x00007ff7b46fa0f0 aws_event_loop_thread (libaws-c-io.so.1.0.0 + 0x1f0f0)
                #2  0x00007ff7b45534b1 thread_fn (libaws-c-common.so.1 + 0x364b1)
                #3  0x00007ff7b5db0d02 start_thread (libc.so.6 + 0x90d02)
                #4  0x00007ff7b5e303ac __clone3 (libc.so.6 + 0x1103ac)
                
                Stack trace of thread 135918:
                #0  0x00007ff7b5e3086e epoll_wait (libc.so.6 + 0x11086e)
                #1  0x00007ff7b46fa0f0 aws_event_loop_thread (libaws-c-io.so.1.0.0 + 0x1f0f0)
                #2  0x00007ff7b45534b1 thread_fn (libaws-c-common.so.1 + 0x364b1)
                #3  0x00007ff7b5db0d02 start_thread (libc.so.6 + 0x90d02)
                #4  0x00007ff7b5e303ac __clone3 (libc.so.6 + 0x1103ac)
                
                Stack trace of thread 135919:
                #0  0x00007ff7b5e3086e epoll_wait (libc.so.6 + 0x11086e)
                #1  0x00007ff7b46fa0f0 aws_event_loop_thread (libaws-c-io.so.1.0.0 + 0x1f0f0)
                #2  0x00007ff7b45534b1 thread_fn (libaws-c-common.so.1 + 0x364b1)
                #3  0x00007ff7b5db0d02 start_thread (libc.so.6 + 0x90d02)
                #4  0x00007ff7b5e303ac __clone3 (libc.so.6 + 0x1103ac)
                
                Stack trace of thread 135921:
                #0  0x00007ff7b5e3086e epoll_wait (libc.so.6 + 0x11086e)
                #1  0x00007ff7b46fa0f0 aws_event_loop_thread (libaws-c-io.so.1.0.0 + 0x1f0f0)
                #2  0x00007ff7b45534b1 thread_fn (libaws-c-common.so.1 + 0x364b1)
                #3  0x00007ff7b5db0d02 start_thread (libc.so.6 + 0x90d02)
                #4  0x00007ff7b5e303ac __clone3 (libc.so.6 + 0x1103ac)
                
                Stack trace of thread 135920:
                #0  0x00007ff7b5e3086e epoll_wait (libc.so.6 + 0x11086e)
                #1  0x00007ff7b46fa0f0 aws_event_loop_thread (libaws-c-io.so.1.0.0 + 0x1f0f0)
                #2  0x00007ff7b45534b1 thread_fn (libaws-c-common.so.1 + 0x364b1)
                #3  0x00007ff7b5db0d02 start_thread (libc.so.6 + 0x90d02)
                #4  0x00007ff7b5e303ac __clone3 (libc.so.6 + 0x1103ac)
                
                Stack trace of thread 135922:
                #0  0x00007ff7b5e3086e epoll_wait (libc.so.6 + 0x11086e)
                #1  0x00007ff7b46fa0f0 aws_event_loop_thread (libaws-c-io.so.1.0.0 + 0x1f0f0)
                #2  0x00007ff7b45534b1 thread_fn (libaws-c-common.so.1 + 0x364b1)
                #3  0x00007ff7b5db0d02 start_thread (libc.so.6 + 0x90d02)
                #4  0x00007ff7b5e303ac __clone3 (libc.so.6 + 0x1103ac)
                
                Stack trace of thread 135915:
                #0  0x00007ff7b5e3086e epoll_wait (libc.so.6 + 0x11086e)
                #1  0x00007ff7b46fa0f0 aws_event_loop_thread (libaws-c-io.so.1.0.0 + 0x1f0f0)
                #2  0x00007ff7b45534b1 thread_fn (libaws-c-common.so.1 + 0x364b1)
                #3  0x00007ff7b5db0d02 start_thread (libc.so.6 + 0x90d02)
                #4  0x00007ff7b5e303ac __clone3 (libc.so.6 + 0x1103ac)
                
                Stack trace of thread 128407:
                #0  0x00007ff7b5d613da __sigtimedwait (libc.so.6 + 0x413da)
                #1  0x00007ff7b5d609ec sigwait (libc.so.6 + 0x409ec)
                #2  0x00007ff7b63a0de5 _ZN3nixL19signalHandlerThreadE10__sigset_t (libnixutil.so + 0xd9de5)
                #3  0x00007ff7b639f03c _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJPFv10__sigset_tES3_EEEEE6_M_runEv (libnixutil.so + 0xd803c)
                #4  0x00007ff7b60e86d3 execute_native_thread_routine (libstdc++.so.6 + 0xe86d3)
                #5  0x00007ff7b5db0d02 start_thread (libc.so.6 + 0x90d02)
                #6  0x00007ff7b5e303ac __clone3 (libc.so.6 + 0x1103ac)
                
                Stack trace of thread 135911:
                #0  0x00007ff7b5e3086e epoll_wait (libc.so.6 + 0x11086e)
                #1  0x00007ff7b46fa0f0 aws_event_loop_thread (libaws-c-io.so.1.0.0 + 0x1f0f0)
                #2  0x00007ff7b45534b1 thread_fn (libaws-c-common.so.1 + 0x364b1)
                #3  0x00007ff7b5db0d02 start_thread (libc.so.6 + 0x90d02)
                #4  0x00007ff7b5e303ac __clone3 (libc.so.6 + 0x1103ac)
                
                Stack trace of thread 135912:
                #0  0x00007ff7b5e3086e epoll_wait (libc.so.6 + 0x11086e)
                #1  0x00007ff7b46fa0f0 aws_event_loop_thread (libaws-c-io.so.1.0.0 + 0x1f0f0)
                #2  0x00007ff7b45534b1 thread_fn (libaws-c-common.so.1 + 0x364b1)
                #3  0x00007ff7b5db0d02 start_thread (libc.so.6 + 0x90d02)
                #4  0x00007ff7b5e303ac __clone3 (libc.so.6 + 0x1103ac)
                
                Stack trace of thread 135916:
                #0  0x00007ff7b5e3086e epoll_wait (libc.so.6 + 0x11086e)
                #1  0x00007ff7b46fa0f0 aws_event_loop_thread (libaws-c-io.so.1.0.0 + 0x1f0f0)
                #2  0x00007ff7b45534b1 thread_fn (libaws-c-common.so.1 + 0x364b1)
                #3  0x00007ff7b5db0d02 start_thread (libc.so.6 + 0x90d02)
                #4  0x00007ff7b5e303ac __clone3 (libc.so.6 + 0x1103ac)
                
                Stack trace of thread 135913:
                #0  0x00007ff7b5e3086e epoll_wait (libc.so.6 + 0x11086e)
                #1  0x00007ff7b46fa0f0 aws_event_loop_thread (libaws-c-io.so.1.0.0 + 0x1f0f0)
                #2  0x00007ff7b45534b1 thread_fn (libaws-c-common.so.1 + 0x364b1)
                #3  0x00007ff7b5db0d02 start_thread (libc.so.6 + 0x90d02)
                #4  0x00007ff7b5e303ac __clone3 (libc.so.6 + 0x1103ac)
                ELF object binary architecture: AMD x86-64
```

**Steps To Reproduce**

builtins.fetchurl "s3://highlighter-public/405b3ba02ccb2f07ec6aba9f233d4194.mp4?region=ap-southeast-2"

**Expected behavior**

**`nix-env --version` output**

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by edolstra**
# Motivation

Fixes #11674.

Also, add an activity to show that we're downloading an s3:// file.

# Context

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

File: src/libstore/filetransfer.cc [hunk 1]
```diff
@@ -759,12 +759,17 @@ struct curlFileTransfer : public FileTransfer
...
+                    fmt("downloading '%s'", request.uri),
+                    {request.uri}, request.parentAct);
+
                 // FIXME: implement ETag
                 auto s3Res = s3Helper.getObject(bucketName, key);
                 FileTransferResult res;
                 if (!s3Res.data)
                     throw FileTransferError(NotFound, "S3 object '%s' does not exist", request.uri);
                 res.data = std::move(*s3Res.data);
+                res.urls.push_back(request.uri);
```
Comment (roberth) [inline src/libstore/filetransfer.cc:772]: I assume some other code assumes `urls` to be non-empty, or what was the chain of events that leads to the segfault?

Perhaps we're missing an `assert(!urls.empty())` somewhere?

**Review by roberth — COMMENTED** [review]
I love bugfixes.
Have a question/suggestion, but other than that, LGTM.

**Review by tomberek — APPROVED** [review]

File: src/libstore/filetransfer.cc (hunk 1 above)
Comment (edolstra) [reply src/libstore/filetransfer.cc:772]: `downloadFile()` uses `*res.urls.rbegin()` to get the final URL in the redirect chain.

I've added an assert.

**Review by roberth — APPROVED** [review]
