### PR TITLE
darwin-install: fix break from bad vim plugins

### LINKED ISSUE #5468: Unable to install Nix
**Describe the bug**
Unable to install Nix on MacOS Catalina

**Terminal Output**

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/ex /etc/synthetic.conf

to add Nix to /etc/synthetic.conf

---- oh no! --------------------------------------------------------------------
Jeeze, something went wrong. If you can take all the output and open
an issue, we'd love to fix the problem so nobody else has this issue.

:(

What should my next step be? Thanks!!

### PR DESCRIPTION
**Pull request by abathur**
Should fix #5468, which turned out to be an issue with vimrc/plugin files on the user's system somehow interfering with /usr/bin/ex's ability to return a clean exit code on a successful edit, and subsequently halting the install.

User confirmed they were able to install after downloading the installer and making roughly-equivalent edits.

It doesn't really need to be reviewed here, but for posterity I've attached a [log](https://github.com/NixOS/nix/files/7472311/output.log) the user submitted on Matrix, with verbosity turned up on invocation of ex, and trace on in this section of the install script.

<details><summary>Update: there's a test installer if you're stuck on this:</summary>

Here's how to run the installer built from the [CI process](https://github.com/abathur/nix/actions/runs/1419832582) on my branch:

```console
sh <(curl -L https://abathur-nix-install-tests.cachix.org/serve/b0qcp50ssgbxl3mw440q5696fwsc5vf7/install) --tarball-url-prefix https://abathur-nix-install-tests.cachix.org/serve
```

I've updated the installer to simplify the implementation, but I'll also link the installer (generated by this [CI process](https://github.com/abathur/nix/actions/runs/1552383867) on my branch) for the initial implementation just in case:

```console
sh <(curl -L https://abathur-nix-install-tests.cachix.org/serve/v572agz9xad3az9sxdqn2xdc21rs5ibd/install) --tarball-url-prefix https://abathur-nix-install-tests.cachix.org/serve
```
</details>

### CODE REVIEW

File: scripts/create-darwin-volume.sh [hunk 1]
```diff
@@ -435,12 +435,21 @@ EOF
...
     shift
-    EDITOR="/usr/bin/ex" _sudo "to add nix to fstab" "$@" <<EOF
+    # exporting vim variables to work around a problem with vim plugins
+    # breaking the exit codes; see https://github.com/NixOS/nix/issues/5468
+    # we'd prefer --noplugin flag as elsewhere, but vifs doesn't word-split
+    # the EDITOR env.
+    # VIM == keep it from loading system plugins
+    # HOME == keep it from loading user plugins
+    # EDITOR == just telling vifs which editor to use
+    export VIM=/dev/null HOME= EDITOR="/usr/bin/ex"
```
Comment (abathur) [inline scripts/create-darwin-volume.sh:451]: This is a little dumb, so I'm happy if someone else who knows vim better can find a cleaner solution. 

We're exporting editor so that `vifs` will use it, but including flags in the env didn't seem to work (it doesn't appear to word-split the env). Vim makes it easy to disable this with either the -u NONE or --noplugin flags, but we can't use them here. I tried something like `export VIMINIT="set noloadplugins"`, but I couldn't get that working (I saw some mention that makes me think this may happen _too early_ to matter here?)

Setting VIM and HOME is just making it search the wrong locations for the plugins.

You can play with this behavior like:
```console
$ echo blah | ex -V10
Searching for "pack/*/start/*" in "/Users/abathur/.vim,/dev/null/vimfiles,/dev/null,/dev/null/vimfiles/after,/Users/abathur/.vim/after"
Searching for "/Users/abathur/.vim/pack/*/start/*"
Searching for "/dev/null/vimfiles/pack/*/start/*"
Searching for "/dev/null/pack/*/start/*"
Searching for "/dev/null/vimfiles/after/pack/*/start/*"
Searching for "/Users/abathur/.vim/after/pack/*/start/*"
not found in 'packpath': "pack/*/start/*"
Searching for "plugin/**/*.vim" in "/Users/abathur/.vim,/dev/null/vimfiles,/dev/null,/dev/null/vimfiles/after,/Users/abathur/.vim/after"
Searching for "/Users/abathur/.vim/plugin/**/*.vim"
Searching for "/dev/null/vimfiles/plugin/**/*.vim"
Searching for "/dev/null/plugin/**/*.vim"
not found in 'packpath': "plugin/**/*.vim"
Searching for "pack/*/start/*" in "/Users/abathur/.vim,/dev/null/vimfiles,/dev/null,/dev/null/vimfiles/after,/Users/abathur/.vim/after"
Searching for "/Users/abathur/.vim/pack/*/start/*"
Searching for "/dev/null/vimfiles/pack/*/start/*"
Searching for "/dev/null/pack/*/start/*"
Searching for "/dev/null/vimfiles/after/pack/*/start/*"
Searching for "/Users/abathur/.vim/after/pack/*/start/*"
not found in 'packpath': "pack/*/start/*"
Searching for "plugin/**/*.vim" in "/Users/abathur/.vim,/dev/null/vimfiles,/dev/null,/dev/null/vimfiles/after,/Users/abathur/.vim/after"
Searching for "/dev/null/vimfiles/after/plugin/**/*.vim"
Searching for "/Users/abathur/.vim/after/plugin/**/*.vim"
not found in 'runtimepath': "plugin/**/*.vim" 
Entering Ex mode.  Type "visual" to go to Normal mode.
:blah
E492: Not an editor command: blah

$ echo blah | ex --noplugin -V10
Entering Ex mode.  Type "visual" to go to Normal mode.
:blah
E492: Not an editor command: blah
```

**Comment by abathur** [comment]
Converting this to a draft briefly. lunik1 suggested another approach on Matrix; I should have a better fix pushed up later.

File: scripts/create-darwin-volume.sh (hunk 1 above)
Comment (abathur) [reply scripts/create-darwin-volume.sh]: Replaced this process with a shell wrapper.

File: scripts/create-darwin-volume.sh [hunk 2]
```diff
@@ -631,7 +646,7 @@ EOF
         # technically /etc/synthetic.d/nix is supported in Big Sur+
         # but handling both takes even more code...
         _sudo "to add Nix to /etc/synthetic.conf" \
-            /usr/bin/ex /etc/synthetic.conf <<EOF
+            /usr/bin/ex --noplugin /etc/synthetic.conf <<EOF
```
Comment (cole-h) [inline scripts/create-darwin-volume.sh:649]: May be a bit more verbose, but would it be a good idea to use the wrapper here as well? So that these instances don't fall out of sync?

Comment (abathur) [reply scripts/create-darwin-volume.sh:649]: I agree with the suggestion, and I'll draft something locally, but I'm feeling a little time-pressured to want to risk tacking it on here.

It's been over 5 weeks since the last release and I'm getting anxious about this fix getting in and released. The CI cycle time on these is about 1.5h at the moment, assuming the build doesn't flake, and I'll have limited time the next few days as we get our ducks in a row for a family wedding. 😬
