### PR TITLE
Fix the removal of ca-induced self-references

### LINKED ISSUE #5320: `nix store gc` fails to delete self-referred path: executing SQLite statement 'delete from ValidPaths where path = '...';': constraint failed
**Describe the bug**

My nix store is in state that does not allow removing seemingly unused stored path:

```
$ nix store gc
0 store paths deleted, 0.00 MiB freed
error: executing SQLite statement 'delete from ValidPaths where path = '/nix/store/2pklamh9d8x964wbawway71rks402bxr-gcc-11.1.0-lib';': constraint failed (in '/nix/var/nix/db/db.sqlite')
```

**`nix-env --version` output**

nix-env (Nix) 2.4pre20210922_bcd73eb

Attaching full vacuumed `db.sqlite`: 
[db.sqlite.gz](https://github.com/NixOS/nix/files/7271172/db.sqlite.gz)

### PR DESCRIPTION
**Pull request by thufschmitt**
If the derivation `foo` depends on `bar`, and they both have the same
output path (because they are CA derivations), then this output path
will depend both on the realisation of `foo` and of `bar`, which
themselves depend on each other.
This confuses SQLite which isn’t able to automatically solve this
diamond dependency scheme.

Help it by adding a trigger to delete all the references between the
relevant realisations.

Fix #5320

### CODE REVIEW

File: src/libstore/local-store.cc [hunk 1]
```diff
@@ -130,6 +130,19 @@ void migrateCASchema(SQLite& db, Path schemaPath, AutoCloseFD& lockFd)
             txn.commit();
         }
 
+        if (curCASchema < 3) {
```
Comment (cole-h) [inline src/libstore/local-store.cc:133]: Not totally related to this PR, but I wonder if you could take inspiration from the Hydra db migration setup instead of bloating this file with potentially loads of migrations.

Specifically, I'd imagine there would be a directory full of `.sql` schemas alongside the `ca-specific-schema.sql` and this function would instead just sequentially run all of the transactions that haven't happened yet, according to the current schema version.

(Maybe this was talked about in a past PR / issue / the RFC; if so, sorry)

Comment (regnat) [reply src/libstore/local-store.cc:133]: Indeed, that could be much nicer. I just blindly copied what already existed for the standard schema :D

Comment (cole-h) [reply src/libstore/local-store.cc:133]: I created a new issue so that others can chime in with their thoughts / feelings (specifically, Eelco and other source stakeholders): https://github.com/NixOS/nix/issues/5482

**Review by Sahabee — COMMENTED** [review]
_****_

File: src/libstore/ca-specific-schema.sql [hunk 2]
```diff
@@ -13,6 +13,19 @@ create table if not exists Realisations (
...
 
+-- We can end-up in a weird edge-case where a path depends on itself because
+-- it’s an output of a CA derivation, that happens to be the same as one of its
+-- dependencies.
+-- In that case we have a dependency loop (path -> realisation1 -> realisation2
+-- -> path) that we need to break by removing the dependencies between the
+-- realisations
+create trigger if not exists DeleteSelfRefsViaRealisations before delete on ValidPaths
+  begin
+    delete from RealisationsRefs where realisationReference = (
```
Comment (trofi) [inline src/libstore/ca-specific-schema.sql:24]: I gave it a go on real system and it fails to delete entries still. I suggest the following change:

`delete from RealisationsRefs where realisationReference = ( ...` -> `delete from RealisationsRefs where realisationReference IN (...`. I think we expect multiple realizations to point to the same store path worst case. Not just one.

With `IN` I was able to collect all the garbage on my system \o/.

File: src/libstore/local-store.cc [hunk 3]
```diff
@@ -130,6 +130,19 @@ void migrateCASchema(SQLite& db, Path schemaPath, AutoCloseFD& lockFd)
...
+            SQLiteTxn txn(db);
+            db.exec(R"(
+                create trigger if not exists DeleteSelfRefsViaRealisations before delete on ValidPaths
+                begin
+                    delete from RealisationsRefs where realisationReference = (
```
Comment (trofi) [inline src/libstore/local-store.cc:138]: Same here: `=` -> `IN`.

**Review by trofi — CHANGES_REQUESTED** [review]

File: src/libstore/ca-specific-schema.sql (hunk 2 above)
Comment (trofi) [inline src/libstore/ca-specific-schema.sql:24]: I also suggest adding `CREATE INDEX IndexRealisationsRefsRealisationReference on RealisationsRefs(realisationReference);` index.

Before the index we linearly scan all the RealisationRefs:

```
sqlite>.eqp full
sqlite> delete from RealisationsRefs where realisationReference IN ( select id from Realisations where outputPath = 1234567890 );
QUERY PLAN
|--SCAN RealisationsRefs
`--LIST SUBQUERY 1
   `--SEARCH Realisations USING COVERING INDEX IndexRealisationsRefsOnOutputPath (outputPath=?)
```

After the index bots are index lookups:

```
sqlite> CREATE INDEX IndexRealisationsRefsRealisationReference on RealisationsRefs(realisationReference);
sqlite> delete from RealisationsRefs where realisationReference IN ( select id from Realisations where outputPath = 1234567890 );
QUERY PLAN
|--SEARCH RealisationsRefs USING INDEX IndexRealisationsRefsRealisationReference (realisationReference=?)
`--LIST SUBQUERY 1
   `--SEARCH Realisations USING COVERING INDEX IndexRealisationsRefsOnOutputPath (outputPath=?)
```

Comment (Sahabee) [reply src/libstore/ca-specific-schema.sql:24]: I m larner

**Comment by Ericson2314** [comment]
I'm a bit confused, is this just temporarily deleting some edges, such that the DB "at rest" shouldn't be different? Or is this permently deleting some edges?

**Comment by trofi** [comment]
> I'm a bit confused, is this just temporarily deleting some edges, such that the DB "at rest" shouldn't be different? Or is this permently deleting some edges?

I think this change does neither. The "self-reference-looking" edges are still stored in database and kept being created. Now they can be deleted when path is deleted by `nix-collect-garbage` instead of failing with foreign key constraint violation.

**Comment by regnat** [comment]
> is this just temporarily deleting some edges, such that the DB "at rest" shouldn't be different?

Yes, this is just “forcing” the order in which the related references are removed when we remove a derivation output, because SQLite sees a circular dependency with some `ON DELETE RESTRICT` in the middle, so it can’t do the removal.
In essence this is the same thing as https://github.com/NixOS/nix/blob/bceda304982a34c65d5a1dab449cb5bc59f63b83/src/libstore/schema.sql#L29-L32, just slightly more involved

**Comment by Ericson2314** [comment]
OK whew thanks for confirming :).

**Comment by regnat** [comment]
Rebased on top of #5366 . Should be good to go as soon as #5366 is merged

**Comment by zseri** [comment]
from the build log:
```
2021-12-14T08:58:34.5628351Z     deleting garbage...
2021-12-14T08:58:34.5629635Z     deleting '/build/nix-test/tests/ca/selfref-gc/store/0hmsy2dxg652l7iidg82civ38q2fmsz7-selfref-gc.drv'
2021-12-14T08:58:34.5632185Z     error: executing SQLite statement 'delete from ValidPaths where path = '/build/nix-test/tests/ca/selfref-gc/store/dwxdqfjaym0shbk7iwcnqxdx9z49acz3-selfref-gc';': constraint failed (in '/build/nix-test/tests/ca/selfref-gc/var/nix/db/db.sqlite')
2021-12-14T08:58:34.5633827Z     0 store paths deleted, 0.00 MiB freed
```
doesn't seem like it reliably works.

**Comment by regnat** [comment]
> Mh, must be an issue with the rebase. I’ll have a look

Ah of course, was the `requireDaemonNewerThan` call which wasn’t right anymore. Should be good now :crossed_fingers:

**Comment by thufschmitt** [comment]
@edolstra anything I should do to get this merged?

**Comment by trofi** [comment]
I'd suggest adding indices: https://github.com/NixOS/nix/pull/5479#pullrequestreview-797014560

File: src/libstore/ca-specific-schema.sql (hunk 2 above)
Comment (trofi) [reply src/libstore/ca-specific-schema.sql]: Proposed as https://github.com/NixOS/nix/pull/6324 into this branch.

**Review by trofi — APPROVED** [review]

**Comment by Ericson2314** [comment]
@thufschmitt when I was working on another unrelated change I noticed we can currently have realization->realization self-references (because we don't filter out self-references when write realization deps). Would that help with this?
