### PR TITLE
Actually ignore system/user registries during locking (2nd attempt)

### LINKED ISSUE #13050: User registry ignored on `nix eval` and `nix build`
## Describe the bug

Since #12979 not only the behavior of locking is changed, but also the behavior of `nix build` and `nix eval`.

## Steps To Reproduce

```console
$ nix --version
nix (Nix) 2.28.1
$ nix registry add p nixpkgs
$ nix eval p#path
/nix/store/0d3h8gi2q46fb4l563h6pginjw2a90r4-source
```

```console
$ nix --version
nix (Nix) 2.29.0pre20250418_f683a55
$ nix registry add p nixpkgs
$ nix eval p#path
error: cannot find flake 'flake:p' in the flake registries
```

## Expected behavior

`nix build` and `nix eval` should also respect the user registry.

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open bug issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by edolstra**
## Motivation

Makes https://github.com/NixOS/nix/pull/12068 actually work. All registries are used for resolving top-level flakerefs, but only the global and flag registries are used for resolving flake inputs.

Fixes #13050.

## Context

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by SharzyL** [comment]
Should we also add tests to verify user registry not ignored with other operations (to prevent something like #13050)?

File: tests/functional/flakes/flakes.sh [hunk 1]
```diff
@@ -220,6 +220,13 @@ nix store gc
 nix registry list --flake-registry "file://$registry" --refresh | grepQuiet flake3
 mv "$registry.tmp" "$registry"
 
+# Ensure that locking ignores the user registry.
+mkdir -p "$TEST_HOME/.config/nix"
+ln -sfn "$registry" "$TEST_HOME/.config/nix/registry.json"
+nix flake metadata --flake-registry '' flake1
```
Comment (Mic92) [inline tests/functional/flakes/flakes.sh:226]: @edolstra it looks like the test was not able to capture the previous regression. Do you know why this is the case?

Comment (Mic92) [reply tests/functional/flakes/flakes.sh:226]: Ah, We actually tried to use a flake from the registry. So this usecase is not tested in this pull request.

**Comment by Mic92** [comment]
> Should we also add tests to verify user registry not ignored with other operations (to prevent something like #13050)?

Yeah. At least in nixpkgs we have now a patch merged and backported, so we can take this pull request a bit slower.

**Comment by Mic92** [comment]
Looks like the test is only testing "global" registry entries:

```
\[\][\[\]joerg@turingmachine:/home/joerg/git/nix/tests/functional/flakes]$\[\] nix registry list
global flake:flake2 git+file:///tmp/nix-test/flakes/flakes/flake%202
global flake:flake1 git+file:///tmp/nix-test/flakes/flakes/flake1
global flake:flake3 git+file:///tmp/nix-test/flakes/flakes/flake%2520
global flake:nixpkgs flake:flake1
```
