### PR TITLE
fix: valid branch name

### LINKED ISSUE #6534: GitHub flake URI scheme refuses valid branch identifiers
**Describe the bug**

Some branch identifiers accepted w/o warning by Git are rejected when given as refs for the GitHub flake URI scheme, whether after the second slash or as a query parameter.

Specifically, `blender--desktop+proper-overlay` is rejected but accepted by both Git and GitHub.

**Steps To Reproduce**

1. Create a GitHub repository
2. Create a branch named `blender--desktop+proper-overlay`
3. Create a flake
4. Create an input whose URI references your GitHub repository at the branch `blender--desktop+proper-overlay`, e.g.:
    `"github:maxmFusilQooper/myFantasticDinosaur/blender--desktop+proper-overlay"`

**Expected behavior**

The repository at that branch is pulled in and used for Flake evaluation.

**`nix-env --version` output**

```
nix-env (Nix) 2.9.0pre20220505_f4102de
```

**Additional context**

The repository was https://github.com/schuelermine/nix-warez, a fork of https://github.com/edolstra/nix-warrez.

The error message was:

```
error: URL 'github:schuelermine/nix-warez?ref=blender--desktop%2Bproper-overlay&dir=blender' contains an invalid branch/tag name
```

### PR DESCRIPTION
**Pull request by blaggacao**
closes #6534

`ref` with a `+` still needs to be encoded `%2B` in `flake.nix` so that the query to gitlab becoms `https://gitlab.com/api/v4/projects/some%2Fowner%2Fmyrepo/repository/commits?ref_name=v0.0.1%2Blocal` (`v0.0.1%2Blocal`).

Please feel free to add a suitable commit to fix that, as well. I unfortunately can't muster the research. https://github.com/NixOS/nix/issues/6534#issuecomment-1129809605 promised a quick fix and this got me unblocked.

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

### CODE REVIEW

**Review by roberth — DISMISSED** [review]
I don't think we can afford fixes without tests.

**Comment by roberth** [comment]
> I don't think we can afford fixes without tests.

The implementation is so bad that it doesn't even make sense to test it. We might as well merge this in the interim.

File: src/libutil/url-parts.hh [hunk 1]
```diff
@@ -25,7 +25,8 @@ const static std::string pathRegex = "(?:" + segmentRegex + "(?:/" + segmentRege
 
 /// A Git ref (i.e. branch or tag name).
 /// \todo check that this is correct.
-const static std::string refRegexS = "[a-zA-Z0-9@][a-zA-Z0-9_.\\/@-]*";
+/// This regex incomplete. See https://git-scm.com/docs/git-check-ref-format
+const static std::string refRegexS = "[a-zA-Z0-9@][a-zA-Z0-9_.\\/@-+]*";
```
Comment (roberth) [inline src/libutil/url-parts.hh:29]:
```suggestion
const static std::string refRegexS = "[a-zA-Z0-9@][a-zA-Z0-9_.\\/@+-]*";
```

That's what you (we) get for using stringly regex syntax :facepalm:
