### PR TITLE
preloadNSS: fixup nss_dns load

### LINKED ISSUE #5089: Nix 2.3.15 Sandbox Domain Resolution Failures
**Describe the bug**

Since the update to 2.3.15, nix build is no longer able to resolve domain lookups with sandboxing:

```
warning: unable to download 'http://tarballs.nixos.org/sha256/73d3baf18cf0a197976af2794a848893c35e7d42cee0ff364c89d2e476ebdaa6': Couldn't resolve host name (6); retrying in 300 ms
warning: unable to download 'http://tarballs.nixos.org/sha256/74d97de74c1d4d5cc146182dbbf9cdc3f383ba4c5d1492edbdb14351549a9d64': Couldn't resolve host name (6); retrying in 351 ms
warning: unable to download 'http://tarballs.nixos.org/sha256/73d3baf18cf0a197976af2794a848893c35e7d42cee0ff364c89d2e476ebdaa6': Couldn't resolve host name (6); retrying in 658 ms
warning: unable to download 'http://tarballs.nixos.org/sha256/74d97de74c1d4d5cc146182dbbf9cdc3f383ba4c5d1492edbdb14351549a9d64': Couldn't resolve host name (6); retrying in 518 ms
warning: unable to download 'http://tarballs.nixos.org/sha256/74d97de74c1d4d5cc146182dbbf9cdc3f383ba4c5d1492edbdb14351549a9d64': Couldn't resolve host name (6); retrying in 1366 ms
warning: unable to download 'http://tarballs.nixos.org/sha256/73d3baf18cf0a197976af2794a848893c35e7d42cee0ff364c89d2e476ebdaa6': Couldn't resolve host name (6); retrying in 1155 ms
warning: unable to download 'http://tarballs.nixos.org/sha256/73d3baf18cf0a197976af2794a848893c35e7d42cee0ff364c89d2e476ebdaa6': Couldn't resolve host name (6); retrying in 2750 ms
warning: unable to download 'http://tarballs.nixos.org/sha256/74d97de74c1d4d5cc146182dbbf9cdc3f383ba4c5d1492edbdb14351549a9d64': Couldn't resolve host name (6); retrying in 2416 ms
warning: unable to download 'https://addons.mozilla.org/firefox/downloads/file/3782413/new_tab_override-15.1.1-fx.xpi': Couldn't resolve host name (6); retrying in 298 ms
warning: unable to download 'https://www.rarlab.com/rar/unrarsrc-5.9.2.tar.gz': Couldn't resolve host name (6); retrying in 341 ms
warning: unable to download 'https://addons.mozilla.org/firefox/downloads/file/3782413/new_tab_override-15.1.1-fx.xpi': Couldn't resolve host name (6); retrying in 546 ms
warning: unable to download 'https://www.rarlab.com/rar/unrarsrc-5.9.2.tar.gz': Couldn't resolve host name (6); retrying in 590 ms
warning: unable to download 'https://addons.mozilla.org/firefox/downloads/file/3782413/new_tab_override-15.1.1-fx.xpi': Couldn't resolve host name (6); retrying in 1310 ms
warning: unable to download 'https://www.rarlab.com/rar/unrarsrc-5.9.2.tar.gz': Couldn't resolve host name (6); retrying in 1052 ms
warning: unable to download 'https://addons.mozilla.org/firefox/downloads/file/3782413/new_tab_override-15.1.1-fx.xpi': Couldn't resolve host name (6); retrying in 2534 ms
warning: unable to download 'https://www.rarlab.com/rar/unrarsrc-5.9.2.tar.gz': Couldn't resolve host name (6); retrying in 2033 ms
```

**Steps To Reproduce**

1. Use Nix 2.3.15
2. Use the stock nsswitch.conf from NixOS (presumably with resolved enabled)

**Expected behavior**

Domain lookups to work.

**`nix-env --version` output**

```
❯ nix-env --version
nix-env (Nix) 2.3.15
```

**Additional context**

I tried building without the sandbox, which made it able to resolve domain lookups. This indicates the sandbox cannot actually resolve things as a result of e8711461794ffec203911cc7b6cc4c1319e8f74d. On top of this, at the suggestion of @arcnmx, I removed `[!UNAVAIL=return]` from the host nsswitch.conf and built something differently (for which downloads weren't cached) with sandbox on. ~~It was able to do resolution again.~~ It did not adequately fix the problem.

resolv.conf is currently: `nameserver 1.1.1.1` for testing purposes, however:

I use `useLocalResolver` with resolvconf, for dnscrypt-proxy purposes normally.

I was suggested `--extra-sandbox-paths /var/run/nscd/socket=/var/run/nscd/socket` and this actually makes it work perfectly. This would suggest that the behavior at hand is indeed caused by the removal of nscd socket passthrough and the alternative workaround in the PR not sufficiently working. 

I will be using `nix.sandboxPaths = [ "/var/run/nscd/socket" ];` as a workaround for the time being.

### PR DESCRIPTION
**Pull request by baloo**
Before this commit, the dns lookup in preloadNSS would still go through
nscd. This did not have the effect of loading the nss_dns.so as expected
(nss_dns.so being out of reach from within the sandbox).

Should LOCALDOMAIN environment variable be defined, nss will completely
avoid nscd and will do its dns resolution on its own.

By temporarly setting LOCALDOMAIN variable before calling in NSS, we can
force NSS to load the shared libraries as expected.

Fixes #5089

### CODE REVIEW

**Comment by baloo** [comment]
This is completely untested, I still haven't been able to reproduce the issue #5089 in any of my environments.

**Comment by tomberek** [comment]
https://sourceware.org/git/?p=glibc.git;a=blob;f=nscd/nscd_getai.c;hb=b8c6166b1b75036ab3e4127a1c0aacf52ca93651#l47

**Comment by baloo** [comment]
Got my environment to reproduce the bug. I also got https://github.com/NixOS/nixpkgs/pull/135689/files automated test to reproduce the bug.

This fixes the test:
```
diff --git a/pkgs/tools/package-management/nix/default.nix b/pkgs/tools/package-management/nix/default.nix
index c10b439515d..87d69fefc1a 100644
--- a/pkgs/tools/package-management/nix/default.nix
+++ b/pkgs/tools/package-management/nix/default.nix
@@ -229,6 +229,13 @@ in rec {
     boehmgc = boehmgc_nix;

     inherit storeDir stateDir confDir;
+
+    patches = [
+      (fetchpatch {
+        url = "https://github.com/baloo/nix-1/commit/3d75d87bd3affc59e5d725f218b7cd4b3b38180b.patch";
+        sha256 = "sha256-2B+Fr8xpQMZydFgDM/jgKtIJ/+wa+8CpJYMafJ4mME8=";
+      })
+    ];
   });

   nixUnstable = lib.lowPrio (callPackage common rec {
```

(this is a backport to 2.3.15)

**Comment by baloo** [comment]
Deployed it locally (from baloo/nix/sandbox-dns-lookup branch) and `nix-build -E 'import <nix/fetchurl.nix> { url = "http://example.com"; sha256 = ""; }'` now works fine.

File: src/libstore/build/local-derivation-goal.cc [hunk 1]
```diff
@@ -354,9 +354,19 @@ static void preloadNSS() {
     std::call_once(dns_resolve_flag, []() {
         struct addrinfo *res = NULL;
 
-        if (getaddrinfo("this.pre-initializes.the.dns.resolvers.invalid.", "http", NULL, &res) != 0) {
+        /* nss will only force the "local" (not through nscd) dns resolution if its on the LOCALDOMAIN.
+           We need the resolution to be done locally, as nscd socket will not be accessible in the
+           sandbox. */
+        char * previous_env = getenv("LOCALDOMAIN");
+        setenv("LOCALDOMAIN", "invalid", 1);
```
Comment (edolstra) [inline src/libstore/build/local-derivation-goal.cc:361]: Changing the environment is not thread-safe (and there *can* be other threads running concurrently, like the auto-GC thread).

Comment (baloo) [reply src/libstore/build/local-derivation-goal.cc:361]: I completely agree with that, but I haven't found any other way to force libc to load nss components.

What would you think about moving the call to preloadNSS at the start of the nix-daemon? There would only be on thread and no thread-safety issue.

Comment (baloo) [reply src/libstore/build/local-derivation-goal.cc:361]: One alternative is to inject glibc inside the fetcher sandbox. I don't believe this would cause any major non-reproducibility.
I can work on that, let me know what you think is best.

Comment (edolstra) [reply src/libstore/build/local-derivation-goal.cc:361]: Doing it at the start in `initNix()` sounds good to me.

**Comment by baloo** [comment]
credits @tomberek 
```
# reproduce:
nix build github:baloo/nixpkgs/baloo/tests/nix-fetch#nixosTests.nix-fetch -L
# fixed:
nix build github:baloo/nixpkgs/baloo/nix/sandbox-dns-lookup#nixosTests.nix-fetch -L
```

**Comment by tomberek** [comment]
@edolstra Does this need a backport to 2.3 and a new release of 2.3.16? Or merge https://github.com/NixOS/nixpkgs/pull/137197 ?

**Comment by baloo** [comment]
@tomberek 2.3 backport: https://github.com/NixOS/nix/pull/5228 (merged)
