### PR TITLE
Fix nested flake input overrides

### LINKED ISSUE #5790: Transitive inputs "not in registry"
**Describe the bug**

I want to use `follows` on the input of an input.

Though I get an error, that this is not in the registry.

**Steps To Reproduce**

1. Add an arbitrary `nixpkgs` input to a `flake.nix`.
2. Add the following to your `flake.nix` at appropriate location:
   ```nix
   inputs.rnix-lsp.url = "github:nix-community/rnix-lsp/master";
   inputs.rnix-lsp.inputs.nixpkgs.follows = "nixpkgs";
   inputs.rnix-lsp.inputs.naersk.inputs.nixpkgs.follows = "nixpkgs";
   ```
3. Update the `flake.lock` and observe error:
   ```plain
   error: cannot find flake 'flake:naersk' in the flake registries
   (use '--show-trace' to show detailed location information)
   ```

**Expected behavior**

The `nixpkgs` input of the `naersk` input of `rnix-lsp` is properly overwritten and follows "my" `nixpkgs`.

**`nix-env --version` output**

```
$ nix-env --version
nix-env (Nix) 2.6.0pre20211214_18e4851
```

**Additional context**

I tried this as a way to workaround #5609.

The same problem happens on 2.4 and 2.5:

```plain
$ nix shell github:nixos/nix/2.4 -c nix flake metadata
warning: Git tree '/home/…/Projects/system-config' is dirty
error: cannot find flake 'flake:naersk' in the flake registries
(use '--show-trace' to show detailed location information)
$ nix shell github:nixos/nix/2.5.0 -c nix flake metadata
warning: Git tree '/home/…/Projects/system-config' is dirty
error: cannot find flake 'flake:naersk' in the flake registries
(use '--show-trace' to show detailed location information)
```

### PR DESCRIPTION
**Pull request by Kha**
Currently, `B` in `inputs.A.inputs.B.inputs.C...` is interpreted as registry flake, discarding any of its configuration in `A`, leading to an [unexpected](https://github.com/NixOS/nix/issues/5790) "cannot find flake 'flake:B' in the flake registries". This PR implements the expected behavior:
* input overrides (those nested inside `inputs`) are not defaulted to registry flakes.
* Input overrides do not outright replace the corresponding input of the nested flake, but are recursively merged into it, meaning e.g. `inputs.B.url` set in `A` is preserved by the above config.

Fixes #5790

### CODE REVIEW

File: src/libexpr/flake/flake.cc [hunk 1]
```diff
@@ -404,6 +418,12 @@ LockedFlake lockFlake(
                         // Respect the “flakeness” of the input even if we
                         // override it
                         i->second.isFlake = input2.isFlake;
```
Comment (Kha) [inline src/libexpr/flake/flake.cc:420]: Note that this workaround could be replaced by a "proper" merge as now done with the other attributes below if `isFlake` had a value for "not specified", e.g. was changed to `std::optional<bool>`. But wanting to override the flakeness of an input does seem like an exotic use case.

**Comment by tomberek** [comment]
Works as expected. There are a few changes in-flight to follows/overrides and the lazy-trees branch with which I'd wonder if there is any interaction or conflict.

File: tests/flakes.sh [hunk 2]
```diff
@@ -845,3 +845,31 @@ nix store delete $(nix store add-path $badFlakeDir)
...
+cat <<EOF > $flakeFollowsA/flake.nix
+{
+  inputs.B.url = "path:./flakeB";
+  inputs.D.url = "path:./flakeD";
+  inputs.B.inputs.C.inputs.D.follows = "D";
+  outputs = _: {};
+}
+EOF
+
+nix flake lock $flakeFollowsA
```
Comment (thufschmitt) [inline tests/flakes.sh:875]: Can you move that to its own test file? The `flakes.sh` test is already infuriatingly slow (and totally sequential) and I wouldn't to expand it further

File: tests/flakes.sh [hunk 3]
```diff
@@ -845,3 +845,31 @@ nix store delete $(nix store add-path $badFlakeDir)
...
+EOF
+cat <<EOF > $flakeFollowsC/flake.nix
+{
+  inputs.D.url = "path:nosuchflake";
+  outputs = _: {};
+}
+EOF
+cat <<EOF > $flakeFollowsB/flake.nix
+{
+  inputs.C.url = "path:../flakeC";
```
Comment (thufschmitt) [inline tests/flakes.sh:862]: That input doesn't seem right (`flakeC` is a subdir of `flakeB`). It's probably safer to use absolute paths (via the `$flakeFollows*` variables everywhere here

File: tests/flakes.sh (hunk 2 above)
Comment (thufschmitt) [inline tests/flakes.sh:875]: I get the idea of the test (the flake lock can only succeed if the override is properly taken into account), but it would be nice to have a more explicit check, if only to make the intent clearer. Maybe something like

```
nix flake metadata $flakeFollowsA --json | jq --exit-status '.locks.nodes.C.inputs.D == [ "D" ]'
```

**Review by thufschmitt — CHANGES_REQUESTED** [review]
Thanks for that, and sorry for the delay (I'm always a bit reluctant to touch that logic 😛).

Looks good overall, just a few suggestions, mostly around the tests

File: src/libexpr/flake/flake.cc [hunk 4]
```diff
@@ -90,11 +90,11 @@ static void expectType(EvalState & state, ValueType type,
 
 static std::map<FlakeId, FlakeInput> parseFlakeInputs(
     EvalState & state, Value * value, const PosIdx pos,
-    const std::optional<Path> & baseDir, InputPath lockRootPath);
+    const std::optional<Path> & baseDir, InputPath lockRootPath, bool isOverride);
```
[the remark this answers is not in the document]
Comment (Kha) [reply src/libexpr/flake/flake.cc]: I can do that, but looking at the code again, it seemed more elegant to just pass the recursion depth given that `isOverride` corresponds to depth > 0. Does it look sensible?

File: tests/flakes.sh (hunk 2 above)
Comment (Kha) [reply tests/flakes.sh]: Moved to the new `follows.sh`

File: tests/flakes.sh (hunk 3 above)
Comment (Kha) [reply tests/flakes.sh]: done

File: tests/flakes.sh (hunk 2 above)
Comment (Kha) [reply tests/flakes.sh]: done in the same style as in the other tests in the file

**Comment by Kha** [comment]
I noticed and fixed a related bug, see new commit above. I added it to this PR to avoid merge conflicts in the test file, but happy to relocate.

File: tests/flakes/follow-paths.sh [hunk 5]
```diff
@@ -178,3 +178,33 @@ EOF
...
+{
+  inputs.B.url = "path:$flakeFollowsB";
+  inputs.C.url = "path:$flakeFollowsC";
+  inputs.B.inputs.C.follows = "C";
+  outputs = _: {};
+}
+EOF
+
+# bug was not triggered without recreating the lockfile
+nix flake lock $flakeFollowsA --recreate-lock-file
```
Comment (Kha) [inline tests/flakes/follow-paths.sh:208]: It feels a bit concerning that one gets an entirely different lockfile without this flag, but that's probably a different problem

**Review by thufschmitt — APPROVED** [review]
Sorry for not coming back to this earlier. I'm only 95% confident that this isn't braking something (because I still couldn't wrap my head around the flake locking code), but since we're just at the beginning of a new release cycle, let's merge and revert if needs be. Thanks!
