### PR TITLE
fix an old lost direct

### LINKED ISSUE #9457: Wrong link in NixOS Manual
**Introduce your stance**
Wrong link in https://nixos.org/manual/nixos/stable/#sec-configuration-syntax

**Describe the issue**
In https://nixos.org/manual/nixos/stable/#sec-configuration-syntax , on the statement:

*The syntax and semantics of the Nix language are fully described in the [Nix manual](https://nixos.org/nix/manual/#chap-writing-nix-expressions)*

**Nix manual** is linked to a non-existing resource, *#chap-writing-nix-expressions* seems to not exist anymore and the link redirects to the **Introduction** chapter.

**Page links**
https://nixos.org/manual/nixos/stable/#sec-configuration-syntax

- [ ] I already created a Pull Request

### PR DESCRIPTION
**Pull request by fricklerhandwerk**
this part must have been moved quite a while ago, but apparently so far
no one noticed

closes #9457

thanks @D3vil0p3r for reporting!

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

### CODE REVIEW

File: doc/manual/redirects.js [hunk 1]
```diff
@@ -19,6 +19,7 @@ const redirects = {
     "chap-distributed-builds": "advanced-topics/distributed-builds.html",
     "chap-post-build-hook": "advanced-topics/post-build-hook.html",
     "chap-post-build-hook-caveats": "advanced-topics/post-build-hook.html#implementation-caveats",
+    "chap-writing-nix-expressions": "language/index.html",
```
Comment (roberth) [inline doc/manual/redirects.js:22]:
```suggestion
    "chap-writing-nix-expressions": "language",
```

perhaps

Comment (fricklerhandwerk) [reply doc/manual/redirects.js:22]: This whole piece is rather cargo-cult-y, but leaving the file names explicit keeps it independent of server-side URL rewriting capabilities. Maybe it doesn't matter even in the long run, it sure doesn't for now since the official stuff is served through Netlify that *does* rewrite URLs, but let's leave it for consistency.

Comment (roberth) [reply doc/manual/redirects.js:22]: I was wrong. The menu links to

```suggestion
    "chap-writing-nix-expressions": "language/",
```

and it seems safe to assume that that is the canonical URL for it.

Anything that isn't the canonical URL is inconsistent and should be fixed - not used as an excuse.

Comment (fricklerhandwerk) [reply doc/manual/redirects.js:22]: Let's do that in a separate commit then.
