### PR TITLE
Complain when using --pure-eval with --file

### LINKED ISSUE #12608: `nix eval --pure-eval` doesn't work with `--file`
## Describe the bug

When calling `nix eval --pure-eval --file some-file.nix`, purity doesn't seem to be enforced.

## Steps To Reproduce

```
$ echo 'builtins.currentSystem' > file.nix; nix eval --pure-eval --file file.nix
"x86_64-linux"
```

compare to:
```
$ nix eval --pure-eval --expr 'builtins.currentSystem'
error: attribute 'currentSystem' missing
       at «string»:1:1:
            1| builtins.currentSystem
             | ^
```

## Expected behavior

Purity should be enforced, or the command should error out (ex. `--pure-eval cannot be used with --file`)

## Metadata

`nix-env (Nix) 2.24.12`

## Additional context

Not limited to `builtins.currentSystem`:

```
$ echo 'builtins.getEnv "FOO"' > file.nix; FOO=value-of-foo-var nix eval --pure-eval --file file.nix
"value-of-foo-var"
$ echo 'builtins.storePath "/nix/store/fscdfw8his8sk338n3dpjdwng72cgcbx-source"' > file.nix; nix eval --pure-eval --file file.nix
"/nix/store/fscdfw8his8sk338n3dpjdwng72cgcbx-source"
$ echo '"Your hostname is ${builtins.readFile "/etc/hostname"}"' > file.nix; nix eval --pure-eval --file file.nix
"Your hostname is fw\n"
```

I'm not sure what the "correct" answer is here; is the file allowed to refer to other files in the same directory? Does the whole directory have to be copied to the nix store?

related: https://github.com/NixOS/nix/issues/4651

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open bug issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by edolstra**
## Motivation

Closes #12608.

Using `--pure-eval` with `--file` never worked and cannot work because in pure eval mode, the evaluator doesn't have access to the file. So let's throw an error.

If we're worried that throwing an error breaks scripts, we could also print a warning.

## Context

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

File: src/libcmd/installables.cc [hunk 1]
```diff
@@ -491,7 +491,11 @@ Installables SourceExprCommand::parseInstallables(
             throw UsageError("'--file' and '--expr' are exclusive");
 
         // FIXME: backward compatibility hack
-        if (file) evalSettings.pureEval = false;
+        if (file) {
+            if (evalSettings.pureEval && evalSettings.pureEval.overridden)
+                throw UsageError("'--file' is not compatible with '--pure-eval'");
```
Comment (Mic92) [inline src/libcmd/installables.cc:496]: It can actually work

```
nix build --pure-eval --file . -I . hello-unfree
```

So I am unsure if we should break it?

Comment (edolstra) [reply src/libcmd/installables.cc:496]: With this PR it shows:
```
$ nix build --pure-eval --file . -I . hello-unfree
error: '--file' is not compatible with '--pure-eval'
Try 'nix --help' for more information.
```

It previously worked because the code above overwrote the user's `pureEval` setting.
