### PR TITLE
Force all Pos* to be non-null

### LINKED ISSUE #4893: Nix segfault at evalutation. GC_DONT_GC=1 doesn't help
**Describe the bug**

Nix segfaults when when evaluating.

**Steps To Reproduce**

1. Run `nix flake check git+https://gitlab.com/lama-corp/infra/dotshabka\?rev=c69be3f98dfa8b943f83bf2f9a8cb17ab403ae0b`
2. `[1]    1690602 segmentation fault (core dumped)`

**Expected behavior**

Nix doesn't segfault.

**`nix-env --version` output**

`nix-env (Nix) 2.4pre20210601_5985b8b`
Also happens on `nix-env (Nix) 2.4pre20210503_6d2553a`
Also happens on nix's `8e6ee1b9e924fbbbeb5594eb89e7a570f36ab6e1` (latest commit on master at the time of writing)

**Additional context**

Adding `GC_DONT_GC=1` to the environment doesn't help.

Here are the latest lines output when ran with `-vvv`:
```
evaluating flake...
using substituted/cached input 'github:SoxinOS/soxin/587ae3306c4c1ce130f217b06c07ea8b3b43d400' in '/nix/store/sr31h4gm1gp8clk3y7rqsk6gry3c7i0a-source'
checking access to '/nix/store/sr31h4gm1gp8clk3y7rqsk6gry3c7i0a-source/flake.nix'
evaluating file '/nix/store/sr31h4gm1gp8clk3y7rqsk6gry3c7i0a-source/flake.nix'
using substituted/cached input 'github:NixOS/nixpkgs/4714dcf148dfb528f4107ceb5dc86529ca71294a' in '/nix/store/ghknj4cnjsjajx88zji9wlfr9rrz4x8y-source'
checking access to '/nix/store/ghknj4cnjsjajx88zji9wlfr9rrz4x8y-source/flake.nix'
evaluating file '/nix/store/ghknj4cnjsjajx88zji9wlfr9rrz4x8y-source/flake.nix'
checking access to '/nix/store/ghknj4cnjsjajx88zji9wlfr9rrz4x8y-source/lib'
evaluating file '/nix/store/ghknj4cnjsjajx88zji9wlfr9rrz4x8y-source/lib/default.nix'
checking access to '/nix/store/ghknj4cnjsjajx88zji9wlfr9rrz4x8y-source/lib/default.nix'
checking access to '/nix/store/ghknj4cnjsjajx88zji9wlfr9rrz4x8y-source/lib/fixed-points.nix'
evaluating file '/nix/store/ghknj4cnjsjajx88zji9wlfr9rrz4x8y-source/lib/fixed-points.nix'
checking access to '/nix/store/ghknj4cnjsjajx88zji9wlfr9rrz4x8y-source/lib/attrsets.nix'
evaluating file '/nix/store/ghknj4cnjsjajx88zji9wlfr9rrz4x8y-source/lib/attrsets.nix'
checking access to '/nix/store/ghknj4cnjsjajx88zji9wlfr9rrz4x8y-source/lib/lists.nix'
evaluating file '/nix/store/ghknj4cnjsjajx88zji9wlfr9rrz4x8y-source/lib/lists.nix'
using substituted/cached input 'github:gytis-ivaskevicius/flake-utils-plus/e7ae270a23695b50fbb6b72759a7fb1e3340ca86' in '/nix/store/0ns9ckkig2cv2i3v1lrvnhc0k96vm52k-source'
checking access to '/nix/store/0ns9ckkig2cv2i3v1lrvnhc0k96vm52k-source/flake.nix'
evaluating file '/nix/store/0ns9ckkig2cv2i3v1lrvnhc0k96vm52k-source/flake.nix'
using substituted/cached input 'github:numtide/flake-utils/c6169a2772643c4a93a0b5ac1c61e296cba68544' in '/nix/store/35sfl01w60fsbkxk1j057ipjga2agx2b-source'
checking access to '/nix/store/35sfl01w60fsbkxk1j057ipjga2agx2b-source/flake.nix'
evaluating file '/nix/store/35sfl01w60fsbkxk1j057ipjga2agx2b-source/flake.nix'
checking access to '/nix/store/35sfl01w60fsbkxk1j057ipjga2agx2b-source'
evaluating file '/nix/store/35sfl01w60fsbkxk1j057ipjga2agx2b-source/default.nix'
checking access to '/nix/store/35sfl01w60fsbkxk1j057ipjga2agx2b-source/default.nix'
checking access to '/nix/store/sr31h4gm1gp8clk3y7rqsk6gry3c7i0a-source/lib'
evaluating file '/nix/store/sr31h4gm1gp8clk3y7rqsk6gry3c7i0a-source/lib/default.nix'
checking access to '/nix/store/sr31h4gm1gp8clk3y7rqsk6gry3c7i0a-source/lib/default.nix'
checking access to '/nix/store/sr31h4gm1gp8clk3y7rqsk6gry3c7i0a-source/lib/system-flake.nix'
evaluating file '/nix/store/sr31h4gm1gp8clk3y7rqsk6gry3c7i0a-source/lib/system-flake.nix'
checking access to '/nix/store/ghknj4cnjsjajx88zji9wlfr9rrz4x8y-source/lib/asserts.nix'
evaluating file '/nix/store/ghknj4cnjsjajx88zji9wlfr9rrz4x8y-source/lib/asserts.nix'
checking access to '/nix/store/bd13cm0il77c8mvjdpajxr1zlzxgcxrb-source/hosts'
evaluating file '/nix/store/bd13cm0il77c8mvjdpajxr1zlzxgcxrb-source/hosts/default.nix'
checking access to '/nix/store/bd13cm0il77c8mvjdpajxr1zlzxgcxrb-source/hosts/default.nix'
checking access to '/nix/store/ghknj4cnjsjajx88zji9wlfr9rrz4x8y-source/lib/strings.nix'
evaluating file '/nix/store/ghknj4cnjsjajx88zji9wlfr9rrz4x8y-source/lib/strings.nix'
```

### LINKED ISSUE #5113: segmentation fault in `libnixexpr.so` when derivation has no `name` attribute
**Describe the bug**

```
[104261.670970] nix[3168666]: segfault at 0 ip 00007fdbd05cd919 sp 00007ffcd5445940 error 4 in libnixexpr.so[7fdbd0478000+1e9000]
[104261.670982] Code: ff 48 8b bc 24 c0 02 00 00 48 8d 84 24 d0 02 00 00 48 39 c7 74 11 48 8b 84 24 d0 02 00 00 48 8d 70 01 e8 9a 46 f1 ff 48 8b 03 <f3> 0f 6f 08 0f 29 0c 24 48 8b 40 10 85 c0 48 89 44 24 10 48 8b 05
[104277.064810] nix[3168721]: segfault at 0 ip 00007f7f45675919 sp 00007fff43100dd0 error 4 in libnixexpr.so[7f7f45520000+1e9000]
[104277.064821] Code: ff 48 8b bc 24 c0 02 00 00 48 8d 84 24 d0 02 00 00 48 39 c7 74 11 48 8b 84 24 d0 02 00 00 48 8d 70 01 e8 9a 46 f1 ff 48 8b 03 <f3> 0f 6f 08 0f 29 0c 24 48 8b 40 10 85 c0 48 89 44 24 10 48 8b 05
[104298.184840] nix[3168771]: segfault at 0 ip 00007fae13df5919 sp 00007fff1a8367e0 error 4 in libnixexpr.so[7fae13ca0000+1e9000]
[104298.184851] Code: ff 48 8b bc 24 c0 02 00 00 48 8d 84 24 d0 02 00 00 48 39 c7 74 11 48 8b 84 24 d0 02 00 00 48 8d 70 01 e8 9a 46 f1 ff 48 8b 03 <f3> 0f 6f 08 0f 29 0c 24 48 8b 40 10 85 c0 48 89 44 24 10 48 8b 05
[104325.160402] nix[3168825]: segfault at 0 ip 00007f239ecb5919 sp 00007ffd16b1b930 error 4 in libnixexpr.so[7f239eb60000+1e9000]
[104325.160413] Code: ff 48 8b bc 24 c0 02 00 00 48 8d 84 24 d0 02 00 00 48 39 c7 74 11 48 8b 84 24 d0 02 00 00 48 8d 70 01 e8 9a 46 f1 ff 48 8b 03 <f3> 0f 6f 08 0f 29 0c 24 48 8b 40 10 85 c0 48 89 44 24 10 48 8b 05
[104370.444280] nix[3168864]: segfault at 0 ip 00007f46985b5919 sp 00007ffec8c678d0 error 4 in libnixexpr.so[7f4698460000+1e9000]
[104370.444292] Code: ff 48 8b bc 24 c0 02 00 00 48 8d 84 24 d0 02 00 00 48 39 c7 74 11 48 8b 84 24 d0 02 00 00 48 8d 70 01 e8 9a 46 f1 ff 48 8b 03 <f3> 0f 6f 08 0f 29 0c 24 48 8b 40 10 85 c0 48 89 44 24 10 48 8b 05
```
while running
```
nix build -v -L --keep-going .#nixosConfigurations.orca.config.system.build.toplevel
warning: Git tree '/home/zseri/devel/nixos-configs' is dirty
Segmentation fault (core dumped)
```

```
Mon 2021-08-09 23:54:52 CEST 3168666     0     0  11 present   /nix/store/9qvjvwl05psa9hi9q2b7cl7ihphlrb8p-nix-2.4pre20210728_7816ef6/bin/nix
Mon 2021-08-09 23:55:07 CEST 3168721     0     0  11 present   /nix/store/9qvjvwl05psa9hi9q2b7cl7ihphlrb8p-nix-2.4pre20210728_7816ef6/bin/nix
Mon 2021-08-09 23:55:28 CEST 3168771     0     0  11 present   /nix/store/9qvjvwl05psa9hi9q2b7cl7ihphlrb8p-nix-2.4pre20210728_7816ef6/bin/nix
Mon 2021-08-09 23:55:55 CEST 3168825     0     0  11 present   /nix/store/9qvjvwl05psa9hi9q2b7cl7ihphlrb8p-nix-2.4pre20210728_7816ef6/bin/nix
Mon 2021-08-09 23:56:40 CEST 3168864  1000   100  11 present   /nix/store/9qvjvwl05psa9hi9q2b7cl7ihphlrb8p-nix-2.4pre20210728_7816ef6/bin/nix
```

backtrace head:
```
#0  0x00007f46985b5919 in nix::getAttr(nix::EvalState&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, nix::Bindings*, nix::Pos const&) ()
   from /nix/store/9qvjvwl05psa9hi9q2b7cl7ihphlrb8p-nix-2.4pre20210728_7816ef6/lib/libnixexpr.so
#1  0x00007f46985c19e7 in nix::prim_derivationStrict(nix::EvalState&, nix::Pos const&, nix::Value**, nix::Value&) () from /nix/store/9qvjvwl05psa9hi9q2b7cl7ihphlrb8p-nix-2.4pre20210728_7816ef6/lib/libnixexpr.so
#2  0x00007f4698526055 in nix::EvalState::callPrimOp(nix::Value&, nix::Value&, nix::Value&, nix::Pos const&) () from /nix/store/9qvjvwl05psa9hi9q2b7cl7ihphlrb8p-nix-2.4pre20210728_7816ef6/lib/libnixexpr.so
#3  0x00007f469852bbb3 in nix::EvalState::callFunction(nix::Value&, nix::Value&, nix::Value&, nix::Pos const&) () from /nix/store/9qvjvwl05psa9hi9q2b7cl7ihphlrb8p-nix-2.4pre20210728_7816ef6/lib/libnixexpr.so
#4  0x00007f469852bd5d in nix::ExprApp::eval(nix::EvalState&, nix::Env&, nix::Value&) () from /nix/store/9qvjvwl05psa9hi9q2b7cl7ihphlrb8p-nix-2.4pre20210728_7816ef6/lib/libnixexpr.so
#5  0x000000000056f3a8 in nix::EvalState::forceValue(nix::Value&, nix::Pos const&) ()
#6  0x00007f46985b6667 in nix::prim_getAttr(nix::EvalState&, nix::Pos const&, nix::Value**, nix::Value&) () from /nix/store/9qvjvwl05psa9hi9q2b7cl7ihphlrb8p-nix-2.4pre20210728_7816ef6/lib/libnixexpr.so
#7  0x00007f4698526055 in nix::EvalState::callPrimOp(nix::Value&, nix::Value&, nix::Value&, nix::Pos const&) () from /nix/store/9qvjvwl05psa9hi9q2b7cl7ihphlrb8p-nix-2.4pre20210728_7816ef6/lib/libnixexpr.so
#8  0x00007f469852bbb3 in nix::EvalState::callFunction(nix::Value&, nix::Value&, nix::Value&, nix::Pos const&) () from /nix/store/9qvjvwl05psa9hi9q2b7cl7ihphlrb8p-nix-2.4pre20210728_7816ef6/lib/libnixexpr.so
#9  0x00007f469852bd5d in nix::ExprApp::eval(nix::EvalState&, nix::Env&, nix::Value&) () from /nix/store/9qvjvwl05psa9hi9q2b7cl7ihphlrb8p-nix-2.4pre20210728_7816ef6/lib/libnixexpr.so
#10 0x000000000056f3a8 in nix::EvalState::forceValue(nix::Value&, nix::Pos const&) ()
#11 0x00007f469852e62f in nix::ExprSelect::eval(nix::EvalState&, nix::Env&, nix::Value&) () from /nix/store/9qvjvwl05psa9hi9q2b7cl7ihphlrb8p-nix-2.4pre20210728_7816ef6/lib/libnixexpr.so
#12 0x000000000056f3a8 in nix::EvalState::forceValue(nix::Value&, nix::Pos const&) ()
#13 0x00007f469852da57 in nix::EvalState::coerceToString(nix::Pos const&, nix::Value&, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, bool, bool) () from /nix/store/9qvjvwl05psa9hi9q2b7cl7ihphlrb8p-nix-2.4pre20210728_7816ef6/lib/libnixexpr.so
#14 0x00007f469852e07b in nix::EvalState::coerceToString(nix::Pos const&, nix::Value&, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, bool, bool) () from /nix/store/9qvjvwl05psa9hi9q2b7cl7ihphlrb8p-nix-2.4pre20210728_7816ef6/lib/libnixexpr.so
#15 0x00007f46985b1524 in nix::prim_toString(nix::EvalState&, nix::Pos const&, nix::Value**, nix::Value&) () from /nix/store/9qvjvwl05psa9hi9q2b7cl7ihphlrb8p-nix-2.4pre20210728_7816ef6/lib/libnixexpr.so
#16 0x00007f4698526055 in nix::EvalState::callPrimOp(nix::Value&, nix::Value&, nix::Value&, nix::Pos const&) () from /nix/store/9qvjvwl05psa9hi9q2b7cl7ihphlrb8p-nix-2.4pre20210728_7816ef6/lib/libnixexpr.so
#17 0x00007f469852bbb3 in nix::EvalState::callFunction(nix::Value&, nix::Value&, nix::Value&, nix::Pos const&) () from /nix/store/9qvjvwl05psa9hi9q2b7cl7ihphlrb8p-nix-2.4pre20210728_7816ef6/lib/libnixexpr.so
#18 0x00007f469852bd5d in nix::ExprApp::eval(nix::EvalState&, nix::Env&, nix::Value&) () from /nix/store/9qvjvwl05psa9hi9q2b7cl7ihphlrb8p-nix-2.4pre20210728_7816ef6/lib/libnixexpr.so
#19 0x000000000056f3a8 in nix::EvalState::forceValue(nix::Value&, nix::Pos const&) ()
#20 0x00007f469852da57 in nix::EvalState::coerceToString(nix::Pos const&, nix::Value&, std::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&, bool, bool) () from /nix/store/9qvjvwl05psa9hi9q2b7cl7ihphlrb8p-nix-2.4pre20210728_7816ef6/lib/libnixexpr.so
#21 0x00007f46985b5b85 in nix::prim_substring(nix::EvalState&, nix::Pos const&, nix::Value**, nix::Value&) () from /nix/store/9qvjvwl05psa9hi9q2b7cl7ihphlrb8p-nix-2.4pre20210728_7816ef6/lib/libnixexpr.so
```
[full backtrace](https://ytrizja.de/misc/d639b26b86a1d959a9101c3bdfd09e9f4a8dc9b70a56e698b65fbfca27b190a5.blob)

**Steps To Reproduce**

absolutely no idea, except maybe checkout https://github.com/zseri/nixos-configs/commit/897aa9e081db3e82d962158960104a0f6c70e4f4, and try the command given above to build my main system. might take a few days, tho...

**Expected behavior**

nix client shouldn't segfault ;-)

**`nix-env --version` output**

nix-env (Nix) 2.4pre20210728_7816ef6

**Additional context**

`nix.conf`:
```
# WARNING: this file is generated from the nix.* options in
# your NixOS configuration, typically
# /etc/nixos/configuration.nix.  Do not edit it!
build-users-group = nixbld
max-jobs = 3
cores = 4
sandbox = true
extra-sandbox-paths = 
substituters = https://cache.ngi0.nixos.org/
trusted-substituters = 
trusted-public-keys = cache.ngi0.nixos.org-1:KqH5CBLNSyX184S9BKZJo1LxrxJ9ltnY2uAs5c/f1MA= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
auto-optimise-store = true
require-sigs = true
trusted-users = zseri
allowed-users = *
builders =

system-features = nixos-test benchmark big-parallel kvm
sandbox-fallback = false

experimental-features = nix-command ca-derivations ca-references flakes
keep-outputs = true
keep-derivations = true
flake-registry = /nix/store/8smmncch59idkjk3f9vmxhzzmsjiavrb-flake-empty.json
builders-use-substitutes = true
```

### PR DESCRIPTION
**Pull request by roberth**
This fixes a class of crashes and introduces `ptr<T>` to make the
code robust against this failure mode going forward.

Thanks regnat for the [idea](https://github.com/NixOS/nix/pull/4895#issuecomment-871184078) of a `ref<T>` without overhead! This became `ptr<T>`

Closes #4895
Closes #4893
Closes #5127
Closes #5113

Alternatives considered:
 - `&Pos`: not mutable, so doesn't fit the current usage pattern
 - `ref<Pos>`: undue overhead
 - Just #4895 and #5127: no simplification and no future guarantees. These do cover the most important changes, but it's sad because those could have been found automatically by the type system. At least it won't happen again for this issue.
 - Remove `noPos` and use `nullptr` instead. This is fragile. Same for `optional`, which doesn't prevent this problem at compile time.

### CODE REVIEW

File: src/nix-env/user-env.cc [hunk 1]
```diff
@@ -131,9 +131,9 @@ bool createUserEnv(EvalState & state, DrvInfos & elems,
     state.forceValue(topLevel);
     PathSet context;
     Attr & aDrvPath(*topLevel.attrs->find(state.sDrvPath));
-    auto topLevelDrv = state.store->parseStorePath(state.coerceToPath(aDrvPath.pos ? *(aDrvPath.pos) : noPos, *(aDrvPath.value), context));
+    auto topLevelDrv = state.store->parseStorePath(state.coerceToPath(*aDrvPath.pos, *(aDrvPath.value), context));
     Attr & aOutPath(*topLevel.attrs->find(state.sOutPath));
-    Path topLevelOut = state.coerceToPath(aOutPath.pos ? *(aOutPath.pos) : noPos, *(aOutPath.value), context);
+    Path topLevelOut = state.coerceToPath(*aOutPath.pos, *(aOutPath.value), context);
```
Comment (zseri) [inline src/nix-env/user-env.cc:136]: why isn't `aOutPath.pos` wrapped in parens, but `aOutPath.value` is?

**Comment by zseri** [comment]
comparisons between positions and `noPos` are non-uniform. maybe this should also be fixed...

**Comment by roberth** [comment]
> comparisons between positions and `noPos` are non-uniform. maybe this should also be fixed...

That would be nice, but doing so has the potential to change the behavior. I'd like to keep that to a minimum so this can be merged sooner rather than later.

<details>
 It's just not that simple. `Pos::operator bool()` seems like an obvious candidate, but on closer inspection, flake.cc initializes it with a `file` but `line = 0`.
Could it be changed? Yes. Should it? Probably. Does it help with the release? No.
</details>

File: src/nix-env/user-env.cc (hunk 1 above)
Comment (roberth) [reply src/nix-env/user-env.cc]: Inherited noise. I've tidied it up.
