### PR TITLE
Require `drvPath` attribute to end with `.drv`

### LINKED ISSUE #4977: Assertion `hasSuffix(nameWithSuffix, extension)' failed.
**Describe the bug**

nix-daemon crash

```
❯ nix-env -vvv --quiet -j8 -iA cachix -f https://cachix.org/api/v1/install
downloading 'https://cachix.org/api/v1/install'...
evaluating file '/nix/store/j24029fbiy3nlrcssbq7rdl8ljjym54f-source'
evaluating file '/nix/store/lxr85hw1q3ash335r1sdmwamrg90ih0s-env-manifest.nix'
installing 'cachix-0.6.1'
error: unexpected end-of-file
```

originally posted in https://github.com/NixOS/nix/issues/4903#issuecomment-870906902

**Steps To Reproduce**

1. run `nix-env -vvv --quiet -j8 -iA cachix -f https://cachix.org/api/v1/install`

**Expected behavior**

**`nix-env --version` output**

nix-env (Nix) 2.4pre20210601_5985b8b

**Additional context**

```
jui 02 10:37:33 desktop nix-daemon[1189]: accepted connection from pid 10981, user bbigras (trusted)
jui 02 10:37:33 desktop nix-daemon[10986]: nix-daemon: src/libstore/derivations.cc:630: static std::string_view nix::BasicDerivation::nameFromPath(const nix::StorePath&): Assertion `hasSuffix(nameWithSuffix, extension)' failed.
jui 02 10:37:33 desktop systemd-coredump[10993]: [🡕] Process 10986 (nix-daemon) of user 0 dumped core.
```

```
           PID: 10986 (nix-daemon)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 6 (ABRT)
     Timestamp: Fri 2021-07-02 10:37:33 EDT (7min ago)
  Command Line: nix-daemon 10981
    Executable: /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/bin/nix
 Control Group: /system.slice/nix-daemon.service
          Unit: nix-daemon.service
         Slice: system.slice
       Boot ID: 382020cfad734d168738fea311ede70b
    Machine ID: 21f3effe4caa457ba8dc96924a35d1a2
      Hostname: desktop
       Storage: /var/lib/systemd/coredump/core.nix-daemon.0.382020cfad734d168738fea311ede70b.10986.1625236653000000.lz4
       Message: Process 10986 (nix-daemon) of user 0 dumped core.

GNU gdb (GDB) 10.2
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/bin/nix...
(No debugging symbols found in /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/bin/nix)

warning: Can't open file /nix/var/nix/db/db.sqlite-shm during file-backed mapping note processing

warning: Can't open file /run/nscd/dbPhbKFZ (deleted) during file-backed mapping note processing

warning: Can't open file /run/nscd/dbLwfCp1 (deleted) during file-backed mapping note processing
[New LWP 10986]
[New LWP 10987]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/nix/store/adxc893j47gxx3xjw403zdf0liiddvw2-glibc-2.32-48/lib/libthread_db.so.1".
Core was generated by `nix-daemon 10981   '.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007fc47217033a in raise () from /nix/store/adxc893j47gxx3xjw403zdf0liiddvw2-glibc-2.32-48/lib/libc.so.6
[Current thread is 1 (Thread 0x7fc470f58a80 (LWP 10986))]
warning: File "/nix/store/j5v9qapwwbh27lp1mkqmcczm1yv1n9qa-hm_gdbinit" auto-loading has been declined by your `auto-load safe-path' set to "$debugdir:$datadir/auto-load:/nix/store/d9mfvhvksvsx0ar8pmxwhgwd9my045rp-gcc-10.3.0-lib".
To enable execution of this file add
	add-auto-load-safe-path /nix/store/j5v9qapwwbh27lp1mkqmcczm1yv1n9qa-hm_gdbinit
line to your configuration file "/root/.gdbinit".
To completely disable this security protection add
	set auto-load safe-path /
line to your configuration file "/root/.gdbinit".
For more information about this security protection see the
"Auto-loading safe path" section in the GDB manual.  E.g., run from the shell:
	info "(gdb)Auto-loading safe path"
[?2004h(gdb) bt full
[?2004l
#0  0x00007fc47217033a in raise () from /nix/store/adxc893j47gxx3xjw403zdf0liiddvw2-glibc-2.32-48/lib/libc.so.6
No symbol table info available.
#1  0x00007fc47215a523 in abort () from /nix/store/adxc893j47gxx3xjw403zdf0liiddvw2-glibc-2.32-48/lib/libc.so.6
No symbol table info available.
#2  0x00007fc47215a41f in __assert_fail_base.cold.0 () from /nix/store/adxc893j47gxx3xjw403zdf0liiddvw2-glibc-2.32-48/lib/libc.so.6
No symbol table info available.
#3  0x00007fc472168d92 in __assert_fail () from /nix/store/adxc893j47gxx3xjw403zdf0liiddvw2-glibc-2.32-48/lib/libc.so.6
No symbol table info available.
#4  0x00007fc4729c45d3 in nix::BasicDerivation::nameFromPath(nix::StorePath const&) () from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixstore.so
No symbol table info available.
#5  0x00007fc472acea34 in nix::readDerivationCommon(nix::Store&, nix::StorePath const&, bool) () from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixstore.so
No symbol table info available.
#6  0x00007fc472acec00 in nix::Store::readInvalidDerivation(nix::StorePath const&) () from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixstore.so
No symbol table info available.
#7  0x00007fc472a3b3cd in nix::LocalStore::queryPartialDerivationOutputMap[abi:cxx11](nix::StorePath const&) () from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixstore.so
No symbol table info available.
#8  0x00007fc472a56dcf in nix::Store::queryMissing(std::vector<nix::DerivedPath, std::allocator<nix::DerivedPath> > const&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, unsigned long&, unsigned long&)::{lambda(nix::DerivedPath const&)#3}::operator()(nix::DerivedPath const&) const::{lambda(nix::DerivedPathBuilt)#1}::operator()(nix::DerivedPathBuilt) const ()
   from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixstore.so
No symbol table info available.
#9  0x00007fc472a57b02 in std::__detail::__variant::__gen_vtable_impl<std::__detail::__variant::_Multi_array<std::__detail::__variant::__deduce_visit_result<void> (*)(nix::overloaded<nix::Store::queryMissing(std::vector<nix::DerivedPath, std::allocator<nix::DerivedPath> > const&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, unsigned long&, unsigned long&)::{lambda(nix::DerivedPath const&)#3}::operator()(nix::DerivedPath const&) const::{lambda(nix::DerivedPathBuilt)#1}, nix::Store::queryMissing(std::vector<nix::DerivedPath, std::allocator<nix::DerivedPath> > const&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, unsigned long&, unsigned long&)::{lambda(nix::DerivedPath const&)#3}::operator()(nix::DerivedPath const&) const::{lambda(nix::DerivedPathOpaque)#2}>&&, std::variant<nix::DerivedPathOpaque, nix::DerivedPathBuilt> const&)>, std::integer_sequence<unsigned long, 1ul> >::__visit_invoke(nix::overloaded<nix::Store::queryMissing(std::vector<nix::DerivedPath, std::allocator<nix::DerivedPath> > const&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, unsigned long&, unsigned long&)::{lambda(nix::DerivedPath const&)#3}::operator()(nix::DerivedPath const&) const::{lambda(nix::DerivedPathBuilt)#1}, nix::Store::queryMissing(std::vector<nix::DerivedPath, std::allocator<nix::DerivedPath> > const&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, unsigned long&, unsigned long&)::{lambda(nix::DerivedPath const&)#3}::operator()(nix::DerivedPath const&) const::{lambda(nix::DerivedPathOpaque)#2}>&&, std::variant<nix::DerivedPathOpaque, nix::DerivedPathBuilt> const&) () from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixstore.so
No symbol table info available.
#10 0x00007fc472a58e36 in std::_Function_handler<void (nix::DerivedPath), nix::Store::queryMissing(std::vector<nix::DerivedPath, std::allocator<nix::DerivedPath> > const&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, unsigned long&, unsigned long&)::{lambda(nix::DerivedPath const&)#3}>::_M_invoke(std::_Any_data const&, nix::DerivedPath&&) ()
   from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixstore.so
No symbol table info available.
#11 0x00007fc472a5a2e7 in std::_Function_handler<void (), std::_Bind<std::function<void (nix::DerivedPath)> (nix::DerivedPath)> >::_M_invoke(std::_Any_data const&) ()
   from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixstore.so
No symbol table info available.
#12 0x00007fc47277f91a in nix::ThreadPool::doWork(bool) () from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixutil.so
No symbol table info available.
#13 0x00007fc472781405 in nix::ThreadPool::process() () from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixutil.so
No symbol table info available.
#14 0x00007fc472a54f9d in nix::Store::queryMissing(std::vector<nix::DerivedPath, std::allocator<nix::DerivedPath> > const&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, unsigned long&, unsigned long&) ()
   from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixstore.so
No symbol table info available.
#15 0x00007fc4729b82dd in nix::daemon::processConnection(nix::ref<nix::Store>, nix::FdSource&, nix::FdSink&, nix::daemon::TrustedFlag, nix::daemon::RecursiveFlag, std::function<void (nix::Store&)>) ()
   from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixstore.so
No symbol table info available.
#16 0x000000000052593c in std::_Function_handler<void (), daemonLoop()::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
No symbol table info available.
#17 0x00007fc47279e00c in std::_Function_handler<void (), nix::startProcess(std::function<void ()>, nix::ProcessOptions const&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
   from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixutil.so
No symbol table info available.
#18 0x00007fc472799af9 in nix::doFork(bool, std::function<void ()>) () from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixutil.so
No symbol table info available.
#19 0x00007fc47279de99 in nix::startProcess(std::function<void ()>, nix::ProcessOptions const&) () from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixutil.so
No symbol table info available.
#20 0x0000000000526951 in runDaemon(bool) ()
No symbol table info available.
#21 0x0000000000527175 in main_nix_daemon(int, char**) ()
No symbol table info available.
#22 0x0000000000585b95 in nix::mainWrapped(int, char**) ()
No symbol table info available.
#23 0x00007fc472ca58b8 in nix::handleExceptions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()>) ()
   from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixmain.so
No symbol table info available.
#24 0x0000000000477b96 in main ()
No symbol table info available.
[?2004h(gdb) 
[?2004l
#0  0x00007fc47217033a in raise () from /nix/store/adxc893j47gxx3xjw403zdf0liiddvw2-glibc-2.32-48/lib/libc.so.6
No symbol table info available.
#1  0x00007fc47215a523 in abort () from /nix/store/adxc893j47gxx3xjw403zdf0liiddvw2-glibc-2.32-48/lib/libc.so.6
No symbol table info available.
#2  0x00007fc47215a41f in __assert_fail_base.cold.0 () from /nix/store/adxc893j47gxx3xjw403zdf0liiddvw2-glibc-2.32-48/lib/libc.so.6
No symbol table info available.
#3  0x00007fc472168d92 in __assert_fail () from /nix/store/adxc893j47gxx3xjw403zdf0liiddvw2-glibc-2.32-48/lib/libc.so.6
No symbol table info available.
#4  0x00007fc4729c45d3 in nix::BasicDerivation::nameFromPath(nix::StorePath const&) () from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixstore.so
No symbol table info available.
#5  0x00007fc472acea34 in nix::readDerivationCommon(nix::Store&, nix::StorePath const&, bool) () from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixstore.so
No symbol table info available.
#6  0x00007fc472acec00 in nix::Store::readInvalidDerivation(nix::StorePath const&) () from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixstore.so
No symbol table info available.
#7  0x00007fc472a3b3cd in nix::LocalStore::queryPartialDerivationOutputMap[abi:cxx11](nix::StorePath const&) () from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixstore.so
No symbol table info available.
#8  0x00007fc472a56dcf in nix::Store::queryMissing(std::vector<nix::DerivedPath, std::allocator<nix::DerivedPath> > const&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, unsigned long&, unsigned long&)::{lambda(nix::DerivedPath const&)#3}::operator()(nix::DerivedPath const&) const::{lambda(nix::DerivedPathBuilt)#1}::operator()(nix::DerivedPathBuilt) const ()
   from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixstore.so
No symbol table info available.
#9  0x00007fc472a57b02 in std::__detail::__variant::__gen_vtable_impl<std::__detail::__variant::_Multi_array<std::__detail::__variant::__deduce_visit_result<void> (*)(nix::overloaded<nix::Store::queryMissing(std::vector<nix::DerivedPath, std::allocator<nix::DerivedPath> > const&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, unsigned long&, unsigned long&)::{lambda(nix::DerivedPath const&)#3}::operator()(nix::DerivedPath const&) const::{lambda(nix::DerivedPathBuilt)#1}, nix::Store::queryMissing(std::vector<nix::DerivedPath, std::allocator<nix::DerivedPath> > const&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, unsigned long&, unsigned long&)::{lambda(nix::DerivedPath const&)#3}::operator()(nix::DerivedPath const&) const::{lambda(nix::DerivedPathOpaque)#2}>&&, std::variant<nix::DerivedPathOpaque, nix::DerivedPathBuilt> const&)>, std::integer_sequence<unsigned long, 1ul> >::__visit_invoke(nix::overloaded<nix::Store::queryMissing(std::vector<nix::DerivedPath, std::allocator<nix::DerivedPath> > const&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, unsigned long&, unsigned long&)::{lambda(nix::DerivedPath const&)#3}::operator()(nix::DerivedPath const&) const::{lambda(nix::DerivedPathBuilt)#1}, nix::Store::queryMissing(std::vector<nix::DerivedPath, std::allocator<nix::DerivedPath> > const&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, unsigned long&, unsigned long&)::{lambda(nix::DerivedPath const&)#3}::operator()(nix::DerivedPath const&) const::{lambda(nix::DerivedPathOpaque)#2}>&&, std::variant<nix::DerivedPathOpaque, nix::DerivedPathBuilt> const&) () from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixstore.so
No symbol table info available.
#10 0x00007fc472a58e36 in std::_Function_handler<void (nix::DerivedPath), nix::Store::queryMissing(std::vector<nix::DerivedPath, std::allocator<nix::DerivedPath> > const&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, unsigned long&, unsigned long&)::{lambda(nix::DerivedPath const&)#3}>::_M_invoke(std::_Any_data const&, nix::DerivedPath&&) ()
   from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixstore.so
No symbol table info available.
#11 0x00007fc472a5a2e7 in std::_Function_handler<void (), std::_Bind<std::function<void (nix::DerivedPath)> (nix::DerivedPath)> >::_M_invoke(std::_Any_data const&) ()
   from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixstore.so
No symbol table info available.
#12 0x00007fc47277f91a in nix::ThreadPool::doWork(bool) () from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixutil.so
No symbol table info available.
#13 0x00007fc472781405 in nix::ThreadPool::process() () from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixutil.so
No symbol table info available.
#14 0x00007fc472a54f9d in nix::Store::queryMissing(std::vector<nix::DerivedPath, std::allocator<nix::DerivedPath> > const&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, std::set<nix::StorePath, std::less<nix::StorePath>, std::allocator<nix::StorePath> >&, unsigned long&, unsigned long&) ()
   from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixstore.so
No symbol table info available.
#15 0x00007fc4729b82dd in nix::daemon::processConnection(nix::ref<nix::Store>, nix::FdSource&, nix::FdSink&, nix::daemon::TrustedFlag, nix::daemon::RecursiveFlag, std::function<void (nix::Store&)>) ()
   from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixstore.so
No symbol table info available.
#16 0x000000000052593c in std::_Function_handler<void (), daemonLoop()::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
No symbol table info available.
#17 0x00007fc47279e00c in std::_Function_handler<void (), nix::startProcess(std::function<void ()>, nix::ProcessOptions const&)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
   from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixutil.so
No symbol table info available.
#18 0x00007fc472799af9 in nix::doFork(bool, std::function<void ()>) () from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixutil.so
No symbol table info available.
#19 0x00007fc47279de99 in nix::startProcess(std::function<void ()>, nix::ProcessOptions const&) () from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixutil.so
No symbol table info available.
#20 0x0000000000526951 in runDaemon(bool) ()
No symbol table info available.
#21 0x0000000000527175 in main_nix_daemon(int, char**) ()
No symbol table info available.
#22 0x0000000000585b95 in nix::mainWrapped(int, char**) ()
No symbol table info available.
#23 0x00007fc472ca58b8 in nix::handleExceptions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()>) ()
   from /nix/store/xylpxd82bi25cp9xcmp5a8psx8qh6i4p-nix-2.4pre20210601_5985b8b/lib/libnixmain.so
No symbol table info available.
#24 0x0000000000477b96 in main ()
No symbol table info available.
[?2004h(gdb)  [K[?2004l
quit
```

### PR DESCRIPTION
**Pull request by Ericson2314**
# Motivation

# Context

Fixes #4977

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by fricklerhandwerk** [comment]
Triaged in Nix maintainers meeting:

- @Ericson2314: https://github.com/NixOS/nix/issues/4977#issuecomment-2125069515 shows a minimal reproducer, where `drvPath` is not valid, but the code tries to find the name by stripping `.drv`
- @tomberek: so this is fixing behavior to follow expectations
- @Ericson2314: yes, we can still loosen the requirement for store path names for RFC 92

File: src/libexpr/eval-error.cc [hunk 1]
```diff
@@ -27,8 +27,7 @@ EvalErrorBuilder<T> & EvalErrorBuilder<T>::atPos(Value & value, PosIdx fallback)
 template<class T>
 EvalErrorBuilder<T> & EvalErrorBuilder<T>::withTrace(PosIdx pos, const std::string_view text)
 {
-    error.err.traces.push_front(
-        Trace{.pos = error.state.positions[pos], .hint = HintFmt(std::string(text))});
+    error.addTrace(error.state.positions[pos], text);
```
Comment (Ericson2314) [inline src/libexpr/eval-error.cc:30]: Little dedup I noticed while working on things

**Review by edolstra — APPROVED** [review]
