### PR TITLE
Fix "Failed tcsetattr(TCSADRAIN)" when `nix repl` is not a TTY

### LINKED ISSUE #9941: `nix repl` prints error messages when input is not a TTY
**Describe the bug**

For testing, I sometimes want to feed input to the `nix repl` from a file so I can run it as part of a script. Unfortunately, when I try this, I get a bunch of error messages.

**Steps To Reproduce**

```
$ echo builtins.nixVersion | nix repl
Welcome to Nix 2.18.1. Type :? for help.

Failed tcsetattr(TCSADRAIN): Inappropriate ioctl for device
"2.18.1"

Failed tcsetattr(TCSADRAIN): Inappropriate ioctl for device
```

**Expected behavior**

```
$ echo builtins.nixVersion | nix repl
Welcome to Nix 2.18.1. Type :? for help.

nix-repl> "2.18.1"
```

**`nix-env --version` output**

```
$ nix-env --version
nix-env (Nix) 2.18.1
```

It fails on the latest `master` too.

**Additional context**

I've reproduced this bug on Linux and macOS.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by 9999years**
Fixes #9941.

Before:
```
$ echo builtins.nixVersion | nix repl
Welcome to Nix 2.18.1. Type :? for help.

Failed tcsetattr(TCSADRAIN): Inappropriate ioctl for device
"2.18.1"

Failed tcsetattr(TCSADRAIN): Inappropriate ioctl for device
```

After:
```
$ echo builtins.nixVersion | nix repl
Nix 2.21.0pre20240131_dirty
Type :? for help.
"2.21.0pre20240131_dirty"
```

### CODE REVIEW

File: src/libcmd/repl.cc [hunk 1]
```diff
@@ -351,7 +351,6 @@ bool NixRepl::getLine(std::string & input, const std::string & prompt)
     };
 
     setupSignals();
-    Finally resetTerminal([&]() { rl_deprep_terminal(); });
```
Comment (9999years) [inline src/libcmd/repl.cc:354]: `editline` already calls `rl_prep_terminal` and `rl_deprep_terminal` in `readline`, so I'm not sure what the point of this was, especially since there's no matching `rl_prep_terminal` call.

It was added in #5665 without comment about what sort of "exceptional exits" can lead to the terminal not being reset or any tests.

Comment (edolstra) [reply src/libcmd/repl.cc:354]: I doubt I did #5665 for no reason, so I assume it was needed at the time. So if we remove this, we have to be sure that there are no exceptions that can leave the terminal in a raw state.

Comment (lf-) [inline src/libcmd/repl.cc:354]: alternatively :)

```
    Finally resetTerminal([&]() { if (isatty(STDIN_FILENO) rl_deprep_terminal(); });
```

Comment (lf-) [reply src/libcmd/repl.cc:354]: Can we test this assumption it is necessary by putting some code in there that throws an uncaught exception and see if it indeed fails to deinitialize the terminal?
