### PR TITLE
darwin: encrypt nix volume if filevault is enabled

### LINKED ISSUE #3435: error: could not set permissions on '/nix/var/nix/profiles/per-user' to 755: Operation not permitted
After installing multi-user nix, the following error occurs when running nix-shell:

```
andrewmckinlay@imac ~ % nix-shell -p nix-info --run "nix-info -m"
error: could not set permissions on '/nix/var/nix/profiles/per-user' to 755: Operation not permitted
```

```
andrewmckinlay@imac ~ % ls -ld /nix/var/nix/profiles/per-user
drwxr-xr-x  3 root  staff  96 Mar 21 13:01 /nix/var/nix/profiles/per-user
```

### LINKED ISSUE #3667: Multi-User Darwin Installer: No side effects before old installation check
I think there are a few instances of the installer doing things before deciding whether to abort, which makes retrying a real pain as one has delete files over and over again.

Instances (to be edited):

 - Catalina volume and `/etc/synthetic.conf` `/nix` creation. This one macos has made especially irksome, as one can easily create `/nix`, but must reboot to get rid of it.

### LINKED ISSUE #4150: [OSX catalina] install script fails if a volume starting with [nN]ix.* already exists
**Describe the bug**

* The nix catalina install script will fail if a user happens to have a volume already named with a regex pattern of [nN]ix.* since the `find_nix_volume()` function of the [create-darwin-volume.sh](https://github.com/NixOS/nix/blob/master/scripts/create-darwin-volume.sh#L37) script uses this pattern match to determine if a nix store has already been created.

**Steps To Reproduce**

* Install catalina with a fresh drive, APFS, case-sensitive (as an example).  Name the volume something like: `nixify-me`.
* Once installed, try installing nix:
```
sh <(curl -L https://nixos.org/nix/install) --darwin-use-unencrypted-nix-store-volume --daemon
```
* It will fail because it sees `nixify-me` and believes the appropriate volume for the nix-store has already been created.

**Expected behavior**

* The install to work.

**Additional context**

* Ironically, my behavior of naming the Catalina block device volume for what I intended to do with it unwittingly caused the failure :).
* So others don't stumble upon the same fail, it may be good to:
  * Make the regex match more stringent.  For example, the script creates a volume having a label starting with [Nix Store](https://github.com/NixOS/nix/blob/master/scripts/create-darwin-volume.sh#L173), so why not pattern match on that?
  * Add a line or two in the manual detailing what the volume name will be if created, and what it is looking for to check for if it already exists.

### LINKED ISSUE #4380: Mac installation should not rely on T2 chip encryption
The [installation guide for MacOS](https://nixos.org/manual/nix/stable/#sect-macos-installation) starts with a recommendation that a T2 chip will keep you safe, so you don't need to worry about an unencrypted volume, but this chip was [recently compromised](https://www.theregister.com/2020/10/08/apple_t2_security_chip/), so maybe that is no longer the best advice to lead with.

Regarding docs, I think this shouldn't be the first piece of advice to give. I also grepped for "t2" in the repo and there is a reference to it in the code, but I am in no position to comment on the assumptions there.

### LINKED ISSUE #4390: Reinstalling on macos: "/nix: Read-only file system"
**Describe the bug**
After a broken uninstallation, I wasn't able to install nix.
Here are the error messages when I tried to reinstall using
```sh <(curl -L https://nixos.org/nix/install) --daemon```:

```
---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo mkdir -pv -m 0755 /nix /nix/var /nix/var/log /nix/var/log/nix /nix/var/log/nix/drvs /nix/var/nix /nix/var/nix/db /nix/var/nix/gcroots /nix/var/nix/profiles /nix/var/nix/temproots /nix/var/nix/userpool /nix/var/nix/gcroots/per-user /nix/var/nix/profiles/per-user

to make the basic directory structure of Nix (part 1)

mkdir: /nix: Read-only file system
mkdir: /nix/var: Read-only file system
mkdir: /nix/var/log: Read-only file system
mkdir: /nix/var/log/nix: Read-only file system
mkdir: /nix/var/log/nix/drvs: Read-only file system
mkdir: /nix/var/nix: Read-only file system
mkdir: /nix/var/nix/db: Read-only file system
mkdir: /nix/var/nix/gcroots: Read-only file system
mkdir: /nix/var/nix/profiles: Read-only file system
mkdir: /nix/var/nix/temproots: Read-only file system
mkdir: /nix/var/nix/userpool: Read-only file system
mkdir: /nix/var/nix/gcroots/per-user: Read-only file system
mkdir: /nix/var/nix/profiles/per-user: Read-only file system
```

**Steps To Reproduce**

1. I first install nix successfully(the first time), 
2. then I tried to uninstall it using "sudo rm -rf /nix".
3. After that, I find there's still some files(starting with '.', I don't remember the exact names) left in /nix.
So I use the "disk utitiliy.app" to uninstall the nix partition and do "sudo rm -rf /nix" again.

This time those remaining files were deleted but /nix(empty directory) is left.
When I try to do "sudo rm -rf /nix", it gives:
```
rm: /nix: Read-only file system
```
**Expected behavior**

Can someone points out a possible solution in my case to remove the empty directory /nix, thus I can reinstall nix?

### LINKED ISSUE #4488: Big Sur 11.2 diskutil: command not found
Install script can't find diskutil because the diskutil not in `$PATH`

**Steps To Reproduce**

1. Install macOS Big Sur 11.2
2. Run the installation command:
```sh
curl -L https://nixos.org/nix/install | sh
```
3. See error:
```
...unpack/nix-2.3.10-x86_64-darwin/install: line 115: diskutil: command not found
-:1: parser error : Document is empty
```
---

I think the solution is to call `diskutil` by its full path: `/usr/sbin/diskutil`.

### LINKED ISSUE #4666: Jeeze, Install on MacOS Big Sur went wrong.
**Describe the bug**

Ran `sh <(curl -L https://nixos.org/nix/install) --daemon`

**Steps To Reproduce**

1. Go to terminal
2. Switch from fish to bash by typing `bash`
3. Run `sh <(curl -L https://nixos.org/nix/install) --daemon`
4. See error output below
 <details>
<summary>Jeeze, something went wrong. If you can take all the output and open
an issue, we'd love to fix the problem so nobody else has this issue</summary>

```sh
Volumes/SSD/Github
 [I] ➜ bash
bash-5.1$ sh <(curl -L https://nixos.org/nix/install) --darwin-use-unencrypted-nix-store-volume
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2699  100  2699    0     0  11583      0 --:--:-- --:--:-- --:--:--  439k
downloading Nix 2.3.10 binary tarball for x86_64-darwin from 'https://releases.nixos.org/nix/nix-2.3.10/nix-2.3.10-x86_64-darwin.tar.xz' to '/var/folders/rt/7lc5vcw16459dszl8djk35fh0000gn/T/nix-binary-tarball-unpack.XXXXXXXXXX.LtRTz3g1'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 26.6M  100 26.6M    0     0  12.5M      0  0:00:02  0:00:02 --:--:-- 12.5M
Note: a multi-user installation is possible. See https://nixos.org/nix/manual/#sect-multi-user-installation
Creating volume and mountpoint /nix.

     ------------------------------------------------------------------
    | This installer will create a volume for the nix store and        |
    | configure it to mount at /nix.  Follow these steps to uninstall. |
     ------------------------------------------------------------------

  1. Remove the entry from fstab using 'sudo vifs'
  2. Destroy the data volume using 'diskutil apfs deleteVolume'
  3. Remove the 'nix' line from /etc/synthetic.conf or the file

Creating mountpoint for /nix...
Creating a Nix Store volume...
Password:
error: refusing to create Nix store volume because the boot volume is
       FileVault encrypted, but encryption-at-rest is not available.
       Manually create a volume for the store and re-run this script.
       See https://nixos.org/nix/manual/#sect-macos-installation
bash-5.1$ sh <(curl -L https://nixos.org/nix/install) --daemon
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  2699  100  2699    0     0  10927      0 --:--:-- --:--:-- --:--:-- 10927
downloading Nix 2.3.10 binary tarball for x86_64-darwin from 'https://releases.nixos.org/nix/nix-2.3.10/nix-2.3.10-x86_64-darwin.tar.xz' to '/var/folders/rt/7lc5vcw16459dszl8djk35fh0000gn/T/nix-binary-tarball-unpack.XXXXXXXXXX.fVdYhDjk'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 26.6M  100 26.6M    0     0  11.7M      0  0:00:02  0:00:02 --:--:-- 11.7M
Note: a multi-user installation is possible. See https://nixos.org/nix/manual/#sect-multi-user-installation
Switching to the Daemon-based Installer
Welcome to the Multi-User Nix Installation

This installation tool will set up your computer with the Nix package
manager. This will happen in a few stages:

1. Make sure your computer doesn't already have Nix. If it does, I
   will show you instructions on how to clean up your old one.

2. Show you what we are going to install and where. Then we will ask
   if you are ready to continue.

3. Create the system users and groups that the Nix daemon uses to run
   builds.

4. Perform the basic installation of the Nix files daemon.

5. Configure your shell to import special Nix Profile files, so you
   can use Nix.

6. Start the Nix daemon.

Would you like to see a more detailed list of what we will do?
[y/n] n


---- let's talk about sudo -----------------------------------------------------
This script is going to call sudo a lot. Every time we do, it'll
output exactly what it'll do, and why.

Just like this:

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo echo

to demonstrate how our sudo prompts look


This might look scary, but everything can be undone by running just a
few commands. We used to ask you to confirm each time sudo ran, but it
was too many times. Instead, I'll just ask you this one time:

Can we use sudo?
[y/n] y

Yay! Thanks! Let's get going!

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo test -e /var/root/.nix-defexpr

making sure that /var/root/.nix-defexpr doesn't exist


---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo test -e /var/root/.nix-channels

making sure that /var/root/.nix-channels doesn't exist


---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo test -e /var/root/.nix-profile

making sure that /var/root/.nix-profile doesn't exist


---- Nix config report ---------------------------------------------------------
        Temp Dir:	/var/folders/rt/7lc5vcw16459dszl8djk35fh0000gn/T/tmp.XXXXXXXXXX.JyUSm0kZ
        Nix Root:	/nix
     Build Users:	32
  Build Group ID:	30000
Build Group Name:	nixbld

build users:
    Username:	UID
     nixbld1:	30001
     nixbld2:	30002
     nixbld3:	30003
     nixbld4:	30004
     nixbld5:	30005
     nixbld6:	30006
     nixbld7:	30007
     nixbld8:	30008
     nixbld9:	30009
     nixbld10:	30010
     nixbld11:	30011
     nixbld12:	30012
     nixbld13:	30013
     nixbld14:	30014
     nixbld15:	30015
     nixbld16:	30016
     nixbld17:	30017
     nixbld18:	30018
     nixbld19:	30019
     nixbld20:	30020
     nixbld21:	30021
     nixbld22:	30022
     nixbld23:	30023
     nixbld24:	30024
     nixbld25:	30025
     nixbld26:	30026
     nixbld27:	30027
     nixbld28:	30028
     nixbld29:	30029
     nixbld30:	30030
     nixbld31:	30031
     nixbld32:	30032

Ready to continue?
[y/n] y


~~> Setting up the build group nixbld

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o create -r Nix build group for nix-daemon -i 30000 nixbld

Create the Nix build group, nixbld

            Created:	Yes

~~> Setting up the build user nixbld1

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld1 UniqueID 30001

Creating the Nix build user (#1), nixbld1

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld1 IsHidden 1

in order to make nixbld1 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld1 NFSHomeDirectory /var/empty

in order to give nixbld1 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 1

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld1 UserShell /sbin/nologin

in order to give nixbld1 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld1 nixbld

Add nixbld1 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld1 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld2

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld2 UniqueID 30002

Creating the Nix build user (#2), nixbld2

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld2 IsHidden 1

in order to make nixbld2 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld2 NFSHomeDirectory /var/empty

in order to give nixbld2 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 2

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld2 UserShell /sbin/nologin

in order to give nixbld2 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld2 nixbld

Add nixbld2 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld2 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld3

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld3 UniqueID 30003

Creating the Nix build user (#3), nixbld3

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld3 IsHidden 1

in order to make nixbld3 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld3 NFSHomeDirectory /var/empty

in order to give nixbld3 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 3

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld3 UserShell /sbin/nologin

in order to give nixbld3 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld3 nixbld

Add nixbld3 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld3 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld4

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld4 UniqueID 30004

Creating the Nix build user (#4), nixbld4

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld4 IsHidden 1

in order to make nixbld4 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld4 NFSHomeDirectory /var/empty

in order to give nixbld4 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 4

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld4 UserShell /sbin/nologin

in order to give nixbld4 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld4 nixbld

Add nixbld4 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld4 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld5

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld5 UniqueID 30005

Creating the Nix build user (#5), nixbld5

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld5 IsHidden 1

in order to make nixbld5 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld5 NFSHomeDirectory /var/empty

in order to give nixbld5 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 5

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld5 UserShell /sbin/nologin

in order to give nixbld5 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld5 nixbld

Add nixbld5 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld5 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld6

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld6 UniqueID 30006

Creating the Nix build user (#6), nixbld6

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld6 IsHidden 1

in order to make nixbld6 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld6 NFSHomeDirectory /var/empty

in order to give nixbld6 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 6

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld6 UserShell /sbin/nologin

in order to give nixbld6 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld6 nixbld

Add nixbld6 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld6 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld7

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld7 UniqueID 30007

Creating the Nix build user (#7), nixbld7

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld7 IsHidden 1

in order to make nixbld7 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld7 NFSHomeDirectory /var/empty

in order to give nixbld7 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 7

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld7 UserShell /sbin/nologin

in order to give nixbld7 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld7 nixbld

Add nixbld7 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld7 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld8

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld8 UniqueID 30008

Creating the Nix build user (#8), nixbld8

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld8 IsHidden 1

in order to make nixbld8 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld8 NFSHomeDirectory /var/empty

in order to give nixbld8 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 8

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld8 UserShell /sbin/nologin

in order to give nixbld8 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld8 nixbld

Add nixbld8 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld8 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld9

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld9 UniqueID 30009

Creating the Nix build user (#9), nixbld9

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld9 IsHidden 1

in order to make nixbld9 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld9 NFSHomeDirectory /var/empty

in order to give nixbld9 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 9

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld9 UserShell /sbin/nologin

in order to give nixbld9 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld9 nixbld

Add nixbld9 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld9 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld10

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld10 UniqueID 30010

Creating the Nix build user (#10), nixbld10

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld10 IsHidden 1

in order to make nixbld10 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld10 NFSHomeDirectory /var/empty

in order to give nixbld10 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 10

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld10 UserShell /sbin/nologin

in order to give nixbld10 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld10 nixbld

Add nixbld10 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld10 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld11

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld11 UniqueID 30011

Creating the Nix build user (#11), nixbld11

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld11 IsHidden 1

in order to make nixbld11 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld11 NFSHomeDirectory /var/empty

in order to give nixbld11 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 11

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld11 UserShell /sbin/nologin

in order to give nixbld11 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld11 nixbld

Add nixbld11 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld11 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld12

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld12 UniqueID 30012

Creating the Nix build user (#12), nixbld12

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld12 IsHidden 1

in order to make nixbld12 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld12 NFSHomeDirectory /var/empty

in order to give nixbld12 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 12

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld12 UserShell /sbin/nologin

in order to give nixbld12 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld12 nixbld

Add nixbld12 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld12 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld13

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld13 UniqueID 30013

Creating the Nix build user (#13), nixbld13

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld13 IsHidden 1

in order to make nixbld13 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld13 NFSHomeDirectory /var/empty

in order to give nixbld13 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 13

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld13 UserShell /sbin/nologin

in order to give nixbld13 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld13 nixbld

Add nixbld13 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld13 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld14

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld14 UniqueID 30014

Creating the Nix build user (#14), nixbld14

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld14 IsHidden 1

in order to make nixbld14 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld14 NFSHomeDirectory /var/empty

in order to give nixbld14 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 14

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld14 UserShell /sbin/nologin

in order to give nixbld14 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld14 nixbld

Add nixbld14 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld14 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld15

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld15 UniqueID 30015

Creating the Nix build user (#15), nixbld15

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld15 IsHidden 1

in order to make nixbld15 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld15 NFSHomeDirectory /var/empty

in order to give nixbld15 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 15

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld15 UserShell /sbin/nologin

in order to give nixbld15 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld15 nixbld

Add nixbld15 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld15 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld16

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld16 UniqueID 30016

Creating the Nix build user (#16), nixbld16

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld16 IsHidden 1

in order to make nixbld16 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld16 NFSHomeDirectory /var/empty

in order to give nixbld16 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 16

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld16 UserShell /sbin/nologin

in order to give nixbld16 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld16 nixbld

Add nixbld16 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld16 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld17

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld17 UniqueID 30017

Creating the Nix build user (#17), nixbld17

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld17 IsHidden 1

in order to make nixbld17 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld17 NFSHomeDirectory /var/empty

in order to give nixbld17 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 17

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld17 UserShell /sbin/nologin

in order to give nixbld17 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld17 nixbld

Add nixbld17 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld17 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld18

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld18 UniqueID 30018

Creating the Nix build user (#18), nixbld18

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld18 IsHidden 1

in order to make nixbld18 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld18 NFSHomeDirectory /var/empty

in order to give nixbld18 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 18

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld18 UserShell /sbin/nologin

in order to give nixbld18 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld18 nixbld

Add nixbld18 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld18 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld19

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld19 UniqueID 30019

Creating the Nix build user (#19), nixbld19

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld19 IsHidden 1

in order to make nixbld19 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld19 NFSHomeDirectory /var/empty

in order to give nixbld19 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 19

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld19 UserShell /sbin/nologin

in order to give nixbld19 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld19 nixbld

Add nixbld19 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld19 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld20

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld20 UniqueID 30020

Creating the Nix build user (#20), nixbld20

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld20 IsHidden 1

in order to make nixbld20 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld20 NFSHomeDirectory /var/empty

in order to give nixbld20 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 20

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld20 UserShell /sbin/nologin

in order to give nixbld20 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld20 nixbld

Add nixbld20 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld20 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld21

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld21 UniqueID 30021

Creating the Nix build user (#21), nixbld21

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld21 IsHidden 1

in order to make nixbld21 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld21 NFSHomeDirectory /var/empty

in order to give nixbld21 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 21

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld21 UserShell /sbin/nologin

in order to give nixbld21 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld21 nixbld

Add nixbld21 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld21 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld22

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld22 UniqueID 30022

Creating the Nix build user (#22), nixbld22

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld22 IsHidden 1

in order to make nixbld22 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld22 NFSHomeDirectory /var/empty

in order to give nixbld22 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 22

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld22 UserShell /sbin/nologin

in order to give nixbld22 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld22 nixbld

Add nixbld22 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld22 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld23

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld23 UniqueID 30023

Creating the Nix build user (#23), nixbld23

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld23 IsHidden 1

in order to make nixbld23 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld23 NFSHomeDirectory /var/empty

in order to give nixbld23 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 23

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld23 UserShell /sbin/nologin

in order to give nixbld23 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld23 nixbld

Add nixbld23 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld23 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld24

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld24 UniqueID 30024

Creating the Nix build user (#24), nixbld24

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld24 IsHidden 1

in order to make nixbld24 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld24 NFSHomeDirectory /var/empty

in order to give nixbld24 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 24

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld24 UserShell /sbin/nologin

in order to give nixbld24 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld24 nixbld

Add nixbld24 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld24 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld25

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld25 UniqueID 30025

Creating the Nix build user (#25), nixbld25

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld25 IsHidden 1

in order to make nixbld25 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld25 NFSHomeDirectory /var/empty

in order to give nixbld25 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 25

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld25 UserShell /sbin/nologin

in order to give nixbld25 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld25 nixbld

Add nixbld25 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld25 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld26

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld26 UniqueID 30026

Creating the Nix build user (#26), nixbld26

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld26 IsHidden 1

in order to make nixbld26 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld26 NFSHomeDirectory /var/empty

in order to give nixbld26 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 26

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld26 UserShell /sbin/nologin

in order to give nixbld26 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld26 nixbld

Add nixbld26 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld26 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld27

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld27 UniqueID 30027

Creating the Nix build user (#27), nixbld27

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld27 IsHidden 1

in order to make nixbld27 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld27 NFSHomeDirectory /var/empty

in order to give nixbld27 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 27

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld27 UserShell /sbin/nologin

in order to give nixbld27 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld27 nixbld

Add nixbld27 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld27 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld28

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld28 UniqueID 30028

Creating the Nix build user (#28), nixbld28

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld28 IsHidden 1

in order to make nixbld28 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld28 NFSHomeDirectory /var/empty

in order to give nixbld28 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 28

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld28 UserShell /sbin/nologin

in order to give nixbld28 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld28 nixbld

Add nixbld28 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld28 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld29

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld29 UniqueID 30029

Creating the Nix build user (#29), nixbld29

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld29 IsHidden 1

in order to make nixbld29 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld29 NFSHomeDirectory /var/empty

in order to give nixbld29 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 29

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld29 UserShell /sbin/nologin

in order to give nixbld29 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld29 nixbld

Add nixbld29 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld29 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld30

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld30 UniqueID 30030

Creating the Nix build user (#30), nixbld30

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld30 IsHidden 1

in order to make nixbld30 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld30 NFSHomeDirectory /var/empty

in order to give nixbld30 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 30

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld30 UserShell /sbin/nologin

in order to give nixbld30 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld30 nixbld

Add nixbld30 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld30 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld31

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld31 UniqueID 30031

Creating the Nix build user (#31), nixbld31

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld31 IsHidden 1

in order to make nixbld31 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld31 NFSHomeDirectory /var/empty

in order to give nixbld31 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 31

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld31 UserShell /sbin/nologin

in order to give nixbld31 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld31 nixbld

Add nixbld31 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld31 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

~~> Setting up the build user nixbld32

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . create /Users/nixbld32 UniqueID 30032

Creating the Nix build user (#32), nixbld32

           Created:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld32 IsHidden 1

in order to make nixbld32 a hidden user

            Hidden:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld32 NFSHomeDirectory /var/empty

in order to give nixbld32 a safe home directory

    Home Directory:	/var/empty
              Note:	Nix build user 32

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld32 UserShell /sbin/nologin

in order to give nixbld32 a safe home directory

   Logins Disabled:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/dseditgroup -o edit -t user -a nixbld32 nixbld

Add nixbld32 to the nixbld group

  Member of nixbld:	Yes

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/dscl . -create /Users/nixbld32 PrimaryGroupID 30000

to let the nix daemon use this user for builds (this might seem redundant, but there are two concepts of group membership)

    PrimaryGroupID:	30000

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo mkdir -pv -m 0755 /nix /nix/var /nix/var/log /nix/var/log/nix /nix/var/log/nix/drvs /nix/var/nix /nix/var/nix/db /nix/var/nix/gcroots /nix/var/nix/profiles /nix/var/nix/temproots /nix/var/nix/userpool /nix/var/nix/gcroots/per-user /nix/var/nix/profiles/per-user

to make the basic directory structure of Nix (part 1)

mkdir: /nix: Read-only file system
mkdir: /nix/var: Read-only file system
mkdir: /nix/var/log: Read-only file system
mkdir: /nix/var/log/nix: Read-only file system
mkdir: /nix/var/log/nix/drvs: Read-only file system
mkdir: /nix/var/nix: Read-only file system
mkdir: /nix/var/nix/db: Read-only file system
mkdir: /nix/var/nix/gcroots: Read-only file system
mkdir: /nix/var/nix/profiles: Read-only file system
mkdir: /nix/var/nix/temproots: Read-only file system
mkdir: /nix/var/nix/userpool: Read-only file system
mkdir: /nix/var/nix/gcroots/per-user: Read-only file system
mkdir: /nix/var/nix/profiles/per-user: Read-only file system

---- oh no! --------------------------------------------------------------------
Jeeze, something went wrong. If you can take all the output and open
an issue, we'd love to fix the problem so nobody else has this issue.

:(

We'd love to help if you need it.

If you can, open an issue at https://github.com/nixos/nix/issues

Or feel free to contact the team,
 - on IRC #nixos on irc.freenode.net
 - on twitter @nixos_org
bash-5.1$
```

</details>

**Additional context**

ProductName:	macOS
ProductVersion:	11.2
BuildVersion:	20D64

### LINKED ISSUE #4675: Nix install failed on macOS 11.2.3 with FileVault and a pre-existing unencrypted Nix Store volume
After installing nix using the old method and realizing the created volume was unencrypted I attempted to reinstall using the most recent version of abathur's installer from NixOS/nix/#4289. It went through a number of steps. to remove the pre-existing install and failed mounting the disk.

A second run of the same produced a working install.

The full nix install log follows:

```
% sh <(curl https://abathur-nix-install-tests.cachix.org/serve/7sqcns3hn4brpm53j1afkmmx8im6zjb2/install) --tarball-url-prefix https://abathur-nix-install-tests.cachix.org/serve
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3656    0  3656    0     0   1915      0 --:--:--  0:00:01 --:--:--  1914
downloading Nix 2.4pre19700101_97269f6 binary tarball for x86_64-darwin from 'https://abathur-nix-install-tests.cachix.org/serve/nd0ijj1zp6chap43nnc5k9qwlyylidcb/nix-2.4pre19700101_97269f6-x86_64-darwin.tar.xz' to '/var/folders/nt/807f8y4j179bjf58wq36pymh0000gp/T/nix-binary-tarball-unpack.XXXXXXXXXX.usLEvzFX'...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 25.4M    0 25.4M    0     0  1486k      0 --:--:--  0:00:17 --:--:-- 2716k
Switching to the Multi-user Installer
Welcome to the Multi-User Nix Installation

This installation tool will set up your computer with the Nix package
manager. This will happen in a few stages:

1. Make sure your computer doesn't already have Nix. If it does, I
   will show you instructions on how to clean up your old install.

2. Show you what we are going to install and where. Then we will ask
   if you are ready to continue.

3. Create the system users and groups that the Nix daemon uses to run
   builds.

4. Perform the basic installation of the Nix files daemon.

5. Configure your shell to import special Nix Profile files, so you
   can use Nix.

6. Start the Nix daemon.

Would you like to see a more detailed list of what we will do?
[y/n] n


---- let's talk about sudo -----------------------------------------------------
This script is going to call sudo a lot. Every time we do, it'll
output exactly what it'll do, and why.

Just like this:

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo echo

to demonstrate how our sudo prompts look


This might look scary, but everything can be undone by running just a
few commands. We used to ask you to confirm each time sudo ran, but it
was too many times. Instead, I'll just ask you this one time:

Can we use sudo?
[y/n] y

Yay! Thanks! Let's get going!

~~> Fixing any leftover Nix volume state
Before I try to install, I'll check for any existing Nix volume config
and ask for your permission to remove it (so that the installer can
start fresh). I'll also ask for permission to fix any issues I spot.

---- Found existing Nix volume -------------------------------------------------
  special:	disk1s7
     uuid:	023367B4-9F80-4D37-94C9-32A97AE8FEF2
encrypted:	no

---- warning! ------------------------------------------------------------------
FileVault is on, but your Nix Store volume isn't encrypted.

Should I encrypt it and add the decryption key to your keychain?
[y/n] y

Volume Nix Store on Nix Store mounted

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/security -i

to add your Nix volume's password to Keychain

Password:

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/diskutil apfs encryptVolume Nix Store -user disk -stdinpassphrase

to encrypt your Nix volume

Encrypting with the new "Disk" crypto user on disk1s7
The new "Disk" user will be the only one who has initial access to disk1s7
The new APFS crypto user UUID will be 023367B4-9F80-4D37-94C9-32A97AE8FEF2
Encryption has likely completed due to AES hardware; see "diskutil apfs list"
Volume Nix Store on disk1s7 force-unmounted

During install, I add 'nix' to /etc/synthetic.conf, which instructs
macOS to create an empty root directory for mounting the Nix volume.
Can I remove /etc/synthetic.conf?
[y/n] y


---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo rm /etc/synthetic.conf

to remove /etc/synthetic.conf

During install, I add '/nix' to /etc/fstab so that macOS knows what
mount options to use for the Nix volume.
Can I remove /etc/fstab?
[y/n] y


---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo rm /etc/fstab

to remove /etc/fstab


---- Nix config report ---------------------------------------------------------
        Temp Dir:	/var/folders/nt/807f8y4j179bjf58wq36pymh0000gp/T/tmp.4i3p5bRs2r
        Nix Root:	/nix
     Build Users:	32
  Build Group ID:	30000
Build Group Name:	nixbld

build users:
    Username:	UID
     _nixbld1:	301
     _nixbld2:	302
     _nixbld3:	303
     _nixbld4:	304
     _nixbld5:	305
     _nixbld6:	306
     _nixbld7:	307
     _nixbld8:	308
     _nixbld9:	309
     _nixbld10:	310
     _nixbld11:	311
     _nixbld12:	312
     _nixbld13:	313
     _nixbld14:	314
     _nixbld15:	315
     _nixbld16:	316
     _nixbld17:	317
     _nixbld18:	318
     _nixbld19:	319
     _nixbld20:	320
     _nixbld21:	321
     _nixbld22:	322
     _nixbld23:	323
     _nixbld24:	324
     _nixbld25:	325
     _nixbld26:	326
     _nixbld27:	327
     _nixbld28:	328
     _nixbld29:	329
     _nixbld30:	330
     _nixbld31:	331
     _nixbld32:	332

Ready to continue?
[y/n] y


---- Preparing a Nix volume ----------------------------------------------------
    Nix traditionally stores its data in the root directory /nix, but
    macOS now (starting in 10.15 Catalina) has a read-only root directory.
    To support Nix, I will create a volume and configure macOS to mount it
    at /nix.

~~> Configuring /etc/synthetic.conf to make a mount-point at /nix

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/ex /etc/synthetic.conf

to add Nix to /etc/synthetic.conf


~~> Creating a Nix volume

~~> Configuring /etc/fstab to specify volume mount options

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/sbin/vifs

to add nix to fstab

Volume on disk1s7 failed to mount
This is an encrypted and locked APFS Volume; use "diskutil apfs unlockVolume"

---- oh no! --------------------------------------------------------------------
Jeeze, something went wrong. If you can take all the output and open
an issue, we'd love to fix the problem so nobody else has this issue.

:(

We'd love to help if you need it.

You can open an issue at https://github.com/nixos/nix/issues

Or feel free to contact the team:
 - IRC: in #nixos on irc.freenode.net
 - twitter: @nixos_org
 - forum: https://discourse.nixos.org
```

### PR DESCRIPTION
**Pull request by abathur**
This refactors WIP from #4181 to address things that became obvious:
1. The macOS install is getting too complex for single-user mode.
1. There's already frustration around difficulty of uninstalling multi-user on macOS.
1. I want to support upgrading existing macOS volumes to work the same as those made by this WIP, but simply tacking it on as an extra option at all relevant points was looking like a lot of extra conditional logic and calls to some fairly slow diskutils commands.
1. The greater number of Nix-related artifacts shook loose additional concern around avoiding state/artifact inconsistencies.
1. As I developed a curing process to address these inconsistencies, I realized it won't take too much more work to extend these concepts to uninstalling the other Darwin and general Nix multi-user artifacts. I'm pleasantly surprised how practical an uninstall mode feels from here.

The history had grown unruly even before this refactor, so for now I'm flattening this into an omnibus commit to start fresh. Since this touches on a lot, I've tried to better-document the high-altitude view by making three outlines:
- ~the [general process/logic in pseudocode](https://github.com/abathur/nix/blob/encrypt_darwin_volume/scripts/darwin_volume_reference.py) (as-is, and for the uninstaller I'm imagining)~ removed this for merge
- how high-level user-facing functionality changes here
- what lower-level implementation changes I'm making

## High-level functionality changes
- disable single-user installs on macOS
- if the user's root is read-only, create a volume (overridable default)
	- `--darwin-use-unencrypted-nix-store-volume` flag is now a no-op warning
	- if the boot volume has FileVault enabled, encrypt this volume
		- generate a random credential and place it in the system keychain
	- create a LaunchDaemon to mount it
		- still use fstab to specify mount opts (rw,noauto,nobrowse,suid,owners)
			- noauto so that the system *won't* auto-mount if our mounter breaks (goal: the user finds/presents for help)
		- the daemon isn't strictly necessary for unencrypted volumes, but I'm using it in both cases for consistency
- update volume naming/customization
	- default: use or create volume named "Nix Store" on same disk as /
		- I had changed this to "Nix", but I want to support up-converting current "Nix Store" volumes and can't justify the complexity of supporting both names.
		- no longer tries to match and use volumes labeled `[nN]ix.*` (see #4150)
	- overridable variables for the filesystem, label, and target disk
	- overridable variables to BYOV: volume special device, and UUID
- support curing any volume-related state (if present) on install
	- if Nix Store is encrypted
		- verify we can unlock it from keychain
		- otherwise, prompt the user to delete it or manually add the pw to keychain
	- if filevault is on but Nix Store isn't encrypted, offer to encrypt it
	- if nix is the only item in fstab and synthetic.conf, remove them; otherwise suggest edits that will remove the nix line
	- remove the mounter launchdaemon

## Lower-level implementation changes
- scaffold uninstall and combined uninstall+install actions
- multi-user installer
	- add reminder/remind UI/X idiom (add notes as we go, show all at end)
		- no more saving variables or re-testing conditions at the end
		- if interactive: show one at a time and require acknowledgement
		- convert some existing messages to use this
	- add password_confirm UI/X idiom for actions like deleting a volume
		- forces a sudo prompt (even when headless or sudo was recently authed)
	- add confirm_rm and confirm_edit UI/X idioms
		- these are "for" curing volume state, but I anticipate them being useful for uninstaller (and, I guess, for the installer if we wanted to be more interactive/explicit around some edits)
	- try to make create_directories more idempotent (may cause trouble?)
		- if `/nix` already exists, `chown -R root:nixbld` it
		- use `install -dv -m` instead of `mkdir -pv -m`
		- combine dir-structure steps 2 & 3 with install's `-g` (group) flag
	- only defer to a pre-set NIX_SSL_CERT_FILE if its physical path is not in /nix/store
		- multi-user reinstall over a single-user install was skipping cert setup
	- fail earlier (before sudo lecture etc.) if EUID=0
	- add two new install phases:
		- (poly_)cure_artifacts for reverting changes Nix makes
		- poly_prepare_to_install for preparing the Nix volume on macOS
	- normalize SCRATCH/mktemp path when macOS /usr/bin/mktemp is used:
		- `/usr/bin/mktemp -d -t tmp.XXXXXXXXXX --> /.../tmp.XXXXXXXXXX.2RMrVwkx`
		- `/usr/bin/mktemp -d "${TMPDIR:-/tmp/}tmp.XXXXXXXXXX" --> /.../tmp.JwmZDxN1kf`
	- _sudo "explanation" command ... wrapper now sends explanation to stderr
		- make it easier to pipe commands using the wrapper; see create-darwin-volume.sh:volume_pass_works() for an example
- refactor create-darwin-volume.sh to 
	- be sourceable as a library but still support direct invocation
		- use UI/X idioms from the multi-user installer
		- give multi-user installer fine-grained control of what runs when
		- ~legacy (bare) direct invocation 
			- in case we have to reinstate single-user
			- avoid no/low-notice breaks for anyone who has been directly running it
		- externally invoke a non-main func with args "no-main" "funcname" ...
		- I've seen a fair number of modified forks of this script; over time I hope sourceability and external function invocation will make it easier to re-use
	- largely eradicate a pattern, `<run very slow diskutil command> | <parse a single bit of info out with an xpath query>`, which is OK in isolation but was becoming a bit too common
	- remove (most) instruction dumps that describe how to remove things that the curing process can now handle
	- defensively use absolute default paths for some common executables (coreutils, find, grep, etc.)

@LnL7 @lilyball @matthewbauer @dhess @mroi @domenkozar (others I'm forgetting are inevitably also interested; feel free to add people)

# Try it out?
I have been hosting my own installers for much of the history of this PR. Nix now has a better installer-testing process, so I'm going to see if we can lean on it here. I'll leave the old process note here for a bit in case there are problems with the new approach. If you can't try it out, you can see output from the [CI run](https://github.com/abathur/nix/runs/2469712006).

The new approach requires an extra flag, so it'll be easiest to just use in interactive mode:
```bash
sh <(curl https://abathur-nix-install-tests.cachix.org/serve/yihf8zbs0jwph2rs9qfh80dnilijxdi2/install) --tarball-url-prefix https://abathur-nix-install-tests.cachix.org/serve
```
Here's a history of the versions it has pointed at, with the current at the bottom (note: I'll only update this for substantive changes or breakage):
- ~6132132~ (equivalent to 401afa0, but without the reference darwin_volume_reference.py)
- ~6bb3bc9~
- ~0bd1083~
- ~86dbee7~
- ~97269f6~
- ~c235bed~
- eab14a6

<details><summary>old privately-hosted installer (out of date--use only if above doesn't work)</summary>

I have a temporary installer up at https://files.t-ravis.com/install-multi, so `curl https://files.t-ravis.com/install-multi | sh` (headless) and `sh <(curl https://files.t-ravis.com/install-multi)` (interactive) should work.
</details>

# Other issues
I believe this PR:
- closes #3435 (but see [my comment there](https://github.com/NixOS/nix/issues/3435#issuecomment-745701610))
- closes #3667
- obsoletes #3692
- closes #4150
- closes #4380
- closes #4390
- closes #4488
- closes #4666
- closes #4675

### CODE REVIEW

**Comment by dhess** [comment]
Thanks once again for this work and the attention to detail.

Does anyone know: on T2 Macs, if you encrypt a user-created APFS volume, is the encryption/decryption for that volume still done on the T2, as with the system volumes; or is it done in software on the CPU?

**Comment by abathur** [comment]
> on T2 Macs, if you encrypt a user-created APFS volume, is the encryption/decryption for that volume still done on the T2, as with the system volumes; or is it done in software on the CPU?

I *think* it's on the T2, but I won't swear I personally know this as a fact. For example, see the last line below:
```
$ diskutil apfs encryptVolume disk1s7 -user disk -passphrase foo
Encrypting with the new "Disk" crypto user on disk1s7
The new "Disk" user will be the only one who has initial access to disk1s7
The new APFS crypto user UUID will be 920D4EAD-BFAE-457B-9A19-827AAC0C1B42
Encryption has likely completed due to AES hardware; see "diskutil apfs list"
```

If you encrypt a volume on a pre-T2 mac, that line will say `Background encryption is ongoing; see "diskutil apfs list" to see progress`

**Comment by LnL7** [comment]
That's also how I understood the T2 documentation from apple https://www.apple.com/jp/mac/docs/Apple_T2_Security_Chip_Overview.pdf.

The chip handles all the encryption and is actually always enabled, FileVault only changes the conditions for which the chip unlocks the data. Meaning that the data also doesn't have to change when updating credentials. Which the behaviour you noticed seems to confirm is the case.

File: scripts/install-multi-user.sh [hunk 1]
```diff
@@ -199,6 +202,87 @@ ui_confirm() {
...
+printf -v _UNCHANGED_GRP_FMT "%b" $'\033[2m%='"$ESC" # "dim"
+# bold+invert+red and bold+invert+green just for the +/- below
+# red/green foreground for rest of the line
+printf -v _OLD_LINE_FMT "%b" $'\033[1;7;31m-'"$ESC ${RED}%L${ESC}"
+printf -v _NEW_LINE_FMT "%b" $'\033[1;7;32m+'"$ESC ${GREEN}%L${ESC}"
+
+_diff() {
+    # colorized diff comatible w/ pre `--color` versions
+    diff --unchanged-group-format="$_UNCHANGED_GRP_FMT" --old-line-format="$_OLD_LINE_FMT" --new-line-format="$_NEW_LINE_FMT" --unchanged-line-format="  %L" "$@"
+}
```
Comment (abathur) [inline scripts/install-multi-user.sh:214]: For the curious, this format is something like: 
Screen Shot 2020-11-28 at 11 13 44 AM

File: scripts/install-multi-user.sh [hunk 2]
```diff
@@ -199,6 +202,87 @@ ui_confirm() {
...
+It looks like Nix isn't the only thing here, but I think I know how to edit it
+out. Here's the diff:
+EOF
+
+    # could technically test the diff, but caller should do it
+    _diff "$1" "$2"
+    if ui_confirm "Does the change above look right?"; then
+        _sudo "remove nix from $1" cp "$2" "$1"
+    fi
+}
```
Comment (abathur) [inline scripts/install-multi-user.sh:234]: Here's a screenshot of confirm_rm and confirm_edit (including _diff) in use:
Screen Shot 2020-11-28 at 1 21 20 PM

File: scripts/install-multi-user.sh [hunk 3]
```diff
@@ -199,6 +202,87 @@ ui_confirm() {
...
+
+remind() {
+    if ! [ "${#_reminders}" = 0 ]; then
+        header "Reminders"
+        for line in "${_reminders[@]}"; do
+            echo "$line"
+            if ! headless && [ "${#line}" = 0 ]; then
+                if read -r -p "Press enter/return to acknowledge."; then
+                    printf $'\033[A\33[2K\r'
+                fi
```
Comment (abathur) [inline scripts/install-multi-user.sh:264]: When run interactively, reminder prompts look like:
Screen Shot 2020-11-28 at 1 26 41 PM

File: scripts/install-multi-user.sh [hunk 4]
```diff
@@ -199,6 +202,87 @@ ui_confirm() {
...
+}
+
+_SERIOUS_BUSINESS="${RED}%s:${ESC} "
+password_confirm() {
+    if ui_confirm "Can I $1?"; then
+        # shellcheck disable=SC2059
+        sudo -kv --prompt="$(printf "${_SERIOUS_BUSINESS}" "Enter your password to $1")"
+    fi
+}
+
```
Comment (abathur) [inline scripts/install-multi-user.sh:243]: Here's a screenshot of how this looks:
Screen Shot 2020-11-28 at 1 34 02 PM

**Comment by abathur** [comment]
In case anyone's curious, I added screenshots of the ~interactive UI/X elements in a comment alongside the code for each (and immediately resolved them, so they don't take up gobs of space in the main thread).

**Comment by lilyball** [comment]
For future reference, you can use `<details>` tags to hide screenshots by default.

```markdown
<details><summary>Description of screenshot</summary>

// drag image into this blank line, if it's surrounded by blank lines the markdown ![image](url) syntax will work just fine.

</details>
```

This will show up as

<details><summary>Collapsed summary here</summary>

Once expanded the image will be visible.

</details>

File: scripts/create-darwin-volume.sh [hunk 5]
```diff
@@ -1,33 +1,210 @@
...
+</xsl:stylesheet>
+EOF
+    # I cut label out of the extracted values, but here it is for reference:
+    # <xsl:apply-templates match="string" select="key[text()='IORegistryEntryName']/following-sibling::*[1]"/>
+    # <xsl:text>◊</xsl:text>
+}
+
+# $1 = volume special (i.e., disk1s7)
+right_disk() {
+    [ "${1::${#NIX_VOLUME_USE_DISK}}" = "$NIX_VOLUME_USE_DISK" ]
```
Comment (lilyball) [inline scripts/create-darwin-volume.sh:94]: This is going to have a spurious match on `$1 == disk10s1` and `$NIX_VOLUME_USE_DISK = disk1`. We can fix this and write it more idiomatically as:

```suggestion
    [[ "$1" == "$NIX_VOLUME_USE_DISK"s* ]]
```

File: scripts/create-darwin-volume.sh [hunk 6]
```diff
@@ -1,33 +1,210 @@
...
+# $1 = volume special (i.e., disk1s7)
+right_volume() {
+    # if set, it must match; otherwise ensure it's on the right disk
+    if [ -z "$NIX_VOLUME_USE_SPECIAL" ]; then
+        if right_disk "$1"; then
+            NIX_VOLUME_USE_SPECIAL="$1" # latch on
+            return 0
+        else
+            return 1
+        fi
```
Comment (lilyball) [inline scripts/create-darwin-volume.sh:105]: This could be simplified as

```suggestion
        right_disk "$1" \
        && NIX_VOLUME_USE_SPECIAL="$1" # latch on
```

File: scripts/create-darwin-volume.sh [hunk 7]
```diff
@@ -1,33 +1,210 @@
...
+}
+# $1 = volume uuid
+right_uuid() {
+    # if set, it must match; otherwise allow
+    if [ -z "$NIX_VOLUME_USE_UUID" ]; then
+        NIX_VOLUME_USE_UUID="$1" # latch on
+        return 0
+    else
+        [ "$1" = "$NIX_VOLUME_USE_UUID" ]
+    fi
```
Comment (lilyball) [inline scripts/create-darwin-volume.sh:118]: This isn’t necessarily a clear win, but it could be simplified to

```suggestion
    [ "$1" = "${NIX_VOLUME_USE_UUID:=$1}" ]
```

File: scripts/create-darwin-volume.sh [hunk 8]
```diff
@@ -1,33 +1,210 @@
...
+}
+
+# $1 = label
+cure_volumes() {
+    local found="" volume special uuid
+    # loop just in case they have more than one volume
+    # (nothing stops you from doing this)
+    for volume in $(volumes_labeled "$NIX_VOLUME_LABEL"); do
+        IFS=◊ read -r special uuid <<< "$volume"
```
Comment (lilyball) [inline scripts/create-darwin-volume.sh:127]: Why are we using this unicode character as a separator? Neither UUIDs nor disk BSD names will have spaces, so we can just use a space, or maybe use a `=` instead.

If we did have to worry about spaces then the `for` loop wouldn’t work (as it does word splitting, not line splitting). And in fact I’m tempted to say we should replace it anyway for idiomatic reasons. If we replace the separator with `=` then we can turn this loop into

```bash
    while IFS== read -r special uuid; do
        # ...
    done <<<"$(volumes_labeled "$NIX_VOLUME_LABEL")"
```

File: scripts/create-darwin-volume.sh [hunk 9]
```diff
@@ -1,33 +1,210 @@
...
+        NIX_VOLUME_USE_UUID="$1" # latch on
+        return 0
+    else
+        [ "$1" = "$NIX_VOLUME_USE_UUID" ]
+    fi
+}
+
+# $1 = label
+cure_volumes() {
+    local found="" volume special uuid
```
Comment (lilyball) [inline scripts/create-darwin-volume.sh:123]: Why does `found` have a default value? `local` should erase any previous value anyway.

**Review by lilyball — COMMENTED** [review]
This is only a partial review, I’ll have to come back to this later.

File: scripts/create-darwin-volume.sh [hunk 10]
```diff
@@ -1,33 +1,210 @@
...
+    test_filevault_in_use() { return 0; }
+    # no readonly; we may modify if user refuses from cure_volume
+    NIX_VOLUME_DO_ENCRYPT="${NIX_VOLUME_DO_ENCRYPT:-1}"
+else
+    test_filevault_in_use() { return 1; }
+    NIX_VOLUME_DO_ENCRYPT="${NIX_VOLUME_DO_ENCRYPT:-0}"
+fi
+
+should_encrypt_volume() {
+    test_filevault_in_use && [ "$NIX_VOLUME_DO_ENCRYPT" = "1" ]
```
[the remark this answers is not in the document]
Comment (abathur) [reply scripts/create-darwin-volume.sh:48]: I don't have a _strong_ opinion on these tests, though I did wonder a little about what would be most familiar/accessible in these cases (including the `-xy` arithmetic tests).

I guess it's a chicken-and-egg problem--do you feel like the arithmetic expression form is well-known enough to use in these cases?

File: scripts/create-darwin-volume.sh [hunk 11]
```diff
@@ -1,33 +1,210 @@
...
+    local special_device
+    special_device="$(/usr/bin/stat -f "%Sd" /)"
+    echo "${special_device/s[0-9]*/}"
 }
 
-find_nix_volume() {
-    diskutil apfs list -plist "$1" | xmllint --xpath "(/plist/dict/array/dict/key[text()='Volumes']/following-sibling::array/dict/key[text()='Name']/following-sibling::string[starts-with(translate(text(),'N','n'),'nix')]/text())[1]" - 2>/dev/null || true
+# Strongly assuming we'll make a volume on the device root is on
+# But you can override NIX_VOLUME_USE_DISK to create it on some other device
+readonly NIX_VOLUME_USE_DISK="${NIX_VOLUME_USE_DISK:-$(root_disk_identifier)}"
```
[the remark this answers is not in the document]
Comment (abathur) [reply scripts/create-darwin-volume.sh:65]: Good point. I'll tentatively move the function definition above the variables, and move this variable up with the rest.

File: doc/manual/src/installation/installing-binary.md [hunk 12]
```diff
@@ -1,18 +1,26 @@
...
+The easiest way to install Nix is to run the following command:
 
 ```console
 $ sh <(curl -L https://nixos.org/nix/install)
 ```
 
-If you're using macOS 10.15 (Catalina) or newer, consult [the macOS
-installation instructions](#macos-installation) before installing.
+This will run the installer interactively (causing it to explain what
+it is doing more explicitly, and perform the default "type" of install
```
[the remark this answers is not in the document]
Comment (abathur) [reply doc/manual/src/installation/installing-binary.md:10]: Made change to local copy

File: scripts/create-darwin-volume.sh [hunk 13]
```diff
@@ -1,33 +1,210 @@
-#!/bin/sh
-set -e
+#!/usr/bin/env bash
+set -eu
 
-root_disk() {
-    diskutil info -plist /
+# support import-only `. create-darwin-volume.sh no-main[ ...]`
+if [ "${1-}" = "no-main" ]; then
+    shift
```
[the remark this answers is not in the document]
Comment (abathur) [reply scripts/create-darwin-volume.sh:6]: I guess I'm under-selling it a bit. 

I made *a* change to support import-only, but I am also:
- Trying really hard not to break existing workflows that depend on this script (and I'm not really sure if anyone's sourcing it). I don't necessarily think we need to keep supporting all possible uses--but if we do I think it should be in a narrower changeset.
- Intentionally leaving open the possibility that someone could still invoke the script, but skip the main routine and run some other. (Similarly, I wouldn't really fight for this feature--it just seemed like an agnostic position to leave it in.

I've updated the comment locally to better reflect this.

File: scripts/create-darwin-volume.sh [hunk 14]
```diff
@@ -1,33 +1,210 @@
...
 root_disk_identifier() {
-    diskutil info -plist / | xmllint --xpath "/plist/dict/key[text()='ParentWholeDisk']/following-sibling::string[1]/text()" -
+    # For performance (~10ms vs 280ms) I'm parsing 'diskX' from stat output
+    # (~diskXsY)--but I'm retaining the more-semantic approach since
+    # it documents intent better.
+    # /usr/sbin/diskutil info -plist / | xmllint --xpath "/plist/dict/key[text()='ParentWholeDisk']/following-sibling::string[1]/text()" -
+    #
+    local special_device
+    special_device="$(/usr/bin/stat -f "%Sd" /)"
+    echo "${special_device/s[0-9]*/}"
```
[the remark this answers is not in the document]
Comment (abathur) [reply scripts/create-darwin-volume.sh:60]: I've adopted this locally

File: scripts/create-darwin-volume.sh (hunk 5 above)
Comment (abathur) [reply scripts/create-darwin-volume.sh:94]: Good catch! Adopted locally.

File: scripts/create-darwin-volume.sh (hunk 9 above)
Comment (abathur) [reply scripts/create-darwin-volume.sh:123]: Just vestigial from before I made a pass to add local. Good catch. Adopted local.

File: scripts/create-darwin-volume.sh (hunk 8 above)
Comment (abathur) [reply scripts/create-darwin-volume.sh:127]: Vestigial from when this was still handling volume labels (before I decided not to try to support both `Nix` and `Nix Store`). Another good catch! 👍 Adopted locally.

File: scripts/create-darwin-volume.sh [hunk 15]
```diff
@@ -1,33 +1,210 @@
...
 }
 
-find_nix_volume() {
-    diskutil apfs list -plist "$1" | xmllint --xpath "(/plist/dict/array/dict/key[text()='Volumes']/following-sibling::array/dict/key[text()='Name']/following-sibling::string[starts-with(translate(text(),'N','n'),'nix')]/text())[1]" - 2>/dev/null || true
+# Strongly assuming we'll make a volume on the device root is on
```
[the remark this answers is not in the document]
Comment (abathur) [reply scripts/create-darwin-volume.sh:63]: Rephrased to `Strongly assuming we'll make a volume on the device / is on` in local copy.

File: scripts/create-darwin-volume.sh (hunk 6 above)
Comment (abathur) [reply scripts/create-darwin-volume.sh:105]: I feel roughly the same way about this one and the one on `NIX_VOLUME_USE_UUID` as the arithmetic expression for `NIX_VOLUME_DO_ENCRYPT`. 

I'm trying to err on the side of clarity in these (especially since the env overrides and are more likely to be read by general users), but I like the economy of these and am happy to save a few lines if people agree they are grokkable.

File: scripts/install-multi-user.sh [hunk 16]
```diff
@@ -199,6 +202,87 @@ ui_confirm() {
...
+# setting isn't enough to decide whether to message because you only
+# need to message if you *changed* it.
+
+# reminders stored in array delimited by empty entry; if ! headless,
+# user is asked to confirm after each delimiter.
+_reminders=()
+((_remind_num=1))
+
+remind() {
+    if ! [ "${#_reminders}" = 0 ]; then
```
Comment (SuperSandro2000) [inline scripts/install-multi-user.sh:257]:
```suggestion
    if [ "${#_reminders}" = 0 ]; then
      return
    fi
```
This could remove some intendantions.

File: scripts/install-multi-user.sh [hunk 17]
```diff
@@ -704,5 +843,15 @@ main() {
...
+    # uninstall)
+    #     shift
+    #     uninstall "$@";;
+    ""|install|*)
+        if ! [ "${#@}" = 0 ]; then
+            shift
+        fi
+        # same as the no-arg condition for now (but, explicit)
+        main "$@";;
+esac
```
Comment (SuperSandro2000) [inline scripts/install-multi-user.sh:857]:
```suggestion
    install|*)
      if ! [ "${#@}" = 0 ]; then
        shift
      fi
      # same as the no-arg condition for now (but, explicit)
      main "$@"
      ;;
esac
```

I would do it like this.

File: scripts/install-systemd-multi-user.sh [hunk 18]
```diff
@@ -41,10 +41,8 @@ handle_network_proxy() {
     fi
 }
 
-poly_validate_assumptions() {
-    if [ "$(uname -s)" != "Linux" ]; then
-        failure "This script is for use with Linux!"
-    fi
+poly_cure_artifacts() {
+    :
```
Comment (SuperSandro2000) [inline scripts/install-systemd-multi-user.sh:45]: Why not remove this completely? It does not do anything right now.

File: scripts/install-multi-user.sh [hunk 19]
```diff
@@ -199,6 +202,87 @@ ui_confirm() {
...
+                fi
+            fi
+        done
+    fi
+}
+
+reminder() {
+    printf -v label "${BLUE}[ %d ]${ESC}" "$_remind_num"
+    _reminders+=("$label")
+    if [ "$*" = "" ]; then
```
Comment (SuperSandro2000) [inline scripts/install-multi-user.sh:273]:
```suggestion
    if [[ -z $* ]]; then
```

File: scripts/install-multi-user.sh [hunk 20]
```diff
@@ -627,14 +730,27 @@ configure_shell_profile() {
...
 
 setup_default_profile() {
-    _sudo "to installing a bootstrapping Nix in to the default Profile" \
+    task "Setting up the default profile"
+    _sudo "to install a bootstrapping Nix in to the default profile" \
           HOME="$ROOT_HOME" "$NIX_INSTALLED_NIX/bin/nix-env" -i "$NIX_INSTALLED_NIX"
 
-    if [ -z "${NIX_SSL_CERT_FILE:-}" ] || ! [ -f "${NIX_SSL_CERT_FILE:-}" ]; then
-        _sudo "to installing a bootstrapping SSL certificate just for Nix in to the default Profile" \
+    if [ -z "${NIX_SSL_CERT_FILE:-}" ] || ! [ -f "${NIX_SSL_CERT_FILE:-}" ] || cert_in_store; then
```
Comment (SuperSandro2000) [inline scripts/install-multi-user.sh:752]:
```suggestion
    if [ -z "${NIX_SSL_CERT_FILE:-}" || ! -f "${NIX_SSL_CERT_FILE:-}" ] || cert_in_store; then
```

File: scripts/install-multi-user.sh [hunk 21]
```diff
@@ -660,6 +780,17 @@ EOF
 }
 
 main() {
+    # TODO: I've moved this out of validate_starting_assumptions so we
+    # can fail faster in this case. Sourcing install-darwin... now runs
+    # `touch /` to detect Read-only root, but it could update times on
+    # pre-Catalina macOS if run as root user.
+    if [ $EUID -eq 0 ]; then
```
Comment (SuperSandro2000) [inline scripts/install-multi-user.sh:787]:
```suggestion
    if [ $EUID == 0 ]; then
```

File: scripts/create-darwin-volume.sh (hunk 10 above)
[the remark this answers is not in the document]
Comment (abathur) [reply scripts/create-darwin-volume.sh:48]: I've adopted an approximation of this change locally (I changed sites that set NIX_VOLUME_DO_ENCRYPT to use `let`, and used `(( NIX_VOLUME_DO_ENCRYPT == 1 ))` here to be more explicit.

File: scripts/create-darwin-volume.sh (hunk 6 above)
Comment (abathur) [reply scripts/create-darwin-volume.sh:105]: Keeping the more-explicit version here.

File: scripts/create-darwin-volume.sh (hunk 7 above)
Comment (abathur) [reply scripts/create-darwin-volume.sh:118]: Keeping the more explicit version of this.

File: scripts/install-multi-user.sh (hunk 19 above)
Comment (abathur) [reply scripts/install-multi-user.sh:273]: Partially adopted locally.

File: scripts/install-multi-user.sh (hunk 16 above)
Comment (abathur) [reply scripts/install-multi-user.sh:257]: Not quite adopting this, but the discussion on it did make me realize this would be clearer as an arithmetic expression on `_remind_num`

File: scripts/install-multi-user.sh (hunk 20 above)
Comment (abathur) [reply scripts/install-multi-user.sh:752]:
```console
$ [ -z "${NIX_SSL_CERT_FILE:-}" ] || ! [ -f "${NIX_SSL_CERT_FILE:-}" ]; echo $?
1
$ [ -z "${NIX_SSL_CERT_FILE:-}" || ! -f "${NIX_SSL_CERT_FILE:-}" ]
-bash: [: missing `]'
-bash: -f: command not found
```

This would work with `[[ ... ]]`, but I'm already squeamish about this change (and I don't intend to fold in a general `[` -> `[[` conversion, here--I agree with doing one for the small runtime improvement, but I'm also squeamish about the sheer size of the changeset already; conditional changes like this will be fairly easy to review as a focused commit).

File: scripts/install-multi-user.sh (hunk 21 above)
Comment (abathur) [reply scripts/install-multi-user.sh:787]: I don't intend to modify this in the current PR--just move it. But, thanks for commenting--because looking at the diff made me realize that I forgot to delete it from the other location! <3

File: scripts/install-multi-user.sh (hunk 17 above)
Comment (abathur) [reply scripts/install-multi-user.sh:857]: You're correct, but I'm under-explaining myself here (and you are picking at something that _is_ weird!)

I've updated this locally to hopefully clarify.

File: scripts/install-systemd-multi-user.sh (hunk 18 above)
Comment (abathur) [reply scripts/install-systemd-multi-user.sh:45]: This pattern is used in the `install-{platform}-multi-user.sh` scripts for a function that the outer `install-multi-user.sh` script calls, but which some platforms don't need to invoke.

They're just explicit no-ops to avoid the command-not-found error and be explicit about the API.

**Comment by abathur** [comment]
I've pushed commits addressing one round of comments from @lilyball and @SuperSandro2000 (also thanks to @samueldr and @jtojnar for additional discussion). Going to go ahead and convert this from a draft.

I've started a build of this locally, and will update to confirm its status (status: **TBD**) once it's done and tested.

For anyone champing at the bit, I suspect we'll be holding up just a little bit (if it's a short wait) for the chance I'll be able to help @domenkozar test a new GitHub Actions integration per nix#4047 that should make it easier to test PRs that touch the installer. 

In any case, reviews still welcome in the meantime. :)

File: scripts/create-darwin-volume.sh (hunk 8 above)
Comment (abathur) [reply scripts/create-darwin-volume.sh]: > If we replace the separator with `=` then we can turn this loop into
> 
> ```shell
>     while IFS== read -r special uuid; do
>         # ...
>     done <<<"$(volumes_labeled "$NIX_VOLUME_LABEL")"
> ```

Didn't think to detail the for loop when I triaged this before, but I'm auditing suggestions to make sure I got them all and realized I probably should (I'll also add a comment on this...)

The for loop decision was driven by a gotcha lurking in the function calls, here. The right paths through `cure_volume` can require user interactions that are also being done with `read`, and passing on stdin at the outer level interferes with them (causing them to skip).

You should be able to see this with something like:
```bash
heh(){
    set -x
    while read -r blah; do
        echo "blah? $blah"
        while read -r -p "What do you think?" heh; do
            echo "Do we get here? $heh"
        done
    done <<< "blah blah"
    set +x
}
heh
```

I'm not sure off the top of my head if there's a better fix that doesn't make the code harder to understand. (I noticed `read -u 1` or `read -u 2` "work" here, but I don't grok why and haven't tried to figure it out.)

File: scripts/create-darwin-volume.sh (hunk 6 above)
Comment (lilyball) [reply scripts/create-darwin-volume.sh:109]: Personally I find the more concise one easier to read. But it's not a big deal.

File: scripts/create-darwin-volume.sh (hunk 8 above)
Comment (lilyball) [reply scripts/create-darwin-volume.sh]: `read -u 1` works because stdout and stderr by default point to the terminal (just like stdin) and therefore can actually be read from. A better workaround there is to write it like `read -r -p "What do you think?" heh </dev/tty`, as that's explicitly pointing `read` at the current terminal. Though it would be safe to duplicate fd 0 instead, in case the script is running with stdin pointed elsewhere. We could also update the confirm routines to use a duplicated fd explicitly so we don't have to worry about them.

Having said that, we could also just use fd 3 ourselves and leave fd 0 alone. That would look like

```bash
while IFS== read -r -u 3 special uuid; do
  # ...
done 3<<<"$(volumes_labeled "$NIX_VOLUME_LABEL")"
```

Of course, this assumes fd 3 is free to use, but AFAIK we're not using it anywhere else in the install scripts.

File: scripts/create-darwin-volume.sh [hunk 22]
```diff
@@ -41,129 +243,517 @@ create_synthetic_objects(){
...
+synthetic_conf_uninstall_prompt() {
+    cat <<EOF
+During install, I add '${NIX_ROOT:1}' to /etc/synthetic.conf, which instructs
+macOS to create an empty root directory for mounting the Nix volume.
+EOF
+    # there are a few things we can do here
+    # 1. if grep -v didn't match anything (also, if there's no diff), we know this is moot
+    # 2. if grep -v was empty (but did match?) I think we know that we can just remove the file
+    # 3. if the edit doesn't ~empty the file, show them the diff and ask
+    if ! /usr/bin/grep -v '^'"${NIX_ROOT:1}"'$' /etc/synthetic.conf > "$SCRATCH/synthetic.conf.edit"; then
```
Comment (lilyball) [inline scripts/create-darwin-volume.sh:352]:
```suggestion
    if ! /usr/bin/grep -v "^${NIX_ROOT:1}$" /etc/synthetic.conf > "$SCRATCH/synthetic.conf.edit"; then
```

File: scripts/create-darwin-volume.sh [hunk 23]
```diff
@@ -41,129 +243,517 @@ create_synthetic_objects(){
...
+        if confirm_rm "/etc/synthetic.conf"; then
+            return 0
+        fi
+    else
+        if /usr/bin/cmp <<<"" "$SCRATCH/synthetic.conf.edit"; then
```
Comment (lilyball) [inline scripts/create-darwin-volume.sh:357]: `grep -v`'s error code says whether it printed anything, not whether the regex matches. `echo foo | grep -v bar` returns 0, `echo -n | grep -v bar` returns 1. It also can return an error if the file doesn't exist, though right now we only call this method if we think the file contains our root.

Which is to say, this comparison against empty is unnecessary.

**Review by lilyball — COMMENTED** [review]
Another partial review. Apologies for not managing to do a full one.

File: scripts/create-darwin-volume.sh [hunk 24]
```diff
@@ -1,33 +1,235 @@
...
+# - legacy: `./create-darwin-volume.sh` or `. create-darwin-volume.sh`
+#   (both will run main())
+# - external alt-routine: `./create-darwin-volume.sh no-main func[ ...]`
+if [ "${1-}" = "no-main" ]; then
+    shift
+    readonly _CREATE_VOLUME_NO_MAIN=1
+else
+    readonly _CREATE_VOLUME_NO_MAIN=0
+    # declare some things we expect to inherit from install-multi-user
+    # I don't love this (because it's a bit of a kludge)
```
[the remark this answers is not in the document]
Comment (abathur) [reply scripts/create-darwin-volume.sh:16]: These are just covering enough surface area to avoid breaking existing workflows that directly invoke this script without args.

I don't personally think we should/need to support this long-term, but I think it should get top-billing/consideration in a separate changeset. If we decide to maintain that ability, I agree about re-cutting shared functionality.

File: scripts/create-darwin-volume.sh [hunk 25]
```diff
@@ -1,33 +1,235 @@
-#!/bin/sh
-set -e
+#!/usr/bin/env bash
```
[the remark this answers is not in the document]
Comment (abathur) [reply scripts/create-darwin-volume.sh:1]: Good question. 

I just adopted the shebang from `install-multi-user.sh` for consistency.

I'm not sure how to weight consistency with install-multi-user against being explicit _here_. Everything `install-multi-user.sh` sources has to be 3.2 compatible for this reason (and I did a lot of manual 3.2 testing across all of the scripts as I went). 

I assumed/inferred from the `#!/usr/bin/env bash` shebang on install-multi-user that at least some of the platforms we might be run on don't have a /bin/bash, but if that's not true I suppose they could all change.

What do you think?

File: scripts/create-darwin-volume.sh [hunk 26]
```diff
@@ -1,33 +1,235 @@
...
+    fi
+}
+
+# $1 = special
+volume_encrypted() {
+    # Trying to match the first line of output; known first lines:
+    # No cryptographic users for <special>
+    # Cryptographic user for <special> (1 found)
+    # Cryptographic users for <special> (2 found)
+    diskutil apfs listCryptoUsers "$1" | /usr/bin/grep -q "Cryptographic users* for $1 ([0-9]* found)"
```
[the remark this answers is not in the document]
Comment (abathur) [reply scripts/create-darwin-volume.sh:186]: Good catch. Thanks for seeing the forest. Change made local.

File: scripts/create-darwin-volume.sh [hunk 27]
```diff
@@ -41,129 +243,517 @@ create_synthetic_objects(){
...
+}
+
+# TODO: remove with --uninstall?
+uninstall_launch_daemon_directions() {
+    substep "Uninstall LaunchDaemon $1" \
+      "  sudo launchctl bootout system/$1" \
+      "  sudo rm $2"
+}
+
+uninstall_launch_daemon_prompt() {
```
[the remark this answers is not in the document]
Comment (abathur) [reply scripts/create-darwin-volume.sh:296]: Fixed local

File: scripts/create-darwin-volume.sh (hunk 22 above)
Comment (abathur) [reply scripts/create-darwin-volume.sh:352]: Adopted local

File: scripts/create-darwin-volume.sh (hunk 23 above)
Comment (abathur) [reply scripts/create-darwin-volume.sh:357]: Gah. Good catch. I think I iterated to a better pattern for this anyways. I've edited the function locally to:
```bash
synthetic_conf_uninstall_prompt() {
    cat <<EOF
During install, I add '${NIX_ROOT:1}' to /etc/synthetic.conf, which instructs
macOS to create an empty root directory for mounting the Nix volume.
EOF
    # make the edit to a copy
    /usr/bin/sed -e "/^${NIX_ROOT:1}$/d" "$1" > "$SCRATCH/synthetic.conf.edit"
    # ask to rm if this left the file empty, else edit
    if /usr/bin/diff -q <(:) <(/usr/bin/grep -v "^#" "$SCRATCH/synthetic.conf.edit") &>/dev/null; then
        if confirm_rm "/etc/synthetic.conf"; then
            return 0
        fi
    else
        if confirm_edit "$SCRATCH/synthetic.conf.edit" "/etc/synthetic.conf"; then
            return 0
        fi
    fi
    # fallback instructions
    echo "Manually remove nix from /etc/synthetic.conf"
    return 1
}
```
Does that look okay?

File: scripts/create-darwin-volume.sh [hunk 28]
```diff
@@ -41,129 +243,517 @@ create_synthetic_objects(){
...
+        "$NIX_DAEMON_DEST"
+}
+
+
+# TODO: remove with --uninstall?
+synthetic_conf_uninstall_directions() {
+    # :1 to strip leading slash
+    substep "Remove ${NIX_ROOT:1} from /etc/synthetic.conf" \
+        "  If nix is the only entry: sudo rm /etc/synthetic.conf" \
+        "  Otherwise: grep -v '^${NIX_ROOT:1}$' /etc/synthetic.conf | sudo dd of=/etc/synthetic.conf"
```
[the remark this answers is not in the document]
Comment (abathur) [reply scripts/create-darwin-volume.sh:340]: Applied local

File: scripts/create-darwin-volume.sh [hunk 29]
```diff
@@ -41,129 +243,517 @@ create_synthetic_objects(){
...
+}
+
+uninstall_launch_daemon_prompt() {
+    cat <<EOF
+
+The installer adds a LaunchDaemon to $3: $1
+EOF
+    if ui_confirm "Can I remove it?"; then
+        _sudo "to terminate the daemon" \
+            launchctl bootout "system/$1" 2> >(_eat_bootout_err) || true
```
[the remark this answers is not in the document]
Comment (abathur) [reply scripts/create-darwin-volume.sh:303]: applied local

File: scripts/create-darwin-volume.sh [hunk 30]
```diff
@@ -41,129 +243,517 @@ create_synthetic_objects(){
...
+# $1 == encrypted|unencrypted, $2 == uuid
+generate_mount_command() {
+    case "${1-}" in
+        encrypted)
+            printf "    <string>%s</string>\n" /bin/sh -c "/usr/bin/security find-generic-password -s '$2' -w | /usr/sbin/diskutil apfs unlockVolume '$2' -mountpoint $NIX_ROOT -stdinpassphrase";;
+        unencrypted)
+            printf "    <string>%s</string>\n" /usr/sbin/diskutil mount -mountPoint "$NIX_ROOT" "$2";;
+        *)
+            failure "Invalid first arg $1 to generate_mount_command";;
+    esac
```
[the remark this answers is not in the document]
Comment (abathur) [reply scripts/create-darwin-volume.sh:262]: Good points--what about:
```bash
generate_mount_command() {
    local uuid mountpoint cmd=()
    printf -v uuid "%q" "$2"
    printf -v mountpoint "%q" "$NIX_ROOT"

    case "${1-}" in
        encrypted)
            cmd=(/bin/sh -c "/usr/bin/security find-generic-password -s '$uuid' -w | /usr/sbin/diskutil apfs unlockVolume '$uuid' -mountpoint '$mountpoint' -stdinpassphrase");;
        unencrypted)
            cmd=(/usr/sbin/diskutil mount -mountPoint "$mountpoint" "$uuid");;
        *)
            failure "Invalid first arg $1 to generate_mount_command";;
    esac
    
    printf "    <string>%s</string>\n" "${cmd[@]}"
}
```

File: scripts/create-darwin-volume.sh [hunk 31]
```diff
@@ -1,33 +1,235 @@
...
+    /usr/bin/grep -qE "^${NIX_ROOT:1}\s+\S{3,}" /etc/synthetic.conf 2>/dev/null
+}
+
+test_nix_volume_mountd_installed() {
+    test -e "$NIX_VOLUME_MOUNTD_DEST"
+}
+
+# current volume password
+# $1 = uuid
+test_keychain_by_uuid() {
```
[the remark this answers is not in the document]
Comment (abathur) [reply scripts/create-darwin-volume.sh:209]: Fair. I'll leave this one open for now and hopefully remember to get them all in one pass after I test existing changes.

File: scripts/create-darwin-volume.sh [hunk 32]
```diff
@@ -1,33 +1,235 @@
...
+# $1 = special device, $2 = uuid
+verify_volume_pass() {
+    diskutil apfs unlockVolume "$1" -verify -stdinpassphrase -user "$2"
 }
 
-test_synthetic_conf() {
-    grep -q "^nix$" /etc/synthetic.conf 2>/dev/null
+# $1 = special device, $2 = uuid
+volume_pass_works() {
+    get_volume_pass "$2" | verify_volume_pass "$1" "$2"
```
[the remark this answers is not in the document]
Comment (abathur) [reply scripts/create-darwin-volume.sh:228]: Not opposed, but I'll also defer this one until I test to affirm I haven't newly-broken anything.

[the remark this answers is not in the document]
Comment (abathur) [reply scripts/create-darwin-volume.sh:228]: I went ahead and made this edit locally. 

I was forgetting that pipefail is already set in the multi-user installer, so it should only be new here for direct invocations of create-darwin-volume.

File: scripts/create-darwin-volume.sh (hunk 24 above)
[the remark this answers is not in the document]
Comment (abathur) [reply scripts/create-darwin-volume.sh:16]: I've appended a longer dated comment here locally; sorry for not connecting the dots. :)

For reference:
```bash
    # CAUTION: (Dec 19 2020)
    # This is a stopgap. It doesn't cover the full slate of
    # identifiers we inherit--just those necessary to:
    # - avoid breaking direct invocations of this script (here/now)
    # - avoid hard-to-reverse structural changes before the call to rm
    #   single-user support is verified
    #
    # In the near-mid term, I (personally) think we should:
    # - decide to deprecate the direct call and add a notice
    # - fold all of this into install-darwin-multi-user.sh
    # - intentionally remove the old direct-invocation form (kill the
    #   routine, replace this script w/ deprecation notice and a note
    #   on the remove-after date)
    #
```

File: scripts/create-darwin-volume.sh [hunk 33]
```diff
@@ -1,33 +1,235 @@
...
 test_nix_symlink() {
-    [ -L "/nix" ] || grep -q "^nix." /etc/synthetic.conf 2>/dev/null
+    [ -L "$NIX_ROOT" ] || /usr/bin/grep -q "^nix." /etc/synthetic.conf 2>/dev/null
+}
+test_synthetic_conf_mountable() {
+    /usr/bin/grep -q "^${NIX_ROOT:1}$" /etc/synthetic.conf 2>/dev/null
+}
+test_synthetic_conf_symlinked() {
+    /usr/bin/grep -qE "^${NIX_ROOT:1}\s+\S{3,}" /etc/synthetic.conf 2>/dev/null
+}
```
[the remark this answers is not in the document]
Comment (abathur) [reply scripts/create-darwin-volume.sh:201]: Erg. Another good catch. 

I wasn't sure if/how the curing process should try to handle a synthetic.conf that symlinks Nix. At the time I thought stubbing out the check would be enough of a reminder to to revisit it after focusing on the golden path, but obviously not. I'll revisit it in a separate commit after I get a round of testing in...

[the remark this answers is not in the document]
Comment (abathur) [reply scripts/create-darwin-volume.sh]: I have a draft fix for this in bf5290d, and you can see example output in [this CI run](https://github.com/abathur/syspolicyd_assessments/actions/runs/433227428): 
- [success on symlink in synthetic.conf, but not stitched](https://github.com/abathur/syspolicyd_assessments/runs/1583275412?check_suite_focus=true)
- [fail on symlink in synthetic.conf stitched](https://github.com/abathur/syspolicyd_assessments/runs/1583275629?check_suite_focus=true)

The stitched jobs fail because once we've stitched, we need a reboot to remove the symlink. I'll rehash this in a top-level comment as well.

File: scripts/create-darwin-volume.sh [hunk 34]
```diff
@@ -1,33 +1,235 @@
...
 }
 
 test_fstab() {
-    grep -q "/nix apfs rw" /etc/fstab 2>/dev/null
+    /usr/bin/grep -q "$NIX_ROOT apfs rw" /etc/fstab 2>/dev/null
 }
 
 test_nix_symlink() {
-    [ -L "/nix" ] || grep -q "^nix." /etc/synthetic.conf 2>/dev/null
+    [ -L "$NIX_ROOT" ] || /usr/bin/grep -q "^nix." /etc/synthetic.conf 2>/dev/null
```
[the remark this answers is not in the document]
Comment (abathur) [reply scripts/create-darwin-volume.sh]: This should also be covered in bf5290d.

**Comment by abathur** [comment]
bf5290d fixes an oversight [caught by lilyball](https://github.com/NixOS/nix/pull/4289#discussion_r546093440) regarding curing/checking for the presence of Nix as a symlink in synthetic.conf. You can see sample output in [this CI run](https://github.com/abathur/syspolicyd_assessments/actions/runs/433227428): 
- [success on symlink in synthetic.conf, but not stitched](https://github.com/abathur/syspolicyd_assessments/runs/1583275412?check_suite_focus=true)
- [fail on symlink in synthetic.conf stitched](https://github.com/abathur/syspolicyd_assessments/runs/1583275629?check_suite_focus=true)

The stitched jobs fail because once we've stitched, we need a reboot to remove the symlink.

File: scripts/create-darwin-volume.sh (hunk 31 above)
[the remark this answers is not in the document]
Comment (abathur) [reply scripts/create-darwin-volume.sh]: Addressed in 0bd1083

**Comment by ethnt** [comment]
@abathur Thanks a lot for your work on this! Is there an ETA for when this will be made publicly available?

**Comment by abathur** [comment]
Not sure. We're on the busy side of a bottleneck. :)

File: scripts/create-darwin-volume.sh (hunk 25 above)
[the remark this answers is not in the document]
Comment (lilyball) [reply scripts/create-darwin-volume.sh:1]: I suppose consistency is worthwhile. If we do need to run `install-multi-user.sh` on a platform that doesn't have `/bin/bash` then the current shebang makes sense.

**Comment by andir** [comment]
Used this yesterday to install Nix on an M1 Mac as I did want my Nix volume properly encrypted but didn't feel like manually fiddling with the details. Worked like a charm :+1: Looking forward to having this as the default.

**Comment by abathur** [comment]
I've updated my installer for the latest commits. I:
- re-ran a CI job against this, but it looks like GH has [temporarily pulled the 11.0 image from public use](https://github.com/actions/virtual-environments/issues/2486). I was only able to confirm the 10.15 builds there.
- manually tested installs on rc `11.2 20D64`:
    - [x] non-interactive
    - [x] interactive + filevault

> Used this yesterday to install Nix on an M1 Mac as I did want my Nix volume properly encrypted but didn't feel like manually fiddling with the details. Worked like a charm 👍 Looking forward to having this as the default.

@andir Thanks for giving it a go and reporting back :)

**Comment by d12frosted** [comment]
@abathur just tried it and getting the following error:

```
~~> Fixing any leftover Nix volume state
Before I try to install, I'll check for any existing Nix volume config
and ask for your permission to remove it (so that the installer can
start fresh). I'll also ask for permission to fix any issues I spot.
/var/folders/8f/4rf99dhs1p9g6k4bcy8n9w6c0000gn/T/nix-binary-tarball-unpack.i5L6WETgCZ/unpack/nix-2.4pre20210131_86dbee7-x86_64-darwin/create-darwin-volume.sh: line 194: found: unbound variable
```

Not sure if it's me only. What information should I provide? I am on macOS 11.0.1 (20B50), bash 5.1.4.

**Comment by abathur** [comment]
@d12frosted it looks like a code-review change caused that to start breaking in newer bash, and I didn't notice it because my test runs have been targeting macOS bash 3.2.

I pushed a fix just now and started a new build. I'll post again when I've got it finished/uploaded.

**Comment by abathur** [comment]
@d12frosted Should be uploaded now.

**Comment by d12frosted** [comment]
@abathur works like a charm! thank you very much 💯 for the first time in my life I managed to install nix on macOS! 

P. S. I am late for the nix party, so not sure if it was seamless some time ago.

**Comment by klardotsh** [comment]
This worked for me on a `mac1.metal` EC2 box where the upstream installer seemed to break, but only after disabling filesystem sandboxing for `sh` in System Preferences (which is fun to get to on a headless box to say the least...) and `sudo launchctl kickstart -k system/org.nixos.nix-daemon`.

While I can document this process for my coworkers for now, is there a way to have this all Just Work without diving through System Preferences and restarting stuff through `launchctl`? I'm not a Nix wizard per-se, nor am I a Mac user, but I'm happy to test drive stuff as necessary!

```
ec2-user@ip-10-201-11-142 ~ % nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-darwin"`
 - host os: `Darwin 19.6.0, macOS 10.15.7`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.4pre20210201_0760edc`
 - channels(root): `"nixpkgs-21.03pre267753.60d9784263c"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```

remmina_localhost_localhost_202123-105929

**Comment by richardcooper** [comment]
Thank you so much for this work!

I tried running the https://files.t-ravis.com/install-multi installer and it failed at the point of creating `/nix`.

This is on a 2017 Macbook Pro (so no T2 chip) with a clean install of Big Sur 11.2 and file-vault enabled.

```
% sh <(curl https://files.t-ravis.com/install-multi)

[... snip ...]

---- Preparing a Nix volume ----------------------------------------------------
    Nix traditionally stores its data in the root directory /nix, but
    macOS now (starting in 10.15 Catalina) has a read-only root directory.
    To support Nix, I will create a volume and configure macOS to mount it
    at /nix.

~~> Configuring /etc/synthetic.conf to make a mount-point at /nix

---- sudo execution ------------------------------------------------------------
I am executing:

    $ sudo /usr/bin/ex /etc/synthetic.conf

to add Nix to /etc/synthetic.conf

Password:

---- oh no! --------------------------------------------------------------------
error: failed to bootstrap /nix

We'd love to help if you need it.

You can open an issue at https://github.com/nixos/nix/issues

Or feel free to contact the team:
 - IRC: in #nixos on irc.freenode.net
 - twitter: @nixos_org
 - forum: https://discourse.nixos.org
```

It looks like the failure is in the `apfs.util` call in `create-darwin-volume.sh:create_synthetic_objects()`

```
% cat /etc/synthetic.conf 
nix
% /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -t     
failed to stitch firmlinks and/or create synthetics for root volume (c002) ...
```

I know I can just reboot to get the mount point to show up and then rerun the installer. But if there's anything I can do to help debug the failure, I'm happy to do so.

**Comment by abathur** [comment]
> ```
> % /System/Library/Filesystems/apfs.fs/Contents/Resources/apfs.util -t     
> failed to stitch firmlinks and/or create synthetics for root volume (c002) ...
> ```
> 
> I suspect I can just reboot to get the mount point to show up and then rerun the installer. But if there's anything I can do to help debug the failure, I'm happy to do so.

Any chance you enabled FileVault/FDE during the same boot? I did notice, while trying to work out a CI procedure for testing this installer, that stitching wasn't working correctly after enabling it.

**Comment by richardcooper** [comment]
> Any chance you enabled FileVault/FDE during the same boot?

I think I probably did. I ran the installer very soon after a clean OS install/restore and don't remember rebooting at any point after enabling FileVault.

**Comment by abathur** [comment]
> I think I probably did. I ran the installer very soon after a clean OS install/restore and don't remember rebooting at any point after enabling FileVault.

In my experience this doesn't apply when enabling it in the setup assistant (I guess technically I only saw it using `fdesetup`). I'm not sure if it applies to enabling it via System Preferences.

**Comment by richardcooper** [comment]
> In my experience this doesn't apply when enabling it in the setup assistant (I guess technically I only saw it using `fdesetup`). I'm not sure if it applies to enabling it via System Preferences.

I left file-vault off in the setup assistant, then enabled it via System Preferences, then ran the installer. All - IIRC - without rebooting. 

If there's no known workaround/fix for this issue then is it worth having a more useful error message? E.g. expand `"error: failed to bootstrap /nix"` with something like `"Failed to bootstrap /nix. This is a known issue. Please reboot and run the installer again. If that still fails you can open an issue ..."` or whatever wording you think works best.

**Comment by abathur** [comment]
@richardcooper I've expanded the message in ef4d6b9

**Comment by evanjs** [comment]
I have been having issues installing nix on Big Sur with FileVault enabled.

This PR (and specifically, the installer with `sh <(curl https://files.t-ravis.com/install-multi)` allowed me to install nix successfully, and packages seem to install fine.

Thank you!

**Comment by abathur** [comment]
@domenkozar here's an installer-test run on a copy of this branch rebased to include the installer tests: https://github.com/abathur/nix/actions/runs/600476594

**Comment by abathur** [comment]
I've rebased to re-run tests now that #4577 is merged. macOS install: https://github.com/abathur/nix/runs/2088011639

**Comment by abathur** [comment]
I've rebased to fix a merge conflict #4532 and re-run tests. clean macOS test run: https://github.com/abathur/nix/runs/2195061752

I also updated the "Try it out?" instructions to use the matching CI-generated installer from Cachix (instead of my privately-hosted test build).

**Comment by abathur** [comment]
I've pushed a new commit to fix an issue identified in #4675 and updated the head comment with the latest installer and test output.

**Comment by siraben** [comment]
@abathur Thank you so much for your work on this. I wiped Nix from macOS today to make some space for something else, but had a hard time reinstalling it using the official installer. The command you gave in the first PR comment works flawlessly.

How would I be able to update the version of Nix using https://github.com/numtide/nix-unstable-installer ? I get the following error:

```
/var/folders/s1/sm71lqk553d1_f8drd3tz_5r0000gn/T/nix-binary-tarball-unpack.KKQeuIDk0C/unpack/nix-2.4pre20210415_76980a1-x86_64-darwin/install: directory /nix exists, but is not writable by you. This could indicate that another user has already performed a single-user installation of Nix on this system. If you wish to enable multi-user support see https://nixos.org/nix/manual/#ssec-multi-user. If you wish to continue with a single-user install for siraben please run 'chown -R siraben /nix' as root.
```

File: scripts/create-darwin-volume.sh [hunk 35]
```diff
@@ -1,33 +1,262 @@
-#!/bin/sh
-set -e
+#!/usr/bin/env bash
+set -eu
+set -o pipefail
```
Comment (samuela) [inline scripts/create-darwin-volume.sh:3]:
```suggestion
set -eou pipefail
```

**Comment by samuela** [comment]
i just used the install command from the PR description and omg it's so good. shout out @abathur !

**Comment by grahamc** [comment]
I've seen good success with this PR and I think it is time to give our users a better experience, so I'm going to go ahead and merge it :)

**Comment by jgeerds** [comment]
@abathur Thank you very much for your work! Am I right that these changes only affect nixUnstable and upcoming releases? If so, is there a chance for a 2.3.x backport?

**Comment by abathur** [comment]
@jgeerds Yep.

Backport decisions are above my paygrade, but unless 2.4 is impending I think it spares enough pain to be worth a backport and release.

**Comment by abathur** [comment]
This may also be a good place to note: I think the merge of this PR lights a path to full uninstall/reinstall. I can't pursue it any time soon, but I'm happy to discuss as needed if someone else can. I wrote a proof-of-concept in Oct. that should be reheatable. Validation is also much easier since domen added installer tests.

**Comment by rpearce** [comment]
Holy smokes; what a great install experience. This worked for me on a macOS early 2013 running `10.15.7`. Thank you!!!

**Comment by rpearce** [comment]
@abathur Sorry to bother: how will we know when this will become the default installer for Darwin? This is what I'm telling coworkers currently:
```sh
sh <(curl https://abathur-nix-install-tests.cachix.org/serve/yihf8zbs0jwph2rs9qfh80dnilijxdi2/install) --tarball-url-prefix https://abathur-nix-install-tests.cachix.org/serve
```

**Comment by abathur** [comment]
@rpearce No worries. Subscribing to this thread is probably the best bet.

**Comment by abathur** [comment]
@rpearce No worries. Subscribing to this thread is probably the best bet. 

I deferred a sprawling, intricate refactor of another project for a few months to focus on this PR. For my own sanity, I had to stick a fork in this a couple months back so that I could shift enough of my focus back to that effort to make any headway. 

I guess we're waiting for either:
- a new release from master (whether that's 2.4 or 3.0)
- someone to drive an effort to backport it to the 3.2-maintenance branch and get a new release from there

It _can_ be backported (and I agree with releasing it), but there are a few caveats that probably make it more complicated than just bugging domen:
1. There are other commits in master that haven't been backported, and this PR is extensive enough that I imagine someone would need to audit the other changes there to make sure anything this builds on (and any fixes to this?) get pulled in. A good place to start is probably something like: `git log --color=always --format='%C(auto,blue)%h%Creset %C(auto,green)%cs%Creset [%C(auto,red)%<|(37)%S%Creset]%C(auto,yellow) %m %Creset%s' --cherry-mark --no-merges  master...2.3-maintenance -- scripts | grep -v ' = '`
2. The documentation format was converted from xml to markdown between 2.3-maintenance and this work, so the doc changes will need to be re-applied in the xml.
3. The installer-testing work domen implemented this winter isn't present in 2.3-maintenance, so someone will need to either backport that work as well, or manually generate installers to test them (i.e., the old way :/)

**Comment by mpscholten** [comment]
An issue was just reported to IHP with the following error running this installer:

```
SHA-256 hash mismatch in 'https://abathur-nix-install-tests.cachix.org/serve/jqr52m6w8dwag5932hw67kq0rvbnji01/nix-2.4pre19700101_eab14a6-x86_64-darwin.tar.xz'; expected @binaryTarball_x86_64-darwin@, got eb40f032d84e2fadb1e875ad7a35a075f9c5b47a4737084a87f925292378b57a
```

Was anything changed on the installer? Did it already get released and @abathur's installer is deprecated?


Linked issue: https://github.com/digitallyinduced/ihp/issues/960

**Comment by domenkozar** [comment]
Most likely a transient network error, the hash is correct when I test it locally.

**Comment by mpscholten** [comment]
Thanks for the quick help Domen! :)

The user reported back that the problem still occurs. Notable it's happening on a Macbook Air with a M1. Maybe this could be causing the problems?

**Comment by domenkozar** [comment]
The installer that's used by IHP doesn't support M1, I'd suggest to use the newest one from Nix master or use the default installer that ships M1 support as of yesterday.

**Comment by mpscholten** [comment]
Thanks, using the default installer solved the problem :)
