### PR TITLE
Fix issue #14287

### LINKED ISSUE #14287: `OUT_PATHS` in post-build-hook no longer populated for successful rebuilds
## Describe the bug

As part of https://github.com/JulienMalka/lila, we have a post-build-hook that posts an attestation of the build to the hash collection service. Since a recent nixpkgs update, this doesn't work for me anymore. I haven't properly bisected yet, but it seems it still worked on nix 2.29.2 and fails on nix 2.30.3

## Steps To Reproduce

* register a post-build-hook that prints the `OUT_PATHS` environment variable
* `nix-build '<nixpkgs>' -A nethogs --no-out-link; nix-build '<nixpkgs>' -A nethogs --check --no-out-link` or `nix build nixpkgs#nethogs; nix build nixpkgs#nethogs --rebuild`. 

The post-build-hook is called for the rebuild, but `OUT_PATHS` appears to be unset

## Expected behavior

The post-build-hook should be called for the rebuild with `OUT_PATHS` pointing to the out paths

## Metadata

nix-env (Nix) 2.31.2

Also verified it exists on Nix 2.32pre20250919_07b96c1d

## Additional context

This is on nixos. Issue in lila is https://github.com/JulienMalka/lila/issues/66 .

#13802 looks potentially related but isn't in 2.31.2 yet so that's unlikely to be it.

Maybe #13769?

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open bug issues and pull requests] for possible duplicates

[latest Nix manual]: https://nix.dev/manual/nix/development/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by Ericson2314**
## Motivation

Fix #14287

## Context

New test (which fails) then bug fix which makes the test pass. As it should be. :)

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by Ericson2314** [comment]
Ah the test it needs to be gated on the daemon version

**Comment by raboof** [comment]
(can confirm it indeed seems to have the desired effect)

File: src/libstore/build/derivation-building-goal.cc [hunk 1]
```diff
@@ -678,7 +678,17 @@ Goal::Co DerivationBuildingGoal::tryToBuild()
...
         builder.reset();
         StorePathSet outputPaths;
-        for (auto & [_, output] : builtOutputs) {
+        /* In the check case we install no store objects, and so
+           `builtOutputs` is empty. However, per issue #14287, there is
+           an expectation that the most build hook will still be-run.
+           (This is useful for e.g. logging successfully successful
+           deterministic rebuilds in various systems.)
+
+
```
Comment (edolstra) [inline src/libstore/build/derivation-building-goal.cc:684]:
```suggestion
```

File: src/libstore/build/derivation-building-goal.cc [hunk 2]
```diff
@@ -678,7 +678,17 @@ Goal::Co DerivationBuildingGoal::tryToBuild()
     {
         builder.reset();
         StorePathSet outputPaths;
-        for (auto & [_, output] : builtOutputs) {
+        /* In the check case we install no store objects, and so
+           `builtOutputs` is empty. However, per issue #14287, there is
+           an expectation that the most build hook will still be-run.
+           (This is useful for e.g. logging successfully successful
+           deterministic rebuilds in various systems.)
```
Comment (edolstra) [inline src/libstore/build/derivation-building-goal.cc]:
```suggestion
           `builtOutputs` is empty. However, per issue #14287, there is
           an expectation that the post-build hook is still executed.
           (This is useful for e.g. logging successful deterministic rebuilds.)
```

File: src/libstore/build/derivation-building-goal.cc [hunk 3]
```diff
@@ -678,7 +678,17 @@ Goal::Co DerivationBuildingGoal::tryToBuild()
...
+
+
+           In order to make that work, in the check case just load the
+           (preexisting) infos from scratch, rather on relying on what
```
Comment (edolstra) [inline src/libstore/build/derivation-building-goal.cc]:
```suggestion
           (preexisting) infos from scratch, rather than relying on what
```

**Comment by raboof** [comment]
Is the build failure because it tests against the latest 'master' version of the daemon, which doesn't have the change yet? Or is there 'actually' something left to do here?

File: tests/functional/post-hook.sh [hunk 4]
```diff
@@ -29,6 +29,16 @@ nix-build -o "$TEST_ROOT"/result dependencies.nix --post-build-hook "$pushToStor
...
 
+if isDaemonNewer "2.32.0pre20251020"; then
+    # Regression test for issue #14287: `--check` should re-run post build
+    # hook, even though nothing is getting newly registered.
+    export HOOK_DEST=$TEST_ROOT/listing
+    nix-build -o "$TEST_ROOT"/result-mult multiple-outputs.nix --check -A a.first --post-build-hook "$PWD/build-hook-list-paths.sh"
+    grepQuiet a-first "$HOOK_DEST"
+    grepQuiet a-second "$HOOK_DEST"
+    unset HOOK_DEST
+fi
```
Comment (fzakaria) [inline tests/functional/post-hook.sh]: what's the point of functional tests having version check?
it's run against the same source?

Comment (xokdvium) [reply tests/functional/post-hook.sh]: It's run against multiple daemon versions in hydra. See `functional_root` e.t.c.

**Comment by xokdvium** [comment]
@Ericson2314, please apply this diff to your branch. We still can't push to obsidian's feature branches:

```patch
diff --git a/tests/functional/post-hook.sh b/tests/functional/post-hook.sh
index ad491a782..1c86f2963 100755
--- a/tests/functional/post-hook.sh
+++ b/tests/functional/post-hook.sh
@@ -29,10 +29,11 @@ nix-build -o "$TEST_ROOT"/result dependencies.nix --post-build-hook "$pushToStor
 export BUILD_HOOK_ONLY_OUT_PATHS=$([ ! "$NIX_TESTS_CA_BY_DEFAULT" ])
 nix-build -o "$TEST_ROOT"/result-mult multiple-outputs.nix -A a.first --post-build-hook "$pushToStore"
 
-if isDaemonNewer "2.32.0pre20251020"; then
+if isDaemonNewer "2.33.0pre20251020"; then
     # Regression test for issue #14287: `--check` should re-run post build
     # hook, even though nothing is getting newly registered.
     export HOOK_DEST=$TEST_ROOT/listing
+    restartDaemon
     nix-build -o "$TEST_ROOT"/result-mult multiple-outputs.nix --check -A a.first --post-build-hook "$PWD/build-hook-list-paths.sh"
     grepQuiet a-first "$HOOK_DEST"
     grepQuiet a-second "$HOOK_DEST"
```

~~Also this doesn't actually resolve the issue with `hydraJobs.installTests`. No idea what's going on there.~~

The env variable needs a daemon restart to make its way to the hook.

**Comment by Ericson2314** [comment]
Thanks @xokdvium. Pushed!

**Review by xokdvium — APPROVED** [review]
