### PR TITLE
printValue(): Don't show repeated values

### LINKED ISSUE #6157: Segfault during evaluation
In the following evaluation, nix incrementally allocates all system memory and then segfaults:
```bash
read -d '' src <<'EOF' || :
  with (builtins.getFlake "github:NixOS/nixpkgs/40ef692a55b188b1f5ae3967f3fc7808838c3f1d").legacyPackages.x86_64-linux;
  let
    file = pkgs.writeText "json" "{}";
    json = builtins.fromJSON (builtins.readFile (builtins.trace file file));
    jsonFile = pkgs.writeText "json" (builtins.toJSON json);
  in {
    segfault = jsonFile;
    noSegfault = json;
  }
EOF
# nix 2.6.1
nix shell nixpkgs/38346f64616c3176f73ad0f20e51557ec0f3d75d#nix_2_6 -c nix eval --expr "$src" segfault
```
This is somehow caused by the `builtins.trace` statement.
Evaluating attr `noSegfault`, which triggers the same `trace` statement, leads to normal evaluation without segfaulting:
```bash
nix shell nixpkgs/38346f64616c3176f73ad0f20e51557ec0f3d75d#nix_2_6 -c nix eval --expr "$src" noSegfault
```
Also, `nix-instantiate` works correctly without segfaulting:
```
nix shell nixpkgs/38346f64616c3176f73ad0f20e51557ec0f3d75d#nix_2_6 -c nix-instantiate --eval -E "$src" -A segfault
```
#### Affected versions
Nix ≥2.4, including `master`. I haven't tested Nix 2.3.
```
nix shell nixpkgs/38346f64616c3176f73ad0f20e51557ec0f3d75d#nix_2_4 -c nix eval --expr "$src" segfault
nix shell nixpkgs/38346f64616c3176f73ad0f20e51557ec0f3d75d#nix_2_5 -c nix eval --expr "$src" segfault
# Nix master as of 2022-02-24
nix shell github:NixOS/nix/3144b373a486bf0d5ff35d3202a658311b26c6f0 -c nix eval --expr "$src" segfault
```
#### Context

I've noticed this while debugging #6156.

### PR DESCRIPTION
**Pull request by edolstra**
Fixes #6157.

### CODE REVIEW

File: src/libexpr/eval.cc [hunk 1]
```diff
@@ -120,24 +115,32 @@ void printValue(std::ostream & str, std::set<const Value *> & active, const Valu
         str << "null";
         break;
     case tAttrs: {
-        str << "{ ";
-        for (auto & i : v.attrs->lexicographicOrder()) {
-            str << i->name << " = ";
-            printValue(str, active, *i->value);
-            str << "; ";
+        if (!v.attrs->empty() && !seen.insert(v.attrs).second)
+            str << "<REPEAT>";
```
Comment (cole-h) [inline src/libexpr/eval.cc:119]: It seems like the `<REPEAT>` can sometimes be interpreted as a Nix diamond path (e.g. `<nixpkgs>`) -- c.f. https://github.com/NixOS/nix/issues/6243 and https://github.com/NixOS/nixpkgs/issues/163374.

(Just attempting to facilitate communication as a concerned bystander; I haven't run into this myself)
