### PR TITLE
Fix for `unknown serve command 13`

### LINKED ISSUE #3039: unknown serve command 13
**Error description**

When using the ssh:// protocol, for example with `nix-copy-closure` but it can be other commands, the server might return the error `unknown serve command 13`.

Reproduced with nix 2.2.2 and master ( 35ebae198f5af5b5283bfb36ef6e85a29006e4c9 )

**How to reproduce**

Run these two commands on multiple machines at the same time. Replace `nix-ssh@server` with your remote builder:

```sh
nix-instantiate --expr '(import <nixpkgs> {}).libreoffice' --add-root ./libreoffice.drv --indirect
nix-copy-closure --to nix-ssh@server ./libreoffice.drv
```

I made a test repo that reproduces the issue fairly reliably (1 in 2 runs) using nixops+virtualbox: https://github.com/zimbatm/test-nix-unknown-serve-command-13

**Example output**

from the repo above:
```
client2: copying path '/nix/store/064jmylcq7h6fa5asg0rna9awcqz3765-0001-x86-Properly-merge-GNU_PROPERTY_X86_ISA_1_USED.patch' to 'ssh://nix-ssh@server'...
client2: adding path '/nix/store/064jmylcq7h6fa5asg0rna9awcqz3765-0001-x86-Properly-merge-GNU_PROPERTY_X86_ISA_1_USED.patch' to remote host 'nix-ssh@server'
client1: querying remote host 'nix-ssh@server' for info on '/nix/store/064jmylcq7h6fa5asg0rna9awcqz3765-0001-x86-Properly-merge-GNU_PROPERTY_X86_ISA_1_USED.patch'
client3: querying remote host 'nix-ssh@server' for info on '/nix/store/05519al3nfm3xh52br6byx1n4h6p48pg-readline63-006.drv'
client2: warning: SQLite database '/nix/var/nix/db/db.sqlite' is busy
client2: querying remote host 'nix-ssh@server' for info on '/nix/store/072184hqi2mk5535faivca0vz8ig8pvz-setup-hook.sh'
client2: copying path '/nix/store/072184hqi2mk5535faivca0vz8ig8pvz-setup-hook.sh' to 'ssh://nix-ssh@server'...
client2: adding path '/nix/store/072184hqi2mk5535faivca0vz8ig8pvz-setup-hook.sh' to remote host 'nix-ssh@server'
client1: querying remote host 'nix-ssh@server' for info on '/nix/store/072184hqi2mk5535faivca0vz8ig8pvz-setup-hook.sh'
client3: querying remote host 'nix-ssh@server' for info on '/nix/store/05n09s9jf836y2bv1fkv6nlsv8ss596y-clucene-core-2.3.3.4.tar.gz.drv'
client1: copying path '/nix/store/072184hqi2mk5535faivca0vz8ig8pvz-setup-hook.sh' to 'ssh://nix-ssh@server'...
client1: adding path '/nix/store/072184hqi2mk5535faivca0vz8ig8pvz-setup-hook.sh' to remote host 'nix-ssh@server'
client2: querying remote host 'nix-ssh@server' for info on '/nix/store/09rh601rydk5xgl1msgwpzdjmr5fa1f7-fix-rpath.patch.drv'
client2: querying remote host 'nix-ssh@server' for info on '/nix/store/0a4dyd5rfbgl5bifm21r18mchd9n4rn3-xsltml_2.1.2.zip.drv'
client1: error: unknown serve command 13
client1: querying remote host 'nix-ssh@server' for info on '/nix/store/09rh601rydk5xgl1msgwpzdjmr5fa1f7-fix-rpath.patch.drv'
client1: debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
client1: debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
client1: debug1: channel 0: free: client-session, nchannels 1
client1: debug1: fd 0 clearing O_NONBLOCK
client1: debug1: fd 2 clearing O_NONBLOCK
client1: Transferred: sent 129092, received 4912 bytes, in 4.0 seconds
client1: Bytes per second: sent 32008.7, received 1217.9
client1: debug1: Exit status 1
client3: querying remote host 'nix-ssh@server' for info on '/nix/store/064jmylcq7h6fa5asg0rna9awcqz3765-0001-x86-Properly-merge-GNU_PROPERTY_X86_ISA_1_USED.patch'
client1: killing process 1979
client1: error: unexpected end-of-file
client2: querying remote host 'nix-ssh@server' for info on '/nix/store/0ah0phqh2cdqxyrrkd8g9wq86c3hwmqi-perl5.28.1-XML-Simple-2.25.drv'
client3: querying remote host 'nix-ssh@server' for info on '/nix/store/072184hqi2mk5535faivca0vz8ig8pvz-setup-hook.sh'
client3: querying remote host 'nix-ssh@server' for info on '/nix/store/09rh601rydk5xgl1msgwpzdjmr5fa1f7-fix-rpath.patch.drv'
client3: querying remote host 'nix-ssh@server' for info on '/nix/store/0a4dyd5rfbgl5bifm21r18mchd9n4rn3-xsltml_2.1.2.zip.drv'
client2: querying remote host 'nix-ssh@server' for info on '/nix/store/0dm3l9pdi9mikclhllgq1wvxa2l9lw7a-CoinMP-1.8.3.tgz.drv'
client3: querying remote host 'nix-ssh@server' for info on '/nix/store/0ah0phqh2cdqxyrrkd8g9wq86c3hwmqi-perl5.28.1-XML-Simple-2.25.drv'
client3: querying remote host 'nix-ssh@server' for info on '/nix/store/0dm3l9pdi9mikclhllgq1wvxa2l9lw7a-CoinMP-1.8.3.tgz.drv'
client2: querying remote host 'nix-ssh@server' for info on '/nix/store/0dvl576zxhfnfkvryy1jqp4x4d420dnf-harfbuzz-1.8.4.tar.bz2.drv'
client3: querying remote host 'nix-ssh@server' for info on '/nix/store/0dvl576zxhfnfkvryy1jqp4x4d420dnf-harfbuzz-1.8.4.tar.bz2.drv'
client2: querying remote host 'nix-ssh@server' for info on '/nix/store/0dw6v7x9s0rhd1v4h19sh2hsvahyhqw3-ed-1.15.drv'
client3: querying remote host 'nix-ssh@server' for info on '/nix/store/0dw6v7x9s0rhd1v4h19sh2hsvahyhqw3-ed-1.15.drv'
client2: querying remote host 'nix-ssh@server' for info on '/nix/store/0gzlabxdx5xhf75wrsgcq1awikvcrn6y-c-ares-1.15.0.tar.gz.drv'
client3: querying remote host 'nix-ssh@server' for info on '/nix/store/0gzlabxdx5xhf75wrsgcq1awikvcrn6y-c-ares-1.15.0.tar.gz.drv'
client2: copying path '/nix/store/0gzlabxdx5xhf75wrsgcq1awikvcrn6y-c-ares-1.15.0.tar.gz.drv' to 'ssh://nix-ssh@server'...
client2: adding path '/nix/store/0gzlabxdx5xhf75wrsgcq1awikvcrn6y-c-ares-1.15.0.tar.gz.drv' to remote host 'nix-ssh@server'
client2: querying remote host 'nix-ssh@server' for info on '/nix/store/0i3ap5600ipbdcqy2fsaxkjjsrprywn5-cdparanoia-III-10.2.drv'
client3: querying remote host 'nix-ssh@server' for info on '/nix/store/0i3ap5600ipbdcqy2fsaxkjjsrprywn5-cdparanoia-III-10.2.drv'
client2: querying remote host 'nix-ssh@server' for info on '/nix/store/0i5i9mj0n4nry46qvzlmi6h1k9d3pbcn-gtk2-theme-paths.patch'
client3: querying remote host 'nix-ssh@server' for info on '/nix/store/0i5i9mj0n4nry46qvzlmi6h1k9d3pbcn-gtk2-theme-paths.patch'
client3: copying path '/nix/store/0i5i9mj0n4nry46qvzlmi6h1k9d3pbcn-gtk2-theme-paths.patch' to 'ssh://nix-ssh@server'...
client3: adding path '/nix/store/0i5i9mj0n4nry46qvzlmi6h1k9d3pbcn-gtk2-theme-paths.patch' to remote host 'nix-ssh@server'
client2: copying path '/nix/store/0i5i9mj0n4nry46qvzlmi6h1k9d3pbcn-gtk2-theme-paths.patch' to 'ssh://nix-ssh@server'...
client2: adding path '/nix/store/0i5i9mj0n4nry46qvzlmi6h1k9d3pbcn-gtk2-theme-paths.patch' to remote host 'nix-ssh@server'
[4]  32278 Exit 1                  run_test client1
[5]- 32296 Running                 run_test client2 &
[6]+ 32321 Running                 run_test client3 &
client3: querying remote host 'nix-ssh@server' for info on '/nix/store/0jgbzap1nq63r0s1wicp5lim2cis4b5y-atk-2.30.0.tar.xz.drv'
client2: error: unknown serve command 13
client2: querying remote host 'nix-ssh@server' for info on '/nix/store/0jgbzap1nq63r0s1wicp5lim2cis4b5y-atk-2.30.0.tar.xz.drv'
client3: querying remote host 'nix-ssh@server' for info on '/nix/store/0k2gzk4jfkm7i3prx35k4yifj50fk52b-libcmis-0.5.0.drv'
client2: debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
client2: debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
client2: debug1: channel 0: free: client-session, nchannels 1
client2: debug1: fd 0 clearing O_NONBLOCK
client2: debug1: fd 2 clearing O_NONBLOCK
client2: Transferred: sent 157188, received 4792 bytes, in 4.8 seconds
client2: Bytes per second: sent 32489.1, received 990.5
client2: debug1: Exit status 1
client2: killing process 1968
client2: error: unexpected end-of-file
./run-test: line 30: 32321 Terminated              run_test client3
```

**Incomplete analysis**

In the above example, two clients try to upload `'/nix/store/0i5i9mj0n4nry46qvzlmi6h1k9d3pbcn-gtk2-theme-paths.patch` at the same time and one of them gets the error 13 back.

I *believe* that this issue happens only on fixed-output derivation. To be confirmed.

The serve-protocol.hh has only commands up to 9. The worker-protocol.hh command 13 is wopSyncWithGC which is called by `LocalFSStore::addPermRoot`. So it might be that the wrong protocol is being used but I haven't found the link yet. Plus it doesn't explain how it works in the normal case so this might be a dead end.

**How to continue?**

I would like to find the root cause of the issue but need a few pointers how to proceed next.

### PR DESCRIPTION
**Pull request by zimbatm**
Fixes #3039 

`libstore->addToStore(ValidPathInfo & info, Source & source, ...)` can exit early if the path already exists into the store. It's an optimization. The source doesn't need to be read and is left untouched.

Unfortunately, the remote store protocols assume that the while NAR file will be send. So when that happens the protocol gets out of sync.

This PR introduces a `SizedSource(Source & source, size_t size)` which reads the `source` until `size` is reached. That way we can wrap the source and make sure it's read until `narSize` is reached. And then nix-store and nix-daemon are patched to use that new source.

If the NAR file is not consumed by `addToStore` the protocol gets out of sync. This introduces a new SizedReader that we can drain at the end in order to keep the protocol in sync. It means that

### CODE REVIEW

File: src/nix-store/nix-store.cc [hunk 1]
```diff
@@ -950,8 +950,12 @@ static void opServe(Strings opFlags, Strings opArgs)
                 info.sigs = readStrings<StringSet>(in);
                 in >> info.ca;
 
-                // FIXME: race if addToStore doesn't read source?
-                store->addToStore(info, in, NoRepair, NoCheckSigs);
+                SizedSource sizedSource(in, info.narSize);
```
Comment (edolstra) [inline src/nix-store/nix-store.cc]: I don't really understand what `SizedSource` is for, in conjunction with `drainAll()`. Shouldn't `drainAll` just read and discard `remain` bytes?

Comment (edolstra) [reply src/nix-store/nix-store.cc]: There should be a check for `info.narSize == 0`, which can happen in some legacy situations. It's probably fine to just throw an exception.

File: src/libutil/serialise.cc [hunk 2]
```diff
@@ -107,6 +107,20 @@ std::string Source::drain()
 }
 
 
+size_t Source::drainAll(const size_t bufSize)
```
Comment (edolstra) [inline src/libutil/serialise.cc]: The `bufSize` argument seems unnecessary.

File: src/libutil/serialise.hh [hunk 3]
```diff
@@ -179,6 +183,26 @@ struct TeeSource : Source
...
+    SizedSource(Source & orig, size_t size)
+        : orig(orig), remain(size) { }
+    size_t read(unsigned char * data, size_t len)
+    {
+        if (this->remain <= 0) {
+            throw EndOfFile("sized: unexpected end-of-file");
+        }
+        if (len > this->remain) {
+            len = this->remain;
+        }
```
Comment (edolstra) [inline src/libutil/serialise.hh]: This can be written as `len = std::min(len, this->remain)`.

File: src/nix-store/nix-store.cc [hunk 4]
```diff
@@ -950,8 +950,12 @@ static void opServe(Strings opFlags, Strings opArgs)
...
+
+                store->addToStore(info, sizedSource, NoRepair, NoCheckSigs);
+
+                // consume all the data that has been sent before continuing.
+                sizedSource.drainAll();
```
Comment (edolstra) [inline src/nix-store/nix-store.cc]: Won't this block indefinitely waiting for EOF?

Comment (edolstra) [reply src/nix-store/nix-store.cc]: In any case I'd except this to be something like `sizedSource.discard(sizedSource.remain)`.

File: src/libutil/serialise.cc (hunk 2 above)
Comment (zimbatm) [reply src/libutil/serialise.cc]: How do you know what `bufSize` is the most efficient?

File: src/nix-store/nix-store.cc (hunk 1 above)
Comment (zimbatm) [reply src/nix-store/nix-store.cc]: The SizedSource is a way to track the `remain` bytes inside of `addToStore()` since we don't know how much it will consume. It also acts as a guard that `addToStore()` won't read more than `info.narSize` on the socket (not that this has been a problem).

File: src/libutil/serialise.cc (hunk 2 above)
Comment (zimbatm) [reply src/libutil/serialise.cc]: It would be nice if there was a `seek-forward()` function since the reading is really pointless here.

Comment (edolstra) [reply src/libutil/serialise.cc]: You don't, but neither does the caller...

Comment (edolstra) [reply src/libutil/serialise.cc]: Maybe `sendfile()` to `/dev/null`. Probably not worth it though (and not very portable).

File: src/nix-store/nix-store.cc (hunk 1 above)
Comment (edolstra) [reply src/nix-store/nix-store.cc]: That's what I thought but I assumed the point is so that you can then skip `remain` bytes at the end (rather than drain the FD, which introduces problems when the client is pipelining requests or hasn't written everything yet).

File: src/libutil/serialise.cc (hunk 2 above)
Comment (zimbatm) [reply src/libutil/serialise.cc]: Okay. I'm now using the same 8192 as in drain()

File: src/nix-store/nix-store.cc (hunk 4 above)
Comment (zimbatm) [reply src/nix-store/nix-store.cc]: `drainAll()` discards all the data until it reaches EOF. SizedSource emits EOF when `remain` is zero. So it does what you expects but uses an exception as part of the control flow.

What I could do is attack drainAll() to sizedSource instead and be a bit smarter about this.

Comment (zimbatm) [reply src/nix-store/nix-store.cc]: in f21662b I now implement `drainAll()` on the SizedSource only (since it's the only user right now) and which allows me to `read()` until `remain` is zero. And avoid using the Except for control flow.

**Comment by zimbatm** [comment]
hitting issues with `error: sized: unexpected end-of-file` at the moment

**Comment by zimbatm** [comment]
I removed the nix-daemon patch because it had unexpected side-effects. The PR is now ready to be merged and has been tested manually.

File: src/libutil/serialise.hh [hunk 5]
```diff
@@ -179,6 +179,36 @@ struct TeeSource : Source
...
+        return n;
+    }
+
+    /* Consume the original source until no remain data is left to consume. */
+    size_t drainAll()
+    {
+        std::vector<unsigned char> buf(8192);
+        size_t sum = 0;
+        while (this->remain > 0) {
+            size_t n = read(buf.data(), buf.size());
```
Comment (edolstra) [inline src/libutil/serialise.hh]: Maybe this should read `std::min(this->remain, buf.size())` bytes, otherwise it may drain too much data (like commands after the NAR).

Comment (zimbatm) [reply src/libutil/serialise.hh]: @edolstra the `read()` implementation already does this just above.

Comment (zimbatm) [reply src/libutil/serialise.hh]: It's a bit convoluted, that's why I put both implementations next to each-other in the header.
