### PR TITLE
nix shell: Handle output paths that are symlinks

### LINKED ISSUE #10375: nix shell fails if a derivation output is a symlink
**Describe the bug**
With nix 2.20 and 2.21, `nix shell` refuses to work if a derivation output is a symlink to another directory. It seems to trigger an assert that the output must not be a symbolic link.

Originally reported here https://github.com/NixOS/nixpkgs/pull/296751#issuecomment-2028721215.

@SuperSandro2000 points out this is probably related to #9882.

**Steps To Reproduce**
Run `nix shell nixpkgs#texliveInfraOnly`:
```
error: path '/nix/store/78kh795l7d9apmap4y7hwpmm238dgc6g-texlive-2023-env-man' is a symlink
```
The `man` output is just a symlink to a different `buildEnv` derivation.

**Expected behavior**
Derivations outputs which are symlinks to other directories should just work, as they did in nix 2.19 and earlier.

**`nix --version` output**
```
nix (Nix) 2.21.0
```

**Additional context**
TeX Live uses the split output because the man page folders contain PDFs, are not compressed, and link to the rest of the 'doc' container which can be quite large.

I can easily work around this issue by making the outputs just folders containing symlinks, instead of symlinks themselves.

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by edolstra**
# Motivation

This requires moving resolveSymlinks() into SourceAccessor. Also, it requires LocalStoreAccessor::maybeLstat() to work on parents of the store (to avoid an error like "/nix is not in the store").

Fixes #10375.

# Context

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

File: tests/functional/shell.sh [hunk 1]
```diff
@@ -10,6 +10,8 @@ nix shell -f shell-hello.nix hello -c hello NixOS | grep 'Hello NixOS'
 nix shell -f shell-hello.nix hello^dev -c hello2 | grep 'Hello2'
 nix shell -f shell-hello.nix 'hello^*' -c hello2 | grep 'Hello2'
 
+# Test output paths that are a symlink.
+#nix shell -f shell-hello.nix hello-symlink -c hello | grep 'Hello World'
```
Comment (thufschmitt) [inline tests/functional/shell.sh:14]:
```suggestion
nix shell -f shell-hello.nix hello-symlink -c hello | grep 'Hello World'
```

File: src/libstore/local-fs-store.cc [hunk 2]
```diff
@@ -33,6 +33,10 @@ struct LocalStoreAccessor : PosixSourceAccessor
 
     std::optional<Stat> maybeLstat(const CanonPath & path) override
     {
+        /* Handle the case where `path` is (a parent of) the store. */
+        if (isDirOrInDir(store->storeDir, path.abs()))
+            return Stat{ .type = tDirectory };
```
Comment (thufschmitt) [inline src/libstore/local-fs-store.cc:38]: It's not clear why this is needed (calling it with a parent of the store feels quite wrong).

I guess it should at least honor `requireValidPath`

**Review by thufschmitt — CHANGES_REQUESTED** [review]

File: src/libstore/local-fs-store.cc (hunk 2 above)
Comment (edolstra) [reply src/libstore/local-fs-store.cc:38]: Because when following a symlink from one store path to another, `resolveSymlinks()` will stat the parents of those paths, so it will do a `maybeLstat("/nix")` and `maybeLstat("/nix/store")`. Those are not valid store paths so it failed.

File: src/libutil/source-accessor.cc [hunk 3]
```diff
@@ -67,4 +67,42 @@ std::string SourceAccessor::showPath(const CanonPath & path)
...
+                    if (hasPrefix(target, "/"))
+                        res = CanonPath::root;
+                    todo.splice(todo.begin(), tokenizeString<std::list<std::string>>(target, "/"));
+                }
+            }
+        }
+    }
+
+    return res;
+}
```
Comment (Ericson2314) [inline src/libutil/source-accessor.cc:106]: I think this can be deduped

Comment (Ericson2314) [reply src/libutil/source-accessor.cc:106]: With the code in `src/libutil/file-path-impl.hh`

See the implementation of `canonPath` in `src/libutil/file-system.cc`

File: src/libstore/local-fs-store.cc (hunk 2 above)
Comment (Ericson2314) [reply src/libstore/local-fs-store.cc:38]: I've been thinking about whether stores' source accessors should prefix everything with the store directory or not, and leaning towards "no".

This would be something not doing that helps with: the path is just `xxxxxxxxxxxx-foo`, no parent directories etc.

Comment (Ericson2314) [reply src/libstore/local-fs-store.cc:38]: `makeMountedInputAccessor` can be used to put put things in store directories if it matters.

File: src/libutil/source-accessor.cc (hunk 3 above)
Comment (edolstra) [reply src/libutil/source-accessor.cc:106]: That's not the job of this PR though. It just moves `resolveSymlinks()`.

Comment (Ericson2314) [reply src/libutil/source-accessor.cc:106]: OK fair

File: src/libstore/local-fs-store.cc (hunk 2 above)
Comment (Ericson2314) [reply src/libstore/local-fs-store.cc:38]: #10510 Broke into new issue

**Review by Ericson2314 — APPROVED** [review]
I think this is OK for now, but I would really like Eelco to take on #10510 / #9852 / https://github.com/NixOS/nix/issues/9892#issuecomment-1919746059 so we have a more robust solution for this stuff

**Comment by Ericson2314** [comment]
If you could take a stab at https://github.com/NixOS/nix/pull/10467#pullrequestreview-2001462789 @edolstra, I would be happy to take on this one per my plan above.

File: src/libstore/local-fs-store.cc (hunk 2 above)
Comment (Ericson2314) [reply src/libstore/local-fs-store.cc:38]: Given that #10510 *isn't* fixed, I think this is actually a fine fix for now.

**Review by thufschmitt — APPROVED** [review]

**Comment by tobim** [comment]
Would be great to have this backported.

**Comment by thufschmitt** [comment]
> Would be great to have this backported.

Uuuuh, I though this had arrived after the release. Created the backport, should be merged once the CI is green
