### PR TITLE
fromJSON/fromTOML: throw if string contains null byte

### LINKED ISSUE #10317: Weird behaviour with NUL code points in strings
**Describe the bug**
`builtins.fromJSON` allows crafting strings that contain the null code point by representing it as `\u0000`.
However, these are considered as terminating strings in a number of places, such as in the printing code or equality tests:
```
nix-repl> builtins.fromJSON ''"foo\u0000bar"''
"foo"
nix-repl> builtins.fromJSON ''"foo\u0000bar"'' == "foo"
true
```
Nevertheless, they are not actually truncated from the beginning:
```
nix-repl> builtins.fromJSON ''{ "lol": 1, "lol\u0000": 2 }'' // builtins.fromJSON ''{ "lol\u0000": 3 }'' // { lol = 4; }
{ lol = 4; "lol" = 3; }
```

**Steps To Reproduce**

Play around with fromJSON on JSON representations of strings containing \u0000 in various ways.

**Expected behavior**

Not quite clear, since Nix's syntax (AFAIK) has no native way to represent NUL. Sound-ish behaviours would probably be to truncate the strings as soon as part of fromJSON (comparatively easy, but also kind of wrong), or to ensure that none of the string-handling code stops at NULs.

**`nix-env --version` output**
nix-env (Nix) 2.18.1

**Additional context**

This was not originally discovered by me. It was brought to my attention (this time) and discussed a little on Matrix: https://matrix.to/#/!NBBFPbiuttRgTqbrcY:nixos.org/$2aTf5XblwYtjptsravT2dA2DBc_m6RMaDmxE7xYUtqs?via=nixos.org&via=matrix.org&via=nixos.dev

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by NaN-git**
## Motivation

Internally Nix uses C-strings, i.e. it's not possible to represent the `NUL` character. `builtins.fromJSON` and `builtins.fromTOML` allow escaping of the`NUL` character, so that null bytes can appear in strings causing inconsistent behaviour.

`builtins.readFile` already throws an error, if the input file contains a null byte.

## Context

Fixes #10317 by throwing an error when a null byte is encountered.

Tests of the new behaviour are provided.

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

File: src/libexpr/eval.cc [hunk 1]
```diff
@@ -3178,5 +3178,20 @@ std::ostream & operator << (std::ostream & str, const ExternalValueBase & v) {
     return v.print(str);
 }
 
+void forceNoNullByte(std::string_view s)
+{
+    if (memchr(s.data(), '\0', s.size())) {
```
Comment (edolstra) [inline src/libexpr/eval.cc:3183]:
```suggestion
    if (s.find(0) != s.npos) {
```

File: src/libexpr/eval.cc [hunk 2]
```diff
@@ -3178,5 +3178,20 @@ std::ostream & operator << (std::ostream & str, const ExternalValueBase & v) {
...
+        std::string str;
+        for (auto c : s) {
+            if (c != '\0') {
+                str.push_back(c);
+            } else {
+                str.append("␀");
+            }
+        }
+        throw Error("input string '%s' cannot be represented as Nix string because it contains null bytes", str);
```
Comment (edolstra) [inline src/libexpr/eval.cc:3192]:
```suggestion
        throw Error("input string '%s' cannot be represented as Nix string because it contains null bytes", 
            replaceStrings(s, "\0"sv, "␀"sv));
```

**Review by edolstra — APPROVED** [review]

File: src/libexpr/eval.cc (hunk 2 above)
Comment (NaN-git) [reply src/libexpr/eval.cc:3192]: I'll apply your suggestions, but this doesn't compile.
