### PR TITLE
withFramedSink(): Don't use a thread to monitor the other side

### LINKED ISSUE #11312: RemoteStore creates a lot of threads
**Describe the bug**

For example:

```
# strace -f -eclone3 nix flake show --no-eval-cache --all-systems github:NixOS/nix/afdd12be5e19c0001ff3297dea544301108d298 2>&1 | grep 'clone3(' | wc -l
46418
```

This is because every `addToStore()` call creates a thread in `RemoteStore::ConnectionHandle::withFramedSink()`. IIRC most `addToStore()` variants didn't go through the latter in the past, but now they do.

**Steps To Reproduce**

**Expected behavior**

**`nix-env --version` output**

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by edolstra**
# Motivation

Since `withFramedSink()` is now used a lot more than in the past (for every `addToStore()` variant), we were creating a lot of threads, e.g.

```
nix flake show --no-eval-cache --all-systems github:NixOS/nix/afdd12be5e19c0001ff3297dea544301108d298
```

would create 46418 threads. While threads on Linux are cheap, this is still substantial overhead.

So instead, just poll from `FramedSink` before every write whether there are pending messages from the daemon. This could slightly increase the latency on log messages from the daemon, but not on exceptions (which were only synchronously checked from `FramedSink` anyway).

This speeds up the command above from 19.2s to 17.5s on my machine (a 9% speedup).

Fixes #11312.

# Context

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by tomberek** [comment]
Related? https://github.com/NixOS/nix/issues/11098

**Comment by edolstra** [comment]
@tomberek Don't think so. Copying nixpkgs to the store is a single `addToStore()` operation so the overhead would be very small.

File: src/libutil/serialise.hh [hunk 1]
```diff
@@ -522,15 +532,16 @@ struct FramedSource : Source
 /**
  * Write as chunks in the format expected by FramedSource.
  *
- * The exception_ptr reference can be used to terminate the stream when you
- * detect that an error has occurred on the remote end.
+ * The `checkError` function can be used to terminate the stream when you
+ * detect that an error has occurred.
```
Comment (Ericson2314) [inline src/libutil/serialise.hh:536]:
```suggestion
 * The `checkError` function can be used to terminate the stream when you
 * detect that an error has occurred. It does so by throwing an exception.
```

File: src/libutil/serialise.cc [hunk 2]
```diff
@@ -158,6 +160,24 @@ bool FdSource::good()
...
+        struct pollfd fds[1];
+        fds[0].fd = fd;
+        fds[0].events = POLLIN;
+        auto n = poll(fds, 1, 0);
+        if (n < 0) {
+            if (errno == EINTR) continue;
+            throw SysError("polling file descriptor");
+        }
+        return n == 1 && (fds[0].events & POLLIN);
+    }
```
Comment (Ericson2314) [inline src/libutil/serialise.cc:177]: Can you use `select` instead of `poll` since windows has it? 
https://learn.microsoft.com/en-us/windows/win32/api/winsock2/nf-winsock2-select

Don't think it should matter match for a single FD.

**Review by Ericson2314 — DISMISSED** [review]
Good idea! Just a few small tidbits

File: src/libutil/serialise.cc (hunk 2 above)
Comment (edolstra) [reply src/libutil/serialise.cc]: Done.

Comment (matklad) [reply src/libutil/serialise.cc]: Hm, ideally a better solution should be found than using `select`. Select *is* problematic even for a single file descriptor, because select can only work with low-numbered file descriptors. Eg, If you put just a single fd into select, but that fd happens to have large numeric value larger than 1024, then you'd get an error. See the WARNING section from the manpage: https://man7.org/linux/man-pages/man2/select.2.html

We hit this in cargo a while ago, when Cargo was spawned by a different process which didn't set CLOEXEC flag on its file descriptors, so fds cargo ended up seeing were beyond `FD_SETSIZE`: https://github.com/rust-lang/cargo/pull/4477

**Comment by roberth** [comment]
Potential solution to #7359?

**Comment by Mic92** [comment]
@roberth oh, you might be right.
