### PR TITLE
Fix #10747

### LINKED ISSUE #10747: run nix in a non root container in openshift - restricted SCC
**Describe the bug**

i'm trying to deploy nix in openshift under the restricted scc.

it looks like the nix is using unshare which can't work with non root user

image

As i'm using restricted SCC we can't add capabilities to the pod.

From the doc I have the impression that root permission is only needed for creating the nix folder but apprently no

image

Also tried to disable sandboxing but same result :

image

image

Bellow my attempts 

Single user installation : 

image

Multi user installation

image

**Steps To Reproduce**

RUN useradd --create-home appuser -u 1010130000 -g 0
RUN usermod -a -G root  appuser
RUN mkdir /nix
RUN chown appuser /nix
RUN mkdir -p /etc/nix
RUN echo "build-users-group = root\nsandbox = false" > /etc/nix/nix.conf
USER appuser
RUN curl -L https://nixos.org/nix/install | sh -s -- --no-daemon

**Expected behavior**

have this command work properly:
nix run --option sandbox false nixpkgs#htop --extra-experimental-features nix-command --extra-experimental-features flakes

**`nix-env --version` output**
nix-env (Nix) 2.22.1

### PR DESCRIPTION
**Pull request by Ericson2314**
# Motivation

- Fix error reporting to separate caller and callee
- Rename function to indicate it's best effort
- Ignore `ENOSYS` too which looks like it would solve #10747

# Context

Fix #10747

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

File: src/libstore/filetransfer.cc [hunk 1]
```diff
@@ -580,7 +580,12 @@ struct curlFileTransfer : public FileTransfer
         #endif
 
         #if __linux__
-        unshareFilesystem();
+        try {
+            tryUnshareFilesystem();
```
Comment (edolstra) [inline src/libstore/filetransfer.cc:584]: Shouldn't the try/catch be moved inside `tryUnshareFilesystem()` since it claims to be best-effort?

**Review by edolstra — APPROVED** [review]

File: src/libstore/filetransfer.cc (hunk 1 above)
Comment (edolstra) [reply src/libstore/filetransfer.cc:584]: Maybe it should never throw an exception? Are there any errors that should not be ignored?

Comment (Ericson2314) [reply src/libstore/filetransfer.cc:584]: I am not sure, but I am generally uncomfortable with ignoring errors without a whitelist.
