### PR TITLE
libutil: relax git URL parsing to accept paths without a user component

### LINKED ISSUE #14852: unable to fetch flake submodule (unexpected authority) using SSH transport
## Describe the bug

I'm trying to add a submodule to my NixOS flake repository to segregate secrects, but attempting to `nix flake update` or `nixos-rebuild build` results in an unexpected error:

```
$ sudo nixos-rebuild build
building the system configuration...
warning: could not read HEAD ref from repo at '/home/paul/src/nix-config', using 'master'
error:
       … while fetching the input 'git+file:///home/paul/src/nix-config?rev=de26939a1ff68c8e38542163e0c9d17555e17f4f&submodules=1'

       error: file:// URL 'file://moserv.lan.home.arpa:/storage/src/nix-secrets.git' has unexpected authority 'moserv.lan.home.arpa'
```

## Steps To Reproduce

1. Add a submodule to your flake repository: `git submodule init && git submodule add some_server:/path/to/repo.git secrets`
2. Update flake.nix to declare submodule use: `inputs.self.submodules = true;`
3. Attempt to build `sudo nixos-rebuild build`
4. Observe "has unexpected authority error"

## Expected behavior

flake builds successfully

## Metadata

```
$ nix-env --version
nix-env (Nix) 2.31.2+1
```

## Additional context

The error is similar to ~#7545~ #14244, but I think this is likely a different edge case.

The error didn't occur immediately.  It was only once the changes to my NixOS configuration started stabilizing that the failure started happening every time.  Also, it appears to work better when the username is specified in the submodule url (`user@host:/path/to/reo.git`), however, that prevents other users from being able to work on the repository.

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open bug issues and pull requests] for possible duplicates

[latest Nix manual]: https://nix.dev/manual/nix/development/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### LINKED ISSUE #14867: core dump on malformed remote repo build
## Describe the bug

Accidentally mistyped the remote repo nix build command:
```
nix build git:github.com:nixos/nixpkgs
```

## Steps To Reproduce

1. Run `nix build git:github.com:nixos/nixpkgs#ripgrep`
2. fail

## Expected behavior

The package `ripgrep` should be built or downloaded from the cache

## Metadata

`nix-env (Nix) 2.32.4`
`nix-info -m`:
 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.57, NixOS, 26.05 (Yarara), 26.05.20251225.3e2499d`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.32.4`
 - nixpkgs: `/nix/store/0lc6kbmhkqk8vmgflpn2n1d1qb3vl2f5-source`

## Additional context

Core dump:
```
nix build git:github.com:nixos/nixpkgs#ripgrep


terminating due to unexpected unrecoverable internal error: Assertion 'path.empty() || path.front().empty()' failed in std::string nix::ParsedURL::renderAuthorityAndPath() const at ../url.cc:351
Nix crashed. This is a bug. Please report this at https://github.com/NixOS/nix/issues with the following information included:

std::terminate() called without exception
Stack trace:
 0# 0x0000557DC3BB1C81 in nix
 1# 0x00007F34544BF1AA in /nix/store/xm08aqdd7pxcdhm0ak6aqb1v7hw5q6ri-gcc-14.3.0-lib/lib/libstdc++.so.6
 2# std::unexpected() in /nix/store/xm08aqdd7pxcdhm0ak6aqb1v7hw5q6ri-gcc-14.3.0-lib/lib/libstdc++.so.6
 3# 0x00007F3455306BFF in /nix/store/d1j3flz8qr4n3lypwhk0v8ffvflfz914-nix-util-2.32.4/lib/libnixutil.so.2.32.4
 4# __wrap___assert_fail in /nix/store/d1j3flz8qr4n3lypwhk0v8ffvflfz914-nix-util-2.32.4/lib/libnixutil.so.2.32.4
 5# nix::ParsedURL::renderAuthorityAndPath[abi:cxx11]() const in /nix/store/d1j3flz8qr4n3lypwhk0v8ffvflfz914-nix-util-2.32.4/lib/libnixutil.so.2.32.4
 6# nix::ParsedURL::to_string[abi:cxx11]() const in /nix/store/d1j3flz8qr4n3lypwhk0v8ffvflfz914-nix-util-2.32.4/lib/libnixutil.so.2.32.4
 7# 0x00007F3454D94F60 in /nix/store/apbfhnn69hx6f8piiknhir3liv0xggld-nix-fetchers-2.32.4/lib/libnixfetchers.so.2.32.4
 8# 0x00007F3454D9494C in /nix/store/apbfhnn69hx6f8piiknhir3liv0xggld-nix-fetchers-2.32.4/lib/libnixfetchers.so.2.32.4
 9# nix::fetchers::Input::fromURL(nix::fetchers::Settings const&, nix::ParsedURL const&, bool) in /nix/store/apbfhnn69hx6f8piiknhir3liv0xggld-nix-fetchers-2.32.4/lib/libnixfetchers.so.2.32.4
10# 0x00007F3454855504 in /nix/store/drcd5p4hhgzpk3ygbgc1fxb1dzdkcpjk-nix-flake-2.32.4/lib/libnixflake.so.2.32.4
11# nix::parseURLFlakeRef(nix::fetchers::Settings const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&, bool) in /nix/store/drcd5p4hhgzpk3ygbgc1fxb1dzdkcpjk-nix-flake-2.32.4/lib/libnixflake.so.2.32.4
12# nix::parseFlakeRefWithFragment(nix::fetchers::Settings const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::optional<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > const&, bool, bool, bool) in /nix/store/drcd5p4hhgzpk3ygbgc1fxb1dzdkcpjk-nix-flake-2.32.4/lib/libnixflake.so.2.32.4
13# nix::SourceExprCommand::parseInstallables(nix::ref<nix::Store>, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >) in /nix/store/sf38q0nrgg5y52670n1v10b7z5gazasj-nix-cmd-2.32.4/lib/libnixcmd.so.2.32.4
14# nix::InstallablesCommand::run(nix::ref<nix::Store>, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&&) in /nix/store/sf38q0nrgg5y52670n1v10b7z5gazasj-nix-cmd-2.32.4/lib/libnixcmd.so.2.32.4
15# nix::RawInstallablesCommand::run(nix::ref<nix::Store>) in /nix/store/sf38q0nrgg5y52670n1v10b7z5gazasj-nix-cmd-2.32.4/lib/libnixcmd.so.2.32.4
16# nix::StoreCommand::run() in /nix/store/sf38q0nrgg5y52670n1v10b7z5gazasj-nix-cmd-2.32.4/lib/libnixcmd.so.2.32.4
17# 0x0000557DC3C21D03 in nix
18# nix::handleExceptions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()>) in /nix/store/9gb81q29df4q275c2pqdx8w52pvb67n6-nix-main-2.32.4/lib/libnixmain.so.2.32.4
19# 0x0000557DC3B8950B in nix
20# 0x00007F345402A4D8 in /nix/store/xx7cm72qy2c0643cm1ipngd87aqwkcdp-glibc-2.40-66/lib/libc.so.6
21# __libc_start_main in /nix/store/xx7cm72qy2c0643cm1ipngd87aqwkcdp-glibc-2.40-66/lib/libc.so.6
22# 0x0000557DC3B8D9B5 in nix

Aborted                    (core dumped) nix -vL build git:github.com:nixos/nixpkgs#ripgrep
```

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open bug issues and pull requests] for possible duplicates

[latest Nix manual]: https://nix.dev/manual/nix/development/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by tones111**
## Motivation

This change resolves several deficiencies with the current url normalization.  Tests documenting these deficiencies have been corrected and new tests added to cover additional fetchGit test expectations.

## Context

fixes #14852
fixes #14867

The primary new functionality is that SCP-like paths no longer require specifying the user component of the uri authority.  This complicates the implementation as there is now overlap with simple uris.  To prevent processing uris as SCP paths we now attempt to filter them, but the regex for uri and scp detection are definitely more complicated.

While this effort keeps the url normalization logic in `fixGitURL` it feels like it's poorly duplicating boosts parsing logic.  However, I understand parsing urls has a lot of edge cases, so leveraging a high-quality external library is likely still the right strategy.  These regex are only trying to identify enough shape to differentiate them from SCP-like paths.

I'm very new to Nix/NixOS.  I'd like to confirm this build fixes the `nixos-rebuild` error motivating this change but can't figure out how to get it to use my custom build.  Having it in the path (from `nix develop` in the source tree) was not sufficient.  Is there any documentation on how to do this?

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by tones111** [comment]
Looking over the history of `libutil/url.cc` I've come across #13821 (and its revert #13888).  I had initially tried going down a similar path (manually parsing instead of regex) but trying to handle all the corner cases from optional fields got very unwieldy.

It looks like the tests introduced during that effort made it in 2b310aee and more test work has landed since.  Hopefully the impact to the tests made here is palatable as it tries to address some known shortcomings.

**Comment by xokdvium** [comment]
Thanks! Generally, not a fan of re-adding regexes once again - using those is what got us into this messy situation. Could we look into re-landing the https://github.com/NixOS/nix/pull/13821? That was mostly reverted due to the fact that we wanted tests first before functional changes (also the handling of relative paths was borked). Hardcoding `github.com` in the regex is definitely not the right approach here.

**Comment by tones111** [comment]
I agree about the regex usage.  Putting the implementation aside, would you be willing to (in)validate some of my assumptions with the test changes?  I'd like to get the tests nailed down and then will work on simplifying the implementation (will take a longer look at #13821).

Some questions that came up while working with the tests:
1. Do the changes need to be 100% compatible with the current implementation?
* The IPV6 test appears to add an additional directory separator at the root level which I don't understand.
* What about the `xxxParsesPoorly` cases?

2. What's the expected behavior for relative paths (file and scp-like)?
* I don't believe URIs can express relative paths.  This was the main justification for special casing github urls.  `github.com:owner/repo.git` is very common and I didn't want to break that case.
* Changing relative paths to be absolute from the root seems like surprising behavior

3. For the `file` scheme I found the Nix tests depend on a default-constructed authority (`file:///path`) instead of (`file:/path`) which should be equivalent but requires a `std::nullopt` authority.  Is there any opportunity for a future effort to reconcile the discrepancy or are we constrained to retaining backward compatibility?

The "git+file" and "path with a space" cases were added to cover regressions discovered when running against the full Nix test suite.

Thanks for taking a look over the changes!

**Comment by xokdvium** [comment]
> Do the changes need to be 100% compatible with the current implementation?

Bug fixes are good. All the test changes aside from relative paths look good to me. We can fix the cases when we produce utterly invalid results that git doesn't understand or can't reasonable succeed. One thing is that this is used in `builtins.fetchGit`, so bug fixes would change the behaviour of that language builtin fetcher, but since it's already quite broken today I don't think that's an issue.

> The IPV6 test appears to add an additional directory separator at the root level which I don't understand.

This looks like a bug. Currently nix discards consecutive slashes in libfetchers already in quite a few places (not sure it's the case in the git fetcher), so this change seems good to me from the back-compat side of things.

> What's the expected behavior for relative paths (file and scp-like)?

I'm not sure. Issue is that we can't distinguish scp-style URLs from ligitimate URLs where it's a scheme, but git-style URLs shouldn't have that collision. Can you make sure that fixGitUrl is only used when we know it must be a git one? It might be that it's misused in a few places (hopefully I'm wrong).

> I don't believe URIs can express relative paths. This was the main justification for special casing github urls.

Yeah, I'm not sure how to reconcile this. What are the semantics of this? Use the working directory in the remote? We can stick with fixing everything but that and explicitly ban relative paths for now.

> Changing relative paths to be absolute from the root seems like surprising behavior

Yeah, this doesn't sound like a good idea.

> For the file scheme I found the Nix tests depend on a default-constructed authority (file:///path)

I think that we prefer to use the empty authority case rather than the no-authority. I recall from the RCCs that the second variant is less preferred.

> The "git+file" and "path with a space" cases were added to cover regressions discovered when running against the full Nix test suite.

That is good, thanks! Always nice to be thorough about these things. Technically nix URL semantics sit somewhere between WHATWG spec (spaces and ^ are allowed unencoded), but closer to RFC3986.

**Comment by xokdvium** [comment]
FWIW, it's only recently that we started doing proper URL parsing in more places and it was all stringly typed everywhere, so that recent big rework is surfacing some bugs. Specifically in the to_string assertions that validate the invariants required by the spec.

**Comment by xokdvium** [comment]
Also can you make sure that we also fix https://github.com/NixOS/nix/issues/5958?

**Comment by tones111** [comment]
> Can you make sure that fixGitUrl is only used when we know it must be a git one?

I've not familiar with this code base but all the `fixGitURL` invocations appear to be passed git urls.

> What are the semantics of this? Use the working directory in the remote? We can stick with fixing everything but that and explicitly ban relative paths for now.

I'm unable to reason about the semantics either.  I like banning relative paths, but that breaks `github.com:owner/repo.git`.  So we either have to allow them generally (rooted at /) or special-case github urls, right?  **Some clarification on how to handle scp-style relative paths would be helpful**.

> Also can you make sure that we also fix https://github.com/NixOS/nix/issues/5958?

I'm confused here.  You reopened on Oct 20, but [this test](https://github.com/NixOS/nix/blob/master/src/libutil-tests/url.cc#L34-L50) appears to validate the expected behavior (port number parsed as the authority's port instead of a path component).
```c++
        // https://github.com/NixOS/nix/issues/5958
        // Already proper URL with git+ssh
        FixGitURLParam{
            .input = "git+ssh://user@domain:1234/path",
            .expected = "ssh://user@domain:1234/path",
            .parsed =
                ParsedURL{
                    .scheme = "ssh",
                    .authority =
                        ParsedURL::Authority{
                            .host = "domain",
                            .user = "user",
                            .port = 1234,
                        },
                    .path = {"", "path"},
                },
        },
```

**Comment by tones111** [comment]
I think this is ready for another look. I can rebase+squash if that would be easier to read. Thanks!

File: src/libutil/url.cc [hunk 1]
```diff
@@ -414,20 +414,54 @@ ParsedUrlScheme parseUrlScheme(std::string_view scheme)
...
+                if (url[hostEnd+1] != '/') {
+                    url.insert(hostEnd+1, "/");
+                }
+            }
+            // SCP-like paths use ssh scheme
+            url.insert(0, "ssh://");
+        }
+    }
+
+    auto parsed = parseURL(replaceStrings(url, " ", "%20"));
```
Comment (xokdvium) [inline src/libutil/url.cc]: Can't this be `parseURL(url, /*lenient=*/true)`? That will handle unescaped spaces.

Comment (tones111) [reply src/libutil/url.cc]: Turns out the `lenient` flag only %-encodes characters in the query and fragment strings.

I've added logic for the flag to also escape path characters.

Comment (xokdvium) [reply src/libutil/url.cc]: Hmm, changing `parseURL` that doesn't make sense then, as in would be a backwards incompatible change.
How does git itself handle percent encoded URLs and especially ones with spaces? Why is this needed? Do we rely on this somewhere in the test suite?

File: src/libutil/url.cc [hunk 2]
```diff
@@ -130,6 +135,32 @@ try {
...
+            // Parse authority (optional)
+            if (view.starts_with("//")) {
+                if (const auto pathStart = view.find('/', 2); pathStart != view.npos) {
+                    fixed += view.substr(0, pathStart);
+                    view.remove_prefix(pathStart);
+                }
+            }
+
+            // Parse path (can be empty)
+            if (view.starts_with("/")) {
```
Comment (tones111) [inline src/libutil/url.cc]: URL parsing is hard...

This check assumes the authority logic above found the path start position.  Otherwise it sees the leading `/` from the authority separator and applies the substitution to the authority string.  This is where regex's can more succinctly express what we need here.

File: src/libutil/url.cc (hunk 1 above)
Comment (tones111) [reply src/libutil/url.cc]: Without it we get a failure at fetchGit.sh:288
```
+(fetchGit.sh:286) cd '/tmp/nix-shell.v12OvF/nix-test/main/fetchGit/a b'
++(fetchGit.sh:288) nix eval --impure --raw --expr '(builtins.fetchGit ./.).outPath'
error:
       … while calling the 'fetchGit' builtin
         at «string»:1:2:
            1| (builtins.fetchGit ./.).outPath
             |  ^

       error: 'file:///tmp/nix-shell.v12OvF/nix-test/main/fetchGit/a b' is not a valid URL: leftover
```

The current implementation gets around this by making assumptions with file scheme (like not having an authority) and doesn't run them through `parseURL`.  This preserves the space in the path, but in my implementation boost throws when it sees the space.

```c++
    if (!hasPrefix(url, "file:") && !hasPrefix(url, "git+file:") && url.find("://") == std::string::npos)
        return ParsedURL{
            .scheme = "file",
            .authority = ParsedURL::Authority{},
            .path = splitString<std::vector<std::string>>(url, "/"),
        };
```

Comment (tones111) [reply src/libutil/url.cc]: I played around with `boost::urls::url_view` to see if it had any flexibility to accept spaces, but no such luck.  Their page on [sanitizing urls](https://www.boost.org/doc/libs/latest/doc/antora/url/examples/sanitize.html) is pretty ridiculous.  If something like their `extract_uri_components` is needed to pull apart the url and massage it into the right shape what value is `url_view` as we've now rewritten all the logic the abstraction is supposed to provide? Unfortunately `boost::urls::url` has the same behavior, even though it's an owned type.

`git` appears to handle paths with spaces just fine.
```
$ git clone localhost:src/my\ repo my\ repo2
$ cd my\ repo2
$ git remote -v
origin	localhost:src/my repo (fetch)
origin	localhost:src/my repo (push)
```
I get the same behavior with an `ssh://localhost/path/with spaces` url, so I think this use case will need to be supported.

`git` treats %-encoded strings as literals (doesn't decode them)
```
$ git clone my%20repo my\ repo2
fatal: repository 'my%20repo' does not exist
```

There is a `boost::urls::decode_view` that decodes url strings that could be used in `fromBoostUrlView` when pulling fields back out of the `url_view`.  Since `url_view` isn't publicly visible maybe that could allow us to encode everything going into the `url_view` and maintain back-compat by decoding fields like the path.  That's a more invasive change then I'd like to make here, so if we decide to go that route I suggest we restore the file scheme hack to land this change and then work the encode/decode change as a new effort.

Any other ideas on how to make progress here?

File: src/libutil/url.cc [hunk 3]
```diff
@@ -414,20 +446,60 @@ ParsedUrlScheme parseUrlScheme(std::string_view scheme)
...
+        if (url.starts_with("git+")) {
+            url.erase(0, 4);
+            schemeEnd -= 4;
+        }
+
+        // https://github.com/NixOS/nix/issues/14867
+        // SCP syntax overlaps with simple URIs like file:/path/to/repo
+        // Don't be fooled by invalid auth separator (ex: http:/server.com/path)
+        if (!(
+            url.starts_with("file:") || url.starts_with("git:") || url.starts_with("ssh:") ||
```
Comment (tones111) [inline src/libutil/url.cc]: CI didn't like the formatting in this area

Note to future me: run `./maintainers/format.sh` once we've resolved the outstanding issues.

File: src/libutil/url.cc (hunk 1 above)
Comment (xokdvium) [reply src/libutil/url.cc]: So several notes.

`ParsedURL` stores decoded strings. Technically spaces must be percent encoded in the path and that can be perfectly fine, since we stick pretty much to the letter of RFC 3986. Prior versions of nix never really accepted unencoded spaces (in `parseURL`, stick with me here), so that can be treated as a separate issue and can be left for a follow-up PR. Using boost here directly doesn't make much sense I think, all of the parsing logic should be hidden behind `parseURL` mostly.

Also, probably what would be less prone to a regression would be to not use parseURL in case of path cases (what was previously returning a `ParsedURL`).

Also, seems like spaces break flakerefs quite a bit:

```
nix flake show "git+file://$PWD"
error: getting status of '/home/xokdvium/work/code/nix /git+file:/home/xokdvium/work/code/nix ': No such file or directory
```

(That's with master and 2.28 before major URL rework).

So proceed:

- File case doesn't go through `parseURL`, since we don't want percent decoding here at all. We just straight-up construct the `ParsedURL` directly like it used to. This will get you back to the status quo. All characters will be treated as literals (though flakes add their own pct-encoding on top in `fetchTree`).
- Add tests for existing broken behaviour that we can address separately. URLs are such a can of worms that it would be best to handle piece-by-piece in manageable chunks.

> I get the same behavior with an ssh://localhost/path/with spaces url, so I think this use case will need to be supported.

Agreed, this would be best to support, but the thing to keep in mind that flakeref-style URIs like `nix flake show "git+file:///path with spaces"` or `git+ssh://host:port/path with spaces` could be confusing. What's passed down to `fixGitUrl` in that case will be the percent decoded string (so "file://path with spaces" or "ssh://path with spaces").

The more I think about this the more I'm convinced that the best way forward here would be to first do `percentEncode` in `fixGitURL` before doing `parseURL`, since as you show we should treat all characters as literals.

Also it occurs to me that we should start checking that the git url doesn't have a fragment or query part, but we can split that out too.

File: src/libutil/url.cc (hunk 2 above)
Comment (xokdvium) [reply src/libutil/url.cc]: I'm not opposed to using regexes here if it's more ergonomic and readable.

**Comment by xokdvium** [comment]
IIUC, the primary headache comes from the fact that git itself doesn't treat really do pct encoding, but fetchTree does, so you must ensure that everything is percent encoded when it's converted back into a string, but when rendering into a string when passing to git it doesn't get re-encoded. Special-casing just the spaces doesn't seem like the best approach.

So my suggestion (more concise than above):

- Do the trick with percentEncode before doing parseURL (making sure that path separators don't get encoded).

- Check that when we render the URL and pass that to git we don't re-encode.

That should cover all the bases pretty ok-ish. It's not efficient to do this encoding/decoding but we care about correctness here. fitGitURL should only really care about massaging scp-style into ssh one without touching the contents at all and ensuring that ParsedURL gets the contents verbatim.

**Comment by tones111** [comment]
Thank you for the feedback/insight.  I've moved the path %-encoding into fixGitURL and working with a `std::string` feels much cleaner.  I'm less sure how/where to write tests to validate your second point about decoding before passing to git.

**Comment by xokdvium** [comment]
@tones111, I'm going to push over your changes if there are no objections.

**Comment by xokdvium** [comment]
@tones111, also added support for IPv6 and made the percent encoding much less janky. Should be much more consistent now.

File: doc/manual/rl-next/git-url-scp.md [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+---
+
+Nix now (once again) recognizes [SCP-like syntax for Git URLs](https://git-scm.com/docs/git-clone#_git_urls). This partially
+restores compatibility with Nix 2.3 for `fetchGit`. The following syntax is once again supported:
+
+```nix
+builtins.fetchGit "host:/absolute/path/to/repo"
+```
+
+Nix also passes through the tilde expansion verbatim:
```
Comment (Ericson2314) [inline doc/manual/rl-next/git-url-scp.md]:
```suggestion
Nix also passes through the tilde (for home directories) verbatim:
```

File: src/libutil/url.cc [hunk 5]
```diff
@@ -414,20 +416,154 @@ ParsedUrlScheme parseUrlScheme(std::string_view scheme)
...
+    // http[s]://<host>[:<port>]/<path-to-git-repo>
+    // ftp[s]://<host>[:<port>]/<path-to-git-repo>
+    //
+    // An alternative scp-like syntax may also be used with the ssh protocol:
+    // [<user>@]<host>:/<path-to-git-repo>
+    // This syntax is only recognized if there are no slashes before the first colon.
+    //
+    // For local repositories, also supported by Git natively, the following syntaxes may be used:
+    // /path/to/repo.git/
+    // file:///path/to/repo.git/
```
Comment (Ericson2314) [inline src/libutil/url.cc]: I think this comment should move to the header, since it is documenting what it does, not how it is implemented.

File: src/libutil/url.cc [hunk 6]
```diff
@@ -414,20 +416,154 @@ ParsedUrlScheme parseUrlScheme(std::string_view scheme)
...
+            maybeIpv6Start != urlView.npos && maybeIpv6Start < firstColon) {
+            /* Find the end. */
+            auto maybeIpv6End = urlView.find_first_of(']', maybeIpv6Start);
+            if (maybeIpv6End == urlView.npos)
+                throw BadURL("missing closing bracket in SCP Git URL: '%s'", urlView);
+            std::string_view maybeIPv6Bracketed = urlView.substr(maybeIpv6Start + 1, maybeIpv6End - maybeIpv6Start - 1);
+            auto ipv6 = boost::urls::parse_ipv6_address(maybeIPv6Bracketed);
+            if (!ipv6)
+                throw BadURL(
+                    "Git SCP bracketed URL is not valid: '%s' is not a valid IPv6 address", maybeIPv6Bracketed);
```
Comment (Ericson2314) [inline src/libutil/url.cc]: I don't like parsing things just to throw it away. If we just remove this, will it change the semantics? I think it might not, because the code below will unconditionally parse this as IPv6, right? 
```suggestion
```

Comment (xokdvium) [reply src/libutil/url.cc]: Hm I'm pretty sure if will not diagnose it anymore. Don't think the double parsing is too much of a concern. It's not like we care about the performance of this too much. It was cleaner to do first validate and then parse the username and the ipv6 again.

**Comment by xokdvium** [comment]
> Some clarification on how to handle scp-style relative paths would be helpful.

Probably the best way is to stick with rewriting to absolute ones for now. I think we actual git and not git forges using tilde expansion for the home directory is best for the time being. Ideally we'd be able to differentiate between ssh URLs and SCP ones, but that poses a bit of an issue with flake lockfiles and back-compat.

File: src/libutil/url.cc [hunk 7]
```diff
@@ -414,20 +416,141 @@ ParsedUrlScheme parseUrlScheme(std::string_view scheme)
...
+        if (auto maybeIpv6Start = urlView.find_first_of('[');
+            /* @[ or [ must be before the colon. */
+            maybeIpv6Start != urlView.npos && maybeIpv6Start < firstColon) {
+            /* Find the end. */
+            auto maybeIpv6End = urlView.find_first_of(']', maybeIpv6Start);
+            if (maybeIpv6End == urlView.npos)
+                throw BadURL("missing closing bracket in SCP Git URL: '%s'", urlView);
+            /* Bracketed URLs should always enclose IPv6 addresses (for now). TODO: Maybe there's a reason to allow
+             * arbitrary strings? This is conservative for now. */
+            return urlView.substr(0, maybeIpv6End + 1);
```
Comment (Ericson2314) [inline src/libutil/url.cc]: Let's also throw if the `maybeIpv6End + 1` character is not a `:`. Then we always return a view that immediately precedes a colon.

File: src/libutil/url.cc [hunk 8]
```diff
@@ -414,20 +416,141 @@ ParsedUrlScheme parseUrlScheme(std::string_view scheme)
...
         };
+    }
+
+    const std::string_view schemeOrHost = [urlView = std::string_view{url}] {
+        auto firstColon = urlView.find_first_of(':');
+
+        if (firstColon == urlView.npos)
+            throw BadURL(
+                "Git URL '%s' doesn't have a scheme, is not an absolute path and doesn't look like an SCP-like URL",
+                urlView);
```
Comment (Ericson2314) [inline src/libutil/url.cc]: Actually, in conjunction with https://github.com/NixOS/nix/pull/14863/files#r2663545430, we can just do this in the `no-bracket` case.

> if contains `[`
> 
> then is must be in the form `...[....]:...`, and return everything up until that `:`.
>
>  else return everything until the first `:`, which must exist.

File: src/libutil/url.cc [hunk 9]
```diff
@@ -414,20 +416,141 @@ ParsedUrlScheme parseUrlScheme(std::string_view scheme)
...
+           forges. There's also home expansion to consider. Should be possible to work around using tilde expansion
+           by specifying something like host:~/path/to/repo instead of host:path/to/repo. */
+        if (auto & path = res.path; !path.empty() && !path.front().empty())
+            path.insert(path.begin(), "");
+
+        return res;
+    }
+
+    /* TODO: What to do about query parameters? Git should pass those to the * http(s) remotes. Ignore for now and
+     * just pass through. Will fail later. */
```
Comment (Ericson2314) [inline src/libutil/url.cc:702]: I'm confused, it is parsing query params?

File: src/libutil/url.cc [hunk 10]
```diff
@@ -414,20 +416,141 @@ ParsedUrlScheme parseUrlScheme(std::string_view scheme)
...
+        return res;
+    }();
+
+    /* When Git encounters a URL of the form <transport>://<address>, where <transport> is a protocol that it cannot
+       handle natively, it automatically invokes git remote-<transport> with the full URL as the second argument.
+       https://git-scm.com/docs/gitremote-helpers. If the url doesn't look like it would be accepted by the remote
+       helper, treat it as a SCP-style one. Don't do any pct-decoding in that case. Schemes supported by git are
+       excluded. */
+    if (std::string_view urlView = url;
+        urlView.remove_prefix(schemeOrHost.size()),
```
Comment (Ericson2314) [inline src/libutil/url.cc]:
```suggestion
        urlView.remove_prefix(schemeOrHost.size()),
        assert(urlView.starts_with(':')),
        urlView.remove_prefix(1), /* Trim the colon. */
```

File: src/libutil/url.cc [hunk 11]
```diff
@@ -414,20 +416,141 @@ ParsedUrlScheme parseUrlScheme(std::string_view scheme)
...
+        } else {
+            authority = ParsedURL::Authority{
+                .hostType = ParsedURL::Authority::HostType::Name,
+                .host = std::string(host),
+            };
+        }
+
+        authority.user = username;
+        assert(urlView.starts_with(':'));
+        urlView.remove_prefix(1); /* Trim the colon. */
```
Comment (Ericson2314) [inline src/libutil/url.cc]:
```suggestion
```

File: src/libutil/url.cc [hunk 12]
```diff
@@ -414,20 +416,141 @@ ParsedUrlScheme parseUrlScheme(std::string_view scheme)
...
+
+    /* When Git encounters a URL of the form <transport>://<address>, where <transport> is a protocol that it cannot
+       handle natively, it automatically invokes git remote-<transport> with the full URL as the second argument.
+       https://git-scm.com/docs/gitremote-helpers. If the url doesn't look like it would be accepted by the remote
+       helper, treat it as a SCP-style one. Don't do any pct-decoding in that case. Schemes supported by git are
+       excluded. */
+    if (std::string_view urlView = url;
+        urlView.remove_prefix(schemeOrHost.size()),
+        /* This syntax is only recognized if there are no slashes before the first colon. */
+        !schemeOrHost.contains('/') && !urlView.starts_with("://") && !schemesSupportedByGit.contains(schemeOrHost)) {
```
Comment (Ericson2314) [inline src/libutil/url.cc]:
```suggestion
        !schemeOrHost.contains('/') && !urlView.starts_with("//") && !schemesSupportedByGit.contains(schemeOrHost)) {
```

File: src/libutil/url.cc [hunk 13]
```diff
@@ -414,20 +416,141 @@ ParsedUrlScheme parseUrlScheme(std::string_view scheme)
...
+            return urlView.substr(0, maybeIpv6End + 1);
+        }
+
+        return urlView.substr(0, firstColon);
+    }();
+
+    /* HACK: SCP syntax overlaps with file:/path/to/repo. Git itself doesn't recognize it (or rather treats `file` as
+     * the host name), but Nix accepts file:/path/to/repo as well as file:///path/to/repo. */
+    if (schemeOrHost == "file" || schemeOrHost == "git+file") {
+        auto res = parseURL(url);
```
Comment (tones111) [inline src/libutil/url.cc]: A potential issue with using `parseURL` here and not for the absolute path above is that they're no longer equivalent.  If I modify this test to use a file scheme the output differs.

existing test:
```
            .input = "/repos/git repo",
            .expected = "file:///repos/git%20repo",
```

modified to use file:///
```
        FixGitURLParam{
            .input = "file:///repos/git repo",
            .expected = "file:///repos/git%20repo",
            .parsed =
                ParsedURL{
                    .scheme = "file",
                    .authority = ParsedURL::Authority{},
                    .path = {"", "repos", "git repo"},
                },
        },
```

fails with
```
unknown file: Failure
C++ exception with description "[31;1merror:[0m '[35;1mfile:///repos/git repo[0m' is not a valid URL: [35;1mleftover[0m" thrown in the test body.
```

The git clone url documentation says they should be equivalent

> For local repositories, also supported by Git natively, the following syntaxes may be used:
> /path/to/repo.git/
> file:///path/to/repo.git/
> These two syntaxes are mostly equivalent, except the former implies --local option.

While it is a url, git is able to handle the raw space.
```
$ git clone file:///home/paul/src/my\ repo my\ repo2
Cloning into 'my repo2'...
<...>
$ cd my\ repo2/
$ git remote -v
origin	file:///home/paul/src/my repo (fetch)
origin	file:///home/paul/src/my repo (push)
```

File: src/libutil/url.cc [hunk 14]
```diff
@@ -414,20 +416,141 @@ ParsedUrlScheme parseUrlScheme(std::string_view scheme)
...
+         * path. Any pct-encoded sequences get treated as literals. Should probably use
+         * std::filesystem::path::generic_string here for normalization, but that would be a slight behaviour change. */
         return ParsedURL{
             .scheme = "file",
             .authority = ParsedURL::Authority{},
             .path = splitString<std::vector<std::string>>(url, "/"),
         };
+    }
+
+    const std::string_view schemeOrHost = [urlView = std::string_view{url}] {
```
Comment (Ericson2314) [inline src/libutil/url.cc]:
```suggestion
    /**
     * If is SCP style, (and not `file:` or `git+file:`, which is ambiguous, but which we choose to parse as a regular URL), return the pair of raw string authority and remaining path.
     */
    const auto parseScpStylePair = [urlView = std::string_view{url}]() -> std::optional<std::pair<std::string_view, std::string_view>> {
```
@xokdvium I think, especially after my suggestions, we have too much comma operator, and we should just move the entire if condition to this function and *not* immediately call it.

We'll instead call it from within the `if`.

File: src/libutil/url.cc (hunk 12 above)
Comment (Ericson2314) [inline src/libutil/url.cc]: Actual suggestion, once the conditions are moved up.
```suggestion
    if (auto scpStylePair = parseScpStylePair()) {
```

File: src/libutil/url.cc (hunk 10 above)
Comment (tones111) [inline src/libutil/url.cc]: Had to look this up to learn about the [comma operator](https://stackoverflow.com/questions/16475032/comma-operator-in-if-condition) which might also be surprising to other readers (clever though).

Maybe we could combine the strip + assignment instead?
```c++
    if (std::string_view urlView = url.data() + schemeOrHost.size();
        /* This syntax is only recognized if there are no slashes before the first colon. */
        !schemeOrHost.contains('/') && !urlView.starts_with("://") && !schemesSupportedByGit.contains(schemeOrHost)) {
```

Comment (Ericson2314) [reply src/libutil/url.cc]: This is fixed now

File: src/libutil/url.cc (hunk 13 above)
Comment (Ericson2314) [reply src/libutil/url.cc]: I think it is OK for us to be stricter than Git --- the most important thing is that when we do succeed, we agree with Git. It is OK to fail where Git would succeed I think, especially because the point of `file://` vs plain paths is to be explicit.

**Comment by Ericson2314** [comment]
OK @xokdvium, this is back to you now.

**Review by Ericson2314 — DISMISSED** [review]
```
$ git clone 'user[2001:db8:1::2]:/home/@file'
Cloning into '@file'...
ssh: Could not resolve hostname user[2001: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
```
$ git clone 'user:[2001:db8:1::2]:/home/file'
Cloning into 'file'...
ssh: Could not resolve hostname user: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
```
$ git clone 'user:@[2001:db8:1::2]:/home/file'
Cloning into 'file'...
^C⏎  # timeout connecting to IP
```
@xokdvium from some manual testing of truly insane stuff, I don't think the new algorithm is right yet.

**Comment by Ericson2314** [comment]
I added some WIP additinoal tests for these crazy cases.

File: src/libutil/url.cc (hunk 9 above)
Comment (xokdvium) [reply src/libutil/url.cc:702]: Yeah but downstream users are broken.

**Review by Ericson2314 — COMMENTED** [review]
I made all the code changes I want to make

**Comment by tones111** [comment]
@xokdvium 
Just checking in to make sure this isn't waiting on me.  Is there anything left to do for this effort?

Thanks

**Comment by Ericson2314** [comment]
This isn't waiting on you, @tones111. I hope @xokdvium can review the changes I made in addition to his changes. He mentioned some things are still not right, but we haven't gone into the details yet.

**Comment by tones111** [comment]
Pinging @xokdvium again to see if we can get a list of any remaining shortcomings.

**Comment by Ericson2314** [comment]
@xokdvium I just did another pass on this, making it more like the Git original, adding a bunch of comments, and adding more test cases.

The LLM could have put in some bogus line numbers in the links in the comments, but otherwise I think it is rock solid.

File: src/libutil/url.cc [hunk 15]
```diff
@@ -401,41 +403,302 @@ ParsedUrlScheme parseUrlScheme(std::string_view scheme)
...
+                    "instead, to explicitly use an absolute path (and silence this warning). "
+                    "Or, to be relative to the remote user's home directory:\n\n"
+                    "    %s\n\n"
+                    "or with an explicit SSH URL:\n\n"
+                    "    %s",
+                    url,
+                    scpAbsolute,
+                    sshAbsolute,
+                    scpTilde,
+                    sshTildeUrl.to_string());
```
Comment (Ericson2314) [inline src/libutil/url.cc:670]: Eventually I will redo this with the lint infra

**Comment by Ericson2314** [comment]
OK I fixed the Windows test failures, just need to make alt versions of a few more abs path tests.

**Comment by Ericson2314** [comment]
Maybe let's test

- `xfilex:/foo@[bar]:baz/quux`
- `file:/foo@[bar]:baz/quux`

too

**Comment by Ericson2314** [comment]
@xokdvium Reminder I think this is ready now.

File: src/libutil/url.cc [hunk 16]
```diff
@@ -401,41 +403,302 @@ ParsedUrlScheme parseUrlScheme(std::string_view scheme)
...
+ * second argument. https://git-scm.com/docs/gitremote-helpers. If the
+ * url doesn't look like it would be accepted by the remote helper,
+ * treat it as a SCP-style one. Don't do any pct-decoding in that case.
+ * Schemes supported by git are excluded.
+ *
+ * Use
+ *
+ * ```bash GIT_TRACE=1 git ls-remote "$URL" ```
+ *
+ * to manual test this, e.g. with out unit test URLs that should cover
```
Comment (xokdvium) [inline src/libutil/url.cc]:
```suggestion
 * to manual test this, e.g. with our unit test URLs that should cover
```

File: src/libutil/url.cc [hunk 17]
```diff
@@ -401,41 +403,302 @@ ParsedUrlScheme parseUrlScheme(std::string_view scheme)
...
-        if (hasPrefix(url, "/") || hasDriveLetter)
-            return ParsedURL{
-                .scheme = "file",
-                .authority = ParsedURL::Authority{},
-                .path = hasDriveLetter ? pathToUrlPath(std::filesystem::path(url)) : path,
+    /* The funny functional structure indicates how this happens in two
+       parts.
+
+       The first part decides whether we have a SCP-style pseudo-URL or not ---
+       any throwing errors rather than returning std::nullopt is just a chance
```
Comment (xokdvium) [inline src/libutil/url.cc]:
```suggestion
       and throwing errors rather than returning std::nullopt is just a chance
```

File: src/libutil/url.cc [hunk 18]
```diff
@@ -401,41 +403,302 @@ ParsedUrlScheme parseUrlScheme(std::string_view scheme)
...
+                   in this case. */
+            } else {
+                /* Found `]`. Expect `:` immediately after for SCP-style. */
+                if (closeBracket + 1 < url.size() && url[closeBracket + 1] == ':') {
+                    schemeOrHost = url.substr(0, closeBracket + 1);
+                } else if (url.find(':', closeBracket + 1) != url.npos) {
+                    /* `:` exists after `]` but not immediately — git's
+                       `strchr(end, ':')` would find it, silently discarding
+                       characters between `]` and `:` (e.g.
+                       `user@[::1]foo:path` → host `::1`, `foo` is lost).
```
Comment (xokdvium) [inline src/libutil/url.cc]: Can we avoid UTF chars here? Is this claude?

```suggestion
                       `user@[::1]foo:path` -> host `::1`, `foo` is lost).
```

File: src/libutil/url.cc [hunk 19]
```diff
@@ -401,41 +403,302 @@ ParsedUrlScheme parseUrlScheme(std::string_view scheme)
...
+        auto maybeIPv6 = [](std::string_view host) -> std::optional<ParsedURL::Authority> {
+            if (host.starts_with('[') && host.ends_with(']')) {
+                host.remove_prefix(1);
+                host.remove_suffix(1);
+                auto ipv6 = boost::urls::parse_ipv6_address(host);
+                if (!ipv6)
+                    throw BadURL("Git SCP bracketed URL is not valid: '%s' is not a valid IPv6 address", host);
+                return ParsedURL::Authority{
+                    .hostType = ParsedURL::Authority::HostType::IPv6,
+                    .host = ipv6->to_string(),
```
Comment (xokdvium) [inline src/libutil/url.cc:593]: Worth noting that we are intentionally diverging from git here which accepts anything inbetween the square brackets. libgit2 also rejects such cases. Possibly another git bug...

File: src/libutil/url.cc [hunk 20]
```diff
@@ -401,41 +403,302 @@ ParsedUrlScheme parseUrlScheme(std::string_view scheme)
...
+
+           Paths starting with `~` are also fine: git strips the `/` before
+           `~` at the transport layer (see git's `connect.c`).
+
+           FIXME: Turn warning into hard error, or talk to upstream git about
+           some way to make this possible to represent.
+         */
+        if (auto & path = res.path; !path.empty() && !path.front().empty()) {
+            /* Make the path absolute for the ssh:// URL. */
+            path.insert(path.begin(), "");
```
Comment (xokdvium) [inline src/libutil/url.cc:643]: This doesn't work with github:

```
fatal: remote error:
 /NixOS/nix is not a valid repository name
```

Comment (xokdvium) [reply src/libutil/url.cc:643]: Ah right, we are not changing that yet. It continues to work then - we just lack the ability to encode the "relative to home" without explicitly adding the home directory. Though I guess we would be adding a bit too much noise from warning on forges, no?

Comment (Ericson2314) [reply src/libutil/url.cc:643]: @xokdvium and I talked about this, and I think we are OK, since an initial `/` is in fact accepted by at least all of GitHub, GitLab, and Gitea.

**Review by Ericson2314 — APPROVED** [review]
