### PR TITLE
nix flake lock: Fail if there is an unlocked input

### LINKED ISSUE #12022: 'nix flake lock' should fail if it can't write the lock file
## Describe the bug

`nix flake lock` currently prints a warning if it can't write a lock file due to unlocked inputs. Since the sole purpose of `nix flake lock` is to write a lock file, this should be a fatal error.

Maybe it could remind users that the appropriate thing to do is to pass `--override-input` to commands like `nix build` rather than `nix flake lock`.

See also #11181.

## Steps To Reproduce

```
$ nix flake lock --override-input nixpkgs /home/eelco/Dev/nixpkgs
warning: Git tree '/home/eelco/Dev/nixpkgs' is dirty
warning: will not write lock file of flake 'git+file:///home/eelco/Misc/eelco-configurations?dir=bla' because it has an unlocked input ('git+file:///home/eelco/Dev/nixpkgs')
```

## Checklist

- [ ] checked [latest Nix manual] \([source])
- [ ] checked [open bug issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by edolstra**
## Motivation

Since the only purpose of `nix flake lock` is to write a new lock file, it should be a fatal error if we can't write the lock file.

Fixes #12022.

## Context

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Review by roberth — APPROVED** [review]

File: src/libflake/flake/flake.cc [hunk 1]
```diff
@@ -672,6 +672,8 @@ LockedFlake lockFlake(
             if (lockFlags.writeLockFile) {
                 if (sourcePath || lockFlags.outputLockFilePath) {
                     if (auto unlockedInput = newLockFile.isUnlocked()) {
+                        if (lockFlags.failOnUnlocked)
+                            throw Error("cannot write lock file of flake '%s' because it has an unlocked input ('%s').\n", topRef, *unlockedInput);
```
Comment (roberth) [inline src/libflake/flake/flake.cc:676]:
```suggestion
                            throw Error("cannot write lock file of flake '%s' because it has an unlocked input ('%s'). Unlocked inputs can be passed to most nix commands using --override-input, but do not result in a lock file.\n", topRef, *unlockedInput);
```

**Review by roberth — CHANGES_REQUESTED** [review]
Still confusing when users get the error, as mentioned in the issue.

**Comment by roberth** [comment]
(could merge in a hurry, but then we'll need a new issue)

File: src/libflake/flake/flake.cc (hunk 1 above)
Comment (edolstra) [reply src/libflake/flake/flake.cc:676]: I thought about that, but unlocked inputs don't need to come from `--override-input`. So this message could be potentially confusing.

Comment (Mic92) [reply src/libflake/flake/flake.cc:676]: In that case, we shouldn't have it.

**Comment by Mic92** [comment]
> (could merge in a hurry, but then we'll need a new issue)

What do you mean by that? What new issue?

**Comment by Mic92** [comment]
@mergify queue
