### PR TITLE
Macos big sur installer fixes

### LINKED ISSUE #3852: macOS version check broken in Big Sur beta 3.
Big Sur beta 3 changes the version from 10.15.6 (or 10.16? Whatever it was yesterday. :)) to 11.0.

looks like it should be something like:
```
# macOS support for 10.12.6 or higher
if [ "$(uname -s)" = "Darwin" ]; then
    macos_major=$(sw_vers -productVersion | cut -d '.' -f 1)
    macos_minor=$(sw_vers -productVersion | cut -d '.' -f 2)
    macos_patch=$(sw_vers -productVersion | cut -d '.' -f 3)
    if [ "$macos_major" -lt 10 ] || { [ "$macos_major" -eq 10 ] && [ "$macos_minor" -lt 12 ]; } || { [ "$macos_major" -eq 10 ] && [ "$macos_minor" -eq 12 ] && [ "$macos_patch" -lt 6 ]; }; then
        echo "$0: macOS $(sw_vers -productVersion) is not supported, upgrade to 10.12.6 or higher"
        exit 1
    fi
fi
```

### LINKED ISSUE #3957: investigate fixes for macOS Big Sur installer if `apfs.util -B` is indeed removed
I want to go ahead and put a pin in a [Big Sur installation issue I saw on Discourse](https://discourse.nixos.org/t/installing-on-macos-11-big-sur/8739):

> I can’t get the firmlinks thing working. Because (1) apfs.util doesn’t have the `-B` anymore, which I resolved by just doing a reboot.

IIRC, someone discovered `apfs.util -B` (`apfs.util --help` describes the purpose of this option as "bootstrap the root filesystem") as a way to skirt what had previously appeared to be a required reboot between adding /nix to synthetic.conf and being able to actually make the /nix directory. Here it is in the installer:

https://github.com/NixOS/nix/blob/c129e7c8f4846fcc146cfb3e408a75dd73794794/scripts/create-darwin-volume.sh#L135

If this is indeed true and the functionality hasn't moved elsewhere (or isn't a bug; or isn't something we can get restored by griping), I think our install process is going to necessarily become a clunky two-phase thing?

### PR DESCRIPTION
**Pull request by abathur**
Goal: make sure the installer scripts will run across macOS versions

Caveats, in case this ends up like the last one... 😬 
- I have tested installs with multiple macOS versions on a single system, but not on Linux.
- This work is just focused on procedural differences necessary to install on Big Sur as seen on existing Intel hardware; it has nothing directly to do with the ARM/DTK effort. (I gather the install will fail on a DTK without a release tarball available for that architecture.)

This will also fix #3852 and fix #3957.

A few notes (repeated from a later comment):
1. I had to fix a few macOS install breaks introduced by other commits already in master. If a new release needs to be cut from master before these changes land, those fixes will need to be cherry-picked/ported to keep macOS installs (for _all_ versions) working correctly.
2. After daemon installs, commands throw `file 'nixpkgs' was not found in the Nix search path...` errors on invocation. I don't think I caused this (maybe ec9dd9a did)? If that's correct, it'll need attention outside the scope of this PR.

### CODE REVIEW

**Comment by domenkozar** [comment]
cc @LnL7

File: scripts/create-darwin-volume.sh [hunk 1]
```diff
@@ -89,9 +73,7 @@ test_t2_chip_present(){
 }
 
 test_filevault_in_use() {
-    disk=$1
-    #      list vols on disk | get value of Filevault key | value is true
-    apfs_volumes_for "$disk" | volume_list_true FileVault | grep -q true
+    fdesetup isactive
```
Comment (matthewbauer) [inline scripts/create-darwin-volume.sh:76]: This command doesn't exist on macOS catalina. Could we keep `volume_list_true` to continue supporting it?

Comment (abathur) [reply scripts/create-darwin-volume.sh:76]: We'll obviously keep whatever works, but can you double-check? I have it on Catalina (and Mojave, and Big Sur) at `/usr/bin/fdesetup`:
```
$ sw_vers -productVersion && fdesetup isactive
10.15.5
false
```

Comment (abathur) [reply scripts/create-darwin-volume.sh:76]: I also triggered a travis-ci build to check availability for this on a span of available versions from 10.12.6 through 10.15 at https://travis-ci.com/github/nix-community/nix-travis-ci/builds/183399921. These are "failing" because fdesetup isactive returns 1, but they all appear to have the command so far.

Comment (matthewbauer) [reply scripts/create-darwin-volume.sh:76]: Ahh sorry! Yeah I have it. I had been trying fdsetup :)

Comment (abathur) [reply scripts/create-darwin-volume.sh:76]: No worries. Happy to have you giving it a shake :)

File: scripts/install-nix-from-closure.sh [hunk 2]
```diff
@@ -108,8 +109,13 @@ if [ "$(uname -s)" = "Darwin" ]; then
         "$self/create-darwin-volume.sh"
     fi
 
-    info=$(diskutil info -plist / | xpath "/plist/dict/key[text()='Writable']/following-sibling::true[1]" 2> /dev/null)
-    if ! [ -e $dest ] && [ -n "$info" ] && [ "$macos_major" -gt 14 ]; then
+    writable="$(diskutil info -plist / | xmllint --xpath "/plist/dict/key[text()='Writable']/following-sibling::*[1]/text()" -)"
+    # TODO: I wonder a bit if we need the version test, here. This may seem odd since I
```
Comment (LnL7) [inline scripts/install-nix-from-closure.sh:113]: I think I suggested removing it, just checking if it's writable should be enough.

File: scripts/install-nix-from-closure.sh [hunk 3]
```diff
@@ -24,10 +24,11 @@ fi
 
 # macOS support for 10.12.6 or higher
 if [ "$(uname -s)" = "Darwin" ]; then
-    macos_major=$(sw_vers -productVersion | cut -d '.' -f 2)
-    macos_minor=$(sw_vers -productVersion | cut -d '.' -f 3)
-    if [ "$macos_major" -lt 12 ] || { [ "$macos_major" -eq 12 ] && [ "$macos_minor" -lt 6 ]; }; then
-        echo "$0: macOS $(sw_vers -productVersion) is not supported, upgrade to 10.12.6 or higher"
+    verinfo="$(mktemp)"
```
Comment (LnL7) [inline scripts/install-nix-from-closure.sh:27]: Should be pretty easy to avoid creating and leaving behind unnecessary tempfiles.

File: scripts/create-darwin-volume.sh [hunk 4]
```diff
@@ -55,6 +26,19 @@ test_synthetic_conf() {
     grep -q "^nix$" /etc/synthetic.conf 2>/dev/null
 }
 
+# Create the paths defined in synthetic.conf, saving us a reboot.
+create_synthetic_objects(){
+    # Big Sur takes away the -B flag we were using and replaces it
```
Comment (LnL7) [inline scripts/create-darwin-volume.sh:31]: I had a feeling this might not be very stable, that's why I included the true fallback. I'd look at it as best effort so this seems fine. Perhaps even just always try both.

File: scripts/create-darwin-volume.sh [hunk 5]
```diff
@@ -5,42 +5,13 @@ root_disk() {
...
-        fi
-        case "$name" in
-            [Nn]ix*)
-                echo "$name"
-                break
-                ;;
-        esac
-        i=$((i+1))
-    done
+    diskutil apfs list -plist "$1" | xmllint --xpath "/plist/dict/array/dict/key[text()='Volumes']/following-sibling::array/dict/key[text()='Name']/following-sibling::string[contains(translate(text(),'N','n'),'nix')]/text()" -
```
Comment (LnL7) [inline scripts/create-darwin-volume.sh:14]: Nice, did you check this with a few conditions?

File: scripts/create-darwin-volume.sh (hunk 1 above)
Comment (LnL7) [reply scripts/create-darwin-volume.sh:76]: Does this need testing for T1/no T1 conditions or did you already do that?

**Review by LnL7 — COMMENTED** [review]
Looks pretty good to me.

File: scripts/create-darwin-volume.sh [hunk 6]
```diff
@@ -11,7 +11,7 @@ root_disk_identifier() {
 }
 
 find_nix_volume() {
-    diskutil apfs list -plist "$1" | xmllint --xpath "/plist/dict/array/dict/key[text()='Volumes']/following-sibling::array/dict/key[text()='Name']/following-sibling::string[contains(translate(text(),'N','n'),'nix')]/text()" -
+    diskutil apfs list -plist "$1" | xmllint --xpath "/plist/dict/array/dict/key[text()='Volumes']/following-sibling::array/dict/key[text()='Name']/following-sibling::string[contains(translate(text(),'N','n'),'nix')]/text()" - || true 2>/dev/null
```
Comment (cole-h) [inline scripts/create-darwin-volume.sh:14]: Should this be `- 2>/dev/null || true`, not `- || true 2>/dev/null`?

```suggestion
    diskutil apfs list -plist "$1" | xmllint --xpath "/plist/dict/array/dict/key[text()='Volumes']/following-sibling::array/dict/key[text()='Name']/following-sibling::string[contains(translate(text(),'N','n'),'nix')]/text()" - 2>/dev/null || true
```

Comment (abathur) [reply scripts/create-darwin-volume.sh]: Thanks :)

File: scripts/create-darwin-volume.sh (hunk 4 above)
Comment (abathur) [reply scripts/create-darwin-volume.sh:31]: I've pushed a commit to do this. :)

File: scripts/install-nix-from-closure.sh (hunk 3 above)
Comment (abathur) [reply scripts/install-nix-from-closure.sh]: Addressed in 7ccb5b0

File: scripts/install-nix-from-closure.sh (hunk 2 above)
Comment (abathur) [reply scripts/install-nix-from-closure.sh:111]: Tentatively addressed in 30bd194, but leaving this open as a reminder to remove the comment once I've confirmed it works.

File: scripts/create-darwin-volume.sh (hunk 5 above)
Comment (abathur) [reply scripts/create-darwin-volume.sh]: While thinking through this again I did notice and fix a pair of issues:
- after 16d6181 it should break after the first match like the existing loop
- after 4b42097 it should match at the beginning of the volume name only

Does that cover what you have in mind?

**Comment by abathur** [comment]
I think this now achieves the main goal--making sure the installer scripts will run across macOS versions.

A few notes:
1. I had to fix a few macOS install breaks introduced by other commits already in master. If a new release needs to be cut from master before these changes land, those fixes will need to be cherry-picked/ported to keep macOS installs (for _all_ versions) working correctly.
2. I've only tested this on macOS. 
3. After daemon installs, commands throw `file 'nixpkgs' was not found in the Nix search path...` errors on invocation. I don't think I caused this (maybe ec9dd9a did)? If that's correct, it'll need attention outside the scope of this PR.

**Comment by abathur** [comment]
@domenkozar I think this is roughly ready. Notes:

- Despite adding support, 0baa6e7 also adds a temporary check to limit Big Sur installs in case Apple releases it before some issues related to supporting Big Sur in nixpkgs can be ironed out (requested by @LnL7).
- Changes here probably merit a broad installer test before the next release
- When I tested this on daemon installs, nix-commands throw `file 'nixpkgs' was not found in the Nix search path...` errors on invocation. I'm planning to open a separate issue for that unless you see something I've done that you think could cause it (I suspect ec9dd9a may be the source).

**Comment by Atemu** [comment]
> When I tested this on daemon installs, nix-commands throw file `'nixpkgs' was not found in the Nix search path...` errors on invocation.

This already happened on my recent Catalina installation. Doing step 3. from [here](https://github.com/nix-community/home-manager#installation) fixes the issue.

See https://github.com/NixOS/nix/issues/2033 for more info.

**Comment by domenkozar** [comment]
@abathur I'm a bit short on time to test this. However, if you generate the installer script, it should be trivial to test with github actions once 11.0 is available for testing.

**Comment by abathur** [comment]
@domenkozar I have them for the last two commits. I'll ping you on IRC.

**Comment by abathur** [comment]
If anyone wants to test this, I've hosted two darwin-x86_64 tarballs with matching stub install scripts (these scripts don't check the tarball hash).

1. To test the actual Big Sur install, target https://files.t-ravis.com/install-allowed (which will download nix-3.0pre20200914_4b42097-x86_64-darwin.tar.xz, built from 4b42097).
2. To test the install guards that exclude Big Sur systems until Nixpkgs support is ready, target https://files.t-ravis.com/install-blocked (which will download nix-3.0pre20200917_0baa6e7-x86_64-darwin.tar.xz, built from 0baa6e7).

For reference, I also re-ran some trivial CI jobs with these URLs. 
- "allowed" run: https://travis-ci.com/github/nix-community/nix-travis-ci/builds/188871929
- "blocked" run: https://travis-ci.com/github/nix-community/nix-travis-ci/builds/188873113

Notes:
- You shouldn't see any difference between the allowed/blocked installers here; the "blocked" installer should only affect Big Sur+, and travis-ci hasn't added Big Sur runners yet.
- The macOS jobs "fail" after successfully installing because there's no nixpkgs pre-specified on the daemon installs (single-user should be OK). I'm not sure if that behavior is correct, but I'm pretty sure it's out-of-scope here.
- All of the Linux jobs are canceled--there's no Linux installer.

**Comment by abathur** [comment]
@domenkozar GitHub Actions added Big Sur preview runners today, so I've done comparison runs with the installers above:
- Normal run (default installer) with Big Sur in the OS matrix to document existing condition https://github.com/abathur/resholve/actions/runs/307640557
- Run with "install-allowed" https://github.com/abathur/resholve/actions/runs/307647998
   - install-nix-action runs clean
   - but my build does fail with a c compiler issue; this is roughly why @LnL7 asked me to block installs
- Run with "install-blocked" https://github.com/abathur/resholve/actions/runs/307655319
   - install fails with the message `nixpkgs isn't quite ready to support macOS 11.0 yet`

**Comment by domenkozar** [comment]
Could we also run with the tbd branch?

**Comment by abathur** [comment]
I've force-pushed a squashed history which collapses all of the incremental fix commits back down into:
- 4 commits fixing issues directly necessary for Big Sur, which can be cherry-picked to `2.3-maintenance`: 9c3dc9d 1f02b65 e736f8f fe80790
- 3 commits fixing issues problems already present in master: 3a8699a b719f68 c40bad4
- 1 commit which blocks install on Big Sur install, which we can eventually drop/revert depending on the status of the tbd/stdenv work: f289bdb

**Comment by domenkozar** [comment]
Thanks!

**Comment by domenkozar** [comment]
Cherry-picked 4 commits to 2.3-maintenance, we'll hopefully release 2.3.8 once nixpkgs is ready.

**Comment by abathur** [comment]
@domenkozar I didn't notice that 2.3.8 has already been cut or I would've done this sooner, but I ran an install test just now on my laptop with Big Sur:

```
 - system: `"x86_64-darwin"`
 - host os: `Darwin 20.1.0, macOS 10.16`
 - multi-user?: `no`
 - sandbox: `no`
 - version: `nix-env (Nix) 2.3.8`
 - channels(abathur): `"nixpkgs-21.03pre246624.cfed29bfcb2"`
 - nixpkgs: `/Users/abathur/.nix-defexpr/channels/nixpkgs`
```

**Comment by domenkozar** [comment]
Nice!!
