### PR TITLE
Fix flake registry ignoring `dir` parameter

### LINKED ISSUE #13269: nix 2.29.0 ignores "dir" field on registry.json
## Describe the bug

nix 2.29.0 doesn't takes into account dir parameter from nix registry

## Steps To Reproduce

With nix 2.26.2 or 2.28.3:
$ nix eval blender-bin
«derivation /nix/store/g6sqfammi9j6qx4c2fn834r91a4f7b71-blender-bin-4.4.3.drv»

but with nix 2.29.0:
$ nix eval blender-bin
error: path '«github:edolstra/nix-warez/85d76721132cc6631bbaa8c950d4d0f3aa4003fd»/flake.nix' does not exist
$ nix eval github:edolstra/nix-warez?dir=blender
«derivation /nix/store/g6sqfammi9j6qx4c2fn834r91a4f7b71-blender-bin-4.4.3.drv»

## Expected behavior

$ nix eval blender-bin
«derivation /nix/store/g6sqfammi9j6qx4c2fn834r91a4f7b71-blender-bin-4.4.3.drv»

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by cole-h**
This broke in e3042f10afb5f4e64ef9a5e08bef52b168cb4bf1.

Forward port of https://github.com/DeterminateSystems/nix-src/pull/196.

## Motivation

Fixes #13269.

## Context

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Review by tomberek — APPROVED** [review]

File: tests/functional/flakes/flakes.sh [hunk 1]
```diff
@@ -470,3 +470,20 @@ cat > "$flake3Dir/flake.nix" <<EOF
...
+cat > "$subdirFlakeDir"/flake.nix <<EOF
+{
+  outputs = inputs: {
+    shouldBeOne = 1;
+  };
+}
+EOF
+
+nix registry add --registry "$registry" flake2 "path:$baseDir?dir=foo"
+[[ "$(nix eval --flake-registry "$registry" flake2#shouldBeOne)" = 1 ]]
```
Comment (xokdvium) [inline tests/functional/flakes/flakes.sh:489]: @cole-h, could you also add a regression test for https://github.com/NixOS/nix/issues/13918? I suspect that has the same root cause?

Comment (cole-h) [reply tests/functional/flakes/flakes.sh:489]: It does not have the same root cause -- at least, this fix does not also fix that, from my testing. I ran out of time to figure out why / what is causing that one, but figured I could at least get this fix up.
