### PR TITLE
libfetchers/git: add support for '.' in gitmodules

### LINKED ISSUE #13215: `bultins.fetchGit` with submodules failes to clone branch `.`
## Describe the bug

Trying to use `builtins.fetchGit` with `submodules` enabled to clone entire boost project. The [`.gitmodules`](https://github.com/boostorg/boost/blob/master/.gitmodules) file of boost said that branch of submodules are `.`. I suppose this is means the same branch, as head repo. The `fetchGit` failed on this.

## Steps To Reproduce

```
❯ nix repl
Nix 2.28.3
Type :? for help.
nix-repl> url="https://github.com/boostorg/boost.git" 

nix-repl> builtins.fetchGit { inherit url; submodules=true; } 
error:
       … while calling the 'fetchGit' builtin
         at «string»:1:1:
            1| builtins.fetchGit { inherit url; submodules=true; }
             | ^

       … while fetching the input 'git+https://github.com/boostorg/boost.git?submodules=1'

       error: invalid Git branch/tag name '.'
```

## Expected behavior

Successful fetching to nix store

## Metadata

❯ nix-env --version
nix-env (Nix) 2.28.3

❯ git --version
git version 2.49.0

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open bug issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by fzakaria**
## Motivation

Please see https://github.com/NixOS/nix/issues/13215

Basically, `.gitmodules` file may have `.` as the branch listed for a submodule.
The git-documentation claims this is a "special" branch that represents it should be identical to the parent repository. [[ref](https://git-scm.com/docs/gitmodules#Documentation/gitmodules.txt-submodulenamebranch)]

### Validation

**broken**
```
[----------] 1 test from GitTest
[ RUN      ] GitTest.submodule_period_support
unknown file: Failure
C++ exception with description "error:
       … while fetching the input 'git+file:///tmp/nix-120109-2774730724/repo?ref=main&submodules=1'

       error: invalid Git branch/tag name '.'" thrown in the test body.

[  FAILED  ] GitTest.submodule_period_support (20 ms)
[----------] 1 test from GitTest (20 ms total)
```

**fixed**

```
meson test -C build nix-fetchers-tests
ninja: Entering directory `/home/fmzakari/code/github.com/NixOS/nix/build'
[2/2] Linking target src/libfetchers-tests/nix-fetchers-tests
1/1 libfetchers-tests / nix-fetchers-tests        OK              0.08s
```

Alternatively, I made a demo repo with this feature.

```
> cat /tmp/test/.gitmodules
[submodule "nix-auto-follow"]
	path = nix-auto-follow
  url = https://github.com/fzakaria/nix-auto-follow.git
  branch = .

> _NIX_FORCE_HTTP=1 ./build/src/nix/nix eval --impure --expr 'builtins.fetchGit { url="file:///tmp/test"; submodules=true; }'
{ lastModified = 1755229090; lastModifiedDate = "20250815033810"; narHash = "sha256-yNOsLiJAtS/atdWMto3usCEBmerWonCVoe557zQRvt4="; outPath = "/nix/store/3mcd25dyi8nfz84zxlz8v3bg0ch9crbz-source"; rev = "9e37ffc3ab465887b20be4ac42224e483706cefc"; revCount = 1; shortRev = "9e37ffc"; submodules = true; }
```

fixes #13215

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by fzakaria** [comment]
@xokdvium current failure is because of how the test runs inside a Nix flake :S
```
nix-fetchers-tests-run> [ RUN      ] GitTest.submodule_period_support
nix-fetchers-tests-run> unknown file: Failure
nix-fetchers-tests-run> C++ exception with description "error:
nix-fetchers-tests-run>        … while fetching the input 'git+file:///build/nix-5-432530085/repo?ref=main&submodules=1'
nix-fetchers-tests-run> 
nix-fetchers-tests-run>        error: creating directory '/homeless-shelter/.cache/nix': Permission denied" thrown in the test body.
```

I need to either set the git cache to a different directory... If you have advice let me know

File: src/libfetchers-tests/git.cc [hunk 1]
```diff
@@ -0,0 +1,205 @@
...
+    // 5) Finalize now that the worktree exists; libgit2 can read its HEAD OID
+    CHECK(git_submodule_add_finalize(sm.get()));
+    // 6) Commit the addition in super
+    commit_all(super.get(), "Add submodule with branch='.'");
+
+    // Create a temporary store
+    // TODO: can this be an in-memory store somehow?
+    Path storeTmpDir = createTempDir();
+    auto storeTmpDirAutoDelete = AutoDelete(storeTmpDir, true);
+    ref<Store> store = openStore(storeTmpDir);
```
Comment (xokdvium) [inline src/libfetchers-tests/git.cc:184]: I think @Ericson2314 had a old PR to make `dummy://` use more in-memory stuff. Would that be useful here? That never got merged.

Comment (xokdvium) [reply src/libfetchers-tests/git.cc:184]: This one https://github.com/NixOS/nix/pull/10915

Comment (fzakaria) [reply src/libfetchers-tests/git.cc:184]: Discussed on matrix.
I will like to pick it up; seems worthwhile -- I might also make it a separate store.

Either way I think it doesn't block this PR.

File: src/libfetchers-tests/package.nix [hunk 2]
```diff
@@ -58,17 +58,13 @@ mkMesonExecutable (finalAttrs: {
...
-              touch $out
-            ''
-          );
+          (''
+            export HOME="$PWD/home-dir"
+            mkdir -p "$HOME"
+            export _NIX_TEST_UNIT_DATA=${resolvePath ./data}
+            ${stdenv.hostPlatform.emulator buildPackages} ${lib.getExe finalAttrs.finalPackage}
+            touch $out
+          '');
```
Comment (fzakaria) [inline src/libfetchers-tests/package.nix]: This was needed for Linux as well otherwise the Git fetcher will try to create cache directory under `/homeless-shelter`

File: src/libfetchers-tests/git.cc [hunk 3]
```diff
@@ -0,0 +1,208 @@
...
+class GitTest : public ::testing::Test
+{
+protected:
+    fs::path tmp;
+
+    void SetUp() override
+    {
+        tmp = createTempDir();
+        // Initialize libstore
+        nix::initLibStore(false);
```
Comment (fzakaria) [inline src/libfetchers-tests/git.cc]: Interestingly, I don't seem to need this init when I build it locally.
`nix build .#checks.x86_64-linux.nix-fetchers-tests-run` passes locally but on CI it fails with:
```
 > The program must call nix::initNix() before calling any libstore library functions.
```

File: src/libfetchers-tests/package.nix (hunk 2 above)
Comment (xokdvium) [reply src/libfetchers-tests/package.nix]: You can use `writableTmpDirAsHomeHook` hook to automate this.

Comment (fzakaria) [reply src/libfetchers-tests/package.nix]: Seems minor but we can fix in a subsequent PR.
Looks like we just add it as a buildInput.

File: src/libfetchers-tests/git.cc [hunk 4]
```diff
@@ -0,0 +1,208 @@
...
+        if (_e < 0)      \
+            die(_e, #x); \
+    } while (0)
+
+static void die(int err, const char * what)
+{
+    const git_error * e = git_error_last();
+    throw std::runtime_error(
+        std::string(what) + " failed: " + std::to_string(err) + " " + (e && e->message ? e->message : ""));
+}
```
Comment (xokdvium) [inline src/libfetchers-tests/git.cc]: Why not implement this in terms of `ASSERT_TRUE`?

Comment (fzakaria) [reply src/libfetchers-tests/git.cc]: Want me to ?
My c++ skills are dull so I'm re-sharpening them.

File: src/libfetchers/git.cc [hunk 5]
```diff
@@ -741,6 +741,11 @@ struct GitInputScheme : InputScheme
                 attrs.insert_or_assign("url", resolved);
                 if (submodule.branch != "")
                     attrs.insert_or_assign("ref", submodule.branch);
+                // A special value of . is used to indicate that the name of the branch in the submodule
+                // should be the same name as the current branch in the current repository.
+                // https://git-scm.com/docs/gitmodules
+                if (submodule.branch == ".")
+                    attrs.insert_or_assign("ref", ref);
```
Comment (xokdvium) [inline src/libfetchers/git.cc]: Isn't this doing extra work? It would make more sense:
```suggestion
                if (submodule.branch != "") {
                  auto branch = [&](){
                    // A special value of . is used to indicate that the name of the branch in the submodule
                  // should be the same name as the current branch in the current repository.
                  // https://git-scm.com/docs/gitmodules
                    if (submodule.branch == ".")
                      return ref;
                    return submodule.branch;
                  }();
                  attrs.insert_or_assign("ref", branch);
                }   
```

Comment (fzakaria) [reply src/libfetchers/git.cc]: my opinion:
"extra" work via 1 assignment into a `std::map` ?
That seems really minor vs the creation of a closure which is passed to the function....

I could embed the if statement inside so its

```
if submodule.branch != "":
   if submodule.branch == ".":
        # do X
   else:
      # do Y
```

File: src/libfetchers-tests/git.cc [hunk 6]
```diff
@@ -0,0 +1,208 @@
...
+template<class T, void (*F)(T *)>
+using handle = std::unique_ptr<T, Deleter<T, F>>;
+
+using repo_h = handle<git_repository, git_repository_free>;
+using idx_h = handle<git_index, git_index_free>;
+using tree_h = handle<git_tree, git_tree_free>;
+using sig_h = handle<git_signature, git_signature_free>;
+using ref_h = handle<git_reference, git_reference_free>;
+using cmt_h = handle<git_commit, git_commit_free>;
+using sub_h = handle<git_submodule, git_submodule_free>;
```
Comment (xokdvium) [inline src/libfetchers-tests/git.cc]: nit: naming conventions

```suggestion
template<class T, void (*F)(T *)>
using Handle = std::unique_ptr<T, Deleter<T, F>>;

using RepoHandle = Handle<git_repository, git_repository_free>;
using IdxHandle = Handle<git_index, git_index_free>;
using TreeHandle = Handle<git_tree, git_tree_free>;
using SigHandle = Handle<git_signature, git_signature_free>;
using RefHandle = Handle<git_reference, git_reference_free>;
using CommitHandle = Handle<git_commit, git_commit_free>;
using SubmoduleHandle = handle<git_submodule, git_submodule_free>;
```

File: src/libfetchers-tests/git.cc [hunk 7]
```diff
@@ -0,0 +1,208 @@
...
+#define CHECK(x)         \
+    do {                 \
+        int _e = (x);    \
+        if (_e < 0)      \
+            die(_e, #x); \
+    } while (0)
+
+static void die(int err, const char * what)
+{
+    const git_error * e = git_error_last();
```
Comment (xokdvium) [inline src/libfetchers-tests/git.cc]: nit:

```suggestion
    const gitError * e = git_error_last();
```

File: src/libfetchers-tests/git.cc (hunk 6 above)
Comment (fzakaria) [reply src/libfetchers-tests/git.cc]: These handles have some overlap in `git-utils.cc` which is unfortunate; 
Longer term probably makes sense to give `git-utils` a header and make it more shareable.
(I plan to clean up afterwards as I'm familiarizing myself with the tree)

File: src/libfetchers/git.cc (hunk 5 above)
Comment (xokdvium) [reply src/libfetchers/git.cc]: Yeah, the extra work argument is minor, but overwriting the previous value is pretty unreadable.

File: src/libfetchers-tests/git.cc (hunk 6 above)
Comment (xokdvium) [reply src/libfetchers-tests/git.cc]: Either way: please follow the naming conventions.

File: src/libfetchers/git.cc (hunk 5 above)
Comment (fzakaria) [reply src/libfetchers/git.cc]: how about the if/else offered above?
I'll do that --

Comment (xokdvium) [reply src/libfetchers/git.cc]: That would be ok as well, though I'm a fan of the Immediately Invoked Lambda since it avoids mutation.

File: src/libfetchers-tests/git.cc (hunk 4 above)
Comment (xokdvium) [reply src/libfetchers-tests/git.cc]: Since we are using GTest framework it'd be better to not reinvent the test framework and just reuse what it offers. You can do something like:

```cpp
#define CHECK_LIBGIT(expr) ASSERT_TRUE((expr) >= 0) << git_error_last();
```
