### PR TITLE
Filesystem error improvements

### LINKED ISSUE #11376: All std::filesystem related errors need to be re-thrown as nix errors
**Describe the bug**

Since @siddhantk232 has introduced std::filesystem in many places
we no longer generate nix traces i.e. when a directory does not exit.
We need to catch all std::filesystem related exception and throw a proper nix error instead,
because only nix errors are catched in eval.cc and get nix error context added.

### PR DESCRIPTION
**Pull request by Ericson2314**
## Motivation

File system error improvements

- Make `descriptorToPath` cross-platform (renamed from `windows::handleToPath`). Uses `/proc/self/fd` on Linux and `F_GETPATH` on macOS. Add `HAVE_F_GETPATH` meson check.

  This is based on 7226a116a0bbc1f304d8160615525cb0aeb46096, which was removed in 479c356510dcdcb43f16c7483a48ff3308c6dd2b, but is now introduced more judiciously.

- Unix error messages in `readFull`, `writeFull`, `readLine` now include file paths via `descriptorToPath`.

- Convert `std::filesystem::filesystem_error` to `SystemError`

  Wrappers like `readLink`, `createDirs`, `DirectoryIterator`, etc. now catch `std::filesystem::filesystem_error` and rethrow as `SystemError` with the error code preserved. This ensures consistent exception types throughout the codebase.

  Call sites that previously caught `filesystem_error` and rethrew with `throw;` now throw `SystemError(e.code(), ...)` instead.

  Some call sites can stop catching `filesystem_error` at all, because they only call the wrapped functions.

- Rework `SystemError` constructors to auto-append error message

  The public `SystemError(std::error_code, ...)` constructor now automatically appends `errorCode.message()` to the error message. A protected constructor takes an explicit error message string for subclasses.

  `SysError` delegates to the protected constructor with `strerror(errNo)`. `WinError` delegates with `renderError(lastError)` (now static).

  This removes the need to manually append `e.code().message()` at call sites when converting `filesystem_error` to `SystemError`.

- Use perfect forwarding (`Args &&...` with `std::forward`) consistently in `BaseError`, `SystemError`, `SysError`, and `WinError` constructors.

## Context

Possibly fixes #11376

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by xokdvium** [comment]
Probably somewhat fully addresses https://github.com/NixOS/nix/issues/11376? Now that we have more wrapper functions for std::filesystem things...

File: src/libutil/include/nix/util/error.hh [hunk 1]
```diff
@@ -247,19 +247,35 @@ MakeError(UnimplementedError, Error);
...
+
+    /**
+     * Protected constructor for subclasses that provide their own error message.
+     * The error message is appended to the formatted hint.
+     */
     template<typename... Args>
-    SystemError(std::errc posixErrNo, Args &&... args)
-        : Error(std::forward<Args>(args)...)
-        , errorCode(std::make_error_code(posixErrNo))
+    SystemError(Disambig, std::error_code errorCode, std::string_view errorDetails, const Args &... args)
```
Comment (xokdvium) [inline src/libutil/include/nix/util/error.hh]:
```suggestion
    SystemError(Disambig, std::error_code errorCode, std::string_view errorDetails, Args &&... args)
```

File: src/libutil/include/nix/util/error.hh [hunk 2]
```diff
@@ -247,19 +247,35 @@ MakeError(UnimplementedError, Error);
...
+        : Error("")
+        , errorCode(errorCode)
+        , errorDetails(errorDetails)
     {
+        auto hf = HintFmt(args...);
```
Comment (xokdvium) [inline src/libutil/include/nix/util/error.hh]:
```suggestion
        auto hf = HintFmt(std::forward<Args>(args)...);
```

File: src/libutil/include/nix/util/error.hh (hunk 1 above)
Comment (xokdvium) [reply src/libutil/include/nix/util/error.hh]: Why not this?

File: src/libutil/include/nix/util/error.hh [hunk 3]
```diff
@@ -247,19 +247,35 @@ MakeError(UnimplementedError, Error);
...
+    /**
+     * Construct with an error code. The error code's message is automatically
+     * appended to the error message.
+     */
     template<typename... Args>
-    SystemError(std::error_code errorCode, Args &&... args)
-        : Error(std::forward<Args>(args)...)
-        , errorCode(errorCode)
+    SystemError(std::error_code errorCode, const Args &... args)
+        : SystemError(Disambig{}, errorCode, errorCode.message(), args...)
```
Comment (xokdvium) [inline src/libutil/include/nix/util/error.hh]: Ditto? Is there a reason to not forward stuff?

```suggestion
    SystemError(std::error_code errorCode, Args &&... args)
        : SystemError(Disambig{}, errorCode, errorCode.message(), std::forward<Args>(args)...)
```

File: src/libutil/unix/file-system-at.cc [hunk 4]
```diff
@@ -71,27 +71,32 @@ void unix::fchmodatTryNoFollow(Descriptor dirFd, const CanonPath & path, mode_t
...
-            path.rel());
+            savedErrno,
+            "opening %s to get an O_PATH file descriptor (fchmodat2 is unsupported)",
+            PathFmt(descriptorToPath(dirFd) / path.rel()));
+    }
 
     struct ::stat st;
     /* Possible since https://github.com/torvalds/linux/commit/55815f70147dcfa3ead5738fd56d3574e2e3c1c2 (3.6) */
     if (::fstat(pathFd.get(), &st) == -1)
         throw SysError("statting '%s' relative to parent directory via O_PATH file descriptor", path.rel());
```
Comment (xokdvium) [inline src/libutil/unix/file-system-at.cc:96]: Should this also get updated?

Comment (xokdvium) [reply src/libutil/unix/file-system-at.cc:96]: Can be left for later I suppose

**Review by xokdvium — COMMENTED** [review]
Seems good to me. The error message improvement is good

**Review by xokdvium — APPROVED** [review]
