### PR TITLE
Enter debugger more reliably in `let` expressions and function calls

### LINKED ISSUE #6649: builtins.break doesn't break
**Describe the bug**

I add `builtins.break` to some code, and it doesn't break.

**Steps To Reproduce**

1.  Add this simple `flake.nix`:

    ```nix
    {
      inputs.nixpkgs.url = "nixpkgs/f1c9c23aad972787f00f175651e4cb0d7c7fd5ea";
      outputs = {
        self,
        nixpkgs,
      }: let
        pkgs = builtins.break nixpkgs.legacyPackages.x86_64-linux;
      in {
        devShells.x86_64-linux.default = pkgs.mkShell {
          buildInputs = [pkgs.hello];
        };
      };
    }
    ```

2.  Run `nix develop --debugger`

https://user-images.githubusercontent.com/973709/173176380-870c1b4c-2ebd-41e1-9980-f57428d38d83.mp4

**Expected behavior**

Nix repl should stop at the break point.

**`nix-env --version` output**
nix-env (Nix) 2.9.0

**Additional context**

The screencast seems to display bug #6594 but the main problem is that it doesn't stop at the desired break point.

### PR DESCRIPTION
**Pull request by 9999years**
# Motivation

Currently, if you attempt to evaluate this file with the debugger:

```nix
let
  a = builtins.trace "before inner break" (
    builtins.break "hello"
  );
  b = builtins.trace "before outer break" (
    builtins.break a
  );
in
  b
```

Nix will correctly enter the debugger at `builtins.break a`, but if you ask it to `:continue`, it'll skip over the `builtins.break "hello"` expression entirely:

```
$ nix eval --file xxx-test.nix --debugger
trace: before outer break
info: breakpoint reached

      at «none»:0: (source not available)


Starting REPL to allow you to inspect the current state of the evaluator.

Welcome to Nix 2.18.1. Type :? for help.

nix-repl> :c
trace: before inner break
"hello"
```

This is because the set of debug traces is empty by the time Nix gets to the second call:

https://github.com/NixOS/nix/blob/0127d54d5e86db9039e6322d482d26e66af8bd8a/src/libexpr/primops.cc#L757

With this patch, Nix will correctly enter the debugger both times:

```
$ nix eval --file xxx-test.nix --debugger
trace: before outer break
info: breakpoint reached


Starting REPL to allow you to inspect the current state of the evaluator.

Welcome to Nix 2.20.0pre20231222_dirty. Type :? for help.

nix-repl> :c
trace: before inner break
info: breakpoint reached


Starting REPL to allow you to inspect the current state of the evaluator.

Welcome to Nix 2.20.0pre20231222_dirty. Type :? for help.

nix-repl> :c
"hello"
```

# Context

Fixes #6649.

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

File: src/libexpr/eval.cc [hunk 1]
```diff
@@ -1322,6 +1322,19 @@ void ExprLet::eval(EvalState & state, Env & env, Value & v)
...
+    auto dts = state.debugRepl
+        ? makeDebugTraceStacker(
+            state,
+            *this,
+            env2,
+            getPos()
+                ? std::make_shared<Pos>(state.positions[getPos()])
+                : nullptr,
+            "while evaluating a '%1%' expression",
+            "let"
```
Comment (thufschmitt) [inline src/libexpr/eval.cc:1334]: Can't we just replace that by

```suggestion
            "while evaluating a 'let' expression",
```

and not add the formatting logic in `makeDebugTraceStacker`?

**Review by thufschmitt — CHANGES_REQUESTED** [review]

**Review by thufschmitt — APPROVED** [review]

File: src/libexpr/eval.cc (hunk 1 above)
Comment (thufschmitt) [reply src/libexpr/eval.cc:1334]: Oh, right :) This thing is still too magical for me
