### PR TITLE
libutil: Use Boost.URL for URI parsing

### LINKED ISSUE #10898: nix-copy-closure to ssh:// store tries to log in with empty SSH username
**Describe the bug**

I'm not sure if this is supposed to work, but it does seem to almost work, so maybe it should work?

If I run `nix-copy-closure --to 'ssh://user@machine?base64-ssh-public-host-key=...&ssh-key=...'`, Nix seems to try to (eventually) log in to the target machine with an empty SSH username (`""`).

Local logs:

```
//ssh-ng://foobar@foobar.example.com: Permission denied (publickey).
error: failed to start SSH connection to '//ssh-ng://foobar@foobar.example.com'
```

Remote logs:

```
Jun 12 14:49:09 foobar sshd[1256612]: Accepted publickey for foobar from 192.168.0.2 port 33540 ssh2: ED25519 SHA256:xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Jun 12 14:49:09 foobar sshd[1256612]: pam_unix(sshd:session): session opened for user foobar(uid=30033) by (uid=0)
Jun 12 14:49:09 foobar systemd-logind[622]: New session 1580 of user foobar.
Jun 12 14:49:09 foobar systemd[1]: Started session-1580.scope - Session 1580 of User foobar.
Jun 12 14:49:09 foobar sshd[1256612]: pam_env(sshd:session): deprecated reading of user environment enabled
Jun 12 14:49:09 foobar sshd[1256619]: Received disconnect from 192.168.0.2 port 33540:11: disconnected by user
Jun 12 14:49:09 foobar sshd[1256619]: Disconnected from user foobar 192.168.0.2 port 33540
Jun 12 14:49:09 foobar sshd[1256612]: pam_unix(sshd:session): session closed for user foobar
Jun 12 14:49:09 foobar systemd[1]: session-1580.scope: Deactivated successfully.
Jun 12 14:49:09 foobar systemd-logind[622]: Session 1580 logged out. Waiting for processes to exit.
Jun 12 14:49:09 foobar systemd-logind[622]: Removed session 1580.
Jun 12 14:49:10 foobar sshd[1256622]: Invalid user  from 192.168.0.2 port 33554
Jun 12 14:49:10 foobar sshd[1256622]: Connection closed by invalid user  192.168.0.2 port 33554 [preauth]
```

Notice how it seems to log in successfully but the last two lines show that it seems to try logging in with an empty username.

**Steps To Reproduce**

1. `nix-copy-closure --to 'ssh://user@machine?base64-ssh-public-host-key=...&ssh-key=...'`

**Expected behavior**

Work, or fail in a reasonable way.

**`nix-env --version` output**

nix-env (Nix) 2.19.1

**Additional context**

N/A

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by xokdvium**
## Motivation

Boost.URL is a significantly more RFC-compliant parser
than what libutil currently has a bundle of incomprehensible
regexes.

One aspect of this change is that RFC4007 ZoneId IPv6 literals
are represented in URIs according to RFC6874 [1].

Previously they were represented naively like so: `[fe80::818c:da4d:8975:415c\%enp0s25]`.
This is not entirely correct, because the percent itself has to be pct-encoded:

> "%" is always treated as
   an escape character in a URI, so, according to the established URI
   syntax [RFC3986] any occurrences of literal "%" symbols in a URI MUST
   be percent-encoded and represented in the form "%25".  Thus, the
   scoped address fe80::a%en1 would appear in a URI as
   http://[fe80::a%25en1].

[1]: https://datatracker.ietf.org/doc/html/rfc6874

## Context

Starting to pay off the tech debt https://github.com/NixOS/nix/issues/9603.
Fixes #10898.

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

File: tests/functional/build-remote-with-mounted-ssh-ng.sh [hunk 1]
```diff
@@ -15,7 +15,7 @@ nix build -Lvf simple.nix \
 nix build -Lvf simple.nix \
   --arg busybox "$busybox" \
   --out-link "$TEST_ROOT/result-from-remote-new-cli" \
-  --store 'mounted-ssh-ng://localhost?remote-program=nix daemon'
+  --store 'mounted-ssh-ng://localhost?remote-program=nix%20daemon'
```
Comment (Ericson2314) [inline tests/functional/build-remote-with-mounted-ssh-ng.sh]: n.b. this is fine with me because this is an experimental feature's test.

**Review by Ericson2314 — APPROVED** [review]
I like this a lot!

But going to leave for others to review a bit just case there is some issues e.g. with how much Boost or compat I didn't think of

File: tests/functional/build-remote-with-mounted-ssh-ng.sh (hunk 1 above)
Comment (Mic92) [reply tests/functional/build-remote-with-mounted-ssh-ng.sh]: Does this also affect other store urls? I don't think they are all experimental.

Comment (Mic92) [reply tests/functional/build-remote-with-mounted-ssh-ng.sh]: Should be at minimum mentioned in release notes I think.

Comment (xokdvium) [reply tests/functional/build-remote-with-mounted-ssh-ng.sh]: Yeah, all URIs (and store references are sometimes URIs) would be affected. That shouldn't occur for flakerefs, because I doubt any web service would actually accept literal spaces in the URI. I could try to make it work by forcefully transforming all spaces in the query -> pct-encoded spaces with a warning. Though I'm not sure if this is possible.

Comment (xokdvium) [reply tests/functional/build-remote-with-mounted-ssh-ng.sh]: Also I have a feeling that this might be silently breaking path flakerefs with spaces. Need to investigate further.

Comment (roberth) [reply tests/functional/build-remote-with-mounted-ssh-ng.sh]: Browsers do it, so users may expect it, but also we have space separated options in Nix (unfortunately), so maybe we shouldn't _make_ users expect it by allowing it. I guess I'm on the fence about it.
What does the error look like?

Comment (xokdvium) [reply tests/functional/build-remote-with-mounted-ssh-ng.sh]: I've looked into the spaces in URIs and it seems that disallowing space literals would be too much of a breaking change. I've modified the code to first percent encode any literal spaces. Also added a test for a space in a query parameter. Also did some manual testing of flakerefs and relative flake inputs that have spaces in them.

Comment (xokdvium) [reply tests/functional/build-remote-with-mounted-ssh-ng.sh]: Made this test work without modifications, so this change no longer breaks existing URIs.

File: src/libutil/url.cc [hunk 2]
```diff
@@ -4,110 +4,118 @@
...
 
-        result.emplace(
-            s.substr(0, e),
-            percentDecode(std::string_view(s).substr(e + 1)));
+        result.emplace(key.decode(), value.decode());
     }
 
     return result;
+} catch (boost::system::system_error & e) {
+    throw BadURL("invalid URI query '%s'", e.code().message());
```
Comment (xokdvium) [inline src/libutil/url.cc]: Unfortunately boost's error messages here are of very little use: https://github.com/boostorg/url/blob/a1a5d18e9356036e446f98fc774eb1a1f5e242af/src/grammar/error.cpp#L44-L49. Though this isn't a regression in any way, old code also had very generic error messages.

File: src/libutil/url.cc [hunk 3]
```diff
@@ -4,110 +4,118 @@
...
+    for (auto && [key, value, value_specified] : encodedQuery) {
+        if (!value_specified) {
+            warn("dubious URI query '%s' is missing equal sign '%s', ignoring", std::string_view(key), "=");
             continue;
         }
 
-        result.emplace(
-            s.substr(0, e),
-            percentDecode(std::string_view(s).substr(e + 1)));
+        result.emplace(key.decode(), value.decode());
```
Comment (xokdvium) [inline src/libutil/url.cc:110]: This is not exactly a no-op refactor, but there's no reason not to allow percent encoding in the parameter key.

**Review by Mic92 — APPROVED** [review]
Fixed some issue in to_string(), let me know what you think.

File: src/libutil/url.cc [hunk 4]
```diff
@@ -122,12 +133,29 @@ std::string encodeQuery(const StringMap & ss)
...
+{
+    // Find the last @ to separate userinfo from host
+    // The last @ is the delimiter, any @ before that is part of userinfo
+    auto lastAt = auth.rfind('@');
+    if (lastAt != std::string::npos) {
+        // We have userinfo
+        auto userinfo = auth.substr(0, lastAt);
+        auto hostPort = auth.substr(lastAt + 1);
+        // In the userinfo part, @ needs to be encoded along with other special chars
+        // But : is allowed in userinfo for username:password
```
Comment (xokdvium) [inline src/libutil/url.cc]: This manual parsing really shouldn't be here. I intentionally did't approach the whole mess that is the current authority. Boost's authority class has all the necessary machinery to do this stuff correctly.

Comment (xokdvium) [reply src/libutil/url.cc]: @Mic92 I'd like to do the authority fixes separately, since it really has a much wider scope.

I think the correct thing to do would be to keep around the boost's authority class around in the `ParsedURL` and use its getters for host, port e.t.c.

Comment (Mic92) [reply src/libutil/url.cc]: Ok. Feel free to drop the commit than.

**Comment by xokdvium** [comment]
Ran the whole `flake-regressions` suite and `hydraJobs.tests`. Best I can tell this doesn't regress anything. What's great is that this also fixed a long-standing issue #10898.

**Comment by grahamc** [comment]
One concern I have is the flake regression suite only tests public flakes, and I suspect some flakes out there will no longer work correctly with new parsing semantics.

**Comment by xokdvium** [comment]
> I suspect some flakes out there will no longer work correctly with new parsing semantics.

I did see that Determinate runs GHA CI with a private flake-regressions-data repository.

> work correctly with new parsing semantics.

Any particular issues you can think of? Did some of the prior non-compliance get ossified into lock files?
The several major deviations are 1) non pct-encoded spaces (which are handled explicitly in this patchset) and 2) the nested store URI queries, but this is also seemingly handled and tested.
