### PR TITLE
Fix macOS GC failures

### LINKED ISSUE #5717: Investigate non-blocking GC random failures

### PR DESCRIPTION
**Pull request by edolstra**
Fixes #5717.

### CODE REVIEW

**Comment by Artturin** [comment]
Did this fix https://github.com/NixOS/nix/issues/5687 ?

**Comment by abathur** [comment]
xref above from 3605 is on an error message that contains an instance of debug added in d17d46c

File: src/libstore/gc.cc [hunk 1]
```diff
@@ -126,7 +126,17 @@ void LocalStore::addTempRoot(const StorePath & path)
...
+            try {
+                nix::connect(state->fdRootsSocket.get(), socketPath);
+            } catch (SysError & e) {
+                /* The garbage collector may have exited, so we need to
+                   restart. */
+                if (e.errNo == ECONNREFUSED) {
+                    debug("GC socket connection refused");
+                    state->fdRootsSocket.close();
+                    goto restart;
+                }
```
Comment (andersk) [inline src/libstore/gc.cc:138]: This is missing a rethrow for other error codes (#6648).
