### PR TITLE
Fix mingw build

### LINKED ISSUE #14662: MinGW build is broken again
## Steps To Reproduce

https://hydra.nixos.org/job/nix/master/buildCross.nix-expr.x86_64-w64-mingw32.x86_64-linux

## Expected behavior

Hydra builds MinGW fine.

A gazillion regressions from https://github.com/NixOS/nix/pull/14652, https://github.com/NixOS/nix/pull/14649 and https://github.com/NixOS/nix/pull/14640.

## Checklist

- [ ] checked [latest Nix manual] \([source])
- [ ] checked [open bug issues and pull requests] for possible duplicates

[latest Nix manual]: https://nix.dev/manual/nix/development/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by edolstra**
## Motivation

Also fixes a bug in `FdSource::restart()`.

Fixes #14662.

## Context

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

File: src/libutil/serialise.cc [hunk 1]
```diff
@@ -206,8 +206,9 @@ void FdSource::restart()
     if (!isSeekable)
         throw Error("can't seek to the start of a file");
     buffer.reset();
-    read = bufPosOut = bufPosOut = 0;
-    if (lseek(fd, 0, SEEK_SET) == -1)
+    read = bufPosIn = bufPosOut = 0;
```
Comment (xokdvium) [inline src/libutil/serialise.cc:209]: Yikes. Sorry for that!
