### PR TITLE
libstore S3: fix progress bar and make file transfers interruptible

### LINKED ISSUE #12084: `nix copy --to s3://` progress bar is incorrect
## Describe the bug

When uploading to S3 with `nix copy` the progress bar will show hundreds of thousands of megabytes copied for a 1GB closure

## Steps To Reproduce

```
[arian@framework:~/Projects/terraform-aws-ssm-nixos-deploy-document/examples/nix-store-path]$ nix copy --to "s3://cache2024912328328&secret-key=./key.sec" "${out_path}"
[8/460/639 copied (150616.3/143782.0 MiB)] 
```
## Expected behavior

The progress bar shows a sane number. Not `150616.3/143782.0 MiB`

## Metadata

```
nix --version
nix (Nix) 2.24.9
```

## Checklist

- [ ] checked [latest Nix manual] \([source])
- [ ] checked [open bug issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by NaN-git**
## Motivation

At the moment the progress bar is not showing the upload/download progress when uploading to or downloading from S3 buckets. Also uploads are not interruptible.

## Context

Fixes #12084 and #11678.

TODO: All files are downloaded and decompressed in memory without any streaming. This should be fixed in the future.

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

File: src/libstore/s3-binary-cache-store.cc [hunk 1]
```diff
@@ -159,7 +159,11 @@ ref<Aws::Client::ClientConfiguration> S3Helper::makeConfig(
 S3Helper::FileTransferResult S3Helper::getObject(
     const std::string & bucketName, const std::string & key)
 {
-    debug("fetching 's3://%s/%s'...", bucketName, key);
+    std::string uri = "s3://" + bucketName + "/" + key;
+    Activity act(*logger, lvlTalkative, actFileTransfer,
+        fmt("downloading '%s'", uri),
+        Logger::Fields{uri}, getCurActivity());
+    debug("fetching '%s'...", uri);
```
Comment (edolstra) [inline src/libstore/s3-binary-cache-store.cc:166]:
```suggestion
```
Superfluous since we already have an activity that basically says the same thing.

File: src/libstore/s3-binary-cache-store.cc [hunk 2]
```diff
@@ -170,6 +174,27 @@ S3Helper::FileTransferResult S3Helper::getObject(
...
+        act.progress(bytesDone, bytesExpected);
+    });
+
+    request.SetContinueRequestHandler([](const Aws::Http::HttpRequest*) {
+        bool cont = false;
+        try {
+            checkInterrupt();
+            cont = true;
+        } catch(...) {}
+        return cont;
```
Comment (edolstra) [inline src/libstore/s3-binary-cache-store.cc:195]:
```suggestion
        try {
            checkInterrupt();
            return true;
        } catch (...) { return false; }
```

File: src/libstore/s3-binary-cache-store.cc [hunk 3]
```diff
@@ -170,6 +174,27 @@ S3Helper::FileTransferResult S3Helper::getObject(
...
+            }
+        }
+        bytesDone += l;
+        act.progress(bytesDone, bytesExpected);
+    });
+
+    request.SetContinueRequestHandler([](const Aws::Http::HttpRequest*) {
+        bool cont = false;
+        try {
+            checkInterrupt();
```
Comment (edolstra) [inline src/libstore/s3-binary-cache-store.cc:192]: This may be problematic since `checkInterrupt()` sets `interruptThrown`, which prevents the interrupt from being thrown on the same thread. Maybe we need a function that checks the interrupt flag without throwing anything, i.e.
```
    return _isInterrupted || (interruptCheck && interruptCheck();
```

File: src/libstore/s3-binary-cache-store.cc [hunk 4]
```diff
@@ -352,29 +412,57 @@ struct S3BinaryCacheStoreImpl : virtual S3BinaryCacheStoreConfig, public virtual
...
+                act.progress(bytesSent, size);
+            });
+
+            request.SetContinueRequestHandler([](const Aws::Http::HttpRequest*) {
+                bool cont = false;
+                try {
+                    checkInterrupt();
+                    cont = true;
+                } catch(...) {}
+                return cont;
```
Comment (edolstra) [inline src/libstore/s3-binary-cache-store.cc:463]: Idem

**Review by edolstra — APPROVED** [review]
LGTM except for some small comments.
