### PR TITLE
SourcePath::resolveSymlinks(): Fix handling of symlinks that start with '..'

### LINKED ISSUE #8437: [2.16 regression] "Infinite symlink recursion" when evaluating nixos-hardware
With the latest nixos-hardware revision (https://github.com/NixOS/nixos-hardware/commit/4cc688ee711159b9bcb5a367be44007934e1a49d):

```
❯ nix-shell -p nixVersions.nix_2_16 --run "nix eval --expr 'import ./common/pc/laptop/ssd' --impure"
error:
       … while calling the 'import' builtin

         at «string»:1:1:

            1| import ./common/pc/laptop/ssd
             | ^

       error: infinite symlink recursion in path '/home/k900/nixos-hardware/common/pc/laptop/ssd'
```

```
❯ nix-shell -p nixVersions.nix_2_15 --run "nix eval --expr 'import ./common/pc/laptop/ssd' --impure"
<LAMBDA>
```

### PR DESCRIPTION
**Pull request by edolstra**
# Motivation

Fixes #8437.

# Context

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [ ] agreed on idea
 - [ ] agreed on implementation strategy
 - [ ] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests - `tests/nixos/*`
 - [ ] documentation in the manual
 - [ ] documentation in the internal API docs
 - [ ] code and comments are self-explanatory
 - [ ] commit message explains why the change was made
 - [ ] new feature or incompatible change: updated release notes

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

### CODE REVIEW

File: src/libutil/canon-path.hh [hunk 1]
```diff
@@ -174,6 +174,14 @@ public:
      */
     void extend(const CanonPath & x);
 
+    /**
+     * "Apply" a string representation of a path to this one. If `s`
+     * is an absolute path, it replaces `this`. Otherwise, it is
+     * appended to this, where `..` components cause the previous
+     * component to be removed.
+     */
+    void apply(std::string_view s);
```
Comment (roberth) [inline src/libutil/canon-path.hh:183]:
```suggestion
    void asBaseResolve(std::string_view s);
```

`foo.asBaseResolve`: treat foo as a base and resolve the argument.

**Comment by infinisil** [comment]
Can you also add a test case to prevent against this bug in the future?

**Comment by edolstra** [comment]
Added a test.
