### PR TITLE
upgrade-nix: fix profile symlink resolution

### LINKED ISSUE #15437: upgrade-nix produces error: path "/nix/var/nix/profiles/default" is not in the Nix store
Hello all, I'm encountering a new error attempting to run `sudo -i nix upgrade-nix` after a fresh NixOS/nix-installer run:

Nix Version: 2.34.0

```
~ % nix --version
nix (Nix) 2.34.0
```

Running upgrade-nix results in `error: path "/nix/var/nix/profiles/default" is not in the Nix store`

```
~ % sudo -i nix upgrade-nix --verbose
found Nix in "/nix/var/nix/profiles/default/bin"
found profile "/nix/var/nix/profiles/default"
error: path "/nix/var/nix/profiles/default" is not in the Nix store
```

But I can resolve the symlink to a /nix/store directory containing the current `nix` executable:

```
~ % realpath /nix/var/nix/profiles/default
/nix/store/zmb87s02w8g3n58ri45px65k2lw97rfn-user-environment
~ % /nix/store/zmb87s02w8g3n58ri45px65k2lw97rfn-user-environment/bin/nix --version
nix (Nix) 2.34.0
```

<details>
  <summary>System: M2 macOS 15.5; See more details...</summary>

System: M2 macOS 15.5

```
~ % system_profiler SPSoftwareDataType SPHardwareDataType | grep -vE 'UUID|UDID|Serial|User|Computer'
Software:

    System Software Overview:

      System Version: macOS 15.5 (24F74)
      Kernel Version: Darwin 24.5.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 8 days, 18 hours, 10 minutes

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: Mac14,10
      Model Number: MNWC3LL/A
      Chip: Apple M2 Pro
      Total Number of Cores: 12 (8 performance and 4 efficiency)
      Memory: 16 GB
      System Firmware Version: 11881.121.1
      OS Loader Version: 11881.121.1
      Activation Lock Status: Disabled
```

Installer Receipt:

```
~ % jq '{version: .version, planner: .planner}' /nix/receipt.json
{
  "version": "2.34.0",
  "planner": {
    "planner": "macos",
    "settings": {
      "modify_profile": false,
      "nix_build_group_name": "nixbld",
      "nix_build_group_id": 350,
      "nix_build_user_prefix": "_nixbld",
      "nix_build_user_count": 32,
      "nix_build_user_id_base": 350,
      "ssl_cert_file": null,
      "extra_conf": [
        {
          "String": "trusted-users = root allonhadaya\nextra-experimental-features = nix-command flakes\nalways-allow-substitutes = true\nmax-jobs = auto\nextra-nix-path = nixpkgs=flake:nixpkgs"
        }
      ],
      "force": false,
      "skip_nix_conf": false,
      "add_channel": false
    },
    "encrypt": null,
    "case_sensitive": false,
    "volume_label": "Nix Store",
    "root_disk": "disk3"
  }
}
```

</details>

### PR DESCRIPTION
**Pull request by amaanq**
## Motivation

`canonPath(profileDir, true)` (which resolves symlinks) was converted
to `canonPath(profileDir)` (which doesn't) in a5a25626, so the profile
path was never resolved to its store target. This is fixed by using
`store->followLinksToStorePath` instead.

The while loop that attempted to chase symlinks into `/profiles/` is
removed. It called `readLink`, which returns relative targets for
`nix-env` generation links (e.g. `.local-1-link`), crashing `canonPath`
with "not an absolute path". The loop is also unnecessary now that
`followLinksToStorePath` is used, since it resolves the full symlink
chain to the store path regardless of whether the profile is under
`/profiles/`.

A NixOS VM test was added, which is based on nixpkgs' `nixosTests.nix-upgrade`,
with three variants; one for stable, latest, and current.

## Context

- Fixes #15437

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by xokdvium** [comment]
Would be nice to have some nixos upgrade tests in hydra...

**Comment by xokdvium** [comment]
Let's instead use a much better end-to-end test from nixpkgs: `nixosTests.nix-upgrade` (if that's possible). We can just import the file `nixos/tests/nix/upgrade.nix`. Frankly this test is absolutely useless (forgive me if I'm being harsh, but frankly this LLM nonsense is becoming annoying).

File: src/nix/upgrade-nix.cc [hunk 1]
```diff
@@ -157,15 +157,20 @@ struct CmdUpgradeNix : MixDryRun, StoreCommand
...
-        // Resolve profile to /nix/var/nix/profiles/<name> link.
-        while (canonPath(profileDir).string().find("/profiles/") == std::string::npos
-               && std::filesystem::is_symlink(profileDir))
-            profileDir = readLink(profileDir);
+        // Resolve profile to /nix/var/nix/profiles/<name> link,
+        // so that nix-env operates on the real profile path.
+        // For profiles not under /profiles/ (e.g. /root/.local),
+        // the path is used directly.
+        if (std::filesystem::is_symlink(profileDir)) {
+            auto target = std::filesystem::read_symlink(profileDir);
```
Comment (xokdvium) [inline src/nix/upgrade-nix.cc]:
```suggestion
            auto target = readLink (profileDir);
```

File: src/nix/upgrade-nix.cc [hunk 2]
```diff
@@ -157,15 +157,8 @@ struct CmdUpgradeNix : MixDryRun, StoreCommand
 
         auto profileDir = where.parent_path();
 
-        // Resolve profile to /nix/var/nix/profiles/<name> link.
-        while (canonPath(profileDir).string().find("/profiles/") == std::string::npos
```
Comment (Ericson2314) [inline src/nix/upgrade-nix.cc:161]: should use `std::filesystem::path` iterator and look for `"profiles"`, so we don't assume `/` or `\` on windows.

Comment (amaanq) [reply src/nix/upgrade-nix.cc:161]: done in 7e6ab52

File: src/nix/upgrade-nix.cc [hunk 3]
```diff
@@ -157,14 +165,13 @@ struct CmdUpgradeNix : MixDryRun, StoreCommand
...
-
-        printInfo("found profile %s", PathFmt(profileDir));
-
-        auto userEnv = canonPath(profileDir);
+        // Chase symlinks until we find a path under a "profiles"
+        // directory, or we run out of symlinks.
+        auto resolved = profileDir;
+        while (!hasProfilesComponent(resolved) && std::filesystem::is_symlink(resolved))
+            // Note that operator/ replaces lhs when rhs is absolute.
+            resolved = resolved.parent_path() / readLink(resolved);
```
Comment (xokdvium) [inline src/nix/upgrade-nix.cc]: Ah can we also add a `canonPath`

File: src/nix/upgrade-nix.cc [hunk 4]
```diff
@@ -157,14 +165,13 @@ struct CmdUpgradeNix : MixDryRun, StoreCommand
...
-               && std::filesystem::is_symlink(profileDir))
-            profileDir = readLink(profileDir);
-
-        printInfo("found profile %s", PathFmt(profileDir));
-
-        auto userEnv = canonPath(profileDir);
+        // Chase symlinks until we find a path under a "profiles"
+        // directory, or we run out of symlinks.
+        auto resolved = profileDir;
+        while (!hasProfilesComponent(resolved) && std::filesystem::is_symlink(resolved))
```
Comment (Ericson2314) [inline src/nix/upgrade-nix.cc]:
```suggestion
        while (!hasProfilesComponent(canonPath(resolved)) && std::filesystem::is_symlink(resolved))
```
