### PR TITLE
Use a union source accessor to put chroot stores in the logical location

### LINKED ISSUE #11503: `builtins.path` and `builtins.filterSource` use wrong filter paths with `--store` argument
**Describe the bug**

The built-in functions `builtins.path` or `builtins.filterSource` both accept a root path and a filter function.  The filter function is then called with subpaths of the root path as argument.  Under certain circumstances, those subpaths are in fact *not* subpaths of the root path.  As far as I could investigate, this happens if

*   the `--store` argument is used to point to another store that is not the "canonical" store ("canonical" usually is `/nix/store`),
*   the nix file that is evaluate and that contains the call to a built-in function is itself positioned in the "canonical" nix store,
*   the root directory points to `./.`, and
*   the derivation that contains the nix file is also present in the other nix store.

Note that these circumstances are usually given when you install NixOS from a live iso with `nixos-install`: Most nix files involved are contained in the `nixos` channel, which is somewhere in `/nix/store`.  This channel is copied to `/mnt/nix/store` by `nixos-install` before anything else is done.

**Steps To Reproduce**

Put these two files in the same directory, then execute `test.sh` (this expects Nix to be installed and accessible, but no root privileges):

<details>
  <summary><code>test.nix</code></summary>

```nix
let
  root = ./.;
  filter = path: type:
    let
      rootStr = builtins.toString ./.;
    in
      if builtins.substring 0 (builtins.stringLength rootStr) (builtins.toString path) == rootStr then true
      else builtins.throw "root path\n${rootStr}\nnot prefix of path\n${builtins.toString path}";
in

# each one will demonstrate the problem!:
#builtins.path { name="name"; path=root; inherit filter; }
builtins.filterSource filter root
```
</details>

<details>
<summary><code>test.sh</code></summary>

```shell
#! /usr/bin/env bash
tmpdir=$(mktemp -d)
mkdir $tmpdir/directory
cp test.nix $tmpdir/directory/default.nix
result=$(nix-store --add-fixed --recursive sha256 $tmpdir/directory)
nix-instantiate --eval $result
nix-instantiate --eval $result --store $tmpdir/2nd-store
nix-store --add-fixed --recursive sha256 $tmpdir/directory --store $tmpdir/2nd-store
echo this will fail...
nix-instantiate --eval $result --store $tmpdir/2nd-store
```
</details>

The final `nix-instantiate` will trigger the `throw` from `text.nix` -- apparently `filterSource` confuses the store paths:

```
error: root path
/nix/store/dv15ix385vx19wxac0v5h5n7x8i5iwgp-directory
not prefix of path
/tmp/tmp.f3xsGxSb42/2nd-store/nix/store/dv15ix385vx19wxac0v5h5n7x8i5iwgp-directory/default.nix
```

**Expected behavior**

The final `nix-instantiate` invocation should succeed.

**`nix-env --version` output**

nix-env (Nix) 2.18.5

**Additional context**

Nixpkgs contains many instances of `src = lib.fileset.toSouce { root = ./.; fileset = ..something..; }` which are liable to trigger this bug if evaluated from within `nixos-install`; in that case `src` ends up as empty directory because the filter function from the fileset library constantly returns `false`.  One such instance is documented (with steps to reproduce with `nixos-install`) in https://github.com/NixOS/nixpkgs/issues/334098 .

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by edolstra**
## Motivation

When using a chroot store, paths that are in the chroot store (such as those resulting from IFD or similar) should be represented in the evaluator using their logical path (e.g. `/nix/store/foo`), not their physical path (e.g. `/tmp/chroot/nix/store/foo`). This PR does that - it removes all uses of `toRealPath()` in the evaluator. To make chroot stores still work, the physical store path is "mounted" onto the logical store location of `rootFS`. And to handle the case where we also need to access a file in the *real* `/nix/store`, we use a union source accessor that provides a union view of the two stores.

Fixes #11503.

## Context

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

File: src/libexpr/eval.hh [hunk 1]
```diff
@@ -389,6 +394,18 @@ public:
      */
     SourcePath rootPath(PathView path);
 
+    /**
+     * Convert `s` to a path. If `context` is not empty, the resulting
+     * path will use the `storeFS` accessor; otherwise it will use
+     * `rootFS`. When using a chroot store, this allows us to
+     * distinguish between store paths resulting from
+     * import-from-derivation and sources stored in the actual
+     * /nix/store.
```
Comment (roberth) [inline src/libexpr/eval.hh:403]: I'd like to elaborate this a bit, to more clearly define the two scenarios.

I think "passed to this function after their string context is realised." is also important.

```suggestion
     * Convert `s` to a path. If `context` is not empty, the resulting
     * path will use the `storeFS` accessor; otherwise it will use
     * `rootFS`. 
     * This allows us to eagerly distinguish between two similar
     * locations that are possibly referred to by `storeDir` when using
     * a chroot store:
     * - /nix/store as a logical location, the prefix of store references,
     *   which is physically located at some different path
     * - /nix/store as a physical location, that happens to start with
     *   `storeDir`, and which is not even accessed as a store.
     *
     * The logic store path strings are initially produced by functions that return store path
     * strings, such as `derivation` or `builtins.filterSource` and then passed
     * to this function after their string context is realised.
     *
     * The physical path strings generally originate from the CLI or expressions
     * that evaluate in impure mode.
     *
     * The presence of a string context lets us determine whether such a string
     * is a logical or physical path, and we use that info to eagerly return the a
     * `SourcePath` with the correct accessor.
```

File: src/libexpr/paths.cc [hunk 2]
```diff
@@ -12,4 +13,10 @@ SourcePath EvalState::rootPath(PathView path)
     return {rootFS, CanonPath(absPath(path))};
 }
 
+SourcePath EvalState::stringWithContextToPath(std::string_view s, const NixStringContext & context)
+{
+    auto path = CanonPath(s);
+    return !context.empty() ? SourcePath{storeFS, std::move(path)} : rootPath(std::move(path));
```
Comment (roberth) [inline src/libexpr/paths.cc:19]: This should probably validate two rules:

- If it has a context, it needs to start with storeDir. (otherwise, we're probably looking at a script or data with a reference)
- The string needs to be an absolute path. It looks like `rootPath(CanonPath)` just eats garbage if not absolute, and the other overload would be worse, using the process' working directory.

**Comment by infinisil** [comment]
I believe this does fix the problem! Though when I tried it out, the installer test failed with a different issue:

```
$ nixos-rebuild switch
error: path '/nix/var/nix/profiles/per-user/root/channels' is a symlink
```

<details><summary>full error</summary>

```
subtest: Check whether nixos-rebuild works
target: must succeed: nixos-rebuild switch >&2
target # building Nix...
target # building the system configuration...
target # error:
target #        … while calling the 'head' builtin
target #          at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/attrsets.nix:1:35738:
target #        … while evaluating the attribute 'value'
target #          at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/modules.nix:1:35221:
target #        … while evaluating the option `system.build.toplevel':
target # 
target #        … while evaluating definitions from `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/activation/top-level.nix':
target # 
target #        … while evaluating the option `system.systemBuilderArgs':
target # 
target #        … while evaluating definitions from `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/activation/activatable-system.nix':
target # 
target #        … while evaluating the option `system.activationScripts.etc.text':
target # 
target #        … while evaluating definitions from `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/etc/etc-activation.nix':
target # 
target #        … while evaluating definitions from `/nix/var/nix/profiles/per-user/root/channels/nixos/nixos/modules/system/etc/etc.nix':
target # 
target #        … while evaluating the option `environment.etc.dbus-1.source':
target # 
target #        (stack trace truncated; use '--show-trace' to show the full, detailed trace)
target # 
target #        error: path '/nix/var/nix/profiles/per-user/root/channels' is a symlink
target: output: 
Test "Check whether nixos-rebuild works" failed with error: "command `nixos-rebuild switch >&2` failed (exit code 1)"
cleanup
kill machine (pid 91)
qemu-system-x86_64: terminating on signal 15 from pid 8 (/nix/store/0l539chjmcq5kdd43j6dgdjky4sjl7hl-python3-3.12.8/bin/python3.12)
kill vlan (pid 9)
(finished: cleanup, in 0.03 seconds)
error: builder for '/nix/store/skx3rv9y9mk98r8a2r42lwr0hlcn5nks-vm-test-run-installer-simpleUefiSystemdBoot.drv' failed with exit code 1;
```

</details>

To test this I used
```
nix-build -A nixosTests.installer.simpleUefiSystemdBoot
```
with following (non-reproducible) diff (which includes changing the Nix version for the test, and reverts https://github.com/NixOS/nixpkgs/pull/369459) on a recent Nixpkgs version:

<details><summary>diff</summary>

```patch
diff --git a/nixos/tests/installer.nix b/nixos/tests/installer.nix
index 6be3346d9850..4b4e12ccd73b 100644
--- a/nixos/tests/installer.nix
+++ b/nixos/tests/installer.nix
@@ -761,6 +761,7 @@ let
               ++ optionals clevisTest [ pkgs.klibc ]
               ++ optional systemdStage1 pkgs.chroot-realpath;
 
+            nix.package = (builtins.getFlake "github:DeterminateSystems/nix-src/store-fs").outputs.packages.x86_64-linux.default;
             nix.settings = {
               substituters = mkForce [ ];
               hashed-mirrors = null;
diff --git a/pkgs/by-name/ni/nixos-firewall-tool/package.nix b/pkgs/by-name/ni/nixos-firewall-tool/package.nix
index b928487c5277..a5493d495876 100644
--- a/pkgs/by-name/ni/nixos-firewall-tool/package.nix
+++ b/pkgs/by-name/ni/nixos-firewall-tool/package.nix
@@ -6,10 +6,13 @@
   shellcheck-minimal,
 }:
 
-stdenvNoCC.mkDerivation {
+stdenvNoCC.mkDerivation rec {
   name = "nixos-firewall-tool";
 
-  src = builtins.filterSource (name: _: !(lib.hasSuffix ".nix" name)) ./.;
+  src = lib.fileset.toSource {
+    root = ./.;
+    fileset = lib.fileset.fileFilter (file: !file.hasExt "nix") ./.;
+  };
 
   strictDeps = true;
   buildInputs = [ bash ];
```

</details>

**Comment by edolstra** [comment]
@infinisil Hm, that sounds a lot like https://github.com/NixOS/nix/issues/12339.

**Comment by edolstra** [comment]
The tests do expose a problem with `rootFS` and `storeFS` not being equal, e.g.
```
error: lib.fileset.intersect: Expected file sets to have the same filesystem root, but first argument has root "/" while second argument has root "/".
```
and
```
error: lib.path.hasStorePathPrefix: Argument has a filesystem root (/) that's not /, which is currently not supported.
```

I suppose we can add a hack to make the root of `storeFS` equal to the root of `rootFS`...

**Comment by roberth** [comment]
An alternate solution is to mount the logical store as an overlay-mounted onto `rootFS`.
That solves the equality problem (the combined overlay accessor is the only evaluator-facing fs) and it might also solve problems that aren't solved by the string context-based eager decision.
We don't have overlay-mounting logic yet, but we'd only need overlayability for one directory, and it can be shallow, if that helps. Or something that simply only works for store mounts.

**Comment by edolstra** [comment]
> An alternate solution is to mount the logical store as an overlay-mounted onto rootFS.

That wouldn't work for the case where we're accessing files in both the physical and logical Nix store. For instance, the test case in #11503 is evaluating a `default.nix` in the real `/nix/store`, while writing/accessing stuff from the chroot store.

File: src/libexpr/paths.cc (hunk 2 above)
Comment (edolstra) [reply src/libexpr/paths.cc:19]: Unfortunately, this runs into a problem: `EvalState::mkOutputStringRaw()` produces paths that don't include `/nix/store` for some reason (e.g. `/125qgp92...`). (It renders a `DownstreamPlaceholder` and to be honest I don't know what that is...)

@Ericson2314 Apparently in 3a7b330b64c6ea77e18a0a96aad7fb14947382d9 you removed the store prefix from these paths. Do you remember why that is? It seems wrong, since generally we only want to rewrite hashes and not change the lengths of strings.

**Comment by roberth** [comment]
It would have to be an _overlay_ mount, not a normal mount. That way you get a store path from either of the underlying file systems. I don't think we need to care about which one, as long as it can find a path that exists.

I suppose it might resolve a store path to the wrong fs, if it exists in both, which might be weird if it's an input addressed path with an impurity, or when it picks the one on a worse file system (e.g. case insensitive), but besides those corner cases, it seems like it'd be pretty good at picking a path that exists.

File: src/libexpr/paths.cc (hunk 2 above)
Comment (roberth) [reply src/libexpr/paths.cc:19]: - https://github.com/NixOS/nix/issues/12361

File: src/libutil/union-source-accessor.cc [hunk 3]
```diff
@@ -0,0 +1,82 @@
+#include "source-accessor.hh"
+
+namespace nix {
+
+struct UnionSourceAccessor : SourceAccessor
```
Comment (roberth) [inline src/libutil/union-source-accessor.cc:5]: This seems to be not a well-behaved `SourceAccessor`
- a single path can contain simultaneously file contents, a directory listing, and a link target
- a subpath of a file or symlink can exist

These will only be noticeable in corner cases, I presume, but we'll want that fixed.

File: src/libexpr/eval.cc [hunk 4]
```diff
@@ -246,15 +246,37 @@ EvalState::EvalState(
...
+            auto accessor = getFSSourceAccessor();
+
+            /* If we have a chroot store, make a union accessor to
+               make the chroot store available at its logical location
+               while still having the underlying directory
+               available. This is necessary for instance if we're
+               evaluating a file from the physical /nix/store while
+               using a chroot store. */
+            auto realStoreDir = dirOf(store->toRealPath(StorePath::dummy));
+            if (store->storeDir != realStoreDir) {
```
Comment (roberth) [inline src/libexpr/eval.cc:259]: I think we'll want this always
- for simplicity
- in order to expose chroot-store bugs sooner
- in preparation for other stores, e.g. an in-memory or write caching store wrapper for performance
- eventually for https://github.com/NixOS/nix/issues/9319

```suggestion
```

If we're not confident, I'd want a flag to make it unconditional so the team and any other volunteers can dogfood it.

File: src/libutil/union-source-accessor.cc (hunk 3 above)
Comment (edolstra) [reply src/libutil/union-source-accessor.cc:5]: Okay, I've removed the check on the file type. So now the first underlying file that exists determines what operations are allowed.

File: src/libexpr/eval.cc (hunk 4 above)
Comment (edolstra) [reply src/libexpr/eval.cc:259]: The test suite succeeds with this enabled unconditionally, but performance I don't think we should always enable it. For instance, every `maybeLstat()` call will now result in two `maybeLstat()` calls to the underlying accessors if the file doesn't exist. Though since `PosixSourceAccessor` has some caching it's probably not too bad.

File: src/libexpr/eval.cc [hunk 5]
```diff
@@ -246,15 +246,37 @@ EvalState::EvalState(
...
+                auto storeFS = makeMountedSourceAccessor(
+                    {
+                        {CanonPath::root, makeEmptySourceAccessor()},
+                        {CanonPath(store->storeDir), makeFSSourceAccessor(realStoreDir)}
+                    });
+                accessor = makeUnionSourceAccessor({accessor, storeFS});
+            }
```
Comment (Ericson2314) [inline src/libexpr/eval.cc:266]: Why can we not use `getFSSourceAccessor` for this? Also I want `getFSSourceAccessor` to be rooted int the store dir. I don't like all these "union in place" things that both this and `getFSSourceAccessor` do. I want to do `CanonPath(storePath.to_string())` and have that just work with `storeFS` (note that the canon path will be e.g. `w4l4xvw461ywc4ia3accj5i3hh50n4r8-nix-2.24.1` in this case.

Comment (Ericson2314) [reply src/libexpr/eval.cc:266]: CC @puffnfresh who I have been talking to about this same stuff

**Comment by edolstra** [comment]
@infinisil I think that error is coming from Nix 2.24.12, since that's the installed NixOS system in the VM has.

**Comment by Ericson2314** [comment]
Nix Meeting #214 notes:

- Long intricate discussion.

- Conclusion: @edolstra will try avoid the `UnionSourceAccessor` in pure mode

----

Some thoughts from me, paraphrasing the long discussion:

I like this path a lot. Here is my thinking:

Background: I like designs which are more `openfd` / capability-flavored, and I don't like global ambient authority with union/overlay and bind/shadowing mounts --- I think the mounting tricks are a poor substitute for just not having the ambient authority at all.

I think that whatever we do for this bug fix would be tantamount to an instant-stable experimental feature. So I was concerned to have in all code-paths a complex mounting-based fix. This would be more design debt in the name of back-compat getting us further way from a nice capability-based design.

At the same time, @edolstra convinced me that *not* doing the union mechanism was unworkable breakage in the general case. The issue is I had forgotten about `coerceToPath` --- in other words, I had forgotten that there are, thanks to coercions, many more ways to create path values that path literals (and, someday `builtins.fetchTree`). This means that, like it or not, there are tons of ways to get in-store and in-root-filesystem paths today, and those path values need to stay comperable

However, in the pure-eval case, we don't do arbitrary file access. So while we still have the situation of many path values within the store, we *only* have that situation --- not arbitrary root-FS paths. That means that --- for somewhat opposite reasons than I initially realized --- we *can* without breakage avoid a union FS in the pure-eval case.

This make me quite happy that we can achieve all goals:

1. Impure eval doesn't break. Full stop.

2. Impure eval works better with `--store`, and to the extent I don't like the solution, it's impure eval's fault, not `--store`'s fault.

3. Pure eval doesn't get sullied by any of this

4. Pure eval is, in implementation, in fact better than before. (We could have previously outright denied it root fs access, but we hadn't done so. Now we have.) Not only is this not more tech debt in the name of back-compat (as I feared), it *less*,

5. While pure eval is not all the way to a full capability-based workflow (e.g. carefully crafted absolute path literals in conjunction with tricks that exploit the fact that store path white-listing is an effect are possible), it is taking a significant step in that direction.

So in conclusion, horray! I was quite nervous about all this, and now I feel quite the opposite :).

File: src/libexpr/primops.cc [hunk 6]
```diff
@@ -2485,15 +2484,7 @@ static void addPath(
...
             auto rewrites = state.realiseContext(context);
-            path = {state.rootFS, CanonPath(state.toRealPath(rewriteStrings(path.path.abs(), rewrites), context))};
-
-            try {
-                auto [storePath, subPath] = state.store->toStorePath(path.path.abs());
-                // FIXME: we should scanForReferences on the path before adding it
-                refs = state.store->queryPathInfo(storePath)->references;
-                path = {state.rootFS, CanonPath(state.store->toRealPath(storePath) + subPath)};
-            } catch (Error &) { // FIXME: should be InvalidPathError
-            }
```
Comment (Ericson2314) [inline src/libexpr/primops.cc:2496]: Is the idea that `refs` is unused? If so, let's also delete the variable above? If not... what's going on?

**Review by Ericson2314 — COMMENTED** [review]
Looks good modulo the one question

(all but approval :))

File: src/libexpr/primops.cc (hunk 6 above)
Comment (Ericson2314) [reply src/libexpr/primops.cc:2496]: This is a regression in....ea38605d116e1c8db55a8a8cb7400724b931458d?

Comment (edolstra) [reply src/libexpr/primops.cc:2496]: Yeah this appears to be dead code. I think the idea was to propagate the references, but that "feature" was never really well thought out. Maybe we should warn/fail if the path has references...

Comment (Ericson2314) [reply src/libexpr/primops.cc:2496]: We can investigate what happened here later. IIRC there was some regressions with this too.

**Review by Ericson2314 — APPROVED** [review]

**Comment by ElvishJerricco** [comment]
@infinisil btw I tested this with the nixpkgs installer test using these changes: https://github.com/NixOS/nixpkgs/compare/master...ElvishJerricco:nixpkgs:push-uysonulrlluq

I reverted the nixos-firewall-tools filesets thing and changed the revision of nix 2.26 to this merge revision, but I had to also add the nix package's `buildInputs` to the installer's `extraDependencies`. Due to the `nix_2_26` attr itself only being a `buildEnv`, it has `preferLocalBuild = true;`, which means the installation target needs to build the `buildEnv` itself, including building / substituting all its `buildInputs`. Thanks to [the `checkInputs` in the `overrideAttrs` on the `buildEnv` in the `nix-everything` expression](https://github.com/NixOS/nixpkgs/blob/91cdf52f90827cc411116b3784f46ef3a536db75/pkgs/tools/package-management/nix/2_26/packaging/everything.nix#L143-L147), that includes some test derivations that have no output files and therefore are not linked in the `buildEnv` output and therefore not in the installer. Since the empty outputs are considered `buildInputs` to the `nix_2_26` derivation, these test derivations need to be built on the target, which is not possible because the inputs necessary to build them are not in the installer.

That's why you got that error. Adding `nix_2_26.buildInputs` to `extraDependencies` in order to have the empty test outputs in the installer fixes it. And indeed this PR has resolved the issue with filesets breaking installer tests.
