### PR TITLE
Fix missing GC root in zipAttrsWith

### LINKED ISSUE #11547: Inconsistent segfaults in `concatLists` during evaluation
First reported by [@mightyiam on Matrix](https://matrix.to/#/#nix-dev:nixos.org/$DCo38fDqytqjnhemwihUNU1eB20v5GgtBUqdTyJw7PA) with stack trace:

```
Program terminated with signal SIGSEGV, Segmentation fault.                                                                                                 18:49:24 [115/305]
#0  0x00007fe04df5156d in nix::EvalState::concatLists(nix::Value&, unsigned long, nix::Value* const*, nix::PosIdx, std::basic_string_view<char, std::char_traits<char> >) ()
   from /nix/store/xsjggjrd33cbm5szga29c843i2vhr79j-nix-2.24.6/lib/libnixexpr.so
[Current thread is 1 (Thread 0x7fe04b6f54c0 (LWP 2759193))]
(gdb) bt
#0  0x00007fe04df5156d in nix::EvalState::concatLists(nix::Value&, unsigned long, nix::Value* const*, nix::PosIdx, std::basic_string_view<char, std::char_traits<char> >) ()
   from /nix/store/xsjggjrd33cbm5szga29c843i2vhr79j-nix-2.24.6/lib/libnixexpr.so
#1  0x00007fe04dfa8d64 in nix::prim_concatLists(nix::EvalState&, nix::PosIdx, nix::Value**, nix::Value&) [clone .lto_priv.0] ()
   from /nix/store/xsjggjrd33cbm5szga29c843i2vhr79j-nix-2.24.6/lib/libnixexpr.so
#2  0x00007fe04df4e9aa in nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) ()
   from /nix/store/xsjggjrd33cbm5szga29c843i2vhr79j-nix-2.24.6/lib/libnixexpr.so
#3  0x00007fe04df50f0b in nix::ExprSelect::eval(nix::EvalState&, nix::Env&, nix::Value&) () from /nix/store/xsjggjrd33cbm5szga29c843i2vhr79j-nix-2.24.6/lib/libnixexpr.so
#4  0x00007fe04df505b9 in nix::ExprVar::eval(nix::EvalState&, nix::Env&, nix::Value&) () from /nix/store/xsjggjrd33cbm5szga29c843i2vhr79j-nix-2.24.6/lib/libnixexpr.so
#5  0x00007fe04df4b687 in nix::ExprOpEq::eval(nix::EvalState&, nix::Env&, nix::Value&) () from /nix/store/xsjggjrd33cbm5szga29c843i2vhr79j-nix-2.24.6/lib/libnixexpr.so
#6  0x00007fe04df4c856 in nix::EvalState::evalBool(nix::Env&, nix::Expr*, nix::PosIdx, std::basic_string_view<char, std::char_traits<char> >) ()
   from /nix/store/xsjggjrd33cbm5szga29c843i2vhr79j-nix-2.24.6/lib/libnixexpr.so
#7  0x00007fe04df4c9d5 in nix::ExprIf::eval(nix::EvalState&, nix::Env&, nix::Value&) () from /nix/store/xsjggjrd33cbm5szga29c843i2vhr79j-nix-2.24.6/lib/libnixexpr.so
#8  0x00007fe04df50dce in nix::ExprSelect::eval(nix::EvalState&, nix::Env&, nix::Value&) () from /nix/store/xsjggjrd33cbm5szga29c843i2vhr79j-nix-2.24.6/lib/libnixexpr.so
#9  0x00007fe04df4e792 in nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) ()
   from /nix/store/xsjggjrd33cbm5szga29c843i2vhr79j-nix-2.24.6/lib/libnixexpr.so
#10 0x00007fe04df50f0b in nix::ExprSelect::eval(nix::EvalState&, nix::Env&, nix::Value&) () from /nix/store/xsjggjrd33cbm5szga29c843i2vhr79j-nix-2.24.6/lib/libnixexpr.so
#11 0x00007fe04dfaadf5 in nix::prim_map(nix::EvalState&, nix::PosIdx, nix::Value**, nix::Value&) [clone .lto_priv.0] ()
   from /nix/store/xsjggjrd33cbm5szga29c843i2vhr79j-nix-2.24.6/lib/libnixexpr.so
#12 0x00007fe04df4e9aa in nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) ()
   from /nix/store/xsjggjrd33cbm5szga29c843i2vhr79j-nix-2.24.6/lib/libnixexpr.so
#13 0x00007fe04df5272c in nix::ExprCall::eval(nix::EvalState&, nix::Env&, nix::Value&) () from /nix/store/xsjggjrd33cbm5szga29c843i2vhr79j-nix-2.24.6/lib/libnixexpr.so
#14 0x00007fe04df4e792 in nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) ()
   from /nix/store/xsjggjrd33cbm5szga29c843i2vhr79j-nix-2.24.6/lib/libnixexpr.so
#15 0x00007fe04df5272c in nix::ExprCall::eval(nix::EvalState&, nix::Env&, nix::Value&) () from /nix/store/xsjggjrd33cbm5szga29c843i2vhr79j-nix-2.24.6/lib/libnixexpr.so
#16 0x00007fe04df4e792 in nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) ()
   from /nix/store/xsjggjrd33cbm5szga29c843i2vhr79j-nix-2.24.6/lib/libnixexpr.so
#17 0x00007fe04df516cc in nix::EvalState::concatLists(nix::Value&, unsigned long, nix::Value* const*, nix::PosIdx, std::basic_string_view<char, std::char_traits<char> >) ()
   from /nix/store/xsjggjrd33cbm5szga29c843i2vhr79j-nix-2.24.6/lib/libnixexpr.so
#18 0x00007fe04dfa8d64 in nix::prim_concatLists(nix::EvalState&, nix::PosIdx, nix::Value**, nix::Value&) [clone .lto_priv.0] ()
   from /nix/store/xsjggjrd33cbm5szga29c843i2vhr79j-nix-2.24.6/lib/libnixexpr.so
#19 0x00007fe04df4e9aa in nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) ()
```

Then [hit again on Hydra](https://hydra.nixos.org/build/273031249/nixlog/6) with (demangled) stack trace

```
installer # #0  0x00007f5570ffd56d nix::EvalState::concatLists(nix::Value&, unsigned long, nix::Value* const*, nix::PosIdx, std::basic_string_view<char, std::char_traits<char> >) (libnixexpr.so   0x9656d)
installer # #1  0x00007f5571054d64 nix::prim_concatLists(nix::EvalState&, nix::PosIdx, nix::Value**, nix::Value&).lto_priv.0 (libnixexpr.so   0xedd64)
installer # #2  0x00007f5570ffa9aa nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) (libnixexpr.so   0x939aa)
installer # #3  0x00007f5570ffcf0b nix::ExprSelect::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x95f0b)
installer # #4  0x00007f5570ffc5b9 nix::ExprVar::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x955b9)
installer # #5  0x00007f5570ff7687 nix::ExprOpEq::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x90687)
installer # #6  0x00007f5570ff8856 nix::EvalState::evalBool(nix::Env&, nix::Expr*, nix::PosIdx, std::basic_string_view<char, std::char_traits<char> >) (libnixexpr.so   0x91856)
installer # #7  0x00007f5570ff89d5 nix::ExprIf::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x919d5)
installer # #8  0x00007f5570ffcdce nix::ExprSelect::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x95dce)
installer # #9  0x00007f5570ffa792 nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) (libnixexpr.so   0x93792)
installer # #10 0x00007f5570ffcf0b nix::ExprSelect::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x95f0b)
installer # #11 0x00007f5571056df5 nix::prim_map(nix::EvalState&, nix::PosIdx, nix::Value**, nix::Value&).lto_priv.0 (libnixexpr.so   0xefdf5)
installer # #12 0x00007f5570ffa9aa nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) (libnixexpr.so   0x939aa)
installer # #13 0x00007f5570ffe72c nix::ExprCall::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x9772c)
installer # #14 0x00007f5570ffa792 nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) (libnixexpr.so   0x93792)
installer # #15 0x00007f5570ffe72c nix::ExprCall::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x9772c)
installer # #16 0x00007f5570ffa792 nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) (libnixexpr.so   0x93792)
installer # #17 0x00007f5570ffd6cc nix::EvalState::concatLists(nix::Value&, unsigned long, nix::Value* const*, nix::PosIdx, std::basic_string_view<char, std::char_traits<char> >) (libnixexpr.so   0x966cc)
installer # #18 0x00007f5571054d64 nix::prim_concatLists(nix::EvalState&, nix::PosIdx, nix::Value**, nix::Value&).lto_priv.0 (libnixexpr.so   0xedd64)
installer # #19 0x00007f5570ffa9aa nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) (libnixexpr.so   0x939aa)
installer # #20 0x00007f5570ffe72c nix::ExprCall::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x9772c)
installer # #21 0x00007f5570ffcdce nix::ExprSelect::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x95dce)
installer # #22 0x00007f5570ffa792 nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) (libnixexpr.so   0x93792)
installer # #23 0x00007f5570ffcf0b nix::ExprSelect::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x95f0b)
installer # #24 0x00007f5571056df5 nix::prim_map(nix::EvalState&, nix::PosIdx, nix::Value**, nix::Value&).lto_priv.0 (libnixexpr.so   0xefdf5)
installer # #25 0x00007f5570ffa9aa nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) (libnixexpr.so   0x939aa)
installer # #26 0x00007f5570ffe72c nix::ExprCall::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x9772c)
installer # #27 0x00007f5570ffa792 nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) (libnixexpr.so   0x93792)
installer # #28 0x00007f5570ffe72c nix::ExprCall::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x9772c)
installer # #29 0x00007f5570ffa792 nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) (libnixexpr.so   0x93792)
installer # #30 0x00007f5570ffd6cc nix::EvalState::concatLists(nix::Value&, unsigned long, nix::Value* const*, nix::PosIdx, std::basic_string_view<char, std::char_traits<char> >) (libnixexpr.so   0x966cc)
installer # #31 0x00007f5571054d64 nix::prim_concatLists(nix::EvalState&, nix::PosIdx, nix::Value**, nix::Value&).lto_priv.0 (libnixexpr.so   0xedd64)
installer # #32 0x00007f5570ffa9aa nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) (libnixexpr.so   0x939aa)
installer # #33 0x00007f5570ffe72c nix::ExprCall::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x9772c)
installer # #34 0x00007f5570ffcdce nix::ExprSelect::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x95dce)
installer # #35 0x00007f5570ff7757 nix::ExprOpNEq::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x90757)
installer # #36 0x00007f5570ff8856 nix::EvalState::evalBool(nix::Env&, nix::Expr*, nix::PosIdx, std::basic_string_view<char, std::char_traits<char> >) (libnixexpr.so   0x91856)
installer # #37 0x00007f5570ff8b1f nix::ExprOpAnd::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x91b1f)
installer # #38 0x00007f5570ff8856 nix::EvalState::evalBool(nix::Env&, nix::Expr*, nix::PosIdx, std::basic_string_view<char, std::char_traits<char> >) (libnixexpr.so   0x91856)
installer # #39 0x00007f5570ff89d5 nix::ExprIf::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x919d5)
installer # #40 0x00007f55710432e5 nix::prim_seq(nix::EvalState&, nix::PosIdx, nix::Value**, nix::Value&).lto_priv.0 (libnixexpr.so   0xdc2e5)
installer # #41 0x00007f5570ffad0e nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) (libnixexpr.so   0x93d0e)
installer # #42 0x00007f5570ffe72c nix::ExprCall::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x9772c)
installer # #43 0x00007f5570fe478d void nix::EvalState::forceAttrs<nix::EvalState::forceAttrs(nix::Value&, nix::PosIdx, std::basic_string_view<char, std::char_traits<char> >)::{lambda()#1}>(nix::Value&, nix::EvalState::forceAttrs(nix::Value&, nix::PosIdx, std::basic_string_view<char, std::char_traits<char> >)::{lambda()#1}, std::basic_string_view<char, std::char_traits<char> >) (libnixexpr.so   0x7d78d)
installer # #44 0x00007f5570ffcab7 nix::ExprSelect::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x95ab7)
installer # #45 0x000055a8884302e5 main_nix_build(int, char**).lto_priv.0 (nix   0xba2e5)
installer # #46 0x000055a8884cf0b0 nix::mainWrapped(int, char**) (nix   0x1590b0)
installer # #47 0x00007f5570dfec05 nix::handleExceptions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()>) (libnixmain.so   0x24c05)
installer # #48 0x000055a88841851c main (nix   0xa251c)
installer # #49 0x00007f557023b14e __libc_start_call_main (libc.so.6   0x2a14e)
installer # #50 0x00007f557023b209 __libc_start_main@@GLIBC_2.34 (libc.so.6   0x2a209)
installer # #51 0x000055a88841d1b5 _start (nix   0xa71b5)
```

Another possibly related issue [encountered by @lilyinstarlight in a GHA run](https://github.com/lilyinstarlight/foosteros/actions/runs/10822449565/job/30026445898#step:6:4654).

Some failed reproduction attempts by @lf- and @puckipedia on Matrix.

[Hydra again, this time aarch64-linux](https://hydra.nixos.org/build/273036630/nixlog/45), stack trace

```
installer # #0  0x0000ffffaa410824 nix::EvalState::concatLists(nix::Value&, unsigned long, nix::Value* const*, nix::PosIdx, std::basic_string_view<char, std::char_traits<char> >) (libnixexpr.so   0x70824)
installer # #1  0x0000ffffaa40d634 nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) (libnixexpr.so   0x6d634)
installer # #2  0x0000ffffaa40fea4 nix::ExprSelect::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x6fea4)
installer # #3  0x0000ffffaa40f564 nix::ExprVar::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x6f564)
installer # #4  0x0000ffffaa40a2ec nix::ExprOpEq::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x6a2ec)
installer # #5  0x0000ffffaa40b758 nix::EvalState::evalBool(nix::Env&, nix::Expr*, nix::PosIdx, std::basic_string_view<char, std::char_traits<char> >) (libnixexpr.so   0x6b758)
installer # #6  0x0000ffffaa40ba10 nix::ExprIf::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x6ba10)
installer # #7  0x0000ffffaa40fe24 nix::ExprSelect::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x6fe24)
installer # #8  0x0000ffffaa40d4c4 nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) (libnixexpr.so   0x6d4c4)
installer # #9  0x0000ffffaa40fea4 nix::ExprSelect::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x6fea4)
installer # #10 0x0000ffffaa46ae7c nix::prim_map(nix::EvalState&, nix::PosIdx, nix::Value**, nix::Value&).lto_priv.0 (libnixexpr.so   0xcae7c)
installer # #11 0x0000ffffaa40d634 nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) (libnixexpr.so   0x6d634)
installer # #12 0x0000ffffaa412040 nix::ExprCall::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x72040)
installer # #13 0x0000ffffaa40d4c4 nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) (libnixexpr.so   0x6d4c4)
installer # #14 0x0000ffffaa412040 nix::ExprCall::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x72040)
installer # #15 0x0000ffffaa40d4c4 nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) (libnixexpr.so   0x6d4c4)
installer # #16 0x0000ffffaa410954 nix::EvalState::concatLists(nix::Value&, unsigned long, nix::Value* const*, nix::PosIdx, std::basic_string_view<char, std::char_traits<char> >) (libnixexpr.so   0x70954)
installer # #17 0x0000ffffaa40d634 nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) (libnixexpr.so   0x6d634)
installer # #18 0x0000ffffaa412040 nix::ExprCall::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x72040)
installer # #19 0x0000ffffaa40fe24 nix::ExprSelect::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x6fe24)
installer # #20 0x0000ffffaa40d4c4 nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) (libnixexpr.so   0x6d4c4)
installer # #21 0x0000ffffaa40fea4 nix::ExprSelect::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x6fea4)
installer # #22 0x0000ffffaa46ae7c nix::prim_map(nix::EvalState&, nix::PosIdx, nix::Value**, nix::Value&).lto_priv.0 (libnixexpr.so   0xcae7c)
installer # #23 0x0000ffffaa40d634 nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) (libnixexpr.so   0x6d634)
installer # #24 0x0000ffffaa412040 nix::ExprCall::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x72040)
installer # #25 0x0000ffffaa40d4c4 nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) (libnixexpr.so   0x6d4c4)
installer # #26 0x0000ffffaa412040 nix::ExprCall::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x72040)
installer # #27 0x0000ffffaa40d4c4 nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) (libnixexpr.so   0x6d4c4)
installer # #28 0x0000ffffaa410954 nix::EvalState::concatLists(nix::Value&, unsigned long, nix::Value* const*, nix::PosIdx, std::basic_string_view<char, std::char_traits<char> >) (libnixexpr.so   0x70954)
installer # #29 0x0000ffffaa40d634 nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) (libnixexpr.so   0x6d634)
installer # #30 0x0000ffffaa412040 nix::ExprCall::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x72040)
installer # #31 0x0000ffffaa40fe24 nix::ExprSelect::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x6fe24)
installer # #32 0x0000ffffaa40a3fc nix::ExprOpNEq::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x6a3fc)
installer # #33 0x0000ffffaa40b758 nix::EvalState::evalBool(nix::Env&, nix::Expr*, nix::PosIdx, std::basic_string_view<char, std::char_traits<char> >) (libnixexpr.so   0x6b758)
installer # #34 0x0000ffffaa40bbac nix::ExprOpAnd::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x6bbac)
installer # #35 0x0000ffffaa40b758 nix::EvalState::evalBool(nix::Env&, nix::Expr*, nix::PosIdx, std::basic_string_view<char, std::char_traits<char> >) (libnixexpr.so   0x6b758)
installer # #36 0x0000ffffaa40ba10 nix::ExprIf::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x6ba10)
installer # #37 0x0000ffffaa45638c nix::prim_seq(nix::EvalState&, nix::PosIdx, nix::Value**, nix::Value&).lto_priv.0 (libnixexpr.so   0xb638c)
installer # #38 0x0000ffffaa40d904 nix::EvalState::callFunction(nix::Value&, unsigned long, nix::Value**, nix::Value&, nix::PosIdx) (libnixexpr.so   0x6d904)
installer # #39 0x0000ffffaa412040 nix::ExprCall::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x72040)
installer # #40 0x0000ffffaa3f35f8 void nix::EvalState::forceAttrs<nix::EvalState::forceAttrs(nix::Value&, nix::PosIdx, std::basic_string_view<char, std::char_traits<char> >)::{lambda()#1}>(nix::Value&, nix::EvalState::forceAttrs(nix::Value&, nix::PosIdx, std::basic_string_view<char, std::char_traits<char> >)::{lambda()#1}, std::basic_string_view<char, std::char_traits<char> >) (libnixexpr.so   0x535f8)
installer # #41 0x0000ffffaa40fc34 nix::ExprSelect::eval(nix::EvalState&, nix::Env&, nix::Value&) (libnixexpr.so   0x6fc34)
installer # #42 0x0000aaaad7d2b444 main_nix_build(int, char**).lto_priv.0 (nix   0x8b444)
installer # #43 0x0000aaaad7dcfe54 nix::mainWrapped(int, char**) (nix   0x12fe54)
installer # #44 0x0000ffffaa1a2564 nix::handleExceptions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::function<void ()>) (libnixmain.so   0x22564)
installer # #45 0x0000aaaad7d10cc0 main (nix   0x70cc0)
installer # #46 0x0000ffffa95fc584 __libc_start_call_main (libc.so.6   0x2c584)
installer # #47 0x0000ffffa95fc658 __libc_start_main@@GLIBC_2.34 (libc.so.6   0x2c658)
installer # #48 0x0000aaaad7d159f0 _start (nix   0x759f0)
```

Cause currently unknown. Seems to happen more often in systemd-boot NixOS tests?
 
Reverting default Nix version in nixpkgs: https://github.com/NixOS/nixpkgs/pull/343032

### PR DESCRIPTION
**Pull request by edolstra**
# Motivation

Fixes #11547.

My SNAFU was that I assumed that all the `Value *`s we put in `attrsSeen` are already reachable (which they are), but I forgot about the `elems` pointer in `ListBuilder`.

Thanks to @puckipedia and @yorickvP for diagnosing.

# Context

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

File: src/libexpr/primops.cc [hunk 1]
```diff
@@ -3136,7 +3136,7 @@ static void prim_zipAttrsWith(EvalState & state, const PosIdx pos, Value * * arg
         std::optional<ListBuilder> list;
     };
 
-    std::map<Symbol, Item> attrsSeen;
+    std::map<Symbol, Item, std::less<Symbol>, traceable_allocator<std::pair<const Symbol, Item>>> attrsSeen;
```
Comment (roberth) [inline src/libexpr/primops.cc:3139]:
```suggestion
#if HAVE_BOEHMGC
    std::map<Symbol, Item, std::less<Symbol>, traceable_allocator<std::pair<const Symbol, Item>>> attrsSeen;
#else
    std::map<Symbol, Item> attrsSeen;
#endif
```

**Review by roberth — APPROVED** [review]

**Comment by Mic92** [comment]
Fixes the the issue for me. nix 2.24 crashes in 10s

```
#!/usr/bin/env nix-shell
#!nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/4b87f8820eba50283dbcc38442d49439a4117529.tar.gz -i bash -p nix parallel rr
set -e

SCRIPT_DIR=$(dirname -- "$0";)
RRDIR="$SCRIPT_DIR/rr-testing"
cd "$SCRIPT_DIR"
export GC_FREE_SPACE_DIVISOR=69 GC_ENABLE_INCREMENTAL=1

gorun() {
    for (( i=0; i < 80; i = i + 1 )); do
        #_RR_TRACE_DIR=$RRDIR parallel -N0 --verbose --halt-on-error 2 --lb rr record --chaos -- nix eval --eval-store "$(pwd)/store" -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/4b87f8820eba50283dbcc38442d49439a4117529.tar.gz  -I nixos-config=./configuration.nix -f '"<nixpkgs/nixos>"' config.system.build.toplevel ::: {1..80}
        #parallel -N0 --verbose --halt-on-error 2 --lb /nix/store/qi0z5ar7ln3ahmnnd2336221bz5zm2zn-nix-2.25.0pre20240919_75dc688/bin/nix eval --eval-store "$(pwd)/store" -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/4b87f8820eba50283dbcc38442d49439a4117529.tar.gz  -I nixos-config=./configuration.nix -f '"<nixpkgs/nixos>"' config.system.build.toplevel ::: {1..80}
        parallel -N0 --verbose --halt-on-error 2 --lb nix eval --eval-store "$(pwd)/store" -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/4b87f8820eba50283dbcc38442d49439a4117529.tar.gz  -I nixos-config=./configuration.nix -f '"<nixpkgs/nixos>"' config.system.build.toplevel ::: {1..80}
    done
}

nix --version

while true; do
    rm -rvf "$RRDIR"
    gorun
done
```

This script keeps running:

```
#!/usr/bin/env nix-shell
#!nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/4b87f8820eba50283dbcc38442d49439a4117529.tar.gz -i bash -p nix parallel rr
set -e

SCRIPT_DIR=$(dirname -- "$0";)
RRDIR="$SCRIPT_DIR/rr-testing"
cd "$SCRIPT_DIR"
export GC_FREE_SPACE_DIVISOR=69 GC_ENABLE_INCREMENTAL=1

gorun() {
    for (( i=0; i < 80; i = i + 1 )); do
        parallel -N0 --verbose --halt-on-error 2 --lb /nix/store/qi0z5ar7ln3ahmnnd2336221bz5zm2zn-nix-2.25.0pre20240919_75dc688/bin/nix eval --eval-store "$(pwd)/store" -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/4b87f8820eba50283dbcc38442d49439a4117529.tar.gz  -I nixos-config=./configuration.nix -f '"<nixpkgs/nixos>"' config.system.build.toplevel ::: {1..80}
    done
}

nix --version

while true; do
    rm -rvf "$RRDIR"
    gorun
done
```
