### PR TITLE
Error on invalid URL param in github fetcher

### LINKED ISSUE #15304: nix silently ignores unknown attributes on github inputs
## Describe the bug

I found this while doing a large-scale test run on real flakes, so there’re people who’ve actually fallen into this trap.

## Steps To Reproduce

Try to lock this flake:

```nix
{
  inputs.a.url = "github:nixos/nix?tag=2.33.3";
  outputs = _: {};
}
```

It will silently fetch the default branch, ignoring the unrecognized attribute.

## Expected behavior

It should be rejected: it’s spelled `ref`, not `tag`.

## Metadata

nix-env (Nix) 2.31.3

## Additional context

Lix correctly rejects it.

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open bug issues and pull requests] for possible duplicates

[latest Nix manual]: https://nix.dev/manual/nix/development/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by lisanna-dettwyler**
Resolves #15304

## Motivation

It is easy for people to make the mistake of including a `tag` parameter when they want to fetch a tag from a github URL. Currently, Nix will just ignore it and fall back to fetching the default branch, with no error printed, which is highly undesirable.

## Context

#15304

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

File: src/libfetchers-tests/input.cc [hunk 1]
```diff
@@ -58,4 +60,31 @@ INSTANTIATE_TEST_SUITE_P(
...
+
+TEST_F(GitHubInputTest, throwOnInvalidURLParam)
+{
+    fetchers::Settings fetchSettings = fetchers::Settings{};
+    bool gotException = false;
+    try {
+        auto i = Input::fromURL(fetchSettings, "github:a/b?tag=foo");
+    } catch (BadURL & e) {
+        gotException = true;
+    }
```
Comment (xokdvium) [inline src/libfetchers-tests/input.cc]: Maybe EXPECT_THROW or EXPECT_THAT? It can even be used to match exception messages with some gmock matchers that we have for stripping ansi escapes.

File: src/libfetchers-tests/input.cc [hunk 2]
```diff
@@ -58,4 +60,31 @@ INSTANTIATE_TEST_SUITE_P(
...
     [](const ::testing::TestParamInfo<InputFromAttrsTestCase> & info) { return info.param.description; });
 
+namespace fetchers {
+
+class GitHubInputTest : public ::testing::Test
+{
+public:
+    void SetUp() override
+    {
+        experimentalFeatureSettings.experimentalFeatures.get().insert(Xp::Flakes);
```
Comment (Ericson2314) [inline src/libfetchers-tests/input.cc]: Can we use the fetchers experimental feature? also, don't forget to remove it again afterwards!

**Comment by xokdvium** [comment]
Also probably worth a release note I suppose

File: src/libfetchers-tests/input.cc (hunk 2 above)
Comment (lisanna-dettwyler) [reply src/libfetchers-tests/input.cc]: Turns out no experimental features are actually required.

File: src/libfetchers/github.cc [hunk 3]
```diff
@@ -32,6 +32,13 @@ struct GitArchiveInputScheme : InputScheme
     virtual std::optional<std::pair<std::string, std::string>>
     accessHeaderFromToken(const std::string & token) const = 0;
 
+    StringSet validParams = {"rev", "ref", "host", "narHash"};
```
Comment (xokdvium) [inline src/libfetchers/github.cc]: Seems like this goes a bit against DRY principle. Can't we stick the throw in the else clause instead of enumerating things manually?

Comment (lisanna-dettwyler) [reply src/libfetchers/github.cc]: Sure, it required a bit more reworking than initially, but this version is arguably cleaner.

File: src/libfetchers/github.cc [hunk 4]
```diff
@@ -59,38 +57,30 @@ struct GitArchiveInputScheme : InputScheme
...
             }
-            ref = rs;
+            attrs.insert_or_assign("ref", rs);
         } else if (size < 2)
             throw BadURL("URL '%s' is invalid", url);
 
         for (auto & [name, value] : url.query) {
             if (name == "rev") {
-                if (rev)
+                if (attrs.find(name) != attrs.end())
```
Comment (xokdvium) [inline src/libfetchers/github.cc]: We have C++20 .contains FWIW. Slightly cleaner if we want that. I'm fine with this as is

**Comment by xokdvium** [comment]
Since we don't yet have a nice way to run flake-regressions fully I'm just going to push a temporary change to bump the MAX_FLAKES and will drop it afterwards.
