### PR TITLE
libstore: preserve mount flags when remounting store writable

### LINKED ISSUE #9705: Nix fails to remount the store with all the required flags
Normally `/nix/store` is bind-mounted as read-only. That's to avoid accidental changes to the Nix store even by root. `nix`/`nix-daemon` though try to remount the nix-store to read-write in its own namespace, but the implementation is simplistic[1] and will fail in different scenarios.
[1]
https://github.com/NixOS/nix/blob/master/src/libstore/local-store.cc#L581-L582

I'm running nixos as a `systemd-nspawn` container, where the whole nixos filesystem lives on the host system (in `/var/lib/machines/nixos`), and the container is then run with it as a root filesystem ("booting" `/sbin/init` which execs `/nix/store/d842nhr0ckaw7ijlf54q9dnm37dnn00p-nixos-system-nix-container-24.05.20240102.bd645e8/init`).

In that case, the root and the nix-store are mounted with some additional flags compared to "normal" nixos (nodev and idmapped):
```
$ findmnt /
TARGET
  SOURCE                                    FSTYPE OPTIONS
/ /dev/mapper/root[/var/lib/machines/nixos] ext4   rw,nodev,relatime,idmapped

$ findmnt /nix/store/
TARGET     SOURCE                                              FSTYPE OPTIONS
/nix/store /dev/mapper/root[/var/lib/machines/nixos/nix/store] ext4   ro,nodev,relatime,idmapped
```

The problem is nix(nix-daemon) fails to remount the store to read-write:
```
$ strace -f -e mount nix-daemon 
strace: Process 206 attached
accepted connection from pid 230, user root (trusted)
strace: Process 239 attached
[pid   239] mount(NULL, "/nix/store", 0x7fa5ce409bd5, MS_REMOUNT|MS_BIND, NULL) = -1 EPERM (Operation not permitted)
unexpected Nix daemon error: error: remounting /nix/store writable: Operation not permitted
```

The most simple hack to solve the issue was to add the MS_NODEV flag in the remount call:
```diff
diff --git a/src/libstore/local-store.cc b/src/libstore/local-store.cc
index 0f3c37c8a..ce6dd13ae 100644
--- a/src/libstore/local-store.cc
+++ b/src/libstore/local-store.cc
@@ -579,7 +579,7 @@ void LocalStore::makeStoreWritable()
         throw SysError("getting info about the Nix store mount point");
 
     if (stat.f_flag & ST_RDONLY) {
-        if (mount(0, realStoreDir.get().c_str(), "none", MS_REMOUNT | MS_BIND, 0) == -1)
+        if (mount(0, realStoreDir.get().c_str(), "none", MS_REMOUNT | MS_BIND | MS_NODEV, 0) == -1)
             throw SysError("remounting %1% writable", realStoreDir);
     }
 #endif
```

after this change, nix/nix-daemon successfully can remount the /nix/store.

Now a more robust solution would probably be to first introspect all the mount flags and then only flip the read-only flag - other `mount` cli tools seem to do that (busybox or util-linux mount for ex).

I can try to pursue that fix, if it's acceptable.

### PR DESCRIPTION
**Pull request by amaanq**
## Motivation

`makeStoreWritable` passed only `MS_REMOUNT | MS_BIND` to `mount()`,
telling the kernel to drop every other flag. In a user namespace, flags
like `nodev` and `nosuid` are locked by the kernel, so dropping them
causes `EPERM`. This commit reads the active flags from `statvfs` and
translates each `ST_*` constant to its `MS_*` counterpart individually,
because the two sets are not always equal (`ST_RELATIME` is 4096, which
collides with `MS_BIND`; the real `MS_RELATIME` is 1 << 21).

## Context

- Fixes #9705

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by artemist** [comment]
It's a bit unclear that the test actually makes sure that the store is remounted, though it should (since remount is very early in the nix daemon).

the C++ changes look reasonable.

File: src/libstore/local-store.cc [hunk 1]
```diff
@@ -619,7 +622,15 @@ void LocalStore::makeStoreWritable()
...
     if (stat.f_flag & ST_RDONLY) {
-        if (mount(0, config->realStoreDir.get().c_str(), "none", MS_REMOUNT | MS_BIND, 0) == -1)
+        /* In a user namespace, mount flags like `nodev` and `nosuid` are
+           locked and dropping them causes `EPERM`, so forward them from
+           `statvfs`. `ST_RELATIME` (4096) collides with `MS_BIND` and
+           needs explicit translation to the real `MS_RELATIME` (1 << 21). */
+        unsigned long flags = stat.f_flag & ~(unsigned long) (ST_RDONLY | ST_RELATIME);
+        if (stat.f_flag & ST_RELATIME)
+            flags |= MS_RELATIME;
+        flags |= MS_REMOUNT | MS_BIND;
```
Comment (xokdvium) [inline src/libstore/local-store.cc]: Shouldn't we handle each flag separately and not rely on the values matching? That seems very fragile to me

Comment (amaanq) [reply src/libstore/local-store.cc]: Yeah that makes sense

File: tests/nixos/store-remount.nix [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+          "--as-pid2 "
+          "${pkgs.bash}/bin/bash -c '"
+          "  findmnt=${pkgs.util-linux}/bin/findmnt && "
+          "  grep=${pkgs.gnugrep}/bin/grep && "
+          "  ${pkgs.util-linux}/bin/mount -o remount,bind,ro /nix/store && "
+          "  $findmnt /nix/store -no OPTIONS | $grep -qw ro && "
+          "  ${nix}/bin/nix store info --store local "
+          "    --extra-experimental-features nix-command && "
+          "  $findmnt /nix/store -no OPTIONS | $grep -qw rw && "
+          "  $findmnt /nix/store -no OPTIONS | $grep -qw nodev"
```
Comment (xokdvium) [inline tests/nixos/store-remount.nix]: Hm this shouldn't modify the flags in the namespace though. Something's not right about this?

Comment (xokdvium) [reply tests/nixos/store-remount.nix]: Probably unshare fails and we end up remounting inside the mount namespace of the bash process. Not good

**Comment by xokdvium** [comment]
@amaanq, commit message is still wrong?

**Comment by xokdvium** [comment]
Seems relevant. https://unix.stackexchange.com/questions/655409/in-a-user-namespace-as-non-root-on-a-nosuid-nodev-filesystem-why-does-a-bind-m

Otherwise LGTM

File: src/libstore/local-store.cc [hunk 3]
```diff
@@ -624,7 +624,23 @@ void LocalStore::makeStoreWritable()
...
+        if (stat.f_flag & ST_NOSUID)
+            flags |= MS_NOSUID;
+        if (stat.f_flag & ST_NOEXEC)
+            flags |= MS_NOEXEC;
+        if (stat.f_flag & ST_NOATIME)
+            flags |= MS_NOATIME;
+        if (stat.f_flag & ST_NODIRATIME)
+            flags |= MS_NODIRATIME;
+        if (stat.f_flag & ST_RELATIME)
+            flags |= MS_RELATIME;
```
Comment (xokdvium) [inline src/libstore/local-store.cc:639]: Maybe missing ST_SYNCHRONOUS and (maybe undefined) ST_NOSYMFOLLOWS? Though it's mostly academic at this point, I doubt anybody is setting those

Comment (amaanq) [reply src/libstore/local-store.cc:639]: Yeah true, but it doesn't hurt to have. I added an ifdef guard for `ST_NOSYMFOLLOWS` as it's only available on Linux 5.10+.

**Comment by xokdvium** [comment]
@amaanq reformat? Otherwise seems good to me

**Comment by amaanq** [comment]
> @amaanq reformat? Otherwise seems good to me

Yep, done

**Review by xokdvium — APPROVED** [review]

**Comment by xokdvium** [comment]
Did you drop the warning in failing unshare? Seems like we want to keep that still.

**Comment by amaanq** [comment]
> Did you drop the warning in failing unshare? Seems like we want to keep that still.

Oops, just added it back, thanks for catching that
