### PR TITLE
fetchers/git: make relative path absolute for local repo

### LINKED ISSUE #9708: Flake input `git+file:./${submodule}` no longer works
**Describe the bug**

Flake input of a git submodule in a relative subdirectory `git+file:./${submodule}`
- works on 2.18.1 (`nixpkgs.nixVersions.nix_2_18`)
- but no longer works on 2.19.2 (`nixpkgs.nixVersions.nix_2_19`)

**Update:** [it seems](https://github.com/NixOS/nix/issues/9708#issuecomment-1884193418) that the regression happens since #9061. An example of this flake ref:

https://github.com/bryango/cheznix/blob/c445c8c82697de2bde53c65e9acacb9790fcd54e/flake.nix#L20-L23

The breakage would be acceptable to me if there is any alternative syntax that works, but currently I could not find anything that can replace `git+file:./${submodule}`.

**Steps To Reproduce**

```console
$ nix --version
nix (Nix) 2.19.2

## suppose we have `inputs.nixpkgs.url = git+file:./nixpkgs;`
$ nix flake update nixpkgs
fatal: '/nixpkgs' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
warning: could not read HEAD ref from repo at 'file://file:./nixpkgs', using 'master'
fatal: '/nixpkgs' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
error:
       … while updating the lock file of flake 'git+file:///home/$USER/.config/home-manager?ref=refs/heads/master&rev=c445c8c82697de2bde53c65e9acacb9790fcd54e'

       … while updating the flake input 'nixpkgs'

       … while fetching the input 'git+file://file:./nixpkgs'

       error: program 'git' failed with exit code 128
```

**Expected behavior**

I believe submodule sub-flake is quite common and `git+file:./${submodule}` should still work.

**`nix-env --version` output**

```console
evaluating file '/derivation-internal.nix'
nix-env (Nix) 2.19.2
System type: x86_64-linux
Additional system types: i686-linux, x86_64-v1-linux, x86_64-v2-linux, x86_64-v3-linux
Features: gc, signed-caches
System configuration file: /etc/nix/nix.conf
User configuration files: /home/$USER/.config/nix/nix.conf:/etc/xdg/nix/nix.conf
Store directory: /nix/store
State directory: /nix/var/nix
Data directory: /nix/store/0k52aibl2flync375nfw9a0kdjzvrzrc-nix-2.19.2/share
```

**Additional context**

N/A

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by bryango**
## Motivation

Closes #9708 (again).

This patch:
- (naively) Resolves relative paths to local git repos, returning absolute paths, thus allowing flake URIs such as `git+file:./${submodule}` to continue working.
- Adds tests to prevent future breakages.

## Context

Flake URIs such as `git+file:./${submodule}` used to work before 2.18, but broke in 2.19, was fixed later, and broke again recently since 3e0129ce3b9eb094d4a3cc8023884f372f1d7ff6, resulting in a core-dumped assertion error in https://github.com/NixOS/nix/issues/9708#issuecomment-2559095657.

This PR suppresses the error and allows `git+file:./${submodule}`to continue working. However, this fix is not ideal and should potentially be superseded by a better submodule implementation in the future. See:
- #9708
- #9897

A better fix is outlined by @roberth in https://discourse.nixos.org/t/57783, namely:

> This bug seems to have allowed relative git flake inputs to be resolved against the current working directory (as in POSIX), and this tends to work out ok in the context of flakes, but is the wrong behavior, as it should resolve against the flake.nix base directory instead.
> Supporting relative paths in fetchTree would add significant value.
> This behavior was used as a workaround for lacking relative flake input or “subflake” support.

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol). 

Friendly pings:
- @roberth and @tomberek for reviews
- @DamienCassou and @aij for testing

### CODE REVIEW

**Review by aij — APPROVED** [review]
I gave it a quick try and it does work for me:
```
ivan@tobati:~/nixops/aij$ /nix/store/bn0djaymav6qa4zg5vaskzcaija5nq2p-nix-2.26.0pre20241227_9111645/bin/nix flake update 
warning: updating lock file '/home/ivan/nixops/aij/flake.lock':
• Updated input 'unstable':
    'git+file:unstable?rev=3f0036916daca9836ba2c3f236b0ae051949a0a8' (2024-12-21)
  → 'git+file:unstable?ref=refs/heads/ipmiutil&rev=174ae1b581ddd6d5a6c55684da392e0baf500b1e' (2024-12-27)
```

**Review by roberth — APPROVED** [review]
Partial fix

**Comment by edolstra** [comment]
For the example in #9709, namely
```
inputs.nixpkgs.url = git+file:./nixpkgs;
```
doesn't this result in a lock file that has the absolute path of the original Git repo in it? I.e. if I run `nix flake lock` on such a flake in `/home/bob/repo`, doesn't it result in a lock file that references `/home/bob/repo/nixpkgs`?

**Comment by bryango** [comment]
> ```
> inputs.nixpkgs.url = git+file:./nixpkgs;
> ```
> 
> doesn't this result in a lock file that has the absolute path of the original Git repo in it? I.e. if I run `nix flake lock` on such a flake in `/home/bob/repo`, doesn't it result in a lock file that references `/home/bob/repo/nixpkgs`?

@edolstra Actually, no! It still gets locked to the relative path and shows up in `flake.lock` as `file:./nixpkgs`, which is great! I have pushed another test to cement this behavior.

File: tests/functional/flakes/flake-in-submodule.sh [hunk 1]
```diff
@@ -63,3 +63,21 @@ flakeref=git+file://$rootRepo\?submodules=1\&dir=submodule
...
+}
+EOF
+git -C "$rootRepo" add flake.nix
+git -C "$rootRepo" commit -m "Add flake.nix"
+(
+  cd "$rootRepo"
+  # The submodule must be locked to the relative path,
+  # _not_ the absolute path:
+  [[ $(nix flake metadata --json | jq -r .locks.nodes.subRepo.locked.url) = "file:./submodule" ]]
+)
```
Comment (bryango) [inline tests/functional/flakes/flake-in-submodule.sh:83]: `submodule` does get locked to the relative path `file:./submodule`. I don't understand why but hey, it works!

**Comment by bryango** [comment]
Draft-ing and un-draft-ing to try to trigger the new CI...

**Comment by roberth** [comment]
Rebased for GHA config update

**Comment by bryango** [comment]
Rebased on current master, conflicts resolved, CI happy! Friendly ping @roberth @edolstra for re-review!

**Comment by bryango** [comment]
Rebased again, conflicts resolved, CI happy.

File: tests/functional/flakes/flakes.sh [hunk 2]
```diff
@@ -106,6 +106,14 @@ nix build -o "$TEST_ROOT/result" "git+file://$flake1Dir#default"
 nix build -o "$TEST_ROOT/result" "$flake1Dir?ref=HEAD#default"
 nix build -o "$TEST_ROOT/result" "git+file://$flake1Dir?ref=HEAD#default"
 
+# Check that relative paths are allowed for git flakes.
+# This may change in the future once git submodule support is refined.
+# See: https://discourse.nixos.org/t/57783 and #9708.
+(
+  cd "$flake1Dir/.."
```
Comment (roberth) [inline tests/functional/flakes/flakes.sh:113]:
```suggestion
  # This `cd` should not be required and is indicative of aforementioned bug.
  cd "$flake1Dir/.."
```

**Review by roberth — APPROVED** [review]

**Comment by roberth** [comment]
Thanks!

@mergify queue

**Comment by roberth** [comment]
@mergify merge

File: src/libfetchers/git.cc [hunk 3]
```diff
@@ -426,7 +426,16 @@ struct GitInputScheme : InputScheme
...
+        //
+        // FIXME: here we turn a possibly relative path into an absolute path.
+        // This allows relative git flake inputs to be resolved against the
+        // **current working directory** (as in POSIX), which tends to work out
+        // ok in the context of flakes, but is the wrong behavior,
+        // as it should resolve against the flake.nix base directory instead.
+        //
+        // See: https://discourse.nixos.org/t/57783 and #9708
+        //
+        repoInfo.url = repoInfo.isLocal ? std::filesystem::absolute(url.path).string() : url.to_string();
```
Comment (edolstra) [inline src/libfetchers/git.cc:438]: I'm a bit baffled by this. As the comment notes, resolving relative to the cwd is wrong since it could be anything. So why are we doing this?

**Comment by edolstra** [comment]
I fear that this PR enshrines some extremely undesirable semantics, namely that `libfetcher` now depends on the current working directory. As a result, `nix build .` might succeed, while `nix build /path/to/flake` would mysteriously fail, or worse, produce another result if the relative path of the submodule happens to exist in the cwd of the caller. IMHO that's unambiguously a bug.

At the very least, we should print a warning that users should not rely on this behaviour.

**Comment by roberth** [comment]
This was a calculated decision to merge. I believe an alternate result is not possible, and that the wrong behavior would only cause a direct failure ("mysteriously fail"). I've [approved it as a workaround](https://github.com/NixOS/nix/pull/12107#pullrequestreview-2525911277), not as a solution.

I've written https://github.com/NixOS/nix/issues/12281 to clarify the situation and discuss / track the final solution.

**Comment by bryango** [comment]
Yes, this is not the ideal behavior; it's a band-aid to fix the cryptic core-dumped assertion error as in https://github.com/NixOS/nix/issues/9708#issuecomment-2559095657. Note that this PR was proposed and reviewed way before #12254. If the latter fix achieves the same purpose, we can simply revert 96bd9bad2f434fe3489b039ac665679878460b0c (but keep the tests as it prevents future failures).
