### PR TITLE
Fix segfault on infinite recursion in some cases

### LINKED ISSUE #9616: Segfault on infinite recursion
**Describe the bug**

```
nix-instantiate --eval --expr '(x: x x) (x: x x)'
Segmentation Fault: 11
```

Discovered by @Gabriella439.

**Expected behavior**

It shows an "infinite recursion" error and exits.

**`nix-env --version` output**

nix-env (Nix) 2.20.0

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by 9999years**
# Context

Closes #9616.

This fixes a segfault on infinite function call recursion (rather than infinite thunk recursion) by tracking the function call depth in `EvalState`.

Additionally, to avoid printing extremely long stack traces, stack frames are now deduplicated, with a `(19997 duplicate traces omitted)` message. This should only really be triggered in infinite recursion scenarios.

Before:

    $ nix-instantiate --eval --expr '(x: x x) (x: x x)'
    Segmentation fault: 11

After:

    $ nix-instantiate --eval --expr '(x: x x) (x: x x)'
    error: stack overflow

           at «string»:1:14:

                1| (x: x x) (x: x x)
                 |              ^

    $ nix-instantiate --eval --expr '(x: x x) (x: x x)' --show-trace
    error:
           … from call site

             at «string»:1:1:

                1| (x: x x) (x: x x)
                 | ^

           … while calling anonymous lambda

             at «string»:1:2:

                1| (x: x x) (x: x x)
                 |  ^

           … from call site

             at «string»:1:5:

                1| (x: x x) (x: x x)
                 |     ^

           … while calling anonymous lambda

             at «string»:1:11:

                1| (x: x x) (x: x x)
                 |           ^

           … from call site

             at «string»:1:14:

                1| (x: x x) (x: x x)
                 |              ^

           (19997 duplicate traces omitted)

           error: stack overflow

           at «string»:1:14:

                1| (x: x x) (x: x x)
                 |              ^

# Future work

- It would be nice if the maximum function call depth could be customized like `--option function-call-depth-limit 500`.
- ~~In some cases, this may print a message like `(1 duplicate traces omitted)`, which is kind of unhelpful. It would be nice to only print that message if more than a couple traces are omitted.~~

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

### CODE REVIEW

File: src/libexpr/eval.cc [hunk 1]
```diff
@@ -1508,6 +1508,10 @@ void ExprLambda::eval(EvalState & state, Env & env, Value & v)
 
 void EvalState::callFunction(Value & fun, size_t nrArgs, Value * * args, Value & vRes, const PosIdx pos)
 {
+    if (depth > 10000)
```
Comment (9999years) [inline src/libexpr/eval.cc:1511]: Chosen arbitrarily.

File: src/libexpr/eval.cc [hunk 2]
```diff
@@ -1508,6 +1508,10 @@ void ExprLambda::eval(EvalState & state, Env & env, Value & v)
...
+        error("stack depth exhausted").atPos(pos).template debugThrow<EvalError>();
```
Comment (9999years) [inline src/libexpr/eval.cc:1512]: Is this message OK? Maybe it should say "potential infinite recursion" or just "stack overflow".

File: src/libutil/error.cc [hunk 3]
```diff
@@ -50,6 +50,29 @@ std::ostream & operator <<(std::ostream & str, const AbstractPos & pos)
...
+        return true;
+    }
+
+    return (lhs.pos && rhs.pos && *lhs.pos < *rhs.pos)
+        || lhs.hint.str() < rhs.hint.str()
+        || lhs.frame < rhs.frame;
+}
+inline bool operator> (const Trace& lhs, const Trace& rhs) { return rhs < lhs; }
+inline bool operator<=(const Trace& lhs, const Trace& rhs) { return !(lhs > rhs); }
+inline bool operator>=(const Trace& lhs, const Trace& rhs) { return !(lhs < rhs); }
```
Comment (lf-) [inline src/libutil/error.cc:74]: These should probably be in an anonymous namespace as they're not forward-declared nor used from any other source file (c++ people invent a clang-tidy rule for this challenge).

Comment (9999years) [reply src/libutil/error.cc:74]: I get an error if I try that. I think I have to actually make them public in the same namespace as `Trace`/`AbstractPos` to be visible?

https://stackoverflow.com/questions/55390265/defining-a-custom-equality-operator-in-an-anonymous-namespace
https://stackoverflow.com/questions/52629859/adl-for-class-in-anonymous-namespace

Comment (lf-) [reply src/libutil/error.cc:74]: Interesting; the following program compiles with `g++`:

```cpp
namespace meow {
class Blah {};
}

namespace {
    inline bool operator>(const meow::Blah& a, const meow::Blah& b) { return true; }
};

int main(void) {
    meow::Blah{} > meow::Blah{};
}
```

I don't know what's going on, but the code is not problematic as-is; it could also possibly be moved to the header where Trace is defined.

File: src/libutil/error.cc [hunk 4]
```diff
@@ -334,7 +357,15 @@ std::ostream & showErrorInfo(std::ostream & out, const ErrorInfo & einfo, bool s
 
     bool frameOnly = false;
     if (!einfo.traces.empty()) {
+        std::set<Trace> tracesSeen;
+        size_t skippedTraces = 0;
         size_t count = 0;
+        const auto printSkippedTracesMaybe = [&] {
+            if (skippedTraces > 0) {
+                oss << "\n" << ANSI_WARNING "(" << skippedTraces << " duplicate traces omitted)" ANSI_NORMAL << "\n";
```
[the remark this answers is not in the document]
Comment (9999years) [reply src/libutil/error.cc]: Okay, I took another shot at this. Instead of storing an integer of `skippedTraces`, I store a `std::vector` of them, and then I can just check if there's only a couple skipped and print them manually (to avoid "1 duplicate frame omitted" messages).

I'm also clearing the set of seen traces each time we print "duplicate frames omitted", so that we don't accidentally hide interesting parts of the trace. Of course, this could break down in more complex recursion scenarios...

File: src/libexpr/eval.cc (hunk 2 above)
Comment (9999years) [reply src/libexpr/eval.cc]: I made it say "stack overflow" instead.

File: src/libutil/error.cc (hunk 4 above)
[the remark this answers is not in the document]
Comment (lf-) [reply src/libutil/error.cc]: Yeah, I am contemplating the cases:
- Bunch of repeated stuff, finally a different stack frame (this is improbable tho, why would it be 10000 specifically)
- Mutual recursion goes and infinitely recurses
  - If the pattern is *just* a repeated run of A, B, C, A, B, C, in unicorns-and-rainbows land it would recognize the repeated run and truncate just the run? But it would also be ok if we don't notice that; this change is a big improvement over the status quo already.
  - If the pattern is more than that, idk, feels like the upper parts of the stack trace are going to be useless regardless, and users would be better served by the debugger and a breakpoint.
- One function infinitely recurses
  - Here we definitely want to chop the stack trace since it's useless.

We might also want a total limit of how much stack trace we print and `--srsly-show-me-all-of-it`? Kinda like RUST_BACKTRACE=1 vs RUST_BACKTRACE=all.

File: src/libutil/error.cc (hunk 3 above)
Comment (9999years) [reply src/libutil/error.cc]: Done.

File: src/libexpr/eval.cc [hunk 5]
```diff
@@ -1505,9 +1505,27 @@ void ExprLambda::eval(EvalState & state, Env & env, Value & v)
...
+    --count;
+  }
+};
+};
 
 void EvalState::callFunction(Value & fun, size_t nrArgs, Value * * args, Value & vRes, const PosIdx pos)
 {
+    if (depth > 10000)
+        error("stack overflow").atPos(pos).template debugThrow<EvalError>();
+    CallLevel _level(depth);
```
Comment (thufschmitt) [inline src/libexpr/eval.cc:1527]: I think we'll want to benchmark this to make sure that it doesn't bear a noticeable evaluation performance impact.
My usual benchmark is a simple `nix search nixpkgs blah --option eval-cache false`, but maybe @tfc will have something more meaningful to suggest since he's been working heavily on the evaluator performance.

File: src/libutil/error.cc [hunk 6]
```diff
@@ -334,7 +368,33 @@ std::ostream & showErrorInfo(std::ostream & out, const ErrorInfo & einfo, bool s
...
+            if (skippedTraces.size() > 0) {
+                // If we only skipped a few frames, print them out normally;
+                // messages like "1 duplicate traces omitted" aren't helpful.
+                if (skippedTraces.size() <= 5) {
+                    for (auto & trace : skippedTraces) {
+                        printTrace(trace);
+                    }
+                } else {
+                    oss << "\n" << ANSI_WARNING "(" << skippedTraces.size() << " duplicate traces omitted)" ANSI_NORMAL << "\n";
+                    tracesSeen.clear();
```
Comment (thufschmitt) [inline src/libutil/error.cc:392]: (nit): Why do we care about that (and likely clearing `skippedTraces` below)?

**Review by thufschmitt — CHANGES_REQUESTED** [review]
Thanks,

I'm not the right person to judge on the overall mechanism (it feels a bit brittle to me because of the arbitrary magic value, but it's also incredibly nice to have a stack trace – esp on macOS). I'll let others (@edolstra or @roberth in particular) have a more informed opinion here.

Other than that, I let a couple comments. The implementation is great, my main concern is that it doesn't have an impact on the overall performance.

**Comment by roberth** [comment]
For a bigger picture please also read #9627

File: src/libutil/error.cc [hunk 7]
```diff
@@ -50,6 +50,40 @@ std::ostream & operator <<(std::ostream & str, const AbstractPos & pos)
...
+        return lhs.hint.str() < rhs.hint.str();
+
+    if (lhs.frame != rhs.frame)
+        return lhs.frame < rhs.frame;
+
+    return false;
+}
+inline bool operator> (const Trace& lhs, const Trace& rhs) { return rhs < lhs; }
+inline bool operator<=(const Trace& lhs, const Trace& rhs) { return !(lhs > rhs); }
+inline bool operator>=(const Trace& lhs, const Trace& rhs) { return !(lhs < rhs); }
```
[the remark this answers is not in the document]
Comment (roberth) [reply src/libutil/error.cc:85]: `std::tie` seems like a great middle ground of having specified semantics, but less code.

File: src/libexpr/eval.hh [hunk 8]
```diff
@@ -623,6 +623,8 @@ private:
         const SourcePath & basePath,
         std::shared_ptr<StaticEnv> & staticEnv);
 
+    unsigned int depth = 0;
```
Comment (tfc) [inline src/libexpr/eval.hh:626]: For variables that *count* things, typically `size_t` is used.

File: src/libutil/error.cc [hunk 9]
```diff
@@ -50,6 +50,40 @@ std::ostream & operator <<(std::ostream & str, const AbstractPos & pos)
     return str;
 }
 
+inline bool operator<(const AbstractPos& lhs, const AbstractPos& rhs)
+{
+    if (lhs.line != rhs.line)
+        return lhs.line < rhs.line;
+    if (lhs.column != rhs.column)
+        return lhs.column < rhs.column;
+    return false;
```
Comment (tfc) [inline src/libutil/error.cc:59]: What other cases can occur here other than line and column comparison? This makes the code and semantics harder to understand if the code leaves open what else can lead to the `false` return.

File: src/libutil/error.cc (hunk 7 above)
[the remark this answers is not in the document]
Comment (tfc) [reply src/libutil/error.cc:85]: In the C++20 future, one might want to consider using the three-way comparison operator `<=>`. Its implementation allows the compiler to deduce the rest.
This will have multiple advantages:

- we can get rid of preprocessor macros
- strange semantics that are already implemented individually in the different operator implementation might surface in the light of a unified implementation of the `<=>` op

[the remark this answers is not in the document]
Comment (roberth) [reply src/libutil/error.cc:85]: Interesting. Do you know what's blocking this? We do use `c++2a`. Should we track it somewhere?

[the remark this answers is not in the document]
Comment (tfc) [reply src/libutil/error.cc:85]: I don't know if anything blocks this at all. Maybe it's just that no one thought about using it, yet.

[the remark this answers is not in the document]
Comment (thufschmitt) [reply src/libutil/error.cc:85]: Yes, the `c++2a` addition is recent-ish. At least more recent than the cpp machinery

[the remark this answers is not in the document]
Comment (lf-) [reply src/libutil/error.cc:85]: As far as I know Nix is already c++20 and we should probably just write this refactor and make all our comparison code go to space :)

File: src/libexpr/eval.cc (hunk 1 above)
Comment (lf-) [reply src/libexpr/eval.cc:1525]: Status quo: segmentation fault on macOS because our segv handler is Linux x86 only, or so I've heard, and a less than helpful error message if our segv handler does actually work. 

Fixing the handler is beyond the scope of this specific work.

File: src/libutil/error.cc (hunk 7 above)
[the remark this answers is not in the document]
Comment (thufschmitt) [reply src/libutil/error.cc:85]: >  one of the fields here is shared_ptr which by default has very undesirable comparison semantics (pointer address).

Well, if the only reason we need that comparison operator is putting stuff in a `Set`, pointer comparisons is quite reasonable (and as fast as it can get)

[the remark this answers is not in the document]
Comment (9999years) [reply src/libutil/error.cc:85]: Pointer comparisons are not reasonable, because each `Trace` is newly constructed. There's no interning. So it's quite common to have position values that are semantically equal (same line and column number) with different pointer values. I've tried this change and it breaks the tests.

That said, I can simplify these comparisons somewhat and I can replace the `AbstractPos` one with the default.

[the remark this answers is not in the document]
Comment (lf-) [reply src/libutil/error.cc:85]: I wonder how costly it would be to intern positions. We quite possibly should do that anyhow, but at a future date.

[the remark this answers is not in the document]
Comment (9999years) [reply src/libutil/error.cc:85]: Looks like LLVM only got `<=>` for tuples implemented last year: https://github.com/llvm/llvm-project/issues/50396

File: src/libexpr/eval.cc (hunk 5 above)
Comment (9999years) [reply src/libexpr/eval.cc:1527]: Nix 2.18.1:

```
Executed in   13.19 secs    fish           external
   usr time   11.33 secs    0.12 millis   11.33 secs
   sys time    1.76 secs    1.38 millis    1.76 secs
```

This PR:

```
Executed in   13.57 secs    fish           external
   usr time   12.36 secs    0.15 millis   12.35 secs
   sys time    1.10 secs    2.19 millis    1.10 secs
```

3% slowdown. Seems OK for preventing a segfault.

File: src/libutil/error.cc (hunk 6 above)
Comment (9999years) [reply src/libutil/error.cc:377]: I've added a comment to explain this, but I'll copy it here:

Consider a mutually recursive stack trace with:
- 10 entries of A
- 10 entries of B
- 10 entries of A

If we don't clear `tracesSeen` here, we would print output like this:
- 1 entry of A
- (9 duplicate traces omitted)
- 1 entry of B
- (19 duplicate traces omitted)

This obscures the control flow, which went from A, to B, and back to A again.

In contrast, if we do clear `tracesSeen`, the output looks like this:
- 1 entry of A
- (9 duplicate traces omitted)
- 1 entry of B
- (9 duplicate traces omitted)
- 1 entry of A
- (9 duplicate traces omitted)

See: `tests/functional/lang/eval-fail-mutual-recursion.nix` for a test case exercising this property.

File: src/libexpr/eval.cc (hunk 5 above)
Comment (thufschmitt) [reply src/libexpr/eval.cc:1527]: > 3% slowdown. Seems OK for preventing a segfault.

3% isn't really trivial. But I reliably couldn't reproduce it:

```
Summary
  'nixMaster' ran
    1.00 ± 0.01 times faster than 'nixFromPR'
```

So I think it's fine

File: src/libutil/error.cc [hunk 10]
```diff
@@ -333,7 +353,65 @@ std::ostream & showErrorInfo(std::ostream & out, const ErrorInfo & einfo, bool s
...
+                    // - 10 entries of B
+                    // - 10 entries of A
+                    //
+                    // If we don't clear `tracesSeen` here, we would print output like this:
+                    // - 1 entry of A
+                    // - (9 duplicate traces omitted)
+                    // - 1 entry of B
+                    // - (19 duplicate traces omitted)
+                    //
+                    // This obscures the control flow, which went from A, to B,
```
Comment (roberth) [inline src/libutil/error.cc:394]:
```suggestion
                    // This would obscure the control flow, which went from A, to B,
```

File: tests/functional/lang/eval-fail-infinite-recursion-lambda.err.exp [hunk 11]
```diff
@@ -0,0 +1,38 @@
...
+             |           ^
+            2|
+
+       … from call site
+         at /pwd/lang/eval-fail-infinite-recursion-lambda.nix:1:14:
+            1| (x: x x) (x: x x)
+             |              ^
+            2|
+
+       (19997 duplicate traces omitted)
```
Comment (roberth) [inline tests/functional/lang/eval-fail-infinite-recursion-lambda.err.exp:32]: The trace is the whole thing.

```suggestion
       (19997 duplicate trace items omitted)
```

or maybe, if we don't consider frame to be an unnecessary term for users.

```suggestion
       (19997 duplicate frames omitted)
```

File: tests/functional/lang/eval-fail-mutual-recursion.nix [hunk 12]
```diff
@@ -0,0 +1,32 @@
+# Check that "duplicate traces omitted" clears the set of "seen traces" after
+# eliding a group of traces.
```
Comment (roberth) [inline tests/functional/lang/eval-fail-mutual-recursion.nix:2]:
```suggestion
# Check that deduplication only affects consecutive intervals, and that they
# are reported independently of any preceding sections, even if they're
# indistinguishable.
#
# In terms of the current implementation, we check that we clear
# the set of "seen traces" after eliding a group of traces.
```

Trying to phrase it more as a requirement, rather than an implementation "detail".

File: src/libutil/error.cc [hunk 13]
```diff
@@ -343,14 +421,21 @@ std::ostream & showErrorInfo(std::ostream & out, const ErrorInfo & einfo, bool s
...
-            oss << "\n" << "… " << trace.hint.str() << "\n";
-
-            if (printPosMaybe(oss, ellipsisIndent, trace.pos))
-                count++;
+            printTrace(trace);
         }
+
+        printSkippedTracesMaybe();
         oss << "\n" << prefix;
     }
```
Comment (roberth) [inline src/libutil/error.cc:440]: thought: If the algorithm could be factored out, it'd be easier to understand and improve.

thought: One possible improvement is to make it understand that clusters of repetition can themselves repeat. This happens when you're doing some iterative thing for each node in a tree for example. Probably there's an easier improvement that I'm not thinking of.

**Review by roberth — CHANGES_REQUESTED** [review]
A stack limit is a good thing to have, regardless of the other steps we can take (ie #9627 and related issues).
We do need a setting for the limit to make sure we don't regress. See comment.

Scoped out: a page about stack behavior in the manual. This is very needed, but it would increase the scope too much. It would be appreciated very much (and improve and shorten the release note fwiw).

File: src/libutil/error.cc (hunk 7 above)
[the remark this answers is not in the document]
Comment (roberth) [reply src/libutil/error.cc]: > I wonder how costly it would be to intern positions. We quite possibly should do that anyhow, but at a future date.

We do have `PosTable`.

This PR's use case is not in the hot path, so we don't need to explore this now I think.

File: src/libutil/error.cc (hunk 13 above)
Comment (9999years) [reply src/libutil/error.cc:440]: Factored it out, although it should maybe be a class to avoid passing around so much context.

> One possible improvement is to make it understand that clusters of repetition can themselves repeat.

Yeah, I considered this but also wasn't sure of an elegant implementation. I'll keep turning it over.

File: doc/manual/rl-next/stack-overflow-segfaults.md [hunk 14]
```diff
@@ -0,0 +1,31 @@
...
+
+       at «string»:1:14:
+            1| (x: x x) (x: x x)
+             |              ^
+```
+
+Previously, infinite recursion detection in Nix only tracked _thunk_ recursion
+(for self-referential values like `pkgs`). Now, a maximum function call depth
+is enforced and errors are printed when it's exceeded. The maximum call depth
+is 10,000 for now and may be customizable in the future.
```
[the remark this answers is not in the document]
Comment (9999years) [reply doc/manual/rl-next/stack-overflow-segfaults.md:31]: Done.

**Review by roberth — COMMENTED** [review]
If you could rename `EvalState::depth` to `EvalState::callDepth` and review my suggestions for comments, I think this is good to go.

**Review by roberth — COMMENTED** [review]
Final breadcrumb

File: src/libexpr/eval.cc [hunk 15]
```diff
@@ -1505,9 +1505,27 @@ void ExprLambda::eval(EvalState & state, Env & env, Value & v)
...
+  ~CallDepth() {
+    --count;
+  }
+};
+};
 
 void EvalState::callFunction(Value & fun, size_t nrArgs, Value * * args, Value & vRes, const PosIdx pos)
 {
+    if (callDepth > evalSettings.maxCallDepth)
+        error("stack overflow").atPos(pos).template debugThrow<EvalError>();
```
Comment (roberth) [inline src/libexpr/eval.cc:1526]:
```suggestion
        error("stack overflow; max-call-depth exceeded").atPos(pos).template debugThrow<EvalError>();
```

**Review by roberth — APPROVED** [review]

**Comment by roberth** [comment]
Thank you @9999years!

File: src/libexpr/eval.cc (hunk 1 above)
Comment (bjornfor) [reply src/libexpr/eval.cc]: Apparently I'm doing something unreasonable(?), because I'm hitting 12k call depth in two expressions (both doing import-from-derivation). Luckily I can use `max-call-depth = 20000` to fix it, but I have to distribute this setting to not leak this detail to users.

What does 10k mean when translated into memory usage? Or, what's the call depth at which the Nix evaluator would segfault at before? (I guess it varies depending on platform?) Although 10k sounds a lot, I have no idea where the segfault would typically hit. 100k? 1M?
