### PR TITLE
nix-upgrade: resolve profile symlinks

### LINKED ISSUE #2175: nix upgrade-nix borks user profiles containing nix
See https://github.com/NixOS/nix/issues/2070#issuecomment-390772945 .

Hopefully can be addressed with a bit more sanity checking, some of which may benefit other situations (including user invoking commands "incorrectly").

Ideas:

Check "profile" paths (following may need tweaking):
  * Must be a symlink (can be directory today, haha)
  * Always point to a "x-N-link" in the same directory.
  * x-N-link's directly point to store path
  * (?) Should be gc roots, warn if not

On a related note, it may be worth clarifying that the link "~/.nix-profile" is in fact not at all a "profile" (of the kind mentioned in docs, accepted as arguments by commands) but rather a link to a profile.

Anyway the main issue is that upgrade-nix's autodection of profile can mistakenly pick up a "profile link"... which appears to work but silently causes problems such as profile generations no longer being gc roots, as well as other strangeness re:missing generations and whatnot.

LMK if solving the "larger" issue as described above should become a separate issue... hopefully we can fix these together!

### PR DESCRIPTION
**Pull request by LnL7**
The profile present in PATH is not necessarily the actual profile
location. User profiles are generally added as $HOME/.nix-profile
in which case the indirect profile link needs to be resolved first.

```
/home/user/.nix-profile -> /nix/var/nix/profiles/per-user/user/profile
/nix/var/nix/profiles/per-user/user/profile -> profile-15-link
/nix/var/nix/profiles/per-user/user/profile-14-link -> /nix/store/hyi4kkjh3bwi2z3wfljrkfymz9904h62-user-environment
/nix/var/nix/profiles/per-user/user/profile-15-link -> /nix/store/6njpl3qvihz46vj911pwx7hfcvwhifl9-user-environment
```

To upgrade nix here we want /nix/var/nix/profiles/per-user/user/profile-16-link
instead of /home/user/.nix-profile-1-link. The latter is not a gcroot
and would be garbage collected, resulting in a broken profile.

Fixes #2175

### CODE REVIEW

File: src/nix/upgrade-nix.cc [hunk 1]
```diff
@@ -98,11 +103,18 @@ struct CmdUpgradeNix : StoreCommand
         if (hasPrefix(where, "/run/current-system"))
             throw Error("Nix on NixOS must be upgraded via 'nixos-rebuild'");
 
-        Path profileDir;
-        Path userEnv;
+        Path profileDir = dirOf(where);
+
+        // Resolve profile to /nix/var/nix/profiles/<name> link.
```
Comment (LnL7) [inline src/nix/upgrade-nix.cc]: I'm not sure if this is the best condition, does supporting other prefixes matter here?

**Comment by LnL7** [comment]
Thanks!

I noticed there's a 2.1-maintenance branch now. Do I need to do anything to get this included there and is it close enough not to worry about 2.0?
