### PR TITLE
Guard uses of lutimes, for portability

### LINKED ISSUE #7045: lutimes not optional
**Describe the bug**

Although [configure.ac](https://github.com/NixOS/nix/blob/master/configure.ac#L81-L83) states that the lutimes function is optional, I can't build nix on a system without it. Compilation fails with
```
src/libutil/filesystem.cc:76:13: error: use of undeclared identifier 'lutimes'; did you mean 'utimes'?
        if (lutimes(link.c_str(), times))
            ^~~~~~~
            utimes
```

**Steps To Reproduce**

1. try to build nix on a system without lutimes

**Expected behavior**

It should just work around the missing lutimes, like it's done in [some parts](https://github.com/NixOS/nix/blob/master/src/libstore/local-store.cc#L568) of the code already.

**Additional context**

I'm currently trying to package nix for termux, which does not have lutimes at the moment, see [this issue](https://github.com/termux/termux-packages/issues/6176)

### PR DESCRIPTION
**Pull request by puffnfresh**
Fixes #7045

### CODE REVIEW

File: src/libfetchers/git.cc [hunk 1]
```diff
@@ -33,13 +33,17 @@ bool isCacheFileWithinTtl(const time_t now, const struct stat & st)
...
+#if HAVE_LUTIMES
   struct timeval times[2];
   times[0].tv_sec = touch_time;
   times[0].tv_usec = 0;
   times[1].tv_sec = touch_time;
   times[1].tv_usec = 0;
 
   return lutimes(path.c_str(), times) == 0;
+#else
+  return false;
```
Comment (puffnfresh) [inline src/libfetchers/git.cc:45]: Emits a warning when `false` but I have assumed that's acceptable.

File: src/libutil/filesystem.cc [hunk 2]
```diff
@@ -76,6 +77,7 @@ void createSymlink(const Path & target, const Path & link,
         if (lutimes(link.c_str(), times))
             throw SysError("setting time of symlink '%s'", link);
     }
+#endif
```
Comment (thufschmitt) [inline src/libutil/filesystem.cc:80]: That guard (and the one below which acts on essentially duplicated code :/ ) is a bit annoying because it changes the semantics and affects reproducibility. Do you know whether there's a way to emulate `lutimes` if it's absent?

Or maybe we can just ignore setting the time for the symlinks if `lutimes` isn't available and pray that it doesn't matter in practice

**Review by thufschmitt — CHANGES_REQUESTED** [review]
Mh, that's sad (and apologies, at least some of these are my doing).

Dropping these is annoying because it can make things non-reproducible (and in a way that Nix might very much not like). Not sure whether there's a good way around this

File: src/libutil/filesystem.cc (hunk 2 above)
Comment (Et7f3) [reply src/libutil/filesystem.cc:80]: > futimes() is available since glibc 2.3. lutimes() is available since glibc 2.6, and is implemented using the [utimensat](https://linux.die.net/man/2/utimensat)(2) system call, which is supported since kernel 2.6.22.

Comment (Et7f3) [reply src/libutil/filesystem.cc:80]: @jugendhacker Does termux has the mentioned function ?

**Comment by Ericson2314** [comment]
Triaged in the Nix team meeting:

- @thufschmitt: `lutimes` is a syscall that's not available everywhere 
    - its for getting file timestamps while observing symlinks
    - this is relevant for termux
- @edolstra: don't really believe in `autoconf` checks and its philosophy
    - should just have conditionals
- assigned to @Ericson2314 to fix the `autoconf` checks           
  - related: https://github.com/NixOS/nix/issues/7045

**Comment by Ericson2314** [comment]
https://github.com/NixOS/nix/pull/8504 removed the dead code, now there are just two `lutimes` to deduplicate left.

**Comment by fricklerhandwerk** [comment]
This should be good to go, @thufschmitt @Ericson2314 do you want to take another look?

File: src/libutil/file-system.hh [hunk 3]
```diff
@@ -165,6 +166,15 @@ inline Paths createDirs(PathView path)
     return createDirs(Path(path));
 }
 
+/**
+ * Set the access and modification times of the given path, not
+ * following symlinks.
+ *
+ * Whether or not the path is a symlink is taken from the mode of `st`
+ * in fallback code.
```
Comment (thufschmitt) [inline src/libutil/file-system.hh:174]: I don't think that precision really makes sense without the context of that PR (what's “fallback mode”?)

Besides that, I don't think we should trust `st` to tell us whether the file is a symlink or not. Barring possible race conditions (which I think we can't avoid any way), there's no guaranty that `st` refers to the path at `path` (might have been a totally made up struct just to set the time, or taken from another file). We should rather re-check within the function ([std::filesystem::is_symlink](https://en.cppreference.com/w/cpp/filesystem/is_symlink) being our friend here I guess)

**Review by thufschmitt — CHANGES_REQUESTED** [review]

File: src/libutil/file-system.hh (hunk 3 above)
Comment (Ericson2314) [reply src/libutil/file-system.hh:174]: fallback mode is without `lutimes`, with just `utimes` (yes, this should be reworded)

> Besides that, I don't think we should trust `st` to tell us whether the file is a symlink or not. 

Note that this is not a new thing. I agree in principle, but how would you update `canonicaliseTimestampAndPermissions` in practice? It is, already, very geared about working from a prior stat (in a context that we don't think things would change without them looking.

Unless we want to scope creep and overhaul `canonicaliseTimestampAndPermissions`, I think it would be good to just document the race condition on this function and say callers must be confident `st` is up to date.

Comment (Ericson2314) [reply src/libutil/file-system.hh]: OK this is done now. the `struct stat` way still exists, but is not forced upon eveyone else.

**Review by Ericson2314 — APPROVED** [review]
@thufschmitt's request is addressed. All the compat is a bit gnarly, but future improvements are possible.
