### PR TITLE
addMultipleToStore(): Move pathsToCopy

### LINKED ISSUE #7359: Copying lots of paths fails with "too many root sets"
**Describe the bug**

```
$ nix copy ./*.drv --to ssh-ng://root@54.229.150.174 --derivation
warning: error: SQLite database '/nix/var/nix/db/db.sqlite' is busy
[1147 copied (17.0 MiB), 5.2 MiB DL] copying 44430 pathsToo many root sets
Aborted (core dumped)

[linus@geruest:~/nixpkgs/master/to-build]$ terminate called after throwing an instance of 'nix::EndOfFile'
  what():  error: unexpected end-of-file
```

**Steps To Reproduce**

1. Get lots of drvs (546, all the NixOS test drvs for a nixpkgs checkout in my case)
2. Try copying them to a remote machine using `nix copy --to ssh-ng://root@$host ./*.drv` or similar

**Expected behavior**

Successful copy, or useful error message

**`nix-env --version` output**

`nix-env (Nix) 2.12.0pre20221116_561440b`

### PR DESCRIPTION
**Pull request by edolstra**
## Motivation

This allows `RemoteStore::addMultipleToStore()` to free the `Source` objects early (and in particular the associated `sinkToSource()` buffers). This should fix #7359. For example, memory consumption of

```
$ nix copy --derivation --to ssh-ng://localhost?remote-store=/tmp/nix --derivation --no-check-sigs \
    /nix/store/4p9xmfgnvclqpii8pxqcwcvl9bxqy2xf-nixos-system-...drv
```

went from 353 MB to 74 MB.

This fix is an alternative to (or in addition to) #12255.

## Context

- #7359
- #12255

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

File: src/libstore/remote-store.cc [hunk 1]
```diff
@@ -534,21 +534,24 @@ void RemoteStore::addToStore(const ValidPathInfo & info, Source & source,
...
-    PathsSource & pathsToCopy,
+    PathsSource && pathsToCopy,
     Activity & act,
     RepairFlag repair,
     CheckSigsFlag checkSigs)
 {
     auto source = sinkToSource([&](Sink & sink) {
         sink << pathsToCopy.size();
-        for (auto & [pathInfo, pathSource] : pathsToCopy) {
+        std::reverse(pathsToCopy.begin(), pathsToCopy.end());
```
Comment (roberth) [inline src/libstore/remote-store.cc:544]:
```suggestion
        // Reverse, so we can release memory at the original start
        std::reverse(pathsToCopy.begin(), pathsToCopy.end());
```

**Review by roberth — APPROVED** [review]
A proper streaming abstraction might be nicer, but this solves the problem adequately.
