### PR TITLE
Fix Git LFS SSH issues

### LINKED ISSUE #13337: git lfs inputs don't work when ssh is not listening on the default port
## Describe the bug

Everthing works fine with e.g. the following input

```
inputs = {
  bla = {
    url = "ssh://myuser@myserver/username/reponame.git";
    type = "git";
    ref = "main";
    flake = false;
    lfs = true;
  }
};

```
but it breaks with the following

```
inputs = {
  bla = {
    url = "ssh://myuser@myserver:3022/username/reponame.git";
    type = "git";
    ref = "main";
    flake = false;
    lfs = true;
  }
};
```

```
ssh: Could not resolve hostname myserver:3022: Name or service not known
error:
       … while updating the lock file of flake 'path:/mypath?lastModified=1749391096&narHash=sha256-WzaUJw3/ORsoa7QfNaZT0ja/5wngsVXaSUfgw/Y7ImM%3D'

       … while updating the flake input 'bla'

       … while smudging git-lfs file '/myfile'

       error: git-lfs-authenticate: no output (cmd: ssh myser@myserver:3022 git-lfs-authenticate /username/reponame.git download)
```

it seems to me the command is wrong. 

it should have used `ssh myser@myserver -p3022 git-lfs-authenticate /username/reponame.git download` instead .

cloning from` ssh://myuser@myserver:3022/username/reponame.git` and doing a `git lfs pull` manually works just fine. so i think it's a nix specific problem and not a git-lfs one. 

## Steps To Reproduce

Set up a git server with lfs support and let ssh listen on a port other than 22. 
Create a repo, add some lfs objects. try to use it in a flake via ssh. 

## Expected behavior

That it fetches the lfs objects

## Metadata

nix-env (Nix) 2.28.3

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open bug issues and pull requests] for possible duplicates

[latest Nix manual]: https://nixos.org/manual/nix/unstable/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by kip93**
## Motivation

* Adds support for `NIX_SSHOPTS`
* Properly uses the parsed port from URL (fixes #13337)
* Don't guess the HTTP endpoint, use the response of `git-lfs-authenticate`
* Add an SSH Git LFS test
* Removed some unused test code

## Context

Fixes some outstanding issues with Git LFS and SSH. (See #13337 and the `FIXME` in the old code)

For the tests, I had to change to clone from Gitea rather than pure SSH so that we can test fetching LFS files from an SSH server.

Also, renamed the `gitea_admin` to `gitea_user` in the tests since that user is not really an admin and it threw me for a loop until I realized why I was having issues with some of the Gitea API endpoints.

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

File: src/libfetchers/git-lfs-fetch.cc [hunk 1]
```diff
@@ -27,8 +28,8 @@ static void downloadToSink(
 {
     FileTransferRequest request(url);
     Headers headers;
-    if (!authHeader.empty())
-        headers.push_back({"Authorization", authHeader});
+    if (authHeader != std::nullopt)
+        headers.push_back({"Authorization", *authHeader});
```
Comment (xokdvium) [inline src/libfetchers/git-lfs-fetch.cc]:
```suggestion
    if (authHeader.has_value())
        headers.push_back({"Authorization", *authHeader});
```

File: src/libfetchers/git-lfs-fetch.cc [hunk 2]
```diff
@@ -18,7 +19,7 @@ namespace nix::lfs {
 // if authHeader is "", downloadToSink assumes no auth is expected
 static void downloadToSink(
     const std::string & url,
-    const std::string & authHeader,
+    const std::optional<const std::string> & authHeader,
```
Comment (xokdvium) [inline src/libfetchers/git-lfs-fetch.cc]:
```suggestion
    const std::optional<std::string> & authHeader,
```

`std::optional` already propagates const.

File: src/libfetchers/git-lfs-fetch.cc [hunk 3]
```diff
@@ -42,30 +43,54 @@ static void downloadToSink(
             "hash mismatch while fetching %s: expected sha256:%s but got sha256:%s", url, sha256Expected, sha256Actual);
 }
 
-static std::string getLfsApiToken(const ParsedURL & url)
+static std::tuple<std::string, std::optional<std::string>> getLfsApi(const ParsedURL & url)
```
Comment (xokdvium) [inline src/libfetchers/git-lfs-fetch.cc]:
```suggestion
namespace {

struct LfsApiInfo {
  std::string endpoint;
  std::optional<std::string> authorization;
};

} // namespace

static LfsApiInfo getLfsApi(const ParsedURL & url)
```

File: src/libfetchers/git-lfs-fetch.cc [hunk 4]
```diff
@@ -42,30 +43,54 @@ static void downloadToSink(
...
+        std::string sshOpts = getEnv("NIX_SSHOPTS").value_or("");
+
+        try {
+            std::list<std::string> opts = shellSplitString(sshOpts);
+            for (auto & i : opts)
+                args.push_back(i);
+        } catch (Error & e) {
+            e.addTrace({}, "while splitting NIX_SSHOPTS '%s'", sshOpts);
+            throw;
+        }
```
Comment (xokdvium) [inline src/libfetchers/git-lfs-fetch.cc]: We already have this code in `src/libstore/ssh.cc`. Could you factor it out into a separate function maybe? That could probably live in libstore for now.

Maybe something like:

```cpp
Strings getNixSshOpts() {
    static const std::string sshOpts = getEnv("NIX_SSHOPTS").value_or("");

    try {
        return shellSplitString(sshOpts);
    } catch (Error & e) {
        e.addTrace({}, "while splitting NIX_SSHOPTS '%s'", sshOpts);
        throw;
    }
}
```

File: src/libfetchers/git-lfs-fetch.cc [hunk 5]
```diff
@@ -181,13 +206,14 @@ static nlohmann::json pointerToPayload(const std::vector<Pointer> & items)
...
-    FileTransferRequest request(httpUrl.to_string() + "/info/lfs/objects/batch");
+    auto api = lfs::getLfsApi(this->url);
+    auto url = std::get<0>(api) + "/objects/batch";
+    auto authHeader = std::get<1>(api);
+    FileTransferRequest request(url);
     request.post = true;
     Headers headers;
-    if (this->url.scheme == "ssh")
-        headers.push_back({"Authorization", lfs::getLfsApiToken(this->url)});
+    if (authHeader != std::nullopt)
```
Comment (xokdvium) [inline src/libfetchers/git-lfs-fetch.cc]:
```suggestion
    if (authHeader.has_value())
```

File: tests/nixos/fetch-git/testsupport/gitea.nix [hunk 6]
```diff
@@ -118,13 +105,8 @@ in
       echo "Host gitea" >>~/.ssh/config
       echo "  StrictHostKeyChecking no" >>~/.ssh/config
       echo "  UserKnownHostsFile /dev/null" >>~/.ssh/config
-      echo "  User root" >>~/.ssh/config
+      echo "  Port 3001" >>~/.ssh/config
```
Comment (xokdvium) [inline tests/nixos/fetch-git/testsupport/gitea.nix]: I feel like this is going to make the tests less effective for testing that nix passes the correct port on the command line. Is this strictly necessary?

File: src/libfetchers/git-lfs-fetch.cc [hunk 7]
```diff
@@ -42,30 +43,54 @@ static void downloadToSink(
...
-
-    auto queryResp = nlohmann::json::parse(output);
-    if (!queryResp.contains("header"))
-        throw Error("no header in git-lfs-authenticate response");
-    if (!queryResp["header"].contains("Authorization"))
-        throw Error("no Authorization in git-lfs-authenticate response");
-
-    return queryResp["header"]["Authorization"].get<std::string>();
+        if ((*url.authority).port)
+            args.push_back(fmt("-p%d", *(*url.authority).port));
```
Comment (xokdvium) [inline src/libfetchers/git-lfs-fetch.cc]:
```suggestion
        if (url.authority->port)
            args.push_back(fmt("-p%d", *url.authority->port));
```

File: src/libfetchers/git-lfs-fetch.cc [hunk 8]
```diff
@@ -42,30 +43,54 @@ static void downloadToSink(
...
+
+        std::ostringstream hostnameAndUser;
+        if ((*url.authority).user)
+            hostnameAndUser << *(*url.authority).user << "@";
```
Comment (xokdvium) [inline src/libfetchers/git-lfs-fetch.cc]:
```suggestion
        if (url.authority->user)
            hostnameAndUser << *url.authority->user << "@";
```

File: src/libfetchers/git-lfs-fetch.cc [hunk 9]
```diff
@@ -42,30 +43,54 @@ static void downloadToSink(
...
+        hostnameAndUser << (*url.authority).host;
```
Comment (xokdvium) [inline src/libfetchers/git-lfs-fetch.cc]:
```suggestion
        hostnameAndUser << url.authority->host;
```

File: tests/nixos/fetch-git/testsupport/gitea.nix (hunk 6 above)
Comment (kip93) [reply tests/nixos/fetch-git/testsupport/gitea.nix]: Not necessary, it worked fine without it.
