### PR TITLE
Deduplicate string literal rendering, fix 4909

### LINKED ISSUE #4909: nix repl renders strings improperly escaped
**Describe the bug**

`nix repl` prints string values improperly sometimes where pasting the printed expression back into the repl would result in a syntax error due to missing escaping.

**Steps To Reproduce**

Evaluate `''''${checkFlagsArray[@]}''` or `"\${checkFlagsArray[@]}"` into `nix repl` and paste the printed result back:

```
nix-repl> ''''${checkFlagsArray[@]}'' 
"${checkFlagsArray[@]}"

nix-repl> "\${checkFlagsArray[@]}"    
"${checkFlagsArray[@]}"

nix-repl> "${checkFlagsArray[@]}"
error: syntax error, unexpected '@'

       at «string»:1:20:

            1| "${checkFlagsArray[@]}"
             |                    ^
            2|
```

**Expected behavior**

`nix repl` prints `"\${checkFlagsArray[@]}"`

**Additional context**

Affects `nixUnstable` and `nix` 2.13.11.

### PR DESCRIPTION
**Pull request by roberth**
# Motivation

Repay some tech debt and fix #4909

# Context

 - Fixes #4909

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [ ] agreed on idea
 - [ ] agreed on implementation strategy
 - [ ] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests - `tests/nixos/*`
 - [ ] documentation in the manual
 - [ ] documentation in the internal API docs
 - [ ] code and comments are self-explanatory
 - [ ] commit message explains why the change was made
 - [ ] new feature or incompatible change: updated release notes

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

### CODE REVIEW

File: src/libexpr/value/print.cc [hunk 1]
```diff
@@ -0,0 +1,26 @@
+#include "value/print.hh"
+
+namespace nix {
+
+std::ostream &
+printLiteral(std::ostream & str, const std::string_view string) {
```
Comment (edolstra) [inline src/libexpr/value/print.cc:6]:
```suggestion
printLiteral(std::ostream & str, const std::string_view string) 
{
```

File: src/libexpr/value/print.cc [hunk 2]
```diff
@@ -0,0 +1,26 @@
...
+        else if (*i == '\t') str << "\\t";
+        else if (*i == '$' && *(i+1) == '{') str << "\\" << *i;
+        else str << *i;
+    }
+    str << "\"";
+    return str;
+}
+
+std::ostream &
+printLiteral(std::ostream & str, bool boolean) {
```
Comment (edolstra) [inline src/libexpr/value/print.cc:21]:
```suggestion
printLiteral(std::ostream & str, bool boolean) 
{
```

File: src/libexpr/value/print.hh [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+
+namespace nix {
+    /**
+     * Print a string as a Nix string literal.
+     *
+     * Quotes and fairly minimal escaping are added.
+     *
+     * @param s The logical string
+     */
+    std::ostream & printLiteral(std::ostream & o, std::string_view s);
```
Comment (edolstra) [inline src/libexpr/value/print.hh:20]: I'm not sure if this overloaded `printLiteral` function (as opposed to `printBool`, `printString` etc.) is a good idea. For instance, at some point somebody is going to do `printLiteral(null)`, expecting a `null` value to be printed, but instead it will call the `char *` overload...

File: src/libstore/derivations.cc [hunk 4]
```diff
@@ -313,6 +313,15 @@ Derivation parseDerivation(const Store & store, std::string && s, std::string_vi
...
 
+/**
+ * Print a derivation string literal to an std::string.
+ *
+ * This syntax does not generalize to the expression language, which needs to
+ * escape `$`.
+ *
+ * @param res Where to print to
+ * @param s Which logical string to print
+ */
```
Comment (edolstra) [inline src/libstore/derivations.cc:324]: Maybe this function should be moved to `print.cc`?

File: src/libexpr/value/print.cc [hunk 5]
```diff
@@ -0,0 +1,26 @@
+#include "value/print.hh"
```
Comment (edolstra) [inline src/libexpr/value/print.cc:1]: It seems a bit arbitrary to introduce a "value" subdirectory, when nothing else value-related is there...

Comment (Ericson2314) [reply src/libexpr/value/print.cc:1]: We already have a value subdirectory. I previously made `value/context.{hh,cc}` on analogy with `primops/context.cc`. String contexts are part of string values.

File: src/libstore/derivations.cc (hunk 4 above)
Comment (Ericson2314) [reply src/libstore/derivations.cc:324]: Which `print.cc`? This is for the aterm printing of dervations, and part of the store layer.

Comment (Ericson2314) [reply src/libstore/derivations.cc:324]: I certainly wouldn't mind say having `derivation/{aterm,json}.{cc.hh}` to separate data types from serialization, and put both serializations on equal footing, but that seems like a separate PR to me.

File: src/libstore/derivations.cc [hunk 6]
```diff
@@ -313,6 +313,15 @@ Derivation parseDerivation(const Store & store, std::string && s, std::string_vi
 }
 
 
+/**
+ * Print a derivation string literal to an std::string.
```
Comment (Ericson2314) [inline src/libstore/derivations.cc:317]:
```suggestion
 * Print a derivation string literal to an `std::string`.
```

File: src/libstore/derivations.cc (hunk 4 above)
Comment (roberth) [reply src/libstore/derivations.cc:324]: Not feasible, because that's a different library. We should keep these separate. As mentioned in the comment, this is a different function.
I can remove this mention of the language completely if we want to be very (overly?) thorough about libstore not depending on libexpr. Personally I think there's value in cross-referencing components in both directions, although this may not be the brightest example.

File: src/libexpr/value/print.hh (hunk 3 above)
Comment (roberth) [reply src/libexpr/value/print.hh]: Done. It's `printLiteralString` now, so that it's explicit which kind of literal will be rendered; same for `printLiteralBool`.
I've kept the "literal" part because I've renamed the file to cover relevant parts of the whole language, not just the values.

File: src/libexpr/value/print.cc (hunk 5 above)
Comment (roberth) [reply src/libexpr/value/print.cc]: While `value/` was not a terrible choice, generalizing the file to allow printing all of the language is more useful. I've renamed it to just `print.{cc,hh}` in the `libexpr` top level.

**Comment by roberth** [comment]
I've moved the file to the libexpr top level, so that it's more useful. `printIdentifier` and `printAttributeName` are now also in the file, highlight some more tech debt. I won't resolve that in this PR though, because that would not be as reviewable:

 - First commit has the only behavioral change
 - The other ones are pure refactoring; no change in behavior

**Review by Ericson2314 — APPROVED** [review]
