### PR TITLE
fix `nix help-stores` for 2.19

### LINKED ISSUE #10037: nix help-stores stopped working in nix 2.19
**Describe the bug**

`nix help-stores` prints an evaluation error

**Steps To Reproduce**

```
 % nix help-stores
error:
       … while evaluating the lowdown help text

       … while evaluating a branch condition

         at /utils.nix:20:7:

           19|     in
           20|       if replaced == string then string else replaceStringsRec from to replaced;
             |       ^
           21|

       … while calling the 'replaceStrings' builtin

         at /utils.nix:18:18:

           17|     let
           18|       replaced = replaceStrings [ from ] [ to ] string;
             |                  ^
           19|     in

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: path '/generate-store-info.nix' does not exist
```

**Expected behavior**

nix help-stores shows a man-page with documentatio n

**`nix-env --version` output**
```
% nix --version
nix (Nix) 2.19.2
```

**Additional context**

Using the determinate systems nix  installer

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by fricklerhandwerk**
# Motivation
fixes #10037

# Context
the crash when calling `nix help-stores` was probably introduced an artifact from a prior untangling of merge conflicts. that said, `nix help-stores` should eventually cease to exist in favor of dedicated `--help` outputs and `man` pages for the various store types.

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

### CODE REVIEW

**Comment by thufschmitt** [comment]
Care to add a small test for it? Just check that the command succeeds

File: tests/functional/help.sh [hunk 1]
```diff
@@ -0,0 +1,140 @@
...
+nix store make-content-addressed --help
+nix store optimise --help
+nix store path-from-hash-part --help
+nix store ping --help
+nix store prefetch-file --help
+nix store repair --help
+nix store sign --help
+nix store verify --help
+nix upgrade-nix --help
+nix why-depends --help
```
Comment (edolstra) [inline tests/functional/help.sh:140]: This list seems like overkill and a pain to maintain. If we *really* want to test the help of every command, it's better to do something like `nix __dump-cli | jq .args.commands ...` to extract the list of commands.

**Comment by fricklerhandwerk** [comment]
Updated as in https://github.com/NixOS/nix/pull/10143

**Review by thufschmitt — APPROVED** [review]
