### PR TITLE
repl: fix history truncation of long lines

### LINKED ISSUE #15162: `nix repl` splits long lines in `repl-history`
## Describe the bug

Lines more than 255 characters long are split in `repl-history`, making it much harder to reuse the command history.

## Steps To Reproduce

1. Run `nix repl`
2. Run a single-line command which is longer than 255 characters, such as `nixosConfigurations.ci-full-unstable.pkgs.lib.filterAttrs (n: v: n != "frp" && v.enable.isDefined or false && v.enable.value) (checks.x86_64-linux.androidBackupService.extendNixOS { module = { options, ... }: { passthru = { inherit options; }; }; }).node.machine.passthru.options.services`
3. Exit `nix repl`

Observe the split command in `repl-history`.

## Expected behavior

`repl-history` should contain the command above on a single line.

## Metadata

nix-env (Nix) 2.31.3

## Checklist

- [ ] checked [latest Nix manual] \([source])
- [ ] checked [open bug issues and pull requests] for possible duplicates

[latest Nix manual]: https://nix.dev/manual/nix/development/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by amaanq**
## Motivation

Editline's `read_history` uses `fgets(buf, 256, fp)` internally, splitting
any line longer than 255 characters into multiple history entries. This
commit bypasses it with `std::getline` and `add_history` calls, which
handle arbitrary lengths. GNU readline's `read_history` has no such limit
and is left as-is, and `write_history` already writes full lines via
`fprintf` so it needs no change either.

## Context

- Fixes #15162

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

File: src/libcmd/repl-interacter.cc [hunk 1]
```diff
@@ -124,8 +121,17 @@ ReadlineLikeInteracter::Guard ReadlineLikeInteracter::init(detail::ReplCompleter
...
     el_hist_size = 1000;
-#endif
+    // editline's read_history uses a fixed 256-byte buffer (SCREEN_INC),
+    // which silently splits lines longer than 255 characters into separate
+    // history entries. Use std::getline instead, which has no length limit.
+    if (std::ifstream ifs(historyFile); ifs.good()) {
+        std::string line;
+        while (std::getline(ifs, line))
+            add_history(line.c_str());
+    }
```
Comment (xokdvium) [inline src/libcmd/repl-interacter.cc]: Can't we use `FdSource` + `.readLine` here? fstreams are kinda messy error handling is a pain. I wouldn't object if we made this code path unconditional too even for readline.

File: src/libcmd/repl-interacter.cc [hunk 2]
```diff
@@ -119,8 +120,16 @@ ReadlineLikeInteracter::Guard ReadlineLikeInteracter::init(detail::ReplCompleter
     }
 #if !USE_READLINE
     el_hist_size = 1000;
-#endif
+    // editline's read_history uses a fixed 256-byte buffer (SCREEN_INC),
+    // which silently splits lines longer than 255 characters into separate
+    // history entries. Read the file ourselves to avoid the length limit.
+    try {
+        for (auto & line : tokenizeString<std::vector<std::string>>(readFile(historyFile), "\n"))
+            add_history(line.c_str());
```
Comment (xokdvium) [inline src/libcmd/repl-interacter.cc]: Not a fan of loading everything into memory. Why not FdSource + readLine (suggested below)?

Comment (amaanq) [reply src/libcmd/repl-interacter.cc]: Ahh yeah that is probably better, was just trying stuff out and pushed a bit early :sweat_smile:

File: src/libutil/windows/file-system.cc [hunk 3]
```diff
@@ -47,6 +47,18 @@ Descriptor openFileReadonly(const std::filesystem::path & path)
...
+    AutoCloseFD fd = openFileReadonly(path);
+    if (!fd) {
+        auto err = GetLastError();
+        if (err == ERROR_FILE_NOT_FOUND || err == ERROR_PATH_NOT_FOUND)
+            return {};
+        throw windows::WinError(err, "opening file %s", PathFmt(path));
+    }
+    return fd;
+}
+
```
Comment (Ericson2314) [inline src/libutil/windows/file-system.cc]: @xokdvium Can't we just catch `SystemError` and use the portable error codes for this?

Comment (xokdvium) [reply src/libutil/windows/file-system.cc]: openFileReadonly doesn't throw

Comment (Ericson2314) [reply src/libutil/windows/file-system.cc]: @xokdvium we can make a `NativeSysError` and then check it's error code.

Or maybe it should return `std::variant<AutoCloseFD, std::errc>`.

Comment (xokdvium) [reply src/libutil/windows/file-system.cc]: Or we could start using boost::outcome or std::expected (I imagine macOS support for it isn't quite there yet)

File: src/libutil/file-system.cc [hunk 4]
```diff
@@ -265,10 +265,22 @@ std::string readFile(const std::filesystem::path & path)
...
 
+AutoCloseFD maybeOpenFileReadonly(const std::filesystem::path & path)
+{
+    AutoCloseFD fd = openFileReadonly(path);
+    if (!fd) {
+        NativeSysError err("opening file %s", PathFmt(path));
+        if (err.is(std::errc::no_such_file_or_directory) || err.is(std::errc::not_a_directory))
+            return {};
+        throw err;
+    }
```
Comment (xokdvium) [inline src/libutil/file-system.cc]: Would be nicer if we had a `Result` type that could contain the NativeSysError instead. Catching exceptions is kinda expensive

Comment (amaanq) [reply src/libutil/file-system.cc]: Hm that would be nice, but is that out of scope for this PR? I'd be happy to implement it if it'd be useful in general though

Comment (Ericson2314) [reply src/libutil/file-system.cc]: I think we can just have no `maybeOpenFileReadonly` for now. The naming is confusing anyways since `openFileReadonly` never throws.

**Review by Ericson2314 — APPROVED** [review]

**Review by Ericson2314 — APPROVED** [review]

**Comment by andir** [comment]
I don't thinkt the test is working. When I run the repl through `unbuffer` it does indeed not crash any more. When I just run the repl from the current master branch it will crash while calling `hist_add` during the repl init.
```
gdb) bt
#0  0x00007fb4da9a0706 in hist_add () from /nix/store/n0jys3rah5s1162iy4yps7zli7fg8qgz-editline-1.17.1-unstable-2025-05-24/lib/libeditline.so.1
#1  0x00007fb4dbef70de in nix::ReadlineLikeInteracter::init(nix::detail::ReplCompleterMixin*) ()
   from /nix/store/5fi3fhl1c4gs38ca0v91ffb1yq9raz4w-nix-cmd-2.35.0pre/lib/libnixcmd.so.2.35.0
#2  0x00007fb4dbef732a in nix::NixRepl::mainLoop() () from /nix/store/5fi3fhl1c4gs38ca0v91ffb1yq9raz4w-nix-cmd-2.35.0pre/lib/libnixcmd.so.2.35.0
#3  0x00005603f1797eb0 in nix::CmdRepl::run(nix::ref<nix::Store>, std::vector<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&&) ()
#4  0x00007fb4dbee9041 in nix::RawInstallablesCommand::run(nix::ref<nix::Store>) ()
   from /nix/store/5fi3fhl1c4gs38ca0v91ffb1yq9raz4w-nix-cmd-2.35.0pre/lib/libnixcmd.so.2.35.0
#5  0x00007fb4dbebe7af in nix::StoreCommand::run(nix::ref<nix::StoreConfig>) ()
   from /nix/store/5fi3fhl1c4gs38ca0v91ffb1yq9raz4w-nix-cmd-2.35.0pre/lib/libnixcmd.so.2.35.0
#6  0x00007fb4dbebe908 in virtual thunk to nix::StoreConfigCommand::run() ()
   from /nix/store/5fi3fhl1c4gs38ca0v91ffb1yq9raz4w-nix-cmd-2.35.0pre/lib/libnixcmd.so.2.35.0
#7  0x00005603f176490d in nix::mainWrapped(int, char**) ()
#8  0x00007fb4dca63925 in nix::handleExceptions(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, nix::fun<void ()>) () from /nix/store/yhxk8iyb62hkjss61l5a29x9xsbriyxx-nix-util-2.35.0pre/lib/libnixutil.so.2.35.0
#9  0x00005603f16c0513 in main ()
(gdb) disas
Dump of assembler code for function hist_add:
   0x00007fb4da9a06a0 <+0>:	push   %rbp
   0x00007fb4da9a06a1 <+1>:	mov    %rsp,%rbp
   0x00007fb4da9a06a4 <+4>:	push   %r15
   0x00007fb4da9a06a6 <+6>:	push   %r14
   0x00007fb4da9a06a8 <+8>:	push   %r13
   0x00007fb4da9a06aa <+10>:	push   %r12
   0x00007fb4da9a06ac <+12>:	mov    %rdi,%r12
   0x00007fb4da9a06af <+15>:	push   %rbx
   0x00007fb4da9a06b0 <+16>:	sub    $0x8,%rsp
   0x00007fb4da9a06b4 <+20>:	mov    0x92a6(%rip),%ebx        # 0x7fb4da9a9960 <H>
   0x00007fb4da9a06ba <+26>:	test   %ebx,%ebx
   0x00007fb4da9a06bc <+28>:	je     0x7fb4da9a06d7 <hist_add+55>
   0x00007fb4da9a06be <+30>:	mov    0x92a3(%rip),%rdx        # 0x7fb4da9a9968 <H+8>
   0x00007fb4da9a06c5 <+37>:	lea    -0x1(%rbx),%eax
   0x00007fb4da9a06c8 <+40>:	cltq
   0x00007fb4da9a06ca <+42>:	mov    (%rdx,%rax,8),%rsi
   0x00007fb4da9a06ce <+46>:	call   0x7fb4da9a0200 <strcmp@plt>
   0x00007fb4da9a06d3 <+51>:	test   %eax,%eax
   0x00007fb4da9a06d5 <+53>:	je     0x7fb4da9a0711 <hist_add+113>
   0x00007fb4da9a06d7 <+55>:	mov    %r12,%rdi
   0x00007fb4da9a06da <+58>:	call   0x7fb4da9a0360 <strdup@plt>
   0x00007fb4da9a06df <+63>:	mov    %rax,%r12
   0x00007fb4da9a06e2 <+66>:	test   %rax,%rax
   0x00007fb4da9a06e5 <+69>:	je     0x7fb4da9a0711 <hist_add+113>
   0x00007fb4da9a06e7 <+71>:	mov    0x88aa(%rip),%r14        # 0x7fb4da9a8f98
   0x00007fb4da9a06ee <+78>:	mov    0x9273(%rip),%r13        # 0x7fb4da9a9968 <H+8>
   0x00007fb4da9a06f5 <+85>:	cmp    (%r14),%ebx
   0x00007fb4da9a06f8 <+88>:	jg     0x7fb4da9a0730 <hist_add+144>
   0x00007fb4da9a06fa <+90>:	lea    0x1(%rbx),%eax
   0x00007fb4da9a06fd <+93>:	mov    %eax,0x925d(%rip)        # 0x7fb4da9a9960 <H>
   0x00007fb4da9a0703 <+99>:	movslq %ebx,%rax
=> 0x00007fb4da9a0706 <+102>:	mov    %r12,0x0(%r13,%rax,8)
   0x00007fb4da9a070b <+107>:	mov    %ebx,0x9253(%rip)        # 0x7fb4da9a9964 <H+4>
   0x00007fb4da9a0711 <+113>:	add    $0x8,%rsp
   0x00007fb4da9a0715 <+117>:	pop    %rbx
   0x00007fb4da9a0716 <+118>:	pop    %r12
   0x00007fb4da9a0718 <+120>:	pop    %r13
--Type <RET> for more, q to quit, c to continue without paging--q
❌️ Quit
(gdb) 
```

I'm not entirely sure whats going on there.. but perhaps we are missing some other initialization code.

The ` || true` in the repl test command is also kind of strange. Why is that needed? Wouldn't it silence things like a non-zero exit call if that were still the case?

**Comment by xokdvium** [comment]
Meh, somebody forgor to call `rl_initialize`. Will put up a fix now.

@Ericson2314, @amaanq please be more careful and at least run the code. I'm going to fix this mess, but I don't enjoy having to constantly clean up regressions.

**Comment by xokdvium** [comment]
What's even the purpose of `unbuffer` here? The comment is completely wrong, just piping in the input is enough to catch this bug. This is a flaming pile of garbage.

**Comment by Ericson2314** [comment]
Sorry @xokdvium, I thought (though didn't confirm with anyone) that you and @amaanq and talked about this more, and had already gone over things and all that was left was the `maybe` function stuff.
