### PR TITLE
`print-dev-env`: stop inadvertently adding `.` to `PATH`

### LINKED ISSUE #8032: `nix print-dev-env` inadvertently adds `.` to `PATH`
**Describe the bug**

When PATH is empty,

```bash
. <(nix print-dev-env)
```

will set PATH to `<dev-env-path>:`, and bash will correctly interpret the trailing `:` as `:.`.

**Steps To Reproduce**

```bash
$ nix print-dev-env nixpkgs#hello | grep nix_saved_PATH
nix_saved_PATH="$PATH"
PATH="$PATH:$nix_saved_PATH"

$ path=$PATH
$ PATH=
$ . <(PATH=$path nix print-dev-env nixpkgs#hello)

$ echo $PATH
/nix/store/mv5gpi07yzb8m9b6829l8hkw6rpay49c-patchelf-0.15.0/bin:/nix/store/bfbp3ypd9nm3fapz634gvvs738blrl0y-gcc-wrapper-12.2.0/bin:/nix/store/wx4nsqbssywgx9zkabwgl9sxm5l61ni3-gcc-12.2.0/bin:/nix/store/lp8qrhb6hs42jwbapzq20l05jf4kyicq-glibc-2.35-224-bin/bin:/nix/store/bg8f47vihykgqcgblxkfk9sbvc4dnksa-coreutils-9.1/bin:/nix/store/i2pdyabq6nrrnisbkma71h42fw6ha0y6-binutils-wrapper-2.40/bin:/nix/store/fhzz4yrdy17czwc9i4swhlpcp445inzb-binutils-2.40/bin:/nix/store/bg8f47vihykgqcgblxkfk9sbvc4dnksa-coreutils-9.1/bin:/nix/store/8w3xxhbldw1i40a6fdcs17y6vyq3l3dd-findutils-4.9.0/bin:/nix/store/vraimqnjzzvzabh9wvw5a5s32cv5k6lc-diffutils-3.8/bin:/nix/store/4f5jnd0q8b5kj934wm202km3i8ssrl6p-gnused-4.9/bin:/nix/store/4vkv3rzky44hp2b8r13d8hr4ykvqhvwh-gnugrep-3.7/bin:/nix/store/v4dhg1im8yrl1gq1697jgwh2g85mqwr6-gawk-5.2.1/bin:/nix/store/61mzw223sdk26lxawnx64b72xgjrhaj8-gnutar-1.34/bin:/nix/store/jmx6hd6qykl0a8vxrf6pv6m8q2c0kpxn-gzip-1.12/bin:/nix/store/i4ic0p0l83i37dvx8cb1l3cicq0bny5z-bzip2-1.0.8-bin/bin:/nix/store/i36xm3qb20x9mwbigq4gh5626b0vhg9p-gnumake-4.4/bin:/nix/store/5ynbf6wszmggr0abwifdagrixgnya5vy-bash-5.2-p15/bin:/nix/store/xj8vr2sgbz3rhy26xzmg44vkzr5dww1y-patch-2.7.6/bin:/nix/store/c2kkvw6klpyf9p289si6cqv8gw4q2wb9-xz-5.4.1-bin/bin:/nix/store/s29xjzid62937vc17jx6zi785nhk0plk-file-5.44/bin:
```

**Expected behavior**

PATH above should not end in `:`.

**`nix-env --version` output**

nix-env (Nix) 2.13.2

**Additional context**

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by lbodor**
# Motivation

Ensure that `. <(nix print-dev-env)` correctly handles the case when `PATH` is empty.

# Context

Fixes #8032 by changing the output of

```bash
nix print-dev-env nixpkgs#hello | grep nix_saved_
```
from
```bash
nix_saved_PATH="$PATH"
nix_saved_XDG_DATA_DIRS="$XDG_DATA_DIRS"
PATH="$PATH:$nix_saved_PATH"
XDG_DATA_DIRS="$XDG_DATA_DIRS:$nix_saved_XDG_DATA_DIRS"
```
to
```bash
nix_saved_PATH="$PATH"
nix_saved_XDG_DATA_DIRS="$XDG_DATA_DIRS"
PATH="$PATH${nix_saved_PATH:+:$nix_saved_PATH}"
XDG_DATA_DIRS="$XDG_DATA_DIRS${nix_saved_XDG_DATA_DIRS:+:$nix_saved_XDG_DATA_DIRS}"
```

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [ ] agreed on idea
 - [ ] agreed on implementation strategy
 - [ ] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests - `tests/nixos/*`
 - [ ] documentation in the manual
 - [ ] code and comments are self-explanatory
 - [ ] commit message explains why the change was made
 - [ ] new feature or incompatible change: updated release notes

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

### CODE REVIEW

**Comment by roberth** [comment]
This looks uncontroversial. Please add test cases to `tests/nix-shell.sh`.
Looks like you'll want to change the existing test case (and your own) to run in a subshell

```diff
-source <(...
+(
+  source <(...
```

**Comment by lbodor** [comment]
I've added a test, thanks for the pointer. Please let me know what you think.

File: tests/nix-shell.sh [hunk 1]
```diff
@@ -94,16 +94,43 @@ echo foo | nix develop -f "$shellDotNix" shellDrv -c cat | grepQuiet foo
 nix develop -f "$shellDotNix" shellDrv -c echo foo |& grepQuiet foo
 
 # Test 'nix print-dev-env'.
-[[ $(nix print-dev-env -f "$shellDotNix" shellDrv --json | jq -r .variables.arr1.value[2]) = '3 4' ]]
+
+scratch=$(mktemp -d -t tmp.XXXXXXXXXX)
+function finish {
+    rm -rf "$scratch"
+}
+trap finish EXIT
```
Comment (edolstra) [inline tests/nix-shell.sh:102]: No need for a separate scratch directory, just use `$TEST_ROOT` instead of `$scratch`.

**Review by roberth — APPROVED** [review]
