### PR TITLE
eval: Fix crash on missing printValue tBlackhole case

### LINKED ISSUE #8119: Aborted (core dumped) trying to builtins.trace at specialArgs
**Describe the bug**

I get `Aborted (core dumped) "$@"` if I try to `specialArgs = builtins.trace inputs inputs` in my system flake. Tested on 2 different systems (the one below is a VM).

Nothing else changed in the `configuration.nix` (which was entirely different between the two systems).

```console
[root@nixosvm:/etc/nixos]# nixos-rebuild switch
/run/current-system/sw/bin/nixos-rebuild: line 167:  1147 Aborted                 (core dumped) "$@"
```

```nix
{
  description = "NixOS VM";
  inputs.nixpkgs.url = "nixpkgs/nixos-22.05";
  outputs =
    { self
    , nixpkgs
    } @ attrs:
    let
      system = "aarch64-linux";
    in
    {
      nixosConfigurations.nixosvm = nixpkgs.lib.nixosSystem
        {
          inherit system;
          specialArgs = builtins.trace attrs attrs;
          modules = [
            ./configuration.nix
          ];
        };
    };
}
```

**Expected behavior**

Either work or given an error with an explanation.

**`nix-env --version` output**

```
[root@nixosvm:/etc/nixos]# nix-env --version
nix-env (Nix) 2.13.3
```
**Additional context**

I wonder if related:

- https://github.com/NixOS/nix/issues/7383
- https://github.com/NixOS/nix/issues/7280
- https://github.com/NixOS/nix/issues/6772

### PR DESCRIPTION
**Pull request by roberth**
# Motivation

~Very motivated. I hate crashes.~

This fixes a bug.

# Context

Fixes #8119

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [ ] agreed on idea
 - [ ] agreed on implementation strategy
 - [x] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests - `tests/nixos/*`
 - [ ] documentation in the manual
 - [x] code and comments are self-explanatory
 - [x] commit message explains why the change was made
 - [ ] new feature or incompatible change: updated release notes

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

### CODE REVIEW

File: src/libexpr/eval.cc [hunk 1]
```diff
@@ -173,7 +173,11 @@ void Value::print(const SymbolTable & symbols, std::ostream & str,
     case tFloat:
         str << fpoint;
         break;
+    case tBlackhole:
+        str << "«potential infinite recursion»";
+        break;
     default:
+        std::cerr << "Nix evaluator internal error: invalid value type " << internalType << " in Value::print()" << std::endl;
```
Comment (edolstra) [inline src/libexpr/eval.cc:180]: -> `printError`.

File: src/libexpr/eval.cc [hunk 2]
```diff
@@ -173,7 +173,11 @@ void Value::print(const SymbolTable & symbols, std::ostream & str,
     case tFloat:
         str << fpoint;
         break;
+    case tBlackhole:
+        str << "«potential infinite recursion»";
```
Comment (edolstra) [inline src/libexpr/eval.cc:177]: Maybe "potential" can be dropped, since in eval output this denotes an actual infinite recursion.

**Review by edolstra — APPROVED** [review]

**Comment by yorickvP** [comment]
also fixes this one:
```
❯ cat flake.nix 
{
  outputs = { self }: { x = builtins.trace self { }; };
}
❯ nix build .#x
Aborted (core dumped)
```
