### PR TITLE
Make `nix nar [cat|ls]` lazy

### LINKED ISSUE #13944: `nix nar ls` and `nix nar cat` use twice as much memory as the archive they process
## Describe the bug

In my [benchmark](https://github.com/myclevorname/narser/blob/944fed014c8c2df1a5167f5d161d0068eadf3aa4/benchmark) for narser, I noticed that `nix nar cat` uses about 3.7 GB of memory, even though the NAR file size on my system is 1,838,018,592 bytes. I suspect Nix is copying strings while leaving the file contents in memory.

## Steps To Reproduce

1. Clone a repo like Linux
```
$ git clone --depth=1 https://github.com/torvalds/linux
```

2. Pack it into a Nix archive and measure its size
```
$ nix nar pack linux > linux.nar
$ wc -c linux.nar
1838018592 linux.nar
```

3. Run `nix nar cat` or `nix nar ls`
```
$ command time -f %M -- nix nar ls linux.nar / > /dev/null
3663692
```

## Expected behavior

Either `nix nar ls` uses a C++ string view, or it doesn't read the whole file into memory. Also, if the in-memory archive created in `nix nar ls` only stores the file sizes and not the contents, memory usage can be under 500 MB.

## Metadata

nix-env (Nix) 2.28.5

## Additional context

This bug also affects Lix.

In total, the following speed gains can still be made in Nix:
- `nix nar cat`: 2x if you follow symlinks and 20x if you don't
- `nix nar ls`: 20x whether or not you follow symlinks
- `nix nar pack`: 2x
- `nix-store --restore`: 1.1x

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open bug issues and pull requests] for possible duplicates

[latest Nix manual]: https://nix.dev/manual/nix/development/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by fzakaria**
Change to lazy NAR accessor so we don't store the complete NAR object in memory.

### Timing

We can see nearly a 21x speedup
```
fmzakari@leviathan ~/c/g/N/nix (master)> command time -f %M -- ./build/src/nix/nix nar ls /tmp/linux.nar / > /dev/null
169936

fmzakari@leviathan ~/c/g/N/nix (master)> command time -f %M -- nix nar ls /tmp/linux.nar / > /dev/null
3680616
```

fixes #13944

Please see the issue for the rationale.

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

File: src/nix/cat.cc [hunk 1]
```diff
@@ -71,7 +75,38 @@ struct CmdCatNar : StoreCommand, MixCat
...
     {
-        cat(makeNarAccessor(readFile(narPath)), CanonPath{path});
+        AutoCloseFD fd = open(narPath.c_str(), O_RDONLY);
+        auto source = FdSource{fd.get()};
+        auto narAccessor = makeNarAccessor(source);
+        auto listing = listNar(narAccessor, CanonPath::root, true);
+        auto cacheFile = narPath;
+
+        // TODO: This is common in remote-fs-accessor.cc
+        // should this be a utility function somewhere?
```
Comment (Ericson2314) [inline src/nix/cat.cc]: Yes it should be! Good thinking :)

Comment (fzakaria) [reply src/nix/cat.cc]: done!

File: src/nix/ls.cc [hunk 2]
```diff
@@ -145,7 +145,11 @@ struct CmdLsNar : Command, MixLs
 
     void run() override
     {
-        list(makeNarAccessor(readFile(narPath)), CanonPath{path});
+        AutoCloseFD fd = open(narPath.c_str(), O_RDONLY);
+        auto source = FdSource{fd.get()};
+        auto narAccessor = makeNarAccessor(source);
+        auto listing = listNar(narAccessor, CanonPath::root, true);
+        list(makeLazyNarAccessor(listing, seekableGetNarBytes(narPath)), CanonPath{path});
```
Comment (fzakaria) [inline src/nix/ls.cc:152]: I really tried to remove the std::optional<string> from NarAccessor but it's used by RemoteFSAccessor
I think we can make RemoteFSAccessor a lot faster by also using Sink & Source and not storing the whole memory of the NAR

File: src/libstore/include/nix/store/nar-accessor.hh [hunk 3]
```diff
@@ -27,7 +27,12 @@ ref<SourceAccessor> makeNarAccessor(Source & source);
  */
 using GetNarBytes = std::function<std::string(uint64_t, uint64_t)>;
 
-ref<SourceAccessor> makeLazyNarAccessor(const std::string & listing, GetNarBytes getNarBytes);
+/**
+ * The canonical GetNarBytes function for a seekable Source.
+ */
+GetNarBytes seekableGetNarBytes(const std::string & path);
```
Comment (xokdvium) [inline src/libstore/include/nix/store/nar-accessor.hh]: Maybe either a `std::filesystem::path` or `Path` (yeah I know it's an alias to `std::string`)? Still good to show the intention.

File: src/libstore/nar-accessor.cc [hunk 4]
```diff
@@ -169,8 +169,7 @@ struct NarAccessor : public SourceAccessor
                 return;
         };
 
-        json v = json::parse(listing);
-        recurse(root, v);
+        recurse(root, listing);
     }
```
Comment (xokdvium) [inline src/libstore/nar-accessor.cc:173]: Can we move these changes into a separate commit/PR?

File: src/libstore/include/nix/store/nar-accessor.hh (hunk 3 above)
Comment (xokdvium) [reply src/libstore/include/nix/store/nar-accessor.hh]: Also I think this might just be able to accept a `Descriptor` instead?

Comment (fzakaria) [reply src/libstore/include/nix/store/nar-accessor.hh]: Spoke over Matrix. Changed to Path for now.

File: src/libstore/nar-accessor.cc (hunk 4 above)
Comment (fzakaria) [reply src/libstore/nar-accessor.cc:173]: Can we land this squashed instead?

**Comment by myclevorname** [comment]
TYSM

**Review by Mic92 — COMMENTED** [review]
Release note worthy?

**Comment by Mic92** [comment]
Just currious if it finds the issue...

**Comment by Mic92** [comment]
Nope. Not this time...
