### PR TITLE
Also pass unwanted outputs to post-build-hook

### LINKED ISSUE #6960: Unsigned derivations uploaded to S3
**Describe the bug**

On Nix 2.9.2 when signing/uploading store paths in CI using `post-build-hook` [as suggested by the manual](https://nixos.org/manual/nix/stable/advanced-topics/post-build-hook.html#using-the-post-build-hook), unsigned derivations get uploaded to S3.

**Steps To Reproduce**

1. Set up a `post-build-hook` as per the manual:
    ```shell
   #!/bin/sh
   
   set -eu
   set -f # disable globbing
   export IFS=' '
   
   echo "Signing paths" \$OUT_PATHS
   $(which nix) store sign --key-file /etc/nix/bellroy-nix-cache.private \$OUT_PATHS
   echo "Uploading paths" \$OUT_PATHS
   exec $(which nix) copy --to 's3://bellroy-nix-cache' \$OUT_PATHS
   ```
2. Build a bunch of stuff
3. On a machine with a fresh store (e.g., new CI instance, `nix store gc`, ...), 
4. See a lot of `warning: the substitute for '/nix/store/whatever' from 's3://cache-bucket' is not signed by any of the keys in 'trusted-public-keys'`

**Expected behavior**

All derivations uploaded to S3 are signed. I have confirmed that some of the derivations that make it to S3 are unsigned by using `nix path-info --json --sigs --store s3://cache-bucket /nix/store/whatever | jq`.

**Additional context**

Nix 2.7 seems to work fine; Nix 2.8 was affected by #6446 which passed no paths at all to the post build hook. I suspect that leaves might be getting signed but not intermediate derivations; I'm not sure how to verify this. Should I be passing `-r` to `nix store sign`? I can see little difference in how `nix store sign` is implemented between versions 2.7.0 and 2.9.2.

This makes me suspect the way the post-build-hook is invoked. On Nix 2.7.0:

https://github.com/NixOS/nix/blob/ffe155abd36366a870482625543f9bf924a58281/src/libstore/build/derivation-goal.cc#L881-L889

On Nix 2.9.2:

https://github.com/NixOS/nix/blob/f5070e209664a4aedf30bd9c424f7235a034b259/src/libstore/build/derivation-goal.cc#L903-L915

But I don't know enough about Nix internals to know whether or not it's safe to go back to using `finalOutputs` here.

### PR DESCRIPTION
**Pull request by yorickvP**
# Motivation
#6311 caused only wanted outputs to be passed to the post-build-hook, causing #6960.

# Context

Fixes #6960 

For a long time, the post-build-hook was passed all built store paths. This changed, causing some breakage.

- Add a test to see if unwanted outputs are passed to the post-build-hook.
- Collect wanted+unwanted outputs in a separate set and thread them through `DerivationGoal::checkPathValidity`, `DerivationGoal::registerOutputs`, `DerivationGoal::assertPathValidity`.

# Checklist for maintainers

Maintainers: tick if completed or explain if not relevant

 - [ ] agreed on idea
 - [ ] agreed on implementation strategy
 - [ ] tests, as appropriate
   - functional tests - `tests/**.sh`
   - unit tests - `src/*/tests`
   - integration tests - `tests/nixos/*`
 - [ ] documentation in the manual
 - [ ] code and comments are self-explanatory
 - [ ] commit message explains why the change was made
 - [ ] new feature or bug fix: updated release notes

### CODE REVIEW

**Comment by Ericson2314** [comment]
What does the `post-build-hook` if the paths are substituted instead of freshly built?

Yes, this fixes a practical problem, but if the semantics of the hook differ based on how the store object was obtained, I feel a bit uncomfortable about that.

**Comment by ollie-etl** [comment]
Is this likely the underlying bug for my observation that only a single output from a multi-output derivation is uploaded to s3 cache? 
This _used_ to work.

post-hook is 
```sh
#!/bin/sh
set -eu
set -f # disable globbing
export IFS=' '
exec nix copy --to "s3://<store-uri>?endpoint=https://storage.googleapis.com" $OUT_PATHS
```

I'm using nix 2.8.1

**Comment by yorickvP** [comment]
@Ericson2314 the post-build-hook was never called for substituted paths, and doing so wouldn't really fit common usage (uploading everything you build to a cache somewhere).


@ollie-etl the difference comes because, before this bug, a build of `a.dev` would cause the build hook to be invoked with the paths of `a.out`, `a.dev`. (even though building `a.out` is a side-effect).
With the bug, the post-build hook would only get `a.dev` and `a.out` would go unnoticed.

**Comment by ollie-etl** [comment]
@yorickvP Here i'm building `a`, and `a.out` is being uploaded, but not `a.dev`

**Comment by Ericson2314** [comment]
@yorickvP BTW check out https://github.com/NixOS/nix/pull/6312 and in particular the settings `wantedOuputs = Outputs::All { };` I used to do (and Nix originally did). I think that might be a simpler way to achieve this PR too?

**Comment by yorickvP** [comment]
Refactored it quite a bit, moved the `wantedOutputs` filtering to the end of the pipeline in `done()`.
CA tests fail as @thufschmitt predicted. Will look into it tomorrow.

File: src/libstore/outputs-spec.hh [hunk 1]
```diff
@@ -63,6 +67,9 @@ struct OutputsSpec : _OutputsSpecRaw {
     static OutputsSpec parse(std::string_view s);
     static std::optional<OutputsSpec> parseOpt(std::string_view s);
 
+    /* Filter a DrvOutputs by these output names */
+    DrvOutputs filter(DrvOutputs&& input) const;
```
Comment (Ericson2314) [inline src/libstore/outputs-spec.hh:71]: I think this would be better as a method on `DrvOutputs` than `OutputsSpec`. `OutputsSpec` is the much simpler data type that shouldn't know anything about more complex things, even if the header just gets an abstract type.

Comment (yorickvP) [reply src/libstore/outputs-spec.hh:71]: `DrvOutputs` is a `std::map`. Should I subclass or just write a separate function?

Comment (Ericson2314) [reply src/libstore/outputs-spec.hh:71]: @yorickvP Ah, I see. Either a standalone function or make a struct with one field then, I think.

**Comment by yorickvP** [comment]
I spent a while debugging the test, but copying only the outputs doesn't seem to be sufficient for the CA test in any case (without my patch aswell).

@thufschmitt do you know if that's correct and supposed to be the case?

```
out=nix-build ./ca-thing.nix
nix copy --to cache $out
nix copy --from cache -f ca-thing.nix
    error: unable to build with a primary store that isn't a local store; either pass a different '--store' or enable remote builds.
```

**Comment by thufschmitt** [comment]
> @thufschmitt do you know if that's correct and supposed to be the case?
> 
> ```
> out=nix-build ./ca-thing.nix
> nix copy --to cache $out
> nix copy --from cache -f ca-thing.nix
>     error: unable to build with a primary store that isn't a local store; either pass a different '--store' or enable remote builds.
> ```

Yes, it is. It's explained a bit more in https://www.tweag.io/blog/2021-02-17-derivation-outputs-and-output-paths/, but the gist of it is that with CA derivations there's a split between the output path and the information “this Derivation built this output path”. So if you want to be able to fetch “the output of this derivation” then you must copy exactly that (`nix copy --to cache -f ca-thing.nix` or `nix copy --to cache /nix/store/....-ca-thing.drv`) and not just the output path

**Comment by yorickvP** [comment]
Okay, in that case this will have to suffice

**Comment by alyssais** [comment]
Any news here?

**Comment by yorickvP** [comment]
@thufschmitt rebased, please review

**Comment by ollie-etl** [comment]
@thufschmitt @yorickvP Is this dead?

File: tests/push-to-store-old.sh
Comment (thufschmitt) [inline tests/push-to-store-old.sh:1]: That's unrelated to this PR, but this file is weird :thinking:

**Review by thufschmitt — APPROVED** [review]
Sorry for taking so long at reaching here.

I'm still a bit sad this can't be a more local change, but it does fix the problem while making the code marginally more sensible. So let's roll!

**Comment by thufschmitt** [comment]
@yorickvP can I let you rebase one last time? The conflicts seem mostly benign

**Review by thufschmitt — APPROVED** [review]
It's all passing, and looking good :rocket:

**Review by thufschmitt — APPROVED** [review]
It's all passing, and looking good :rocket:
