### PR TITLE
Explicitly model all settings and fail on unrecognized ones

### LINKED ISSUE #1193: --option should exit if option doesn’t exist
Right now, `--option asdfgl` just continues, happily ignoring the option.

It should exit with a message that the option doesn’t exist.

### PR DESCRIPTION
**Pull request by copumpkin**
Previously, the Settings class allowed other code to query for string properties, which led to a proliferation of code all over the place making up new options without any sort of central registry of valid options. This commit pulls all those options back into the central Settings class and removes the public get() methods, to discourage future abuses like that.

Furthermore, because we know the full set of options ahead of time, we now fail loudly if someone enters an unrecognized option, thus preventing subtle typos. With some template fun, we could probably also dump the full set of options (with documentation, defaults, etc.) to the command line,
but I'm not doing that yet here.

cc @edolstra @domenkozar @shlevy @profpatsch

Fixes #1193

P.S: 5 tests failed but I'm never quite sure how many are expected to pass on darwin. I'll test it on Linux tomorrow.

### CODE REVIEW

File: src/libstore/globals.cc [hunk 1]
```diff
@@ -181,13 +180,55 @@ void Settings::update()
...
 
 void Settings::_get(string & res, const string & name)
 {
     SettingsMap::iterator i = settings.find(name);
     if (i == settings.end()) return;
+    settings.erase(i);
+    res = i->second;
+}
+
+void Settings::_get(string & res, const string & name1, const string & name2)
```
Comment (copumpkin) [inline src/libstore/globals.cc]: @edolstra I'm not a fan of this API but I wasn't sure why you made the API take a reference rather than return a value. If I changed these `_get` methods to return a value and take a default, I could chain them nicely, but I figured I'd ask first.

File: src/libstore/build.cc [hunk 2]
```diff
@@ -1744,21 +1735,10 @@ void DerivationGoal::startBuilder()
 
     if (useChroot) {
 
-        string defaultChrootDirs;
-#if __linux__
-        if (worker.store.isInStore(BASH_PATH))
```
Comment (copumpkin) [inline src/libstore/build.cc]: I got rid of this because I can't check `isInStore` from the `Settings` class. How likely is this to be false? It seems like if bash is missing, it'd break a ton of stuff...

File: src/libstore/build.cc [hunk 3]
```diff
@@ -1811,7 +1790,7 @@ void DerivationGoal::startBuilder()
                 }
             }
             if (!found)
-                throw Error(format("derivation ‘%1%’ requested impure path ‘%2%’, but it was not in allowed-impure-host-deps (‘%3%’)") % drvPath % i % allowed);
```
Comment (copumpkin) [inline src/libstore/build.cc]: I should probably restore `allowed` here but I was lazy 😛

**Comment by edolstra** [comment]
I'm not convinced that barfing on unrecognized options is a good thing.

**Comment by copumpkin** [comment]
Why wouldn't it be? I've wasted a significant amount of time over the past
couple of years adding ad-hoc options to my build invocations and having
them quietly not take effect either because I typoed them or because they
weren't called what I thought they were called. We could even do one of
those newfangled "did you mean" suggestion thingies! I bet I'm not alone in
doing that.

Or to put it differently, why do I want to be notified if I type `nix-store
--axport` but not if I type `nix-shell --option build-use-subtsitute false`?

**Comment by edolstra** [comment]
For example, if a configuration setting gets removed, then a configuration file referencing this setting will now cause every Nix command to barf.

**Comment by grahamc** [comment]
I'm actually pro-barf, but would take at least a warning. Silently not doing the thing I want it to do seems not good.

**Comment by shlevy** [comment]
@edolstra That issue suggests we should deprecate old settings, add warnings, and be careful about backwards compatibility, not silently ignore errors...

**Comment by copumpkin** [comment]
Taking out settings makes sense. Perhaps we could barf in cases that are
clearly wrong and warn in deprecated cases? The code would maintain a list
of all options that were ever valid and warn on those, barfing on ones that
just make no sense?

**Comment by copumpkin** [comment]
I'm thinking there could just be a set of macros/templates (haven't quite decided how they'd work yet) that simultaneously let us specify documentation, names, defaults, alternates, and deprecation. It was kind of miserable writing down each of these options in four different places (declaration, default, use site, and retrieval from settings/command-line)

**Comment by copumpkin** [comment]
Actually, the current fallback options for the various "chroot" options could be good tests (which I still need to write obviously) for the warn-on-deprecation machinery. @edolstra want me to throw that in?

**Comment by copumpkin** [comment]
Okay, I've added some basic support for deprecated options. I make a distinction (to the user) between deprecated options that we still support, deprecated options we now ignore, and options that have never existed.

I kind of like it, even though I'd like to rework the implementation as I said earlier. That'll probably be a separate PR though.

**Comment by veprbl** [comment]
Does this address ignored options? Things used to not propagate to nix-daemon for me in NixOS/nixpkgs#14866

**Comment by copumpkin** [comment]
@veprbl I don't currently do anything with propagation, although we should also fix that. Given that link, it seems like @vcunat might also be interested in this PR.

**Comment by domenkozar** [comment]
I'm +1 on general concept, was bitten a few times by this. Explicit handling what is supported leads to better UX.

**Comment by copumpkin** [comment]
@edolstra ping 😄 I got bitten by a typo again yesterday and this seems like a no-regrets improvement. My main hesitation at this point is the `???`s I put into the comments about options I know nothing about.

**Comment by copumpkin** [comment]
@edolstra any more feedback? I think this now addresses the issue of deprecation you raised as a concern.

**Comment by edolstra** [comment]
@copumpkin Will look at it tomorrow, sorry for the delay.

**Comment by copumpkin** [comment]
@edolstra thanks! no problem, I understand that you're constantly getting pinged on just about everything Nix-related 😄

**Comment by edolstra** [comment]
Thinking about it a bit more, I'm convinced unrecognized errors *must not* be a fatal error because it breaks forward compatibility. For instance, if I add a Nix 1.12-specific option to my `nix.conf`, it immediately becomes impossible to run Nix 1.11...

File: src/libstore/globals.cc [hunk 4]
```diff
@@ -73,6 +84,32 @@ Settings::Settings()
...
+    binaryCachesParallelConnections = 25;
+    enableHttp2 = true;
+    tarballTtl = 60 * 60;
+    signedBinaryCaches = "";
+    substituters = Strings();
+    binaryCaches = Strings();
+    extraBinaryCaches = Strings();
+    trustedUsers = Strings({"root"});
+    allowedUsers = Strings({"*"});
+    printMissing = true;
```
Comment (edolstra) [inline src/libstore/globals.cc]: These defaults should be moved to Settings in `globals.hh` as C++11 allows.

**Comment by copumpkin** [comment]
Can we make that behavior optional? I want my evals to fail on nonsense
options and you want your evals to pass if you're upgrading. I think for
user-friendliness standpoint my "typoed options" situation is more likely
and more likely to affect people who don't know how to configure things
like this. You as a Nix developer do :) I guess we could make it default
the other way around but I'd obviously prefer it my way :)

File: src/libstore/download.cc [hunk 5]
```diff
@@ -573,7 +573,7 @@ Path Downloader::downloadCached(ref<Store> store, const string & url_, bool unpa
 
     string expectedETag;
 
-    int ttl = settings.get("tarball-ttl", 60 * 60);
+    int ttl = settings.tarballTtl;
```
Comment (edolstra) [inline src/libstore/download.cc]: Copying the setting is superfluous.

File: src/libexpr/eval.cc [hunk 6]
```diff
@@ -299,7 +299,7 @@ EvalState::EvalState(const Strings & _searchPath, ref<Store> store)
 {
     countCalls = getEnv("NIX_COUNT_CALLS", "0") != "0";
 
-    restricted = settings.get("restrict-eval", false);
+    restricted = settings.restrictEval;
```
Comment (edolstra) [inline src/libexpr/eval.cc]: `restricted` can be replaced by `settings.restrictEval`.

File: src/nix-daemon/nix-daemon.cc [hunk 7]
```diff
@@ -865,8 +865,8 @@ static void daemonLoop(char * * argv)
             struct group * gr = peer.gidKnown ? getgrgid(peer.gid) : 0;
             string group = gr ? gr->gr_name : std::to_string(peer.gid);
 
-            Strings trustedUsers = settings.get("trusted-users", Strings({"root"}));
-            Strings allowedUsers = settings.get("allowed-users", Strings({"*"}));
+            Strings trustedUsers = settings.trustedUsers;
+            Strings allowedUsers = settings.allowedUsers;
```
Comment (edolstra) [inline src/nix-daemon/nix-daemon.cc]: These are superfluous.

**Comment by edolstra** [comment]
@copumpkin Why not just make it a warning?

**Comment by edolstra** [comment]
Another scenario: you add a non-existent option to `nix.extraConfig` and do a nixos-rebuild. Now you're stuck because Nix barfs so you can't run nixos-rebuild again to get rid of the offending option.

**Comment by copumpkin** [comment]
@edolstra I guess it's just that I can miss a warning much more easily and a flavor of problem is when you start something that affects behavior (e.g., `build-use-sandbox`) and walk away. Two hours later, you check back and realized you wrote `buidl-use-sandbox` and throw your computer out the window.

Anyway, I don't feel super strongly about it, but we do fail on bad command-line options, so I don't see this as being too different:

```
$ nix-shell -T -p
error: unknown flag ‘-T’
Try ‘/nix/store/pxf5ri5kdbfqkhd10sw4lpj8sn385ks5-nix-1.11.7/bin/nix-store --help’ for more information.
/Users/copumpkin/.nix-profile/bin/nix-shell: failed to build all dependencies
```

**Comment by Profpatsch** [comment]
> For instance, if I add a Nix 1.12-specific option to my nix.conf, it immediately becomes impossible to run Nix 1.11

> Can we make that behavior optional? I want my evals to fail on nonsense
> options and you want your evals to pass if you're upgrading.

+1 for optional, since normally you want to move *forward*, not backward. And if you move backward you want to be very explicit. Aka you *want* to be notified of options that worked before in the later version but won’t now (that may be critical).


> you add a non-existent option to nix.extraConfig and do a nixos-rebuild. Now you're stuck because Nix barfs so you can't run nixos-rebuild again to get rid of the offending option.

In that version I’d rather question why it’s possible to influence default nix invocation that way at all. It is also trivial to fix it by running with the proposed `--ignore-nonexisting-options` (or similar) option.

**Comment by copumpkin** [comment]
Whoa, how did you merge this when I hadn't fixed the merge conflicts yet? Either way, thanks!

**Comment by edolstra** [comment]
I just resolved the conflicts, they weren't that big :-) Modelling all the settings was super helpful BTW, thanks!

**Comment by copumpkin** [comment]
Yeah, I saw. Thank you, I love all the follow-up work you did on the config. Really looking forward to 1.12 even more than I was before now 😄
