### PR TITLE
repl: catch all errors during tab completion

### LINKED ISSUE #15133: nix repl: fromJSON => Error => tabcomplete => crash
## Describe the bug

When you tab-complete some variables containing errors in `nix-repl`, the repl crashes. Happens with `builtins.fromJSON`, but possibly otherwise too.

## Steps To Reproduce

```nix
[user@nixos:~]$ nix repl
nix-repl> err1 = builtins.fromJSON "nixnix"
nix-repl> err1.<TAB>

error:
       … while calling the 'fromJSON' builtin
         at «string»:1:2:
            1|  builtins.fromJSON "nixnix"
             |  ^

       … while decoding a JSON string

       error: [json.exception.parse_error.101] parse error at line 1, column 2: syntax error while parsing value - invalid literal; last read: 'ni'

[user@nixos:~]$
```
the text input in the resulting shell is invisible too.
## Expected behavior

handling the Error internally without crashing `nix repl`
```nix
[user@nixos:~]$ nix repl
nix-repl> err1 = builtins.fromJSON "nixnix"
nix-repl> err1.<TAB>

error:
       … while calling the 'fromJSON' builtin
         at «string»:1:2:
            1|  builtins.fromJSON "nixnix"
             |  ^

       … while decoding a JSON string

       error: [json.exception.parse_error.101] parse error at line 1, column 2: syntax error while parsing value - invalid literal; last read: 'ni'

nix-repl> err1.
```

## Metadata

`nix-env (Nix) 2.31.3`

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open bug issues and pull requests] for possible duplicates

[latest Nix manual]: https://nix.dev/manual/nix/development/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by amaanq**
## Motivation

The tab completion handler in `completePrefix` only caught `ParseError`,
`EvalError`, `BadURL`, and `FileNotFound`. Other error types like
`JSONParseError` (which derives from `Error`, not `EvalError`) escaped
the catch block and propagated through editline's C code as undefined
behavior, crashing the REPL. This happened when tab-completing
expressions like `(builtins.fromJSON "invalid").` where evaluation
throws a non-`EvalError` exception.

This commit marks `completionCallback` and `listPossibleCallback` as
`noexcept` with function-try-blocks that catch all exceptions at the
C/C++ boundary, preventing any exception from reaching editline.

## Context

- Fixes #15133

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

File: src/libcmd/repl-interacter.cc [hunk 1]
```diff
@@ -105,6 +107,8 @@ static int listPossibleCallback(char * s, char *** avp)
     *avp = vp;
 
     return ac;
+} catch (...) {
+    return 0;
```
Comment (xokdvium) [inline src/libcmd/repl-interacter.cc:112]:
```suggestion
    *avp = nullptr;
    return 0;
```
