### PR TITLE
parser.y: properly abstract over to-be-created strings

### LINKED ISSUE #14642: "dynamic attributes not allowed" in let regression
## Describe the bug

```
let a = 1; "b" = 2; ${"c"} = 3; in [ a b c ]
```

regressed from 2.30 to 2.32.

See

```
Nix 2.30.3
Type :? for help.
nix-repl> let a = 1; "b" = 2; ${"c"} = 3; in [ a b c ]
[
  1
  2
  3
]
```

vs

```
Nix 2.32.4
Type :? for help.
nix-repl> let a = 1; "b" = 2; ${"c"} = 3; in [ a b c ]
error: dynamic attributes not allowed in let
       at «string»:1:1:
            1| let a = 1; "b" = 2; ${"c"} = 3; in [ a b c ]
             | ^
```

## Expected behavior

I'd expect this to not start to fail in a minor version bump, expressions out there might use it.

It's not mentioned in the release notes, and some quick git blaming around the error message also didn't show anything, so I assume this is a regression.

## Additional context

https://cl.snix.dev/c/snix/+/30758

## Checklist

- [x] checked [latest Nix manual] \([source])
- [x] checked [open bug issues and pull requests] for possible duplicates

[latest Nix manual]: https://nix.dev/manual/nix/development/
[source]: https://github.com/NixOS/nix/tree/master/doc/manual/source
[open bug issues and pull requests]: https://github.com/NixOS/nix/labels/bug

---

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by Radvendii**
This fixes #14642 and adds tests to prevent regression.

In https://github.com/NixOS/nix/commit/eab467ecfb829182548276df7d56a4d1c525057a, I had missed cases like `"${"string"}"`, where the `Expr` is already an `ExprString`. This PR provides a wrapper around `std::variant` that correctly abstracts over when we have a string and when we have another `Expr`.

- **parser.y: correctly abstract over to-be-constructed ExprString**
- **tests: add tests for dynamic attribute in let and inherit**

## Context

---

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by Ericson2314** [comment]
Looks pretty good to me, but needs a formatter run.

File: src/libexpr/include/nix/expr/parser-state.hh [hunk 1]
```diff
@@ -47,6 +47,61 @@ struct ParserLocation
...
+private:
+    using Variant = std::variant<std::string_view, Expr *>;
+    Variant variant;
+public:
+    ToBeStringyExpr() {};
+    ToBeStringyExpr(Variant variant)
+        : variant(variant) {};
+
+    void operator=(Variant variant)
+    {
```
Comment (xokdvium) [inline src/libexpr/include/nix/expr/parser-state.hh]: This is the wrong signature for a copy assignment + it's unnecessary to implement a copy constructor for this class, since default copy assignment operator will be provided by the compiler.

**Review by xokdvium — CHANGES_REQUESTED** [review]
One minor comment. Also would like to see more tests. I can take over if that's fine with you @Radvendii

File: src/libexpr/include/nix/expr/parser-state.hh [hunk 2]
```diff
@@ -47,6 +47,61 @@ struct ParserLocation
...
+                    // For backward compatibility, we must consider ${"string"} as though it were just "string".
+                    // SEE: https://github.com/NixOS/nix/issues/14642
+                    ExprString * str = dynamic_cast<ExprString *>(expr);
+                    if (str)
+                        strF(str->v.string_view());
+                    else
+                        exprF(expr);
+                }},
+            variant);
+    }
```
Comment (xokdvium) [inline src/libexpr/include/nix/expr/parser-state.hh]: This could be a template that takes a callable object with overloaded call operator, just like std::variant does. std::function imposes an unnecessary runtime cost when a template will do the trick just fine

File: src/libexpr/include/nix/expr/parser-state.hh [hunk 3]
```diff
@@ -47,6 +47,61 @@ struct ParserLocation
...
+
+    Expr * toExpr(Exprs & exprs)
+    {
+        return std::visit(
+            overloaded{
+                [&](std::string_view str) { return static_cast<Expr *>(exprs.add<ExprString>(exprs.alloc, str)); },
```
Comment (xokdvium) [inline src/libexpr/include/nix/expr/parser-state.hh]:
```suggestion
                [&](std::string_view str) -> Expr * { return exprs.add<ExprString>(exprs.alloc, str); },
```

Implicit upcast is less verbose here?

File: src/libexpr/include/nix/expr/parser-state.hh (hunk 1 above)
Comment (Radvendii) [reply src/libexpr/include/nix/expr/parser-state.hh]: We have several places where we have e.g. an `Expr *`, and we want to assign it to one of these. We could change `$$ = $1;` to `$$ = { $1 };` instead. I suppose that's clearer that we're changing types, so maybe it's better.

File: src/libexpr/include/nix/expr/parser-state.hh (hunk 2 above)
Comment (Radvendii) [reply src/libexpr/include/nix/expr/parser-state.hh]: Sweet. I wasn't sure which of the 8 mechanisms to do this in C++ was the right one.

File: src/libexpr/include/nix/expr/parser-state.hh (hunk 3 above)
Comment (Radvendii) [reply src/libexpr/include/nix/expr/parser-state.hh]: Didn't know that was a thing. thanks!

File: src/libexpr/include/nix/expr/parser-state.hh (hunk 1 above)
Comment (xokdvium) [reply src/libexpr/include/nix/expr/parser-state.hh]: It will already work since there's a non-explicit constructor from Variant.

Comment (Radvendii) [reply src/libexpr/include/nix/expr/parser-state.hh]: yeah, having implemented this change i'm convinced it's the better way to structure things.

**Comment by Radvendii** [comment]
I added a few more tests (some results still surprised me. `inherit ${"foo"};` is valid but `inherit "${foo"}";` is not). 

You're also welcome to add more of course.

One problem is that this is such cursed nix code that the formatter doesn't know what to do with it and CI is failing. 

1. does this count as a bug in the formatter that I should send their way? (the code it's failing to format doesn't succeed to parse but for a reason other than the one the formatter is giving)
2. can we disable the formatter for specific files?

**Comment by flokli** [comment]
@Ericson2314 do you plan to tag a release containing this fix?

**Comment by Ericson2314** [comment]
@flokli I haven't been involved with point releases very much at all, but yes that sounds like a good idea to me. I will raise it with the others.
