### PR TITLE
registerOutputs(): Don't call canonicalisePathMetaData() twice

### LINKED ISSUE #4021: nix develop: unexpected end-of-file
**Describe the bug**

On latest master (3.0pre20200916_609a6d6) `nix develop` always throws "unexpected end-of-file"

**Steps To Reproduce**

```
$ nix develop nixpkgs#hello
error: --- EndOfFile ------------------------------------------------------------------------------------------------------------------------------------- nix
unexpected end-of-file
```

With `-vvvv`:

```
$ nix develop nixpkgs#hello -vvvv
resolved search path element '/nix/store/abp7sfsi0i37dalwkcp2kssjzwjmnix4-nix-3.0pre20200916_609a6d6/share/nix/corepkgs' to '/nix/store/abp7sfsi0i37dalwkcp2kssjzwjmnix4-nix-3.0pre20200916_609a6d6/share/nix/corepkgs'
checking access to '/nix/store/abp7sfsi0i37dalwkcp2kssjzwjmnix4-nix-3.0pre20200916_609a6d6/share/nix/corepkgs/derivation.nix'
evaluating file '/nix/store/abp7sfsi0i37dalwkcp2kssjzwjmnix4-nix-3.0pre20200916_609a6d6/share/nix/corepkgs/derivation.nix'
acquiring global GC lock '/nix/var/nix/gc.lock'
acquiring read lock on '/nix/var/nix/temproots/25799'
acquiring write lock on '/nix/var/nix/temproots/25799'
downgrading to read lock on '/nix/var/nix/temproots/25799'
using cache entry '{"name":"flake-registry.json","type":"file","url":"https://github.com/NixOS/flake-registry/raw/master/flake-registry.json"}' -> '{"etag":"\"30cebe0247c3594057b8c05ed7ce4f6aefd2eb2ab1bc27ae6625e44b0e81a559\"","url":"https://raw.githubusercontent.com/NixOS/flake-registry/master/flake-registry.json"}', '/nix/store/050wdgdbrqya3p8h348iz8bb7lif7pww-flake-registry.json'
acquiring global GC lock '/nix/var/nix/gc.lock'
looked up 'flake:nixpkgs' -> 'github:NixOS/nixpkgs'
acquiring write lock on '/nix/var/nix/temproots/25799'
downgrading to read lock on '/nix/var/nix/temproots/25799'
using cache entry '{"name":"source","type":"file","url":"https://api.github.com/repos/NixOS/nixpkgs/commits/HEAD"}' -> '{"etag":"W/\"f1c887de7ba6ea9f6600ab28598319a8\"","url":"https://api.github.com/repos/NixOS/nixpkgs/commits/HEAD"}', '/nix/store/ly6998sg01xzykyp328j97vfk0nyqvn9-source'
HEAD revision for 'https://api.github.com/repos/NixOS/nixpkgs/commits/HEAD' is 6e98b8ff93bda77048a5c48a88edc907b819e190
acquiring write lock on '/nix/var/nix/temproots/25799'
downgrading to read lock on '/nix/var/nix/temproots/25799'
using cache entry '{"rev":"6e98b8ff93bda77048a5c48a88edc907b819e190","type":"git-tarball"}' -> '{"lastModified":1600262222,"rev":"6e98b8ff93bda77048a5c48a88edc907b819e190"}', '/nix/store/bwlxn998bmwbyxnkqvk32s3id6iyf14j-source'
got tree '/nix/store/bwlxn998bmwbyxnkqvk32s3id6iyf14j-source' from 'github:NixOS/nixpkgs/6e98b8ff93bda77048a5c48a88edc907b819e190'
checking access to '/nix/store/bwlxn998bmwbyxnkqvk32s3id6iyf14j-source/flake.nix'
evaluating file '/nix/store/bwlxn998bmwbyxnkqvk32s3id6iyf14j-source/flake.nix'
old lock file: {
  "nodes": {
    "root": {}
  },
  "root": "root",
  "version": 7
}
computing lock file node ''
new lock file: {
  "nodes": {
    "root": {}
  },
  "root": "root",
  "version": 7
}
using cached string attribute 'legacyPackages.x86_64-linux.hello.type'
using cached string attribute 'legacyPackages.x86_64-linux.hello.drvPath'
using cached string attribute 'legacyPackages.x86_64-linux.hello.outPath'
using cached string attribute 'legacyPackages.x86_64-linux.hello.outputName'
acquiring write lock on '/nix/var/nix/temproots/25799'
downgrading to read lock on '/nix/var/nix/temproots/25799'
acquiring write lock on '/nix/var/nix/temproots/25799'
downgrading to read lock on '/nix/var/nix/temproots/25799'
querying info about missing paths...
starting pool of 15 threads
checking substituter 'https://cache.nixos.org' for path '/nix/store/xdj6pkcgjc6bd4nw8rirfgh0z5nlj7ma-hello-2.10-env'
checking substituter 'https://cache.nixos.org' for path '/nix/store/xdj6pkcgjc6bd4nw8rirfgh0z5nlj7ma-hello-2.10-env'
reaping 2 worker threads
building of '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv': created
building of '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv': woken up
entered goal loop
building of '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv': init
building of '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv': loading derivation
acquiring write lock on '/nix/var/nix/temproots/25799'
downgrading to read lock on '/nix/var/nix/temproots/25799'
building of '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv': have derivation
acquiring write lock on '/nix/var/nix/temproots/25799'
downgrading to read lock on '/nix/var/nix/temproots/25799'
substitution of '/nix/store/xdj6pkcgjc6bd4nw8rirfgh0z5nlj7ma-hello-2.10-env': created
substitution of '/nix/store/xdj6pkcgjc6bd4nw8rirfgh0z5nlj7ma-hello-2.10-env': woken up
substitution of '/nix/store/xdj6pkcgjc6bd4nw8rirfgh0z5nlj7ma-hello-2.10-env': init
acquiring write lock on '/nix/var/nix/temproots/25799'
downgrading to read lock on '/nix/var/nix/temproots/25799'
substitution of '/nix/store/xdj6pkcgjc6bd4nw8rirfgh0z5nlj7ma-hello-2.10-env': trying next substituter
substitution of '/nix/store/xdj6pkcgjc6bd4nw8rirfgh0z5nlj7ma-hello-2.10-env': trying next substituter
substitution of '/nix/store/xdj6pkcgjc6bd4nw8rirfgh0z5nlj7ma-hello-2.10-env': trying next substituter
path '/nix/store/xdj6pkcgjc6bd4nw8rirfgh0z5nlj7ma-hello-2.10-env' is required, but there is no substituter that can build it
substitution of '/nix/store/xdj6pkcgjc6bd4nw8rirfgh0z5nlj7ma-hello-2.10-env': done
building of '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv': waitee 'substitution of '/nix/store/xdj6pkcgjc6bd4nw8rirfgh0z5nlj7ma-hello-2.10-env'' done; 0 left
building of '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv': woken up
substitution of '/nix/store/xdj6pkcgjc6bd4nw8rirfgh0z5nlj7ma-hello-2.10-env': goal destroyed
building of '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv': all outputs substituted (maybe)
building of '/nix/store/4qry96ap0kpkjwjlsyc8p3m3hh6pg5pv-bash-4.4-p23.drv': created
building of '/nix/store/4qry96ap0kpkjwjlsyc8p3m3hh6pg5pv-bash-4.4-p23.drv': woken up
building of '/nix/store/nizihiiy8gcwn61sfd538vq0bf3ll5ll-stdenv-linux.drv': created
building of '/nix/store/nizihiiy8gcwn61sfd538vq0bf3ll5ll-stdenv-linux.drv': woken up
building of '/nix/store/rhsz1nvng131ycy3dchiwpm99sflvyl6-hello-2.10.tar.gz.drv': created
building of '/nix/store/rhsz1nvng131ycy3dchiwpm99sflvyl6-hello-2.10.tar.gz.drv': woken up
building of '/nix/store/4qry96ap0kpkjwjlsyc8p3m3hh6pg5pv-bash-4.4-p23.drv': init
building of '/nix/store/4qry96ap0kpkjwjlsyc8p3m3hh6pg5pv-bash-4.4-p23.drv': loading derivation
acquiring write lock on '/nix/var/nix/temproots/25799'
downgrading to read lock on '/nix/var/nix/temproots/25799'
building of '/nix/store/4qry96ap0kpkjwjlsyc8p3m3hh6pg5pv-bash-4.4-p23.drv': have derivation
acquiring write lock on '/nix/var/nix/temproots/25799'
downgrading to read lock on '/nix/var/nix/temproots/25799'
acquiring write lock on '/nix/var/nix/temproots/25799'
downgrading to read lock on '/nix/var/nix/temproots/25799'
acquiring write lock on '/nix/var/nix/temproots/25799'
downgrading to read lock on '/nix/var/nix/temproots/25799'
acquiring write lock on '/nix/var/nix/temproots/25799'
downgrading to read lock on '/nix/var/nix/temproots/25799'
acquiring write lock on '/nix/var/nix/temproots/25799'
downgrading to read lock on '/nix/var/nix/temproots/25799'
building of '/nix/store/4qry96ap0kpkjwjlsyc8p3m3hh6pg5pv-bash-4.4-p23.drv': done
building of '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv': waitee 'building of '/nix/store/4qry96ap0kpkjwjlsyc8p3m3hh6pg5pv-bash-4.4-p23.drv'' done; 2 left
building of '/nix/store/rhsz1nvng131ycy3dchiwpm99sflvyl6-hello-2.10.tar.gz.drv': init
building of '/nix/store/rhsz1nvng131ycy3dchiwpm99sflvyl6-hello-2.10.tar.gz.drv': loading derivation
acquiring write lock on '/nix/var/nix/temproots/25799'
downgrading to read lock on '/nix/var/nix/temproots/25799'
building of '/nix/store/rhsz1nvng131ycy3dchiwpm99sflvyl6-hello-2.10.tar.gz.drv': have derivation
acquiring write lock on '/nix/var/nix/temproots/25799'
downgrading to read lock on '/nix/var/nix/temproots/25799'
building of '/nix/store/rhsz1nvng131ycy3dchiwpm99sflvyl6-hello-2.10.tar.gz.drv': done
building of '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv': waitee 'building of '/nix/store/rhsz1nvng131ycy3dchiwpm99sflvyl6-hello-2.10.tar.gz.drv'' done; 1 left
building of '/nix/store/nizihiiy8gcwn61sfd538vq0bf3ll5ll-stdenv-linux.drv': init
building of '/nix/store/nizihiiy8gcwn61sfd538vq0bf3ll5ll-stdenv-linux.drv': loading derivation
acquiring write lock on '/nix/var/nix/temproots/25799'
downgrading to read lock on '/nix/var/nix/temproots/25799'
building of '/nix/store/nizihiiy8gcwn61sfd538vq0bf3ll5ll-stdenv-linux.drv': have derivation
acquiring write lock on '/nix/var/nix/temproots/25799'
downgrading to read lock on '/nix/var/nix/temproots/25799'
building of '/nix/store/nizihiiy8gcwn61sfd538vq0bf3ll5ll-stdenv-linux.drv': done
building of '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv': waitee 'building of '/nix/store/nizihiiy8gcwn61sfd538vq0bf3ll5ll-stdenv-linux.drv'' done; 0 left
building of '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv': woken up
building of '/nix/store/nizihiiy8gcwn61sfd538vq0bf3ll5ll-stdenv-linux.drv': goal destroyed
building of '/nix/store/rhsz1nvng131ycy3dchiwpm99sflvyl6-hello-2.10.tar.gz.drv': goal destroyed
building of '/nix/store/4qry96ap0kpkjwjlsyc8p3m3hh6pg5pv-bash-4.4-p23.drv': goal destroyed
building of '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv': all inputs realised
added input paths '/nix/store/0c88xw36hn0wzmnlyai9s3sibbnq3pnd-get-env.sh', '/nix/store/1i5y55x4b4m9qkx5dqbmr1r6bvrqbanw-multiple-outputs.sh', '/nix/store/2f6zzvixj3wsj81flbdcpc6fdscgx4ai-coreutils-8.31', '/nix/store/2gci5q5yz717xycp444wyjxki4mbwwav-zlib-1.2.11', '/nix/store/3x7dwzq014bblazs7kq20p9hyzz0qh8g-hello-2.10.tar.gz', '/nix/store/4g7jg3j6m465k114l3vwxb5wchswspvk-patchelf-0.12', '/nix/store/4ygqr4w06zwcd2kcxa6w3441jijv0pvx-strip.sh', '/nix/store/6ffp6xbr6j2ryqw2dafbbvv55ggq16iv-bash-4.4-p23', '/nix/store/6k829xz9v508ncxfcf2p1b8g1wq54946-patch-shebangs.sh', '/nix/store/78hlxpng1g6hqg064mdq4rk9cfcp30da-pcre-8.44', '/nix/store/7mc844h3g1wj03si5c9x3llkc7mb03nx-gnumake-4.3', '/nix/store/7ylf64vl6747sf45daaw707d4k97wn13-stdenv-linux', '/nix/store/866is80gnngm7q5fiaqvl4d6z1agc79h-patch-2.7.6', '/nix/store/87alzvyjwdf2w1k6i6aj87pn4r0sdm6c-libunistring-0.9.10', '/nix/store/8zxndz5ag0p6s526c2xyllhk1nrn4c3i-audit-tmpdir.sh', '/nix/store/98qzp0pnpdl5wxnf67yvqrf3qdzd43mb-xz-5.2.5', '/nix/store/9h4b6pkgpqawq764752fq5kgaqxcg8c7-xz-5.2.5-bin', '/nix/store/9krlzvny65gdc8s7kpb6lkx8cd02c25b-default-builder.sh', '/nix/store/ba05xi32q6zjcn6niad1zs1adqylwcr7-bzip2-1.0.6.0.1-bin', '/nix/store/bgvxpx97q789xc8rrginprlvk8p03p93-glibc-2.31-dev', '/nix/store/ca3s86mhhwmjs5ksry8s3arzaf9s3dcw-gnutar-1.32', '/nix/store/cgldmnm5lf0bfjdjjm7p66v7aaxkj948-diffutils-3.7', '/nix/store/cickvswrvann041nqxb0rxilc46svw1n-prune-libtool-files.sh', '/nix/store/dd3prkmzh7wjfz5cxnlym54vlh7ni89k-libidn2-2.3.0', '/nix/store/fby8klnixr66d81cldxffq38x0q4bxa9-attr-2.4.48', '/nix/store/fyaryjvghbkpfnsyw97hb3lyb37s1pd6-move-lib64.sh', '/nix/store/g8mk2h9g9j0yh5aazvvc011xikxzh2pw-linux-headers-5.5', '/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1', '/nix/store/jpss6g3cqc9gwih8jflbbc883xc0mbcx-gnugrep-3.4', '/nix/store/jsgpwwhzfd3c8gnq3ymhqlbgfxk3xjkc-binutils-wrapper-2.31.1', '/nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31', '/nix/store/kd4xwxjpjxi71jkm6ka0np72if9rm3y0-move-sbin.sh', '/nix/store/kxw6q8v6isaqjm702d71n2421cxamq68-make-symlinks-relative.sh', '/nix/store/l11x0vclh1a7wadc2545i6lxlb49vqii-gzip-1.10', '/nix/store/lgf91sh6j7pv2fm500vld1cy336jn8xc-bzip2-1.0.6.0.1', '/nix/store/mijx85pw9jn3bhzii3jl0kv5m2sjq7zq-gcc-9.3.0-lib', '/nix/store/mimzy2k99xq842k59zl3f2z2s34rcq5b-gcc-wrapper-9.3.0', '/nix/store/mjjy30kxz775bhhi6j9phw81qh6dsbrf-move-docs.sh', '/nix/store/n2r2i8rz2a2mhpay12y4p177shpvislx-gawk-5.1.0', '/nix/store/ngg1cv31c8c7bcm2n8ww4g06nq7s4zhm-set-source-date-epoch-to-latest.sh', '/nix/store/ql9k257fsgjsrc2dq2cbhhsayis7q66a-findutils-4.7.0', '/nix/store/r5xqfk8p7c79yqphy25rbvm71yfvrzh4-glibc-2.31-bin', '/nix/store/rclksjxdjgp6y6qkxyl9m4dx4b9d45zk-gcc-9.3.0', '/nix/store/rgq5nvs1p96yaap9c9yayymjjrx3a2xp-ed-1.16', '/nix/store/rvg5a5nwa7cihpmbzlwzh931w3g4q108-compress-man-pages.sh', '/nix/store/x01pgagidg1hqkgsg2a1rqzwbq1bvmf0-expand-response-params', '/nix/store/xhb1hfzw71vkd7bdr5vjczlw0k78q1ni-acl-2.2.53', '/nix/store/z4sfs9inv6jvjswqc1xh0fymw2s3jbpf-gnused-4.8'
building of '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv': woken up
building of '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv': trying to build
locking path '/nix/store/xdj6pkcgjc6bd4nw8rirfgh0z5nlj7ma-hello-2.10-env'
lock acquired on '/nix/store/xdj6pkcgjc6bd4nw8rirfgh0z5nlj7ma-hello-2.10-env.lock'
removing invalid path '/nix/store/xdj6pkcgjc6bd4nw8rirfgh0z5nlj7ma-hello-2.10-env'
starting build hook '/nix/store/abp7sfsi0i37dalwkcp2kssjzwjmnix4-nix-3.0pre20200916_609a6d6/libexec/nix/build-remote'
got 0 remote builders
hook reply is 'decline-permanently'
killing process 25803
building of '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv': woken up
found build user 'nixbld1'
found build user 'nixbld10'
found build user 'nixbld11'
found build user 'nixbld12'
found build user 'nixbld13'
found build user 'nixbld14'
found build user 'nixbld15'
found build user 'nixbld16'
found build user 'nixbld2'
found build user 'nixbld3'
found build user 'nixbld4'
found build user 'nixbld5'
found build user 'nixbld6'
found build user 'nixbld7'
found build user 'nixbld8'
found build user 'nixbld9'
trying user 'nixbld1'
killing all processes running under uid '30001'
setting up chroot environment in '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot'
executing builder '/nix/store/6ffp6xbr6j2ryqw2dafbbvv55ggq16iv-bash-4.4-p23/bin/bash'
bind mounting '/nix/store/388zhdxgjk0hvqbxyd51f6ix9rk5qwxh-busybox-1.31.1-x86_64-unknown-linux-musl/bin/busybox' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/bin/sh'
bind mounting '/tmp/nix-build-hello-2.10-env.drv-5' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/build'
bind mounting '/dev/full' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/dev/full'
bind mounting '/dev/kvm' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/dev/kvm'
bind mounting '/dev/null' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/dev/null'
bind mounting '/dev/random' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/dev/random'
bind mounting '/dev/tty' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/dev/tty'
bind mounting '/dev/urandom' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/dev/urandom'
bind mounting '/dev/zero' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/dev/zero'
bind mounting '/nix/store/2f6zzvixj3wsj81flbdcpc6fdscgx4ai-coreutils-8.31' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/2f6zzvixj3wsj81flbdcpc6fdscgx4ai-coreutils-8.31'
bind mounting '/nix/store/2gci5q5yz717xycp444wyjxki4mbwwav-zlib-1.2.11' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/2gci5q5yz717xycp444wyjxki4mbwwav-zlib-1.2.11'
bind mounting '/nix/store/388zhdxgjk0hvqbxyd51f6ix9rk5qwxh-busybox-1.31.1-x86_64-unknown-linux-musl' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/388zhdxgjk0hvqbxyd51f6ix9rk5qwxh-busybox-1.31.1-x86_64-unknown-linux-musl'
bind mounting '/nix/store/4g7jg3j6m465k114l3vwxb5wchswspvk-patchelf-0.12' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/4g7jg3j6m465k114l3vwxb5wchswspvk-patchelf-0.12'
bind mounting '/nix/store/6ffp6xbr6j2ryqw2dafbbvv55ggq16iv-bash-4.4-p23' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/6ffp6xbr6j2ryqw2dafbbvv55ggq16iv-bash-4.4-p23'
bind mounting '/nix/store/78hlxpng1g6hqg064mdq4rk9cfcp30da-pcre-8.44' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/78hlxpng1g6hqg064mdq4rk9cfcp30da-pcre-8.44'
bind mounting '/nix/store/7mc844h3g1wj03si5c9x3llkc7mb03nx-gnumake-4.3' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/7mc844h3g1wj03si5c9x3llkc7mb03nx-gnumake-4.3'
bind mounting '/nix/store/7ylf64vl6747sf45daaw707d4k97wn13-stdenv-linux' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/7ylf64vl6747sf45daaw707d4k97wn13-stdenv-linux'
bind mounting '/nix/store/866is80gnngm7q5fiaqvl4d6z1agc79h-patch-2.7.6' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/866is80gnngm7q5fiaqvl4d6z1agc79h-patch-2.7.6'
bind mounting '/nix/store/87alzvyjwdf2w1k6i6aj87pn4r0sdm6c-libunistring-0.9.10' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/87alzvyjwdf2w1k6i6aj87pn4r0sdm6c-libunistring-0.9.10'
bind mounting '/nix/store/98qzp0pnpdl5wxnf67yvqrf3qdzd43mb-xz-5.2.5' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/98qzp0pnpdl5wxnf67yvqrf3qdzd43mb-xz-5.2.5'
bind mounting '/nix/store/9h4b6pkgpqawq764752fq5kgaqxcg8c7-xz-5.2.5-bin' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/9h4b6pkgpqawq764752fq5kgaqxcg8c7-xz-5.2.5-bin'
bind mounting '/nix/store/ba05xi32q6zjcn6niad1zs1adqylwcr7-bzip2-1.0.6.0.1-bin' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/ba05xi32q6zjcn6niad1zs1adqylwcr7-bzip2-1.0.6.0.1-bin'
bind mounting '/nix/store/bgvxpx97q789xc8rrginprlvk8p03p93-glibc-2.31-dev' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/bgvxpx97q789xc8rrginprlvk8p03p93-glibc-2.31-dev'
bind mounting '/nix/store/ca3s86mhhwmjs5ksry8s3arzaf9s3dcw-gnutar-1.32' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/ca3s86mhhwmjs5ksry8s3arzaf9s3dcw-gnutar-1.32'
bind mounting '/nix/store/cgldmnm5lf0bfjdjjm7p66v7aaxkj948-diffutils-3.7' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/cgldmnm5lf0bfjdjjm7p66v7aaxkj948-diffutils-3.7'
bind mounting '/nix/store/dd3prkmzh7wjfz5cxnlym54vlh7ni89k-libidn2-2.3.0' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/dd3prkmzh7wjfz5cxnlym54vlh7ni89k-libidn2-2.3.0'
bind mounting '/nix/store/fby8klnixr66d81cldxffq38x0q4bxa9-attr-2.4.48' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/fby8klnixr66d81cldxffq38x0q4bxa9-attr-2.4.48'
bind mounting '/nix/store/g8mk2h9g9j0yh5aazvvc011xikxzh2pw-linux-headers-5.5' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/g8mk2h9g9j0yh5aazvvc011xikxzh2pw-linux-headers-5.5'
bind mounting '/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/iygzjy14i075hkxr2gq8cpfjvk2rkx0b-binutils-2.31.1'
bind mounting '/nix/store/jpss6g3cqc9gwih8jflbbc883xc0mbcx-gnugrep-3.4' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/jpss6g3cqc9gwih8jflbbc883xc0mbcx-gnugrep-3.4'
bind mounting '/nix/store/jsgpwwhzfd3c8gnq3ymhqlbgfxk3xjkc-binutils-wrapper-2.31.1' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/jsgpwwhzfd3c8gnq3ymhqlbgfxk3xjkc-binutils-wrapper-2.31.1'
bind mounting '/nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/jvjchabdmcxlwjhbiii5sy6d2hcg6z7r-glibc-2.31'
bind mounting '/nix/store/l11x0vclh1a7wadc2545i6lxlb49vqii-gzip-1.10' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/l11x0vclh1a7wadc2545i6lxlb49vqii-gzip-1.10'
bind mounting '/nix/store/lgf91sh6j7pv2fm500vld1cy336jn8xc-bzip2-1.0.6.0.1' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/lgf91sh6j7pv2fm500vld1cy336jn8xc-bzip2-1.0.6.0.1'
bind mounting '/nix/store/mijx85pw9jn3bhzii3jl0kv5m2sjq7zq-gcc-9.3.0-lib' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/mijx85pw9jn3bhzii3jl0kv5m2sjq7zq-gcc-9.3.0-lib'
bind mounting '/nix/store/mimzy2k99xq842k59zl3f2z2s34rcq5b-gcc-wrapper-9.3.0' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/mimzy2k99xq842k59zl3f2z2s34rcq5b-gcc-wrapper-9.3.0'
bind mounting '/nix/store/n2r2i8rz2a2mhpay12y4p177shpvislx-gawk-5.1.0' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/n2r2i8rz2a2mhpay12y4p177shpvislx-gawk-5.1.0'
bind mounting '/nix/store/ql9k257fsgjsrc2dq2cbhhsayis7q66a-findutils-4.7.0' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/ql9k257fsgjsrc2dq2cbhhsayis7q66a-findutils-4.7.0'
bind mounting '/nix/store/r5xqfk8p7c79yqphy25rbvm71yfvrzh4-glibc-2.31-bin' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/r5xqfk8p7c79yqphy25rbvm71yfvrzh4-glibc-2.31-bin'
bind mounting '/nix/store/rclksjxdjgp6y6qkxyl9m4dx4b9d45zk-gcc-9.3.0' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/rclksjxdjgp6y6qkxyl9m4dx4b9d45zk-gcc-9.3.0'
bind mounting '/nix/store/rgq5nvs1p96yaap9c9yayymjjrx3a2xp-ed-1.16' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/rgq5nvs1p96yaap9c9yayymjjrx3a2xp-ed-1.16'
bind mounting '/nix/store/x01pgagidg1hqkgsg2a1rqzwbq1bvmf0-expand-response-params' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/x01pgagidg1hqkgsg2a1rqzwbq1bvmf0-expand-response-params'
bind mounting '/nix/store/xhb1hfzw71vkd7bdr5vjczlw0k78q1ni-acl-2.2.53' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/xhb1hfzw71vkd7bdr5vjczlw0k78q1ni-acl-2.2.53'
bind mounting '/nix/store/z4sfs9inv6jvjswqc1xh0fymw2s3jbpf-gnused-4.8' to '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv.chroot/nix/store/z4sfs9inv6jvjswqc1xh0fymw2s3jbpf-gnused-4.8'
closing leaked FD 3
closing leaked FD 4
closing leaked FD 5
closing leaked FD 6
closing leaked FD 7
closing leaked FD 8
closing leaked FD 9
closing leaked FD 10
closing leaked FD 11
closing leaked FD 12
closing leaked FD 13
closing leaked FD 14
closing leaked FD 15
building '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv'...
building of '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv': got EOF
building of '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv': woken up
building of '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv': build done
killing process 25822
builder process for '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv' finished
killing all processes running under uid '30001'
lock released on '/nix/store/xdj6pkcgjc6bd4nw8rirfgh0z5nlj7ma-hello-2.10-env.lock'
building of '/nix/store/g3g446xakv5mmcg3vlma9g1dqfr8dxdz-hello-2.10-env.drv': goal destroyed
error: --- Error ----------------------------------------------------------------------------------------------------------------------------------------- nix
boost::bad_format_string: format-string is ill-formed

```

**Expected behavior**

A shell with dependencies of `hello` is started.

**`nix-env --version` output**

```
$ nix --version
nix (Nix) 3.0pre20200916_609a6d6
```

**Additional context**

NixOS 20.09.20200820.c59ea8b (Nightingale)

Worked fine on 7cb5f643a6ee5b8ffee2e0bb9159a677ff76d17c .

### PR DESCRIPTION
**Pull request by edolstra**
Fixes #4021. It also fixes a bad format string failure when debug output is enabled.

@Ericson2314 The second call to `canonicalisePathMetaData()` should be superfluous now since we're always calling `canonicalisePathMetaData()` in the loop over `drv->outputs` at the start of `registerOutputs()`. But maybe I'm missing something, please check.

### CODE REVIEW

**Comment by Ericson2314** [comment]
So we had to `chmod` the root file/directory to move the store entry a few lines above, but maybe we can just `chmod` it back and not recur?

When I first rewrote `registerOutputs` I remember seeing this, but being worried that something might have changed so I better canonicalize again. But I can't really see what i was worried about.

Also, out of curiosity, how did `canonicalisePathMetaData` cause the EOF problem? I thought it would have been idempotent. Good to do this be more efficient in any case :), but I'm curious.

**Comment by edolstra** [comment]
The EOF is because the daemon aborts with an assertion failure.

**Comment by edolstra** [comment]
Ah, I didn't see the `chmod`. Yeah I'll just `chmod` it back after the rename.

**Comment by Ericson2314** [comment]
Ah! I see, the now-deleted comment should've instead read "check if all files *were* owned by the build user", since it's making them no longer be owned by that user. Thanks!

File: tests/simple.sh [hunk 1]
```diff
@@ -10,13 +10,15 @@ outPath=$(nix-store -rvv "$drvPath")
 
 echo "output path is $outPath"
 
+(! [ -w $outPath ])
```
Comment (Ericson2314) [inline tests/simple.sh:13]: I don't think one needs the `(..)` subshell for this?

Comment (edolstra) [reply tests/simple.sh:13]: It is needed. From the bash manpage under `set -e`: "The shell does not exit ... if the command's return value is being inverted with !".

Comment (Ericson2314) [reply tests/simple.sh:13]: Oh, thanks! In that cases I think I need to fix some tests of mine on branches :)
