### PR TITLE
nix repl: hide progress bar during :edit

### LINKED ISSUE #10617: nix repl `:edit`or messes up the terminal
**Describe the bug**

[
2024-04-28T16:09:41+02:00
](url)

**Steps To Reproduce**

```
nix repl .
nix-repl> :e packages.x86_64-linux.nix
```

**Expected behavior**

No garbled lines where cursor is

**`nix-env --version` output**

❯ ./result/bin/nix --version
warning: unknown experimental feature 'repl-flake'
nix (Nix) 2.23.0pre20240426_2f67833

**Additional context**

The culprit appears to be 20cd5eb2b3668f5b95b6f020e1c258011c18ea33 from https://github.com/NixOS/nix/pull/9476

Reverting this atop 2f67833 fixes the problem

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by srhb**
# Motivation

Attempt to fix #10617 

# Context

I have no idea what I'm doing, so someone familiar with, like, C++, or how the progress bar usually works, should probably see if this is sensible. It just looked vaguely-like-the-right-spot to do the thing. :smile_cat: 

# Priorities and Process

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

File: src/libcmd/repl.cc [hunk 1]
```diff
@@ -506,11 +506,15 @@ ProcessLineResult NixRepl::processLine(std::string line)
         auto editor = args.front();
         args.pop_front();
 
+        // avoid garbling the editor with the progress bar
+        logger->pause();
```
Comment (edolstra) [inline src/libcmd/repl.cc:510]:
```suggestion
        logger->pause();
        Finally resume([&]() { logger->resume(); });
```
This should ensure that the logger restarts even if the editor throws an exception

File: src/libcmd/repl.cc [hunk 2]
```diff
@@ -506,11 +506,15 @@ ProcessLineResult NixRepl::processLine(std::string line)
...
+
         // runProgram redirects stdout to a StringSink,
         // using runProgram2 to allow editors to display their UI
         runProgram2(RunOptions { .program = editor, .lookupPath = true, .args = args });
 
         // Reload right after exiting the editor
+        logger->resume();
```
Comment (edolstra) [inline src/libcmd/repl.cc:517]:
```suggestion
```

**Review by edolstra — APPROVED** [review]

**Comment by srhb** [comment]
@edolstra Thanks, squashed in your suggestions! :+1:

**Comment by srhb** [comment]
Re-tested, still seems good!
