### PR TITLE
Detect cycles in flake follows.

### LINKED ISSUE #9144: Segmentation fault when flake inputs follow each other
**Describe the bug**

Segmentation fault when flake inputs follow each other

**Steps To Reproduce**

```nix
{
  inputs = {
    nixpkgs.follows = "dream2nix/nixpkgs";
    dream2nix = {
      url = "github:nix-community/dream2nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };
  outputs = {...}: {};
}
```

**Expected behavior**

A dependency cycle reported by nix

**`nix-env --version` output**
nix-env (Nix) 2.18.1

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by vkryachko**
This change results in an error thrown as opposed to segfaulting due to stack overflow.

Fixes #9144

# Motivation

# Context

# Priorities

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

### CODE REVIEW

File: src/libexpr/flake/lockfile.cc [hunk 1]
```diff
@@ -45,16 +45,26 @@ StorePath LockedNode::computeStorePath(Store & store) const
     return lockedRef.input.computeStorePath(store);
 }
 
-std::shared_ptr<Node> LockFile::findInput(const InputPath & path)
-{
+
+static std::shared_ptr<Node> doFind(const ref<Node>& root, const InputPath & path, std::vector<std::string>& visited) {
     auto pos = root;
 
+    auto pathS = printInputPath(path);
```
Comment (thufschmitt) [inline src/libexpr/flake/lockfile.cc:52]: Do we need to eagerly print the paths? Couldn't we have `visited` be a `std::vector<FlakeId>` and only print the paths if we get a cycle?

(not that it matters too much from a performance pov, but it would make the intent clearer I think)

**Review by thufschmitt — CHANGES_REQUESTED** [review]
Thanks, that's great!

Just one minor question, but it's good apart from that (and with a neat test :star_struck: )

File: src/libexpr/flake/lockfile.cc (hunk 1 above)
Comment (vkryachko) [reply src/libexpr/flake/lockfile.cc]: I'm a bit rusty on c++(no pun intended :)), but:

I used a similar approach although using `std::vector<InputPath>`, then it turned out that `InputPath` is itself a vector, so to avoid the copy I decided to switch to `std::vector<const InputPath&>`, but apparently c++ does not like vectors of vector references, which have to be wrapped in `std::reference_wrapper`. So I decided to convert to path strings for visited.

Like you mention, even using `vector<InputPath>` will likely not matter in terms of performance, switched back to that.

Comment (thufschmitt) [reply src/libexpr/flake/lockfile.cc]: Oh indeed, we're copying too much any way. Well, so be it then, we'll live with that.

**Review by thufschmitt — APPROVED** [review]
Looking great, thanks!
