### PR TITLE
libstore/local-derivation-goal: prohibit creating setuid/setgid binaries

### LINKED ISSUE #10424: Syscall `fchmodat2` allows to create suid binaries
**Describe the bug**

To quote from https://github.com/NixOS/nixpkgs/issues/300635#issuecomment-2031073804:

> With kernel ≥6.6 and glibc 2.39, lxc's install phase uses fchmodat2, which slips through https://github.com/NixOS/nix/blob/9b88e5284608116b7db0dbd3d5dd7a33b90d52d7/src/libstore/build/local-derivation-goal.cc#L1650-L1663. The fixupPhase then uses fchmodat, which fails.
> With older kernel or glibc, setting the suid bit fails in the install phase, which is not treated as fatal, and then the fixup phase does not try to set it again.

As @lf- points out, the use of the seccomp sandbox against creating suid binaries is questionable (https://github.com/NixOS/nixpkgs/issues/300635#issuecomment-2030844251) since the restriction can be bypassed easily by using the `open(2)` syscall for the exact same purpose and the permissions will be wiped later on.

What I'd like to achieve is that we get a fix for that scenario to make sure people aren't running into the problem when upgrading to 24.05. The builds from nixpkgs appear fixed (or actually, worked around), but a lot of people will also build custom stuff.

If you agree on removing the chmod restriction, that's one way forward.
If that requires further discussion, I'll file a patch to add fchmodat2 to https://github.com/NixOS/nix/blob/8b16cced18925aa612049d08d5e78eccbf0530e4/src/libstore/build/local-derivation-goal.cc#L1650-L1663 to have a short-term resolution.

cc @NixOS/nix-team 
cc @vcunat 
cc @lf- 

**Priorities**

Add :+1: to [issues you find important](https://github.com/NixOS/nix/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

### PR DESCRIPTION
**Pull request by Ma27**
# Motivation

With Linux kernel >=6.6 & glibc 2.39 a `fchmodat2(2)` is available that
isn't filtered away by the libseccomp sandbox.

Being able to use this to bypass that restriction has surprising results
for some builds such as lxc[1]:

> With kernel ≥6.6 and glibc 2.39, lxc's install phase uses fchmodat2,
> which slips through https://github.com/NixOS/nix/blob/9b88e5284608116b7db0dbd3d5dd7a33b90d52d7/src/libstore/build/local-derivation-goal.cc#L1650-L1663.
> The fixupPhase then uses fchmodat, which fails.
> With older kernel or glibc, setting the suid bit fails in the
> install phase, which is not treated as fatal, and then the
> fixup phase does not try to set it again.

Please note that there are still ways to bypass this sandbox[2] and this is
mostly a fix for the breaking builds.

This change works by creating a syscall filter for the `fchmodat2`
syscall (number 452 on most systems). The problem is that glibc 2.39
and seccomp 2.5.5 are needed to have the correct syscall number available
via `__NR_fchmodat2` / `__SNR_fchmodat2`, but this flake is still on
nixpkgs 23.11. To have this change everywhere and not dependent on the
glibc this package is built against, I added a header
"fchmodat2-compat.hh" that sets the syscall number based on the
architecture. On most platforms its 452 according to glibc with a few
exceptions:

    $ rg --pcre2 'define __NR_fchmodat2 (?!452)'
    sysdeps/unix/sysv/linux/x86_64/x32/arch-syscall.h
    58:#define __NR_fchmodat2 1073742276

    sysdeps/unix/sysv/linux/mips/mips64/n32/arch-syscall.h
    67:#define __NR_fchmodat2 6452

    sysdeps/unix/sysv/linux/mips/mips64/n64/arch-syscall.h
    62:#define __NR_fchmodat2 5452

    sysdeps/unix/sysv/linux/mips/mips32/arch-syscall.h
    70:#define __NR_fchmodat2 4452

    sysdeps/unix/sysv/linux/alpha/arch-syscall.h
    59:#define __NR_fchmodat2 562

I tested the change by adding the diff below as patch to
`pkgs/tools/package-management/nix/common.nix` & then built a VM from
the following config using my dirty nixpkgs master:

    {
      vm = { pkgs, ... }: {
        virtualisation.writableStore = true;
        virtualisation.memorySize = 8192;
        virtualisation.diskSize = 12 * 1024;
        nix.package = pkgs.nixVersions.nix_2_21;
      };
    }

The original issue can be triggered via

    nix build -L github:nixos/nixpkgs/d6dc19adbda4fd92fe9a332327a8113eaa843894#lxc \
      --extra-experimental-features 'nix-command flakes'

however the problem disappears with this patch applied.

Closes https://github.com/NixOS/nix/issues/10424

[1] https://github.com/NixOS/nixpkgs/issues/300635#issuecomment-2031073804
[2] https://github.com/NixOS/nixpkgs/issues/300635#issuecomment-2030844251

cc @NixOS/nix-team 
cc @lf- (we'll probably want a follow-up ticket for the `open(2)` topic btw, right?)

# Context

# Priorities and Process

This patch should be backported to all Nix versions that are considered supported.

Add :+1: to [pull requests you find important](https://github.com/NixOS/nix/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc).

The Nix maintainer team uses a [GitHub project board](https://github.com/orgs/NixOS/projects/19) to [schedule and track reviews](https://github.com/NixOS/nix/tree/master/maintainers#project-board-protocol).

### CODE REVIEW

**Comment by Ma27** [comment]
fwiw hacked together a dirty, but quicker way to test this:
```nix
with import (builtins.fetchTarball https://github.com/nixos/nixpkgs/archive/nixos-unstable.tar.gz) {};
let
  builder = runCommand "fnord" { } ''
    ${pkgs.gcc}/bin/gcc ${writeText "foo.c" ''
      #include <stdio.h>
      #include <stdlib.h>
      #include <sys/stat.h>
      #include <sys/syscall.h>
      #include <errno.h>

      int main(void) {
          char *name = getenv("OUT_FROM_ENV");
          FILE *fd = fopen(name, "w");
          fprintf(fd, "hello");
          fclose(fd);
          long rs = syscall(__NR_fchmodat2, NULL, name, S_ISUID, 0);
          printf("result: %ld, errno: %ld\n", rs, errno);
      }
    ''} -O0 -g -o $out
  '';
in
runCommand "foobar" { } ''
  OUT_FROM_ENV=$out ${builder}
''
```

`nix-build` on a VM with this patch gives me `result: -1, errno: 1` again (in contrast to `errno` being `0` w/o tthis patch).

File: src/libstore/build/local-derivation-goal.cc [hunk 1]
```diff
@@ -1672,6 +1672,12 @@ void setupSeccomp()
         if (seccomp_rule_add(ctx, SCMP_ACT_ERRNO(EPERM), SCMP_SYS(fchmodat), 1,
                 SCMP_A2(SCMP_CMP_MASKED_EQ, (scmp_datum_t) perm, (scmp_datum_t) perm)) != 0)
             throw SysError("unable to add seccomp rule");
+
+#if defined(__SNR_fchmodat2)
+        if (seccomp_rule_add(ctx, SCMP_ACT_ERRNO(EPERM), SCMP_SYS(fchmodat2), 1,
+                SCMP_A2(SCMP_CMP_MASKED_EQ, (scmp_datum_t) perm, (scmp_datum_t) perm)) != 0)
+            throw SysError("unstable to add seccomp rule");
```
Comment (hexchen) [inline src/libstore/build/local-derivation-goal.cc:1679]: is "unstable" here a typo?

Comment (Ma27) [reply src/libstore/build/local-derivation-goal.cc:1679]: yes 😅 
will push a fix later!

File: src/libstore/build/local-derivation-goal.cc [hunk 2]
```diff
@@ -1672,6 +1672,12 @@ void setupSeccomp()
         if (seccomp_rule_add(ctx, SCMP_ACT_ERRNO(EPERM), SCMP_SYS(fchmodat), 1,
                 SCMP_A2(SCMP_CMP_MASKED_EQ, (scmp_datum_t) perm, (scmp_datum_t) perm)) != 0)
             throw SysError("unable to add seccomp rule");
+
+#if defined(__SNR_fchmodat2)
```
Comment (lf-) [inline src/libstore/build/local-derivation-goal.cc:1676]: when is this not defined? which package is necessary to build with an old version of, to produce a nix that has inconsistent behaviour on newer kernels? 

i forget where these constants come from but i don't like how this makes runtime behaviour depend on building with new enough headers.

**Review by lf- — CHANGES_REQUESTED** [review]

File: src/libstore/build/local-derivation-goal.cc (hunk 2 above)
Comment (Ma27) [reply src/libstore/build/local-derivation-goal.cc:1676]: `__SNR_fchmodat2` is defined in libseccomp and points to `__NR_fchmodat2` from glibc.

The problem here is that we need glibc 2.39 (which means nixos-unstable) to get the correct syscall number.
We may want to update the flake in this project to actually build against that though.

So I see the following options:
* Updating the flake here. Has the downside that 23.11 still has the issue.
* Inject a newer `<sys/syscall.h>` into the build (and also a patched libseccomp header) and I'm not sure if we want that (_looking at @NixOS/nix-team who has to maintain that later on_).
* The syscall number is 452 except on mips, alpha and x32:

```
❯ ~/Projects/glibc release/2.39/master → rg --pcre2 'fchmodat2 (?!452)' **/arch-syscall.h 
sysdeps/unix/sysv/linux/x86_64/x32/arch-syscall.h
58:#define __NR_fchmodat2 1073742276

sysdeps/unix/sysv/linux/mips/mips64/n32/arch-syscall.h
67:#define __NR_fchmodat2 6452

sysdeps/unix/sysv/linux/mips/mips64/n64/arch-syscall.h
62:#define __NR_fchmodat2 5452

sysdeps/unix/sysv/linux/mips/mips32/arch-syscall.h
70:#define __NR_fchmodat2 4452

sysdeps/unix/sysv/linux/alpha/arch-syscall.h
59:#define __NR_fchmodat2 562
```

  x32 seems to be something different than i686, so none of the architectures here seem supported by Nix right now. As a temporary measure we could hardcode the syscall number until the NixOS ecosystem has moved to glibc 2.39.

I don't really like any of these. Opinions? Or better ideas?

Comment (lf-) [reply src/libstore/build/local-derivation-goal.cc:1676]: my preference would be a shim header that defines it if not yet defined, since it's not like it's going to change anyway. and then put the bad system detection code in that header. least build system shenanigans, and puts things that don't matter in a harmless location.

Comment (Ma27) [reply src/libstore/build/local-derivation-goal.cc:1676]: I have a patch now locally that works on my x86_64-linux. Will take a second look tomorrow after having some sleep and push it then.

Comment (Ma27) [reply src/libstore/build/local-derivation-goal.cc]: Pushed a fix for this.

File: src/libstore/build/local-derivation-goal.cc [hunk 3]
```diff
@@ -1672,6 +1673,12 @@ void setupSeccomp()
         if (seccomp_rule_add(ctx, SCMP_ACT_ERRNO(EPERM), SCMP_SYS(fchmodat), 1,
                 SCMP_A2(SCMP_CMP_MASKED_EQ, (scmp_datum_t) perm, (scmp_datum_t) perm)) != 0)
             throw SysError("unable to add seccomp rule");
+
+#if defined(NIX_SYSCALL_FCHMODAT2)
```
Comment (lf-) [inline src/libstore/build/local-derivation-goal.cc:1677]: you shouldn't need this guard i don't believe. (or, rather, please make this guard unnecessary)

Comment (Ma27) [reply src/libstore/build/local-derivation-goal.cc:1677]: Good point, this is also guarded by __linux__/HAVE_SECCOMP 👍 
(And yes, generally a good thing to not have this silently removed by accident)

File: src/libstore/build/fchmodat2-compat.hh [hunk 4]
```diff
@@ -0,0 +1,36 @@
...
+#      define NIX_SYSCALL_FCHMODAT2 5452
+#    elif defined(__mips__) && defined(__mips64) && defined(_ABIN32) // mips64/n32
+#      define NIX_SYSCALL_FCHMODAT2 6452
+#    elif defined(__mips__) && defined(_ABIO32) // mips32
+#      define NIX_SYSCALL_FCHMODAT2 4452
+#    else
+#      define NIX_SYSCALL_FCHMODAT2 452
+#    endif
+#  endif // HAVE_SECCOMP
+#endif // __linux__
```
Comment (Ericson2314) [inline src/libstore/build/fchmodat2-compat.hh:36]: I think better to put this in a `linux/` directory (see `libutil`) and do
```suggestion
#if HAVE_SECCOMP
#  if defined(__alpha__)
#    define NIX_SYSCALL_FCHMODAT2 562
#  elif defined(__x86_64__) && SIZE_MAX == 0xFFFFFFFF // x32
#    define NIX_SYSCALL_FCHMODAT2 1073742276
#  elif defined(__mips__) && defined(__mips64) && defined(_ABIN64) // mips64/n64
#    define NIX_SYSCALL_FCHMODAT2 5452
#  elif defined(__mips__) && defined(__mips64) && defined(_ABIN32) // mips64/n32
#    define NIX_SYSCALL_FCHMODAT2 6452
#  elif defined(__mips__) && defined(_ABIO32) // mips32
#    define NIX_SYSCALL_FCHMODAT2 4452
#  else
#    define NIX_SYSCALL_FCHMODAT2 452
#  endif
#endif // HAVE_SECCOMP
```

Comment (Ericson2314) [reply src/libstore/build/fchmodat2-compat.hh:36]: @Ma27 yes that's right, but I think that's OK. there are already many of them already. See https://github.com/NixOS/nix/pull/10416/files for a recent example.

Comment (Ma27) [reply src/libstore/build/fchmodat2-compat.hh]: Done!

File: src/libstore/build/local-derivation-goal.cc [hunk 5]
```diff
@@ -38,6 +38,7 @@
 
 /* Includes required for chroot support. */
 #if __linux__
+# include "linux/fchmodat2-compat.hh"
```
Comment (Ericson2314) [inline src/libstore/build/local-derivation-goal.cc:41]:
```suggestion
# include "fchmodat2-compat.hh"
```

Comment (Ericson2314) [reply src/libstore/build/local-derivation-goal.cc:41]: the `linux` dirs are conditionally added to the `-I` path.

**Review by Ericson2314 — APPROVED** [review]

**Comment by Ma27** [comment]
@Ericson2314 that's what I tried first :sweat_smile:

**Comment by edolstra** [comment]
The build is currently failing with
```
       > src/libstore/build/local-derivation-goal.cc:41:11: fatal error: fchmodat2-compat.hh: No such file or directory
       >    41 | # include "fchmodat2-compat.hh"
```

`libstore/linux` should be added to the include path somewhere.

**Comment by Ericson2314** [comment]
`src/libstore/local.mk` may need to be updated for it.

**Comment by Ma27** [comment]
Rebased onto latest master. cc @Ericson2314

**Comment by Ericson2314** [comment]
Oh good, I forgot to say I did the thing that was needed for this, but you found it :)

**Review by Ericson2314 — APPROVED** [review]

**Comment by thufschmitt** [comment]
@Ericson2314 @Ma27 will either of you handle the backport to 2.21 (and 2.18) since the automatic one failed?

**Comment by vcunat** [comment]
Could this merge be causing some issues?  (noticed by accident)
https://hydra.nixos.org/build/257144328/nixlog/7/tail

**Comment by Ericson2314** [comment]
@thufschmitt Yes I can do that

**Comment by Ericson2314** [comment]
@vcunat You are right: #10585

**Comment by Ericson2314** [comment]
OK Thanks @Ma27!

**Comment by Ericson2314** [comment]
FWIW, my view is that it is good to also backport the changes needed for the `linux` dir, etc., as that will make future backports to 2.21 go smoothly.

**Comment by Ma27** [comment]
fyi Will provide a backport of both this and #10591 as soon as this one was reviewed :)
